### ISSUE TITLE
Error when uploading CSV file

### ISSUE THREAD

**Issue by syazwan0913** [apache/superset#10341]
### Expected results

CSV file uploaded into database

### Actual results

Got error when uploading CSV file

#### Screenshots

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/views.py", line 94, in this_form_post
    response = self.form_post(form)
  File "/app/superset/views/database/views.py", line 141, in form_post
    delete=False,
  File "/usr/local/lib/python3.6/tempfile.py", line 551, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.6/tempfile.py", line 262, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/app/superset/app/static/uploads/tmpgzxvi893.csv'
```

#### How to reproduce the bug

1. Enable CSV upload
2. Upload CSV file

### Environment

(please complete the following information):

- First installation using Docker
- superset version: `master`
- python version: `based on master branch`
- node.js version: `based on master branch`
- npm version: `based on master branch`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by gaurav1999** [comment]
Looks like your file is not present at the location from where you are trying to pick it up.

```FileNotFoundError: [Errno 2] No such file or directory: '/app/superset/app/static/uploads/tmpgzxvi893.csv'```

**Comment by syazwan0913** [comment]
I tested by uploading the same file on other superset version which is `0.34.0` and it is uploaded

**Comment by reenarosid** [comment]
> I tested by uploading the same file on other superset version which is `0.34.0` in same environment and it is uploaded. What does it mean by your statement here?
> 
> > Looks like your file is not present at the location from where you are trying to pick it up.

This issue occurs in the default (master)

**Comment by reenarosid** [comment]
Cause:  Insufficient privilege, which doesn't allow a file creation in the Docker container environment.

Fix: giving it a root privilege

Please add user: root:root in your docker-compose.yml to fix the issue.


  superset:
    env_file: docker/.env
    build: *superset-build
    container_name: superset_app
    command: ["flask", "run", "-p", "8088", "--with-threads", "--reload", "--debugger", "--host=0.0.0.0"]
    restart: unless-stopped
    ports:
      - 8088:8088
    user: root:root  # make this change  
    depends_on: *superset-depends-on
    volumes: *superset-volumes

**Comment by syazwan0913** [comment]
@reenarosid Okay got it. Thank you

**Comment by willbarrett** [comment]
It should be noted that the solution recommended by @reenarosid should only be used in development environments - if you're using the same dockerfile or docker-compose setup in a hosted environment, it's a questionable idea to give the application root privileges. We can likely add read/write permissions on the appropriate folder in the docker build to avoid the necessity of running as root. I'll take a look into that when I get a few minutes.

**Comment by syazwan0913** [comment]
@willbarrett What is the status of this?

**Comment by willbarrett** [comment]
I haven't gotten a few minutes yet :)

**Comment by rayzor65** [comment]
I managed to get past this issue by creating a new folder in my dockerfile (`RUN mkdir /csvs`) then updating `superset_config.py`
```
# superset_config.py
UPLOAD_FOLDER = "/csvs/"
```
