### ISSUE TITLE
Superset upgrade from 0.35 to 0.36 failed

### ISSUE THREAD

**Issue by labelhero** [apache/superset#10364]
### Expected results

Upgraded to 0.36 version with existing dashboards, charts, databases, users etc., 

### Actual results

Failed "superset db upgrade" 

#### How to reproduce the bug

1. pip install apache-superset upgrade
2. superset db upgrade
3. I see there are new fields added to "tables", "dbs","slices" which is causing issue.
4. Unable to retain dashboards and charts.

Error:

```
INFO:superset.utils.logging_configurator:logging was configured successfully
/usr/local/lib/python3.6/site-packages/flask_caching/__init__.py:202: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
/usr/local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (3719, "'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.")
  result = self._query(query)
DEBUG:asyncio:Using selector: EpollSelector
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'dbs.server_cert' in 'field list'")

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1051, "Unknown table 'superset.sqlite_sequence'")
```

### Environment

(please complete the following information):

- superset version: `0.35`
- python version: `3.6`
- Mysql 8.0.17

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Manually updating each table is tedious task.  
How to upgrade to latest version of superset without manually updating the Mysql tables?

**Comment by tierzhang** [comment]
I have a "runtime error Working outside of application context." and "flask-caching cache_type is set to null" bug too about v0.36 after installation, however v0.35.2 has no error or bug under the same environment. 
When I using v0.36, Superset could run development mode on localhost, but it can't run by uwsgi for network-use.
Probably there are something wrong with packages of v0.36? 
## Environment:
CentOS 8
Python 3.6
PostgreSQL 12

**Comment by labelhero** [comment]
Can someone please help here..

**Comment by mistercrunch** [comment]
Is see `pymysql`, I think we recommend `mysqlclient` ...

**Comment by mistercrunch** [comment]
I also see `dbs.server_cert` which looks like a local fork thing as it's not in our fork as far as I can tell.

**Comment by dbech** [comment]
@labelhero I'm having the same problem, did you ever find a solution? Or even just a copy of what the database schema should be?

**Comment by megakoresh** [comment]
Same issue here

**Comment by labelhero** [comment]
@mistercrunch  I uninstalled pymysql and install mysqlclient but issue still persists. @dbech no solution as of now, however planning some workarounds like manual db migrations.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'dbs.server_cert' in 'field list'")
```

**Comment by dbech** [comment]
I attempted a manual database migration also by spinning up a fresh install of 0.36 and comparing the database to my own. I got it pretty close to working but it seems like there's some data that needs to be encrypted now which I couldn't correct.

Best of luck with your attempt

**Comment by labelhero** [comment]
Hi, 

Can someone please provide update here. Do you think upgrading to 0.37.1 version fixes anything here?

 @dbech were you able to solve this issue?

**Comment by dbech** [comment]
I wasn't able to solve the issue, I ended up moving to a different product
