### ISSUE TITLE
oauth  flask_oauthlib.client.OAuthException: Invalid response from pingID

### ISSUE THREAD

**Issue by jbrunetext** [apache/superset#10569]
hi, i configure my oauth login according to http://superset.apache.org/installation.html#custom-oauth2-configuration. Everything is right, but it turns wrong when the code runs at "oauth_authorized" method in views.py. 

i also setup the  CustomSsoSecurityManager for troubleshooting same error...
i get an exception 500 - Internal Server Error
```Stacktrace

        Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 677, in oauth_authorized
    resp = self.appbuilder.sm.oauth_remotes[provider].authorized_response()
  File "/usr/local/lib/python3.6/site-packages/flask_oauthlib/client.py", line 707, in authorized_response
    data = self.handle_oauth2_response(args)
  File "/usr/local/lib/python3.6/site-packages/flask_oauthlib/client.py", line 692, in handle_oauth2_response
    type='invalid_response', data=data
flask_oauthlib.client.OAuthException: Invalid response from pingID
```

### Expected results

i was expected to redirect to /login

### Actual results
error 500

#### Screenshots

see the stacktrace

#### How to reproduce the bug

1. Go to url_base
2. Click on javascript:set_openid('/login/pingID', 'pingID');
3. valid OK

### Environment

(please complete the following information):

- superset version: 

/usr/local/lib/python3.6/site-packages/flask_caching/__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.36.0

- python version: python --version
Python 3.6.10

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jbrunetext** [comment]
Here there is my config :
```
  import os
  from flask_appbuilder.security.manager import AUTH_OID, AUTH_OAUTH, AUTH_REMOTE_USER
  from custom_sso_security_manager import CustomSsoSecurityManager
  CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager

  #---------------------------------------------------------
  # Superset specific config
  #---------------------------------------------------------
  ROW_LIMIT = 5000
  SUPERSET_WORKERS = 2
  SUPERSET_WEBSERVER_PORT = 8088
  ENABLE_PROXY_FIX = True
  #---------------------------------------------------------

  #---------------------------------------------------------
  # Flask App Builder configuration
  #---------------------------------------------------------
  # Your App secret key
  SECRET_KEY = '\2\1thisismyscretkey\1\2\e\y\y\h'

  # The SQLAlchemy connection string to your database backend
  # This connection defines the path to the database that stores your
  # superset metadata (slices, connections, tables, dashboards, ...).
  # Note that the connection information to connect to the datasources
  # you want to explore are managed directly in the web UI
  SQLALCHEMY_DATABASE_URI = "mysql+mysqldb://" + os.environ.get('username') + ":" + os.environ.get('password') + "@superset-sqlproxy/superset_dev"


  # Flask-WTF flag for CSRF
  WTF_CSRF_ENABLED = True
  # Add endpoints that need to be exempt from CSRF protection
  WTF_CSRF_EXEMPT_LIST = []

  # Set this API key to enable Mapbox visualizations
  MAPBOX_API_KEY = ''

  AUTH_TYPE = AUTH_OAUTH
  OAUTH_PROVIDERS = [
      {   'name':'pingID',
          'token_key':'access_token',
          'icon':'fa-address-card',
          'remote_app': {
              'consumer_key':'CLIENT_ID',
              'consumer_secret':'SECRET_ID',
              'request_token_params':{
                  'scope': 'openid'
              },
              'access_token_method':'POST',
              'access_token_params':{
                    'client_id':'CLIENT_ID'
              },

              'base_url':'https://idpb2e.adeo.com/as/',
              'request_token_url': None,
              'access_token_url':'https://idpb2e.adeo.com/as/token.oauth2',
              'authorize_url':'https://idpb2e.adeo.com/as/authorization.oauth2',
              'access_token_headers':{
              'Authorization': 'Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX(base64)='
              }
          }
      }
  ]

  AUTH_USER_REGISTRATION = True
  AUTH_USER_REGISTRATION_ROLE = "admin"
```

there is a log attempt
``` 
"Flask-Caching: CACHE_TYPE is set to null, "
DEBUG:flask_oauthlib:Prepare oauth2 remote args {'code': 'XXXXXAABv', 'client_secret': 'XXXXXXX', 'redirect_uri': 'https://superset.lmfr-ddp.tech.adeo.cloud/oauth-authorized/pingID'}
DEBUG:flask_oauthlib:Request 'https://idpb2e.adeo.com/as/token.oauth2' with 'POST' method
Exception on /oauth-authorized/pingID [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in 

```

Something is wrong i don't see the secret_id in the request.....

**Comment by jbrunetext** [comment]
It'seems the authorize_url is wrong set : i need to add the scope in the and profile var 
'authorize_url':'https://idpb2e.adeo.com/as/authorization.oauth2?scope=openid%20profile%20email',

also need to implement custom_sso_security_manager.py in extraConfigFiles:
```
 me = oauth_provider.get('idp/userinfo.openid').data
```
which is quite messy in the python code ....
