### ISSUE TITLE
IFrame chart  ERROR

### ISSUE THREAD

**Issue by qinzl1** [apache/superset#10639]
IFrame chart can not explor
![image](https://user-images.githubusercontent.com/20242930/90628463-3d2f6a00-e250-11ea-8e53-6279cba3c234.png)

![image](https://user-images.githubusercontent.com/20242930/90628551-63eda080-e250-11ea-94ce-80aebea87b98.png)

2020-08-19 19:08:55,130:INFO:root:------------k>viz_type-----v>iframe
2020-08-19 19:08:55,130:INFO:root:------------k>slice_id-----v>1522
2020-08-19 19:08:55,130:INFO:root:------------k>url_params-----v>{}
2020-08-19 19:08:55,130:INFO:root:------------k>granularity_sqla-----v>None
2020-08-19 19:08:55,130:INFO:root:------------k>time_grain_sqla-----v>P1D
2020-08-19 19:08:55,130:INFO:root:------------k>time_range-----v>Last day
2020-08-19 19:08:55,130:INFO:root:------------k>url-----v>https://www.youtube.com/embed/AdSZJzb-aX8
2020-08-19 19:08:55,156:INFO:root:Cache key: None
2020-08-19 19:08:55,156:ERROR:root:'NoneType' object has no attribute 'to_dict'
Traceback (most recent call last):
  File "/usr/local/py3env/lib64/python3.6/site-packages/superset/views/core.py", line 1149, in generate_json
    payload = viz_obj.get_payload()
  File "/usr/local/py3env/lib64/python3.6/site-packages/superset/viz.py", line 371, in get_payload
    payload['data'] = self.get_data(df)
  File "/usr/local/py3env/lib64/python3.6/site-packages/superset/viz.py", line 485, in get_data
    return self.get_df().to_dict(orient='records')
AttributeError: 'NoneType' object has no attribute 'to_dict'

**Comment by JunlinC** [comment]
🙏@graceguo-supercat Hey Grace, I saw you worked on iframe chart recently, could you help? Thanks!

**Comment by amitmiran137** [comment]
I believe that Iframe chart is deprecated and is no longer in use in newer versions
