### ISSUE TITLE
TypeError: unhashable type: 'dict' - Dashboard

### ISSUE THREAD

**Issue by pkshr** [apache/superset#10802]
I have a query that is executed against athena. The result is a table with 3 columns -  Account, DayOfYear and Cost. I am trying to send this as a stacked bar chart to the dashboard. The dashboard has only this chart and it throws 500 internal server error.

`Exception on /superset/dashboard/7/ [GET]
Traceback (most recent call last):
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/venv/lib64/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/root/venv/lib64/python3.6/site-packages/superset/views/core.py", line 1616, in dashboard
    for datasource, slices in datasources.items()
  File "/root/venv/lib64/python3.6/site-packages/superset/views/core.py", line 1616, in <dictcomp>
    for datasource, slices in datasources.items()
  File "/root/venv/lib64/python3.6/site-packages/superset/connectors/base/models.py", line 285, in data_for_slices
    metric_names.add(utils.get_metric_name(metric))
TypeError: unhashable type: 'dict'
ERROR:superset.app:Exception on /superset/dashboard/7/ [GET]
Traceback (most recent call last):
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/venv/lib64/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/root/venv/lib64/python3.6/site-packages/superset/views/core.py", line 1616, in dashboard
    for datasource, slices in datasources.items()
  File "/root/venv/lib64/python3.6/site-packages/superset/views/core.py", line 1616, in <dictcomp>
    for datasource, slices in datasources.items()
  File "/root/venv/lib64/python3.6/site-packages/superset/connectors/base/models.py", line 285, in data_for_slices
    metric_names.add(utils.get_metric_name(metric))
TypeError: unhashable type: 'dict'
INFO:werkzeug:192.168.1.235 - - [05/Sep/2020 08:36:06] "GET /superset/dashboard/7/ HTTP/1.1" 500 -`

### Environment
`CentOS Linux release 7.8.2003 (Core) - Linux 3.10.0-1127.el7.x86_64`

- superset version: `Superset 0.37.0`
- python version: `Python 3.6.9`
- node.js version: `-bash: node: command not found`
- npm version: `-bash: npm: command not found`

**Comment by villebro** [comment]
thanks for reporting @pkshr , I'll look into this.

**Comment by pkshr** [comment]
@villebro  Thank you. FYI, I tried adding metric in the table as mentioned in https://github.com/apache/incubator-superset/issues/8041 . The issue still persists.

**Comment by natbusa** [comment]
```
def get_metric_name(metric: Metric) -> str:
    fallback = metric
    if isinstance(metric, dict):
        fallback = metric.get('label', metric['optionName'])
    return metric["label"] if is_adhoc_metric(metric) else fallback  # type: ignore
```

**Comment by natbusa** [comment]
Or you could do a similar fix in the `is_adhoc_metric` function ...
