### ISSUE TITLE
Installation Error - Docker-Compose Up on Ubuntu VM on Windows 10

### ISSUE THREAD

**Issue by sridharj-in** [apache/superset#11081]
**OS:** Windows 10 Pro Version 10.0.18362 Build 18362
**VM:** Ubuntu 20.04.1 LTS using WSL 2
**Docker Version inside Ubuntu:**Docker version 19.03.13, build 4484c46d9d
Docker Desktop of Windows Installed and running Linux Containers
**Superset version:** Latest version as of 26-Sep-2020

**Steps to Reproduce:**
1. Installed Docker-compose
2. Installed Superset through $ git clone https://github.com/apache/incubator-superset.git
3. Navigate to the newly created folder via cd incubator-superset
5. Run sudo Docker-compose up
```
**Issue:**
Connection errors - log pasted below

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 403, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 205, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 228, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 188, in __init__
  File "docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
[745] Failed to execute script docker-compose
```

**Comment by sridharj-in** [comment]
Additional Log info:

```
Traceback (most recent call last)

    File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app

    __import__(module_name)

    During handling of the above exception, another exception occurred:
    File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 343, in __call__

    rv = self._load_unlocked()

    File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 330, in _load_unlocked

    self._app = rv = self.loader()

    File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 388, in load_app

    app = locate_app(self, import_name, name)

    File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 250, in locate_app

    raise NoAppException('Could not import "{name}".'.format(name=module_name))

    flask.cli.NoAppException: Could not import "superset.app".

```

**Comment by trumpetsherald** [comment]
I have this same issue on a clean ubuntu 18 image.

**Comment by nytai** [comment]
Did you clone the repo on windows? If so the files system is incompatible and will cause the scripts to fail once they're moved into docker.

**Comment by suddjian** [comment]
This is pretty old with no discussion, so closing this as part of issue cleanup. If it's still a problem feel free to reopen.
