### ISSUE TITLE
Improve documentation regarding Scheduling and Emailing Reports

### ISSUE THREAD

**Issue by VMois** [apache/superset#11235]
**Is your feature request related to a problem? Please describe.**
- no example/steps (or link to another doc page) regarding setting up a Celery worker for email scheduling
- missing information about naming in EMAIL_REPORTS_WEBDRIVER. Docs suggest `geckodriver` and `chromedriver`, but in reality, it is `firefox` and `chrome`

**Describe the solution you'd like**
- add example regarding EMAIL_REPORTS_WEBDRIVER
- step-by-step instruction including setting up a Celery worker (or linking existing documentation of exists)

**Describe alternatives you've considered**
No alternatives

**Additional context**
Link to existing docs - https://superset.apache.org/docs/installation/email-reports

**Comment by DRavikanth** [comment]
I agree with this. Documentation is very poor and no clear instructions on how to set things up for production environments. I am trying to make Superset work with email scheduling including Celery and it's been 3 days and my struggle continues. I am making progress but I have to debug each and every minute detail. I am very disappointed with not even finding an official architectural image in the documentation.  :(

**Comment by VMois** [comment]
From my side, I managed it with some struggle. Use Redis, do not try filesystem as a backend. This is the article I was using - https://medium.com/@nileshxbhosale/apache-superset-a-cost-effective-alternative-to-quick-sight-for-data-lake-668868fe51c7 (+ docs).

**Comment by DRavikanth** [comment]
https://github.com/apache/incubator-superset/issues/11507

@VMois, running into this problem. Any pointers?

**Comment by VMois** [comment]
@DRavikanth if you are using Docker Compose add the following to your superset image:
```yaml
superset:
    shm_size: '2gb'  # fix for gecko driver failure
    # ...
```
You can find the same in the article I shared with you.

**Comment by DRavikanth** [comment]
@VMois, Thanks for the pointer. I missed that totally, let me try that and keep posted here.

**Comment by DRavikanth** [comment]
@VMois Its the same problem after I changed the shm_size in docker build:

```
[2020-11-03 16:32:34,100: WARNING/ForkPoolWorker-7] Message: Unable to locate element: .grid-container
, retrying in 30 seconds...
[2020-11-03 16:33:04,169: ERROR/ForkPoolWorker-7] Task email_reports.send[92959569-4ee1-4e69-93d2-562fb5b72b1f] raised unexpect
ed: NoSuchElementException('Unable to locate element: .grid-container', None, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/app.py", line 115, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 518, in schedule_email_report
    schedule.deliver_as_group,
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 299, in deliver_dashboard
    get_element, fargs=["grid-container"], tries=2, delay=EMAIL_PAGE_RENDER_WAIT
  File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .grid-container
```

**Comment by VMois** [comment]
@DRavikanth, pls, create a separate issue for your problem. Describe your setup, etc. This is an issue related to improving docs.

Regarding your problem, it is a different error compared to what you had. Good sign. Check if you have the latest stable version of the `geckodriver`, I have `0.27.0`. Other than that, I did everything exactly like in the article, so I cannot help you a lot as I don't know the full setup.

**Comment by DRavikanth** [comment]
@VMois, makes sense.

**Comment by octaviancorlade** [comment]
The documentation for these was introduced in #13104
