### ISSUE TITLE
[error]actionable error msg for broken deck.gl chart

### ISSUE THREAD

**Issue by craig-rueda** [apache/superset#11758]
Hexagons demo chart shows error after loading samples:

<img width="736" alt="Screen Shot 2020-11-19 at 3 25 23 PM" src="https://user-images.githubusercontent.com/2595291/99736561-72c83700-2a7b-11eb-8e9a-2b36616d04fe.png">

<img width="627" alt="Screen Shot 2020-11-19 at 3 26 24 PM" src="https://user-images.githubusercontent.com/2595291/99736646-97241380-2a7b-11eb-892a-ac69bf1cd5ca.png">

POST to `explore_json` fails with error:
```
POST https://my.host.here/superset/explore_json/?form_data=%7B%22slice_id%22%3A77%7D&dashboard_id=5 500 (INTERNAL SERVER ERROR)

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/superset/views/base.py", line 177, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/superset/utils/cache.py", line 108, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/superset/views/core.py", line 534, in explore_json
    return self.generate_json(viz_obj, response_type)
  File "/usr/local/lib/python3.7/site-packages/superset/views/core.py", line 430, in generate_json
    payload = viz_obj.get_payload()
  File "/usr/local/lib/python3.7/site-packages/superset/viz.py", line 480, in get_payload
    payload = self.get_df_payload(query_obj)
  File "/usr/local/lib/python3.7/site-packages/superset/viz.py", line 512, in get_df_payload
    query_obj = self.query_obj()
  File "/usr/local/lib/python3.7/site-packages/superset/viz.py", line 2375, in query_obj
    self.add_null_filters()
  File "/usr/local/lib/python3.7/site-packages/superset/viz.py", line 2356, in add_null_filters
    for column in self.get_spatial_columns(key):
  File "/usr/local/lib/python3.7/site-packages/superset/viz.py", line 2291, in get_spatial_columns
    raise ValueError(_("Bad spatial key"))
ValueError: Bad spatial key
```
### Expected results

Hexagons should load properly

what you expected to happen.

#### How to reproduce the bug

1. Load examples from scratch
2. Navigate to deck.gl dashboard

**Comment by junlincc** [comment]
`Bad spatial key` map layer problem? man i dont know what to do with all these broken charts 😂 i also not sure how many people are still using this chart

**Comment by Akitha** [comment]
Did any one got a fix on this 
I am using superset 1.0.1 still issue exists getting the same error

**Comment by andrewscarani** [comment]
It would be beneficial if the chart logged some more information to the user rather than just "Bad Spatial Key" by showing the field that caused the chart to crash

**Comment by andrewscarani** [comment]
Bump! This is still a useful bug fix to have. Please pin!

**Comment by rusackas** [comment]
I'm no longer seeing this in Superset 2.1.0. Is anyone else? If not, I'll close it.
