### ISSUE TITLE
Docker images are broken

### ISSUE THREAD

**Issue by sdabhi23** [apache/superset#12016]
The containers created from the superset images published on DockerHub are crashing

### Expected results

Superset starts up without error.

### Actual results

The container crashes after throwing the following error:

```
[2020-12-11 19:48:43 +0000] [6] [INFO] Starting gunicorn 20.0.4
[2020-12-11 19:48:43 +0000] [6] [INFO] Listening at: http://0.0.0.0:8080 (6)
[2020-12-11 19:48:43 +0000] [6] [INFO] Using worker: gthread
[2020-12-11 19:48:43 +0000] [9] [INFO] Booting worker with pid: 9
[2020-12-11 19:48:47 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/app/superset/app.py", line 29, in <module>
    from superset.extensions import (
  File "/app/superset/extensions.py", line 30, in <module>
    from superset.utils.async_query_manager import AsyncQueryManager
  File "/app/superset/utils/async_query_manager.py", line 23, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
[2020-12-11 19:48:47 +0000] [9] [INFO] Worker exiting (pid: 9)
[2020-12-11 19:48:47 +0000] [6] [INFO] Shutting down: Master
[2020-12-11 19:48:47 +0000] [6] [INFO] Reason: Worker failed to boot.
```

#### How to reproduce the bug

1. Run the following commands:

```bash
docker pull apache/incubator-superset:latest

docker run -d -p 8080:8080 --name superset apache/incubator-superset:latest
```

### Environment

(please complete the following information):

- superset version: `0.999.0dev`
- python version: `3.7.9`
- node.js version: `NA`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I was able to narrow down the origin of the issue to `4d329071a1651994574c3ad1f26e32b56d9ff810` docker tag. The images right before this tag are working fine, all images including and after this tag are crashing

**Comment by robdiciuccio** [comment]
This should be resolved by https://github.com/apache/superset/pull/12079
