### ISSUE TITLE
Unable to use Group by with multiple entries with TIME-SERIES TABLE 

### ISSUE THREAD

**Issue by guoxin-li** [apache/superset#12066]
**Issue**
This issue has been seen in superset 0.26, 0.35, and the latest version of 0.36. When queries with more than one entires of `Group by` for Time-Series Table, the following error is showing up :
 `Unexpected Error
 keys must be str, int, float, bool or None, not tuple`
 [](url)
 **How to reproduce this Error:**
 Use any available data source to create a TIME-SERIES TABLE, add more than one Group by entries and run query
  
  **Trace log**
  `Traceback (most recent call last):
File "/opt/superset/venv/lib/python3.6/site-packages/superset/views/base.py", line 120, in wraps
return f(self, *args, **kwargs)
File "/opt/superset/venv/lib/python3.6/site-packages/superset/utils/decorators.py", line 69, in wrapper
return f(*args, **kwargs)
File "/opt/superset/venv/lib/python3.6/site-packages/superset/views/core.py", line 1092, in explore_json
viz_obj, csv=csv, query=query, results=results, samples=samples
File "/opt/superset/venv/lib/python3.6/site-packages/superset/views/core.py", line 1014, in generate_json
return data_payload_response(*viz_obj.payload_json_and_has_error(payload))
File "/opt/superset/venv/lib/python3.6/site-packages/superset/viz.py", line 478, in payload_json_and_has_error
return self.json_dumps(payload), has_error
File "/opt/superset/venv/lib/python3.6/site-packages/superset/viz.py", line 470, in json_dumps
obj, default=utils.json_int_dttm_ser, ignore_nan=True, sort_keys=sort_keys
File "/opt/superset/venv/lib64/python3.6/site-packages/simplejson/_init_.py", line 412, in dumps
**kw).encode(obj)
File "/opt/superset/venv/lib64/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/opt/superset/venv/lib64/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not tuple
 `

**Comment by kamalkeshavani-aiinside** [comment]
@junlincc Please add appropriate tag to this issue.
I can reproduce this issue still in v1.1.0 and master.

**Comment by tugra-alp** [comment]
This issue is still exist in v1.3.

**Comment by grzesuav** [comment]
seen that on 1.4

**Comment by emgoryaynova** [comment]
Still exists in 2.0.1

**Comment by jinyangzhen** [comment]
yes, still exists in 2.0.1. Any plan to fix

**Comment by mtrentz** [comment]
Also had the same problem with the same error. 

The result query runs fine in postgres.

**Comment by billcrook** [comment]
I see this in 3.0.1 with a time-series table chart.

**Comment by rusackas** [comment]
This obviously isn't getting much traction, as it doesn't seem to be ruining the day of any core committers. I'm tempted to close it since it's over three years old, but I'm guessing it still exists. Anyone on this thread willing to open a PR?

**Comment by kyledufrane** [comment]
still exists in 2.1.3

**Comment by rusackas** [comment]
2.x is no longer supported. We currently support 3.1 and 4.0. Can anyone confirm the issue still exists in supported versions?

**Comment by tfzrch** [comment]
still exists in 4.0.1

**Comment by VikramKumarArammeem** [comment]
@rusackas Same issue still facing with 3.1.2

**Comment by bluespring2812** [comment]
Hi @michael-s-molina, I'm using Superset 4.1.1 and still unable to use group by with multiple dimensions (see the capture).
Can you reopen this issue?

![Image](https://github.com/user-attachments/assets/309fdb04-b2a9-44fb-8a5f-f222b1fadbeb)

**Comment by rusackas** [comment]
This one has gone silent again for a good while. Let's see if @dosu has any helpful advice to unblock things here.

**Comment by HarshithGamini** [comment]
The root cause is the backend logic to get_data( ) in `class TimeTableViz(BaseViz):`

```
    @deprecated(deprecated_in="3.0")
    def get_data(self, df: pd.DataFrame) -> VizData:
        if df.empty:
            return None

        columns = None
        values: list[str] | str = self.metric_labels
        if self.form_data.get("groupby"):
            values = self.metric_labels[0]
            columns = get_column_names(self.form_data.get("groupby"))
        pt = df.pivot_table(index=DTTM_ALIAS, columns=columns, values=values)
        pt.index = pt.index.map(str)
        pt = pt.sort_index()
        return {
            "records": pt.to_dict(orient="index"),
            "columns": list(pt.columns),
            "is_group_by": bool(self.form_data.get("groupby")),
        }
```

@rusackas, Is this supposed to be deprecated in 3.0?
The time-series table chart still uses it as of latest master, we could implement a fix as mentioned by @dosu to flatten tuple keys to strings before returning the dictionary.

**Comment by LisaHusband** [comment]
Hopefully, this Pr (presumably a software or utility) will finally fix this six-year-old issue. 😄
