### ISSUE TITLE
 ⚠️run pip install typing-extensions before running Superset on py38+

### ISSUE THREAD

**Issue by villebro** [apache/superset#12647]
When installing `apache-superset==1.0.0` via `pip` on Python 3.8, the following error appears:

```
$ superset init
Traceback (most recent call last):
  File "/home/ville/.local/bin/superset", line 5, in <module>
    from superset.cli import superset
  File "/home/ville/.local/lib/python3.8/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/home/ville/.local/lib/python3.8/site-packages/superset/app.py", line 48, in <module>
    from superset.utils.log import DBEventLogger, get_event_logger_from_cfg_value
  File "/home/ville/.local/lib/python3.8/site-packages/superset/utils/log.py", line 30, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
```

### Expected results

`superset init` finishes cleanly

### Actual results

Error

#### How to reproduce the bug

1. Install superset via PyPI on Python 3.8: `pip install apache-superset==1.0.0`
2. run `superset init`
3. See error

### Environment

- superset version: 1.0.0
- python version: 3.8

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Workaround: run `pip install typing-extensions` before running Superset.
