### ISSUE TITLE
Chart Emails not working - Superset-1.0.0

### ISSUE THREAD

**Issue by singh-ab** [apache/superset#12871]
Chart Emails functionality doesn't work after upgrading to superset-1.0.0

### Expected results

Sent chart as an Attachment/Inline in an email to the recipient .

### Actual results
Log from Celery Worker

```
[2021-02-01 13:54:00,197: WARNING/MainProcess] Message: Failed to decode response from marionette
, retrying in 30 seconds...
Message: Tried to run command without establishing a connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/superset/utils/celery.py", line 50, in session_scope
    yield session
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 522, in schedule_email_report
    deliver_slice(
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 456, in deliver_slice
    report_content = _get_slice_visualization(slc, delivery_type, session)
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 417, in _get_slice_visualization
    element = retry_call(
  File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection

[2021-02-01 13:54:30,174: ERROR/MainProcess] Message: Tried to run command without establishing a connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/superset/utils/celery.py", line 50, in session_scope
    yield session
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 522, in schedule_email_report
    deliver_slice(
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 456, in deliver_slice
    report_content = _get_slice_visualization(slc, delivery_type, session)
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 417, in _get_slice_visualization
    element = retry_call(
  File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection

[2021-02-01 13:54:30,188: ERROR/MainProcess] Task email_reports.send[0cd34623-3dcb-4b90-91c2-8583247959ba] raised unexpected: InvalidSessionIdException('Tried to run command without establishing a connection', None, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/app.py", line 116, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 522, in schedule_email_report
    deliver_slice(
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 456, in deliver_slice
    report_content = _get_slice_visualization(slc, delivery_type, session)
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 417, in _get_slice_visualization
    element = retry_call(
  File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection
```

#### Screenshots

NA

### Environment

(please complete the following information):

- superset version: `1.0.0`
- python version: `3.8`
- Geckodriver version : `0.24.0`

The following flags are set to enable related functionalities:

```
ENABLE_SCHEDULED_EMAIL_REPORTS = True
EMAIL_NOTIFICATIONS = True
ENABLE_ALERTS = True
SMTP_HOST = "127.0.0.1"
SMTP_STARTTLS = True
SMTP_SSL = False
SMTP_USER = "superset"
SMTP_PORT = 25
SMTP_PASSWORD = "superset"
SMTP_MAIL_FROM = "superset@superset.com"

EMAIL_REPORTS_WEBDRIVER = 'firefox'

EMAIL_REPORTS_USER = 'admin'

WEBDRIVER_BASEURL = 'http://localhost:8088'
```

**Comment by vnourdin** [comment]
We had an error after upgrading to superset v1.0.0 too, it has been fixed by upgrading `geckodriver` from `0.24` to `0.29`!
It wasn't exactly the same error but if it can help someone :shrug:

**Comment by Hammad-Raza** [comment]
@singh-ab How did you fix this issue?

**Comment by singh-ab** [comment]
Hey @Hammad-Raza  I started using the new Alerts & Reports feature and there I didn't find any issues ,  Give it a try !

something related - https://github.com/apache/superset/issues/10996#issuecomment-779077407
