### ISSUE TITLE
After successful deployment and login, internal query with SQL Alchemy fails

### ISSUE THREAD

**Issue by joehoeller** [apache/superset#13080]
Here is the error that is returned after logging in from GUI:

`
Sorry, something went wrong
500 - Internal Server Error
Stacktrace
        Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "user_attribute" does not exist
LINE 2: FROM user_attribute 
             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/superset/views/core.py", line 2545, in welcome
    .filter_by(user_id=g.user.get_id())
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3496, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3463, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3432, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "user_attribute" does not exist
LINE 2: FROM user_attribute 
             ^

[SQL: SELECT user_attribute.welcome_dashboard_id AS user_attribute_welcome_dashboard_id 
FROM user_attribute 
WHERE user_attribute.user_id = %(user_id_1)s]
[parameters: {'user_id_1': '1'}]
(Background on this error at: http://sqlalche.me/e/13/f405)
`

**Comment by joehoeller** [comment]
@willbarrett plz assist (?)

**Comment by willbarrett** [comment]
Hi @joehoeller - please make sure that your database migrations have completed successfully. If there is an issue with the migrations, please post the backtrace here. Additionally, please fill out the Bug Report issue template so we can better assist you.

**Comment by joehoeller** [comment]
There was no migration, this is literally on startup.

**Comment by nytai** [comment]
There is a k8s job that runs migrations and creates the admin user, you'll want to find the logs for that job as it likely failed. It should be suffixed with `-init-db`

The definition is here: https://github.com/apache/superset/blob/b34c86382525811fd707a9c133b9051d5c46a393/helm/superset/templates/init-job.yaml#L17

**Comment by fxulusoy** [comment]
I am also experiencing with the same problem. It doesn't happen all time. But it happens quite often. 

Here is the logs from ` superset-init-db` pod:

```
INFO:superset.security.manager:Creating missing datasource permissions.                                                                                                                                                                                                                 
 Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]                                                                                                                                                                                                                 
 Traceback (most recent call last):                                                                                                                                                                                                                                                      
   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context                                                                                                                                                                               
     cursor, statement, parameters, context                                                                                                                                                                                                                                              
   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute                                                                                                                                                                                   
     cursor.execute(statement, parameters)                                                                                                                                                                                                                                               
 psycopg2.errors.UndefinedTable: relation "tables" does not exist                                                                                                                                                                                                                        
 LINE 2: FROM tables                                                                                                                                                                                                                                                                     
              ^                                                                                                                                                                                                                                                                          
 The above exception was the direct cause of the following exception:                                                                                                                                                                                                                    
 Traceback (most recent call last):                                                                                                                                                                                                                                                      
   File "/usr/local/bin/superset", line 33, in <module>                                                                                                                                                                                                                                  
     sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())                                                                                                                                                                                                      
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__                                                                                                                                                                                                    
     return self.main(*args, **kwargs)                                                                                                                                                                                                                                                   
   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main                                                                                                                                                                                                         
     return super(FlaskGroup, self).main(*args, **kwargs)                                                                                                                                                                                                                                
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main                                                                                                                                                                                                        
     rv = self.invoke(ctx)                                                                                                                                                                                                                                                               
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke                                                                                                                                                                                                     
     return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                                                                                             
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke                                                                                                                                                                                                     
     return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                                                                                                      
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke                                                                                                                                                                                                      
     return callback(*args, **kwargs)                                                                                                                                                                                                                                                    
   File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func                                                                                                                                                                                               
     return f(get_current_context(), *args, **kwargs)                                                                                                                                                                                                                                    
   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator                                                                                                                                                                                                    
     return __ctx.invoke(f, *args, **kwargs)                                                                                                                                                                                                                                             
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke                                                                                                                                                                                                      
     return callback(*args, **kwargs)                                                                                                                                                                                                                                                    
   File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func                                                                                                                                                                                               
     return f(get_current_context(), *args, **kwargs)                                                                                                                                                                                                                                    
   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator                                                                                                                                                                                                    
     return __ctx.invoke(f, *args, **kwargs)                                                                                                                                                                                                                                             
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke                                                                                                                                                                                                      
     return callback(*args, **kwargs)                                                                                                                                                                                                                                                    
   File "/app/superset/cli.py", line 90, in init        
   security_manager.sync_role_definitions()                                                                                                                                                                                                                                            
  File "/app/superset/security/manager.py", line 634, in sync_role_definitions                                                                                                                                                                                                          
    self.create_missing_perms()                                                                                                                                                                                                                                                         
  File "/app/superset/security/manager.py", line 576, in create_missing_perms                                                                                                                                                                                                           
    datasources = ConnectorRegistry.get_all_datasources(self.get_session)                                                                                                                                                                                                               
  File "/app/superset/connectors/connector_registry.py", line 73, in get_all_datasources                                                                                                                                                                                                
    datasources.extend(qry.all())                                                                                                                                                                                                                                                       
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all                                                                                                                                                                                              
    return list(self)                                                                                                                                                                                                                                                                   
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__                                                                                                                                                                                         
    return self._execute_and_instances(context)                                                                                                                                                                                                                                         
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances                                                                                                                                                                           
    result = conn.execute(querycontext.statement, self._params)                                                                                                                                                                                                                         
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute                                                                                                                                                                                        
    return meth(self, multiparams, params)                                                                                                                                                                                                                                              
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection                                                                                                                                                                         
    return connection._execute_clauseelement(self, multiparams, params)                                                                                                                                                                                                                 
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement                                                                                                                                                                         
    distilled_params,                                                                                                                                                                                                                                                                   
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context                                                                                                                                                                               
    e, statement, parameters, cursor, context                                                                                                                                                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception                                                                                                                                                                        
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e                                                                                                                                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_                                                                                                                                                                                          
    raise exception                                                                                                                                                                                                                                                                     
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context                                                                                                                                                                               
    cursor, statement, parameters, context                                                                                                                                                                                                                                              
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute                                                                                                                                                                                   
    cursor.execute(statement, parameters)                                                                                                                                                                                                                                               
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "tables" does not exist                                                                                                                                                                                      
LINE 2: FROM tables                                                                                                                                                                                                                                                                     
             ^                                                                                                                                                                                                                                                                          
[SQL: SELECT tables.uuid AS tables_uuid, tables.created_on AS tables_created_on, tables.changed_on AS tables_changed_on, tables.id AS tables_id, tables.description AS tables_description, tables.default_endpoint AS tables_default_endpoint, tables.is_featured AS tables_is_featured 
FROM tables                                                                                                                                                                                                                                                                             
WHERE tables.is_sqllab_view = false]                                                                                                                                                                                                                                                    
(Background on this error at: http://sqlalche.me/e/13/f405)                                                                                                                                                                                                                             
Creating admin user...                                                                                                                                                                                                                                                                  
logging was configured successfully           
```

I see the following error messages when I try to open the login page:

![Screenshot 2021-06-25 at 16 21 18](https://user-images.githubusercontent.com/1167958/123438926-80c1d580-d5d1-11eb-94e5-aa2e4da62f90.png)
