### ISSUE TITLE
Dashboard fails to load after adding chart

### ISSUE THREAD

**Issue by prb219** [apache/superset#13290]
Hi,

I had a dashboard with few charts that were working as expected. Then I went ahead and added a line chart (which had empty result) into the dashboard which crashed my dashboard and I see the below error. Please note that this issue exists only in one of the dashboard, all other dashboards loads fine. 

### Expected results

expected to load the dashboard
### Actual results

Sorry, something went wrong
500 - Internal Server Error
Stacktrace

        Traceback (most recent call last):
  File "/appvenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/appvenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/appvenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/appvenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/appvenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/appvenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/appvenv/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/appvenv/lib/python3.6/site-packages/superset/views/core.py", line 1616, in dashboard
    for datasource, slices in datasources.items()
  File "/appvenv/lib/python3.6/site-packages/superset/views/core.py", line 1616, in <dictcomp>
    for datasource, slices in datasources.items()
  File "/appvenv/lib/python3.6/site-packages/superset/connectors/base/models.py", line 285, in data_for_slices
    metric_names.add(utils.get_metric_name(metric))
TypeError: unhashable type: 'dict'

#### How to reproduce the bug

- Adding a line chart with no result to dashboard. however, this behavior is not consitent

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ Y] I have reproduced the issue with at least the latest released version of superset.
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Superset version: 0.37.0

**Comment by junlincc** [comment]
Hi @prb219 what do you mean by added `a line chart (which had empty result)` ? This should not be an issue in latest 1.0.1, you want to check it out?

**Comment by zuzana-vej** [comment]
@prb219 , please reopen if you are still facing this on latest version.
