### ISSUE TITLE
Email report not working - 0.36 superset

### ISSUE THREAD

**Issue by pankajshanbhag** [apache/superset#13382]
Test email reports are not working for "Rawdata" and "visualization" with superset 0.36.

Error trace for "rawdata report" :

ERROR/ForkPoolWorker-1] Task email_reports.send[4875e94f-0225-4dc7-a0df-f874e98b419d] raised unexpected: OSError()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/app.py", line 115, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 384, in schedule_email_report
    deliver_slice(schedule)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 345, in deliver_slice
    email = _get_slice_data(schedule)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 271, in _get_slice_data
    response = opener.open(slice_url)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
OSError

Error trace for "visualization" report type:

ile "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 347, in deliver_slice
    email = _get_slice_visualization(schedule)
[2021-02-26 12:05:43,649: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 316, in _get_slice_visualization
    logger.info(f'driver fget url',dr)
[2021-02-26 12:05:43,649: WARNING/ForkPoolWorker-1] Message: 'driver fget url'
Arguments: (None,)
[2021-02-26 12:05:43,656: WARNING/ForkPoolWorker-1] Message: Unable to locate element: .chart-container
, retrying in 60 seconds...
[2021-02-26 12:06:43,765: ERROR/ForkPoolWorker-1] Task email_reports.send[59a35c70-edd7-411f-af0e-5637a1ee60c3] raised unexpected: NoSuchElementException('Unable to locate element: .chart-container', None, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/app.py", line 115, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 384, in schedule_email_report
    deliver_slice(schedule)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 347, in deliver_slice
    email = _get_slice_visualization(schedule)
  File "/usr/local/lib/python3.6/site-packages/superset/tasks/schedules.py", line 324, in _get_slice_visualization
    delay=PAGE_RENDER_WAIT,
  File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .chart-container

WARNING:flask_appbuilder.security.decorators:Access is Denied for: can_dashboard on: Superset
WARNING:flask_appbuilder.security.decorators:Access is Denied for: can_explore_json on: Superset

#### Screenshots

In activity log user is populated as a null for test email reports.

![image](https://user-images.githubusercontent.com/4137720/109508602-0622f680-7ac6-11eb-9248-fe1187857cc8.png)

### Environment

- superset version: 0.36
- python version: 3.6
- node.js version: 12
- Selenium: 3.141.0
- gecko : 0.29
- firefox : 78.7.0esr

**Comment by pankajshanbhag** [comment]
After fixing below mentioned 2 issues superset started sending beautiful chart emails.
- Identified and fixed the issue exists with the way how cookies were used.
- SMTP related code w.r.t email dryrun.
