### ISSUE TITLE
Redis connectivity failing on including special characters in the password.

### ISSUE THREAD

**Issue by skini-galaxia** [apache/superset#13541]
On deploying superset on K8s (with Terraform), connectivity with Redis fails on including special characters in the password.
### Expected results
Superset should connect to Redis on inclusion of special characters in the password, or allowed special characters should be documented.

### Actual results
```
ERROR:superset.views.base:invalid password
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 183, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 211, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/utils/cache.py", line 153, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/utils.py", line 446, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/core.py", line 618, in explore_json
    return self.generate_json(viz_obj, response_type)
  File "/app/superset/views/core.py", line 455, in generate_json
    payload = viz_obj.get_payload()
  File "/app/superset/viz.py", line 443, in get_payload
    payload = self.get_df_payload(query_obj)
  File "/app/superset/viz.py", line 493, in get_df_payload
    cache_value = cache_manager.data_cache.get(cache_key)
  File "/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py", line 248, in get
    return self.cache.get(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_caching/backends/rediscache.py", line 114, in get
    self._read_clients.get(self._get_prefix() + key)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 340, in read_response
    raise error
redis.exceptions.AuthenticationError: invalid password

```

### Version Info. (Chart.yaml)
```
apiVersion: v1
appVersion: "1.0"
description: Apache Superset is a modern, enterprise-ready business intelligence web application
name: superset
maintainers:
  - name: Chuan-Yen Chiang
    email: cychiang0823@gmail.com
    url: https://github.com/cychiang
version: 0.1.0

```

**Comment by caleb15** [comment]
I believe https://github.com/apache/superset/issues/13995 is the cause of your issue. The password needs to be passed into superset, but superset does not have the configuration necessary yet.

**Comment by rusackas** [comment]
Optimistically closing this since the solution proposed has not been confirmed/denied (i.e. the issue is stale) and the issue is about the 1.0 release of Superset, whereas we are currently supporting the 1.5.x and 2.0.x releases. I'm happy to re-open this if anyone still sees it as an issue! Thanks!
