### ISSUE TITLE
Can not log in with admin:admin using docker

### ISSUE THREAD

**Issue by ismailsunni** [apache/superset#13568]
I followed the steps here: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

I can access http://localhost:8088, but I can't log in with the username `admin` and password `admin` as mentioned in the doc above.

### Expected results

I can log in with admin:admin

### Actual results

Invalid login. Please try again.

#### Screenshots

![image](https://user-images.githubusercontent.com/1421861/110754317-fb93fa00-8247-11eb-9e59-0a3e456ff6df.png)

#### How to reproduce the bug

1. Follow the this steps until superset is online on http://localhost:8088
2. Login with username admin and password admin
3. Not possibl

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

```
superset_app            | 127.0.0.1 - - [11/Mar/2021:08:03:29 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.64.0"
superset_app            | 127.0.0.1 - - [11/Mar/2021:08:03:59 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.64.0"
superset_app            | 172.18.0.1 - - [11/Mar/2021:08:04:09 +0000] "GET / HTTP/1.1" 302 243 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
db_1                    | 2021-03-11 08:04:09.501 UTC [34] ERROR:  relation "logs" does not exist at character 13
db_1                    | 2021-03-11 08:04:09.501 UTC [34] STATEMENT:  INSERT INTO logs (action, slice_id, json, dttm, duration_ms) VALUES ('welcome', 0, '{"path": "/superset/welcome/", "object_ref": "Superset.welcome"}', '2021-03-11T08:04:09.501214'::timestamp, 0) RETURNING logs.id
superset_app            | /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
superset_app            |   "Flask-Caching: CACHE_TYPE is set to null, "
superset_app            | ERROR:root:DBEventLogger failed to log event(s)
superset_app            | ERROR:root:(psycopg2.errors.UndefinedTable) relation "logs" does not exist
superset_app            | LINE 1: INSERT INTO logs (action, slice_id, json, dttm, duration_ms)...
superset_app            |                     ^
superset_app            | 
superset_app            | [SQL: INSERT INTO logs (action, slice_id, json, dttm, duration_ms) VALUES (%(action)s, %(slice_id)s, %(json)s, %(dttm)s, %(duration_ms)s) RETURNING logs.id]
superset_app            | [parameters: {'action': 'welcome', 'slice_id': 0, 'json': '{"path": "/superset/welcome/", "object_ref": "Superset.welcome"}', 'dttm': datetime.datetime(2021, 3, 11, 8, 4, 9, 501214), 'duration_ms': 0}]
superset_app            | (Background on this error at: http://sqlalche.me/e/13/f405)
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
superset_app            |     cursor, statement, parameters, context
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
superset_app            |     cursor.execute(statement, parameters)
superset_app            | psycopg2.errors.UndefinedTable: relation "logs" does not exist
superset_app            | LINE 1: INSERT INTO logs (action, slice_id, json, dttm, duration_ms)...
superset_app            |                     ^
superset_app            | 
superset_app            | 
superset_app            | The above exception was the direct cause of the following exception:
superset_app            | 
superset_app            | Traceback (most recent call last):
superset_app            |   File "/app/superset/utils/log.py", line 319, in log
superset_app            |     sesh.bulk_save_objects(logs)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
superset_app            |     return getattr(self.registry(), name)(*args, **kwargs)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2781, in bulk_save_objects
superset_app            |     False,
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2972, in _bulk_save_mappings
superset_app            |     transaction.rollback(_capture_exception=True)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
superset_app            |     with_traceback=exc_tb,
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
superset_app            |     raise exception
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2966, in _bulk_save_mappings
superset_app            |     render_nulls,
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 102, in _bulk_insert
superset_app            |     bookkeeping=return_defaults,
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1083, in _emit_insert_statements
superset_app            |     c = cached_connections[connection].execute(statement, multiparams)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
superset_app            |     return meth(self, multiparams, params)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
superset_app            |     return connection._execute_clauseelement(self, multiparams, params)
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
superset_app            |     distilled_params,
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
superset_app            |     e, statement, parameters, cursor, context
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
superset_app            |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
superset_app            |     raise exception
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
superset_app            |     cursor, statement, parameters, context
superset_app            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
superset_app            |     cursor.execute(statement, parameters)
superset_app            | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "logs" does not exist
superset_app            | LINE 1: INSERT INTO logs (action, slice_id, json, dttm, duration_ms)...
superset_app            |                     ^
superset_app            | 
superset_app            | [SQL: INSERT INTO logs (action, slice_id, json, dttm, duration_ms) VALUES (%(action)s, %(slice_id)s, %(json)s, %(dttm)s, %(duration_ms)s) RETURNING logs.id]
superset_app            | [parameters: {'action': 'welcome', 'slice_id': 0, 'json': '{"path": "/superset/welcome/", "object_ref": "Superset.welcome"}', 'dttm': datetime.datetime(2021, 3, 11, 8, 4, 9, 501214), 'duration_ms': 0}]
superset_app            | (Background on this error at: http://sqlalche.me/e/13/f405)
superset_app            | 172.18.0.1 - - [11/Mar/2021:08:04:09 +0000] "GET /superset/welcome/ HTTP/1.1" 302 221 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
superset_app            | 172.18.0.1 - - [11/Mar/2021:08:04:09 +0000] "GET /login/ HTTP/1.1" 200 24299 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
superset_app            | 172.18.0.1 - - [11/Mar/2021:08:04:20 +0000] "POST /login/ HTTP/1.1" 302 221 "http://localhost:8088/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
superset_app            | 172.18.0.1 - - [11/Mar/2021:08:04:20 +0000] "GET /login/ HTTP/1.1" 200 24363 "http://localhost:8088/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
superset_worker exited with code 127
superset_worker_beat exited with code 127
superset_app            | 127.0.0.1 - - [11/Mar/2021:08:04:29 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.64.0"
```

**Comment by Mapache18** [comment]
Hi Ismail, I believe this issue was solved here: 

[https://github.com/apache/superset/issues/12851#issuecomment-770429813](url)

I ran into the same problem and now I am just waiting for the frontend to load properly.

Regards, Alex

**Comment by srinify** [comment]
Hi @ismailsunni few things to try with Docker workflow:

- Increase RAM that Docker can use for compose to at least 8 GB. This will prevent containers from dying / "timing out"
- I'd try the non-dev workflow (if you're on bleeding edge master) / latest: https://github.com/apache/superset/blob/master/docker-compose-non-dev.yml Use the command `docker-compose -f docker-compose-non-dev.yml up`
