### ISSUE TITLE
Superset 0.38, 0.37 (and potentially others) are broken with sqlachemy 1.4.0 release

### ISSUE THREAD

**Issue by withernet** [apache/superset#13631]
I was installing superset manually and was unable to get the installation to work properly; I had to downgrade to `0.37.2` and downgrade to `sqlalchemy==1.3.23`

### Expected results

Upon installation of `apache-superset=0.38.1` I expect `superset db upgrade` to work properly

### Actual results

The following error is thrown:

```
$ superset db upgrade
Traceback (most recent call last):
  File "/etc/superset/bin/superset", line 5, in <module>
    from superset.cli import superset
  File "/etc/superset/lib/python3.6/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/etc/superset/lib/python3.6/site-packages/superset/app.py", line 24, in <module>
    from flask_appbuilder import expose, IndexView
  File "/etc/superset/lib/python3.6/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
  File "/etc/superset/lib/python3.6/site-packages/flask_appbuilder/api/__init__.py", line 21, in <module>
    from .convert import Model2SchemaConverter
  File "/etc/superset/lib/python3.6/site-packages/flask_appbuilder/api/convert.py", line 4, in <module>
    from flask_appbuilder.models.sqla.interface import SQLAInterface
  File "/etc/superset/lib/python3.6/site-packages/flask_appbuilder/models/sqla/interface.py", line 16, in <module>
    from sqlalchemy_utils.types.uuid import UUIDType
  File "/etc/superset/lib/python3.6/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/etc/superset/lib/python3.6/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/etc/superset/lib/python3.6/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/etc/superset/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/etc/superset/lib/python3.6/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity'
```

`pip list`:
```
$ pip list
Package                Version
---------------------- -----------
aiohttp                3.7.4.post0
alembic                1.5.7
amqp                   2.6.1
apache-superset        0.38.1
apispec                3.3.2
async-timeout          3.0.1
attrs                  20.3.0
Babel                  2.9.0
backoff                1.10.0
billiard               3.6.3.0
bleach                 3.3.0
Brotli                 1.0.9
cachelib               0.1.1
celery                 4.4.7
cffi                   1.14.5
chardet                4.0.0
click                  7.1.2
colorama               0.4.4
contextlib2            0.6.0.post1
croniter               1.0.8
cryptography           3.4.6
dataclasses            0.6
decorator              4.4.2
defusedxml             0.7.1
dnspython              2.1.0
email-validator        1.1.2
Flask                  1.1.2
Flask-AppBuilder       3.2.0
Flask-Babel            1.0.0
Flask-Caching          1.10.0
Flask-Compress         1.9.0
Flask-JWT-Extended     3.25.1
Flask-Login            0.4.1
Flask-Migrate          2.7.0
Flask-OpenID           1.2.5
Flask-SQLAlchemy       2.4.4
flask-talisman         0.7.0
Flask-WTF              0.14.3
future                 0.18.2
geographiclib          1.50
geopy                  2.1.0
greenlet               1.0.0
gunicorn               20.0.4
humanize               3.2.0
idna                   3.1
idna-ssl               1.1.0
importlib-metadata     3.7.3
isodate                0.6.0
itsdangerous           1.1.0
Jinja2                 2.11.3
jsonschema             3.2.0
kombu                  4.6.11
Mako                   1.1.4
Markdown               3.3.4
MarkupSafe             1.1.1
marshmallow            3.10.0
marshmallow-enum       1.5.1
marshmallow-sqlalchemy 0.23.1
msgpack                1.0.2
multidict              5.1.0
mysqlclient            2.0.3
natsort                7.1.1
numpy                  1.19.5
packaging              20.9
pandas                 1.1.5
parsedatetime          2.6
pathlib2               2.3.5
pip                    21.0.1
pkg-resources          0.0.0
polyline               1.4.0
prison                 0.1.3
py                     1.10.0
pyarrow                1.0.1
pycparser              2.20
PyJWT                  1.7.1
pyparsing              2.4.7
pyrsistent             0.17.3
python-dateutil        2.8.1
python-dotenv          0.15.0
python-editor          1.0.4
python-geohash         0.8.5
python3-openid         3.2.0
pytz                   2021.1
PyYAML                 5.4.1
retry                  0.9.2
selenium               3.141.0
setuptools             54.1.2
simplejson             3.17.2
six                    1.15.0
slackclient            2.5.0
SQLAlchemy             1.4.0
SQLAlchemy-Utils       0.36.8
sqlparse               0.3.0
typing-extensions      3.7.4.3
urllib3                1.26.4
vine                   1.3.0
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.36.2
WTForms                2.3.3
WTForms-JSON           0.3.3
yarl                   1.6.3
zipp                   3.4.1
```

#### How to reproduce the bug
It looks like currently superset does not support `sqlalchemy==1.4.0` (it was released less than an hour ago). To reproduce install manually (which default installs `sqlalchemy==1.4.0`

### Environment

(please complete the following information):

- superset version: `0.38.1`
- python version: `Python 3.6.9`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I was able to get superset to work by downgrading:

```
$ pip install apache-superset==0.37.2
$ pip install sqlalchemy==1.3.23
$ superset db upgrade
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/etc/superset/lib/python3.6/site-packages/flask_caching/__init__.py:202: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
No PIL installation found
INFO:superset.utils.screenshots:No PIL installation found
WARNI [alembic.env] SQLite Database support for metadata databases will         be removed in a future version of Superset.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 4e6a06bad7a8, Init
...
```

**Comment by dpgaspar** [comment]
Thank you for reporting.

This seems like an incompatibility between sqlalchemy-utils and the new sqlalchemy. Looking into it.

Has a note, pinning all your dependencies avoids this kind of problems, you can use superset's repo pinned dependencies: https://github.com/apache/superset/blob/master/requirements/base.txt

**Comment by withernet** [comment]
Hi @dpgaspar, thanks for the info. It doesn't look like that file is in `0.37.2` tag? Is that something recently changed?

**Comment by jonasjancarik** [comment]
Just to flag this again (and for future reference/others having the same issue), `pip install apache-superset` now displays `ERROR: flask-appbuilder 3.2.1 has requirement SQLAlchemy<1.4.0, but you'll have sqlalchemy 1.4.3 which is incompatible.` `pip install "SQLAlchemy<1.4.0"` fixes that

**Comment by dpgaspar** [comment]
@jonasjancarik I was able to reproduce, seems that flask-sqlalchemy has launched 2.5.0 that supports sqlalchemy > 1.4.0 already. I'll remove the pinned dependency on Flask-AppBuilder

**Comment by ronaldmeran** [comment]
is there by any chance that `SQLAlchemy` will be upgraded other than the specified versions?
I have to downgrade to `SQLAlchemy==1.3.16` to get it working. My fitbit version is using `SQLAlchemy==1.4.8`

```
Traceback (most recent call last):
  File "/Applications/beingfit/builds/fitbit.visual.io/fitbit.visual.io/bin/superset", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Applications/beingfit/builds/fitbit.visual.io/fitbit.visual.io/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3262, in <module>
    def _initialize_master_working_set():
  File "/Applications/beingfit/builds/fitbit.visual.io/fitbit.visual.io/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "/Applications/beingfit/builds/fitbit.visual.io/fitbit.visual.io/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Applications/beingfit/builds/fitbit.visual.io/fitbit.visual.io/lib/python3.8/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Applications/beingfit/builds/fitbit.visual.io/fitbit.visual.io/lib/python3.8/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Applications/beingfit/builds/fitbit.visual.io/fitbit.visual.io/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (SQLAlchemy 1.4.8 (/Applications/beingfit/builds/fitbit.visual.io/fitbit.visual.io/lib/python3.8/site-packages), Requirement.parse('SQLAlchemy<1.4.0'), {'flask-appbuilder'})
```

```
Using legacy setup.py install for Flask-JWT-Extended, since package 'wheel' is not installed.
Using legacy setup.py install for Flask-OpenID, since package 'wheel' is not installed.
Using legacy setup.py install for Flask-Login, since package 'wheel' is not installed.
Using legacy setup.py install for pyrsistent, since package 'wheel' is not installed.
Using legacy setup.py install for pymeeus, since package 'wheel' is not installed.
ERROR: flask-appbuilder 3.2.2 has requirement SQLAlchemy<1.4.0, but you'll have sqlalchemy 1.4.8 which is incompatible.
```

**Comment by suddjian** [comment]
Closing this as part of issue cleanup.
