### ISSUE TITLE
Scheduled Report Error: An unexpected occurred while executing the report

### ISSUE THREAD

**Issue by sengesh** [apache/superset#13698]
Hi  ,
I migrated to the latest version of superset a couple of days back.
I have configured the config.py & issued celery commands per the documentation.However I 
I have problem on the scheduled report runs.
All my schedulesd reports are getting stuck in the "sending reports" stage.
When I checked the celery worker log I get a weird error on SQLite wheras iam using Postgresql as my data source. can you please help me.

Thank you,
Senthil
I have pasted the celery log below.
[2021-03-19 11:20:00,339: ERROR/ForkPoolWorker-2] (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO report_execution_log (scheduled_dttm, start_dttm, end_dttm, value, value_row_json, state, error_message, report_schedule_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'report_schedule_id': 1, 'error_message': 'Report Schedule is still working, refusing to re-compute.', 'scheduled_dttm': '2021-03-19T05:50:00', 'sta ... (54 characters truncated) ... 858), 'state': <ReportState.WORKING: 'Working'>, 'end_dttm': datetime.datetime(2021, 3, 19, 5, 50, 0, 325991), 'value_row_json': None, 'value': None}]]
Traceback (most recent call last):
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 839, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/base.py", line 775, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/senthil/venvi/lib/python3.8/site-packages/superset/reports/commands/execute.py", line 370, in run
    ReportScheduleStateMachine(
  File "/home/senthil/venvi/lib/python3.8/site-packages/superset/reports/commands/execute.py", line 343, in run
    state_cls(
  File "/home/senthil/venvi/lib/python3.8/site-packages/superset/reports/commands/execute.py", line 282, in next
    self.set_state_and_log(
  File "/home/senthil/venvi/lib/python3.8/site-packages/superset/reports/commands/execute.py", line 86, in set_state_and_log
    self.create_log(
  File "/home/senthil/venvi/lib/python3.8/site-packages/superset/reports/commands/execute.py", line 117, in create_log
    self._session.commit()
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1206, in _execute_context
    self._handle_dbapi_exception(
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 839, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/home/senthil/venvi/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/base.py", line 775, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO report_execution_log (scheduled_dttm, start_dttm, end_dttm, value, value_row_json, state, error_message, report_schedule_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'report_schedule_id': 1, 'error_message': 'Report Schedule is still working, refusing to re-compute.', 'scheduled_dttm': '2021-03-19T05:50:00', 'sta ... (54 characters truncated) ... 858), 'state': <ReportState.WORKING: 'Working'>, 'end_dttm': datetime.datetime(2021, 3, 19, 5, 50, 0, 325991), 'value_row_json': None, 'value': None}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/senthil/venvi/lib/python3.8/site-packages/superset/utils/celery.py", line 50, in session_scope
    yield session
  File "/home/senthil/venvi/lib/python3.8/site-packages/superset/reports/commands/execute.py", line 376, in run
    raise ReportScheduleUnexpectedError(str(ex))
superset.reports.commands.exceptions.ReportScheduleUnexpectedError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO report_execution_log (scheduled_dttm, start_dttm, end_dttm, value, value_row_json, state, error_message, report_schedule_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'report_schedule_id': 1, 'error_message': 'Report Schedule is still working, refusing to re-compute.', 'scheduled_dttm': '2021-03-19T05:50:00', 'sta ... (54 characters truncated) ... 858), 'state': <ReportState.WORKING: 'Working'>, 'end_dttm': datetime.datetime(2021, 3, 19, 5, 50, 0, 325991), 'value_row_json': None, 'value': None}]]
An unexpected occurred while executing the report: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO report_execution_log (scheduled_dttm, start_dttm, end_dttm, value, value_row_json, state, error_message, report_schedule_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'report_schedule_id': 1, 'error_message': 'Report Schedule is still working, refusing to re-compute.', 'scheduled_dttm': '2021-03-19T05:50:00', 'sta ... (54 characters truncated) ... 858), 'state': <ReportState.WORKING: 'Working'>, 'end_dttm': datetime.datetime(2021, 3, 19, 5, 50, 0, 325991), 'value_row_json': None, 'value': None}]]
An unexpected occurred while executing the report: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO report_execution_log (scheduled_dttm, start_dttm, end_dttm, value, value_row_json, state, error_message, report_schedule_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'report_schedule_id': 4, 'error_message': 'Report Schedule is still working, refusing to re-compute.', 'scheduled_dttm': '2021-03-19T05:50:00', 'sta ... (54 characters truncated) ... 341), 'state': <ReportState.WORKING: 'Working'>, 'end_dttm': datetime.datetime(2021, 3, 19, 5, 50, 0, 317469), 'value_row_json': None, 'value': None}]]

**Comment by sengesh** [comment]
Closing this issue as swtching from sqlite db to postgresql for metadata helped resolving this issue.
SQlite doesnt support date-time and hence this scheduling problem arises

**Comment by kha84** [comment]
For those, who want to stay on SQLite there's an easy fix for that - https://github.com/apache/superset/issues/26335#issuecomment-2088308912

**Comment by AdityaKothari27** [comment]
In the file 
“ /venv/lib64/python3.11/site-packages/superset/commands/report/execute.py “ : 

In the create_log method (line:176),

Replace 
``` scheduled_dttm=self._scheduled_dttm, ```
With 
``` scheduled_dttm=( self._scheduled_dttm if isinstance(self._scheduled_dttm, datetime) else datetime.fromisoformat(self._scheduled_dttm) ), ```
