### ISSUE TITLE
Cannot load example data when setting up local environment for development

### ISSUE THREAD

**Issue by JinJis** [apache/superset#13709]
### Expected results

When following the local development setup [guide](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#os-dependencies), example data should be loaded successfully.

### Actual results

All previous steps successfully addressed, but `superset load_examples` step throws below error message.
```
(superset3.7) ➜  superset git:(master) superset load_examples

logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
Loading examples metadata and related data into examples
Traceback (most recent call last):
  File "/Users/jinj/.virtualenvs/superset3.7/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/jinj/.virtualenvs/superset3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jinj/repositories/superset/superset/cli.py", line 198, in load_examples
    load_examples_run(load_test_data, load_big_data, only_metadata, force)
  File "/Users/jinj/repositories/superset/superset/cli.py", line 123, in load_examples_run
    from superset import examples
  File "/Users/jinj/repositories/superset/superset/examples/__init__.py", line 19, in <module>
    from .birth_names import load_birth_names
  File "/Users/jinj/repositories/superset/superset/examples/birth_names.py", line 47, in <module>
    "Admin user does not exist. "
superset.exceptions.NoDataException: Admin user does not exist. Please, check if test users are properly loaded (`superset load_test_users`).
```

* `superset load_test_users` did not fix this bug
* Admin user already created by `superset fab create-admin`

#### How to reproduce the bug

1. Forked the latest repository
2. Follow the [setup guide](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#setup-local-environment-for-development)
3. `superset load_examples`

### Environment

(please complete the following information):

- superset version: `Superset 0.999.0dev`
- python version: `Python 3.7.2`
- node.js version: `v14.13.1`
- MacOS: `Big Sur 11.2.1 (20D74)`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JinJis** [comment]
NVM, quickly looked through the error message today and solved this by creating admin whose username is `admin`.

But still, it may be quite confusing to newcomers because the guide does not warn us to create admin's username as `admin`.

**Comment by grace-shi** [comment]
`superset load_examples` should find a user who is an admin role instead of looking for a user named as admin.

**Comment by Florents-Tselai** [comment]
IMHO this should be marked as a bug and the fix would be what @grace-shi suggested.
Otherwise, the documentation should state explicitly that on top of the `admin role` permission, the `admin` username is something special - which I guess it's a bad design.
