### ISSUE TITLE
Getting Error When using Celery Worker

### ISSUE THREAD

**Issue by Asturias-sam** [apache/superset#14116]
I have configured the celery worker to run the queries in async mode, but when i am running the queries in sql lab they are getting stuck and getting the below stack trace from logs:

```
Traceback (most recent call last):
  File "/opt/superset/venv/lib/python3.7/site-packages/superset/result_set.py", line 144, in __init__
    series, type=pa.timestamp("ns", tz=tz)
  File "pyarrow/array.pxi", line 859, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 265, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 80, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 107, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Did not pass numpy.dtype object
ERROR:superset.result_set:Did not pass numpy.dtype object
```

Can anyone help me with that ?

**Comment by junlincc** [comment]
@robdiciuccio Rob, maybe you can help?
