### ISSUE TITLE
Can't send dashboard emails

### ISSUE THREAD

**Issue by dusatvoj** [apache/superset#14176]
When I setup dashboard emails I can't send any email with this error:
```
Apr 15 21:29:36 node6 celery[1195780]: [2021-04-15 21:29:36,607: INFO/ForkPoolWorker-1] Starting report for slack: None and recipients: vojtech@dusatko.org.
Apr 15 21:29:36 node6 celery[1195780]: No row was found for one()
Apr 15 21:29:36 node6 celery[1195780]: Traceback (most recent call last):
Apr 15 21:29:36 node6 celery[1195780]:   File "/usr/local/lib/python3.8/site-packages/superset/utils/celery.py", line 51, in session_scope
Apr 15 21:29:36 node6 celery[1195780]:     yield session
Apr 15 21:29:36 node6 celery[1195780]:   File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 264, in deliver_dashboard
Apr 15 21:29:36 node6 celery[1195780]:     driver = create_webdriver(session)
Apr 15 21:29:36 node6 celery[1195780]:   File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 208, in create_webdriver
Apr 15 21:29:36 node6 celery[1195780]:     get_reports_user(session)
Apr 15 21:29:36 node6 celery[1195780]:   File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 214, in get_reports_user
Apr 15 21:29:36 node6 celery[1195780]:     session.query(security_manager.user_model)
Apr 15 21:29:36 node6 celery[1195780]:   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3500, in one
Apr 15 21:29:36 node6 celery[1195780]:     raise orm_exc.NoResultFound("No row was found for one()")
Apr 15 21:29:36 node6 celery[1195780]: sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```

### Expected results

Emails are sent without any problem

### Actual results

There's no emails sent and when I setup Dashboard emails I can see error written above. 

#### Screenshots

N/A

#### How to reproduce the bug
1. Setup dashboard emails
2. See error in log

### Environment

(please complete the following information):

- superset version: `1.1.0`
- python version: `3.8.7`
- node.js version: `v12.21.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@willbarrett @lilykuang 🙏

**Comment by robdiciuccio** [comment]
It appears that you're using the older, deprecated alerts & reports functionality. Please see the docs for the new Alerts and Reports functionality: https://superset.apache.org/docs/installation/alerts-reports
