### ISSUE TITLE
Cannot execute superset  "load_examples" normally

### ISSUE THREAD

**Issue by boomballa** [apache/superset#14259]
Surroundings

Python 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux

When I execute step superset load_examples, the following error occurs

(python3_env) shell :~/python3_env/bin# superset load_examples
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/root/python3_env/lib64/python3.6/site-packages/flask_caching/__init__.py:202: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
Creating database reference for examples
INFO:superset.utils.core:Creating database reference for examples
Loading examples metadata and related data into examples
Creating default CSS templates
Loading energy related dataset
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1415, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:877)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/python3_env/bin/superset", line 11, in <module>
    load_entry_point('apache-superset==0.38.1', 'console_scripts', 'superset')()
  File "/root/python3_env/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/python3_env/lib64/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/root/python3_env/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/python3_env/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/python3_env/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/python3_env/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/python3_env/lib64/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/python3_env/lib64/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/root/python3_env/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/python3_env/lib64/python3.6/site-packages/superset/cli.py", line 172, in load_examples
    load_examples_run(load_test_data, only_metadata, force)
  File "/root/python3_env/lib64/python3.6/site-packages/superset/cli.py", line 110, in load_examples_run
    examples.load_energy(only_metadata, force)
  File "/root/python3_env/lib64/python3.6/site-packages/superset/examples/energy.py", line 41, in load_energy
    data = get_example_data("energy.json.gz")
  File "/root/python3_env/lib64/python3.6/site-packages/superset/examples/helpers.py", line 73, in get_example_data
    content = request.urlopen(f"{BASE_URL}{filepath}?raw=true").read()
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1392, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:877)>

Cannot complete normally  load some data to play with .

**Comment by junlincc** [comment]
@betodealmeida tagging the author for answer. 🙏

**Comment by betodealmeida** [comment]
@boomballa Superset is supported only in Python 3.7 and 3.8. Can you try again with a supported version and reopen if it doesn't work? Thanks!

**Comment by boomballa** [comment]
@betodealmeida  Thanks for your reply, are you sure Superset is supported only in Python 3.7 and 3.8? Now I have passed the load_examples step by other means. I first downloaded the resources to the local, and then started an http service with python, changed the BASE_URL in helpers.py to my http service, and it can be executed normally.
