### ISSUE TITLE
[Report] feature (0.38) works for some dashboards but not others

### ISSUE THREAD

**Issue by klazaj** [apache/superset#14447]
I am using Email reporting feature on Superset 0.38.  There is a weird thing happening, where email reporting feature works for some of the dashboards, but not others (namely works on the old dashboards but not the newly created ones). 
I have `admin` as `EMAIL_REPORTS_USER`, so there shouldn't be an issue with permissions (however I suspect this has to do with permissions issues).

This is the error I get from the reporting that doesn't work:

```
[2021-05-03 16:10:36,108: WARNING/ForkPoolWorker-2] Message: Failed to decode response from marionette
, retrying in 30 seconds...
[2021-05-03 16:11:06,138: ERROR/ForkPoolWorker-2] Task email_reports.send[36d8ae67-4f96-466e-879f-9b2e55fa3c85] raised unexpected: InvalidSessionIdException('Tried to run command without establishing a connection', None, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/superset/app.py", line 114, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/superset/tasks/schedules.py", line 375, in schedule_email_report
    deliver_dashboard(schedule)
  File "/app/superset/tasks/schedules.py", line 223, in deliver_dashboard
    get_element, fargs=["grid-container"], tries=2, delay=PAGE_RENDER_WAIT
  File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection
```
Why is this happening and how can I debug this problem?

**Comment by amitmiran137** [comment]
Try out latest version to confirm bug is still reproducable
