### ISSUE TITLE
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' in Ubuntu 20.04

### ISSUE THREAD

**Issue by proteeti13** [apache/superset#14562]
I am trying to install apache superset on ubuntu 20.04 following [these instructions](https://superset.apache.org/docs/installation/installing-superset-from-scratch) (from scratch). While executing the commands 
`pip install apache-superset` & `superset db upgrade`, It gives me the following error:

`bad interpreter: No such file or directory`

So I used `sudo superset db upgrade`, then it is giving me this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 5, in <module>
    from superset.cli import superset
  File "/usr/local/lib/python3.8/dist-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/usr/local/lib/python3.8/dist-packages/superset/app.py", line 24, in <module>
    from flask_appbuilder import expose, IndexView
  File "/usr/local/lib/python3.8/dist-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/flask_appbuilder/api/__init__.py", line 21, in <module>
    from .convert import Model2SchemaConverter
  File "/usr/local/lib/python3.8/dist-packages/flask_appbuilder/api/convert.py", line 4, in <module>
    from flask_appbuilder.models.sqla.interface import SQLAInterface
  File "/usr/local/lib/python3.8/dist-packages/flask_appbuilder/models/sqla/interface.py", line 16, in <module>
    from sqlalchemy_utils.types.uuid import UUIDType
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py)
```

I searched for solutions and found [this](https://stackoverflow.com/questions/66650110/importerror-cannot-import-name-columnentity-ubuntu20-10), I installed SQLAlchemy==1.3.23, but the error persists. I am using Ubuntu 20.04.

#### How to reproduce the bug

1.pip install apache-superset
2.superset db upgrade

### Environment

(please complete the following information):

- superset version: `bash: /home/proteeti/Documents/R&D LAB/superset/superset-env/bin/superset: /home/proteeti/Documents/R&D: bad interpreter: No such file or directory`
- python version: `3.8.5`
- node.js version: `15.5.1`

**Comment by EMCP** [comment]
@dpgaspar I attempted this but then got a different error

```
ubuntu@juju-7ce481-20:~$ pip install sqlalchemy==1.3.24 --force-reinstall
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting sqlalchemy==1.3.24
  Downloading SQLAlchemy-1.3.24-cp38-cp38-manylinux2010_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 28.2 MB/s 
ERROR: flask-appbuilder 3.3.0 has requirement Flask-WTF<0.15.0,>=0.14.2, but you'll have flask-wtf 0.15.1 which is incompatible.
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-1.3.24
ubuntu@juju-7ce481-20:~$ superset db upgrade
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 8, in <module>
    sys.exit(superset())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 527, in get_command
    self._load_plugin_commands()
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 523, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (itsdangerous 2.0.1 (/usr/local/lib/python3.8/dist-packages), Requirement.parse('itsdangerous<2.0,>=0.24'), {'Flask'})
```

**Comment by majid-al-saidi** [comment]
I solve all issues using:
```
pip install itsdangerous==1.1.0
pip install sqlalchemy==1.3.24
pip install flask-appbuilder==3.1.1
pip install werkzeug==0.16.1
pip install flask-WTF==0.14.2
```
