### ISSUE TITLE
Docker apache/superset:latest not working

### ISSUE THREAD

**Issue by pinduvn** [apache/superset#14867]
Hi, I init container with next command:
```
docker run -d -p 8080:8088 --name superset apache/superset
```
but this container not work. The error message is next:
```
[2021-05-27 12:57:21 +0000] [8] [INFO] Starting gunicorn 20.0.4
[2021-05-27 12:57:21 +0000] [8] [INFO] Listening at: http://0.0.0.0:8088 (8)
[2021-05-27 12:57:21 +0000] [8] [INFO] Using worker: gthread
[2021-05-27 12:57:21 +0000] [11] [INFO] Booting worker with pid: 11
Failed to create app
Traceback (most recent call last):
  File "/app/superset/app.py", line 63, in create_app
    app_initializer.init_app()
  File "/app/superset/app.py", line 576, in init_app
    self.pre_init()
  File "/app/superset/app.py", line 95, in pre_init
    os.makedirs(self.config["DATA_DIR"])
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app/superset_home'
[2021-05-27 12:57:22 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 411, in import_app
    app = app(*args, **kwargs)
  File "/app/superset/app.py", line 70, in create_app
    raise ex
  File "/app/superset/app.py", line 63, in create_app
    app_initializer.init_app()
  File "/app/superset/app.py", line 576, in init_app
    self.pre_init()
  File "/app/superset/app.py", line 95, in pre_init
    os.makedirs(self.config["DATA_DIR"])
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app/superset_home'
```
![Screenshot from 2021-05-27 10-00-36](https://user-images.githubusercontent.com/14108241/119830466-ab394980-bed2-11eb-83af-e9c14059190d.png)

Regards

**Comment by dpgaspar** [comment]
@pinduvn thank you for reporting this issue, I was able to replicate and a fix is on it's way

**Comment by shawnzhu** [comment]
I can not reproduce this problem when `apache/superset:latest` with digest `414cf8967ba2`:

```SHELL
$ docker images --digests | grep apache/superset
docker.io/apache/superset                                     latest                                                            sha256:414cf8967ba22fc50e86a0545ae14e26be7745bab0d1d8fe9c827cdebc752d93  fea52a0010a2  4 minutes ago  1.48 GB
$ docker run -d -p 8080:8088 --name superset apache/superset
ec75e84e25151536d729399568ece529da0328c4ee952d0dbaa6b2ecae952b1c
$ docker logs ec75e84e2515
[2021-06-02 13:59:32 +0000] [2] [INFO] Starting gunicorn 20.0.4
[2021-06-02 13:59:32 +0000] [2] [INFO] Listening at: http://0.0.0.0:8088 (2)
[2021-06-02 13:59:32 +0000] [2] [INFO] Using worker: gthread
[2021-06-02 13:59:32 +0000] [5] [INFO] Booting worker with pid: 5
logging was configured successfully
2021-06-02 13:59:33,908:INFO:superset.utils.logging_configurator:logging was configured successfully
2021-06-02 13:59:33,922:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
```

@pinduvn Do you mind delete the image `apache/superset:latest` then fetch it again? this issue should be fixed

**Comment by pinduvn** [comment]
Hi, the bug is solved. regards
