### ISSUE TITLE
Failed to save slice when filters field is empty

### ISSUE THREAD

**Issue by krsnik93** [apache/superset#14988]
Superset failed to save slice/chart when filters were empty. I got around it by setting an artificial filter with `some_field IS NOT NULL` where I knew `some_field` will not be null.

### Expected results

Expect slice/chart to be saved successfully.

### Actual results

"Failed to save slice" in GUI, but only after opening the Save modal again. No feedback at all until the modal is opened.

Logs:
```
Traceback (most recent call last):
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/superset/utils/log.py", line 224, in wrapper
    value = f(*args, **kwargs)
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/superset/views/core.py", line 781, in explore
    datasource.name,
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/superset/views/core.py", line 886, in save_or_overwrite_slice
    form_data.get("adhoc_filters", [])
  File "/home/fedora/superset/venv/lib64/python3.7/site-packages/superset/views/core.py", line 862, in remove_extra_filters
    return [f for f in filters if not f.get("isExtra")]
TypeError: 'NoneType' object is not iterable
eval - with context - False, False
```

#### How to reproduce the bug

I am not sure why this does not happen every time. I know that I was using the Time series table chart when it happened. It happened both with physical and virtual datasets.

### Environment

(please complete the following information):

- superset version: 1.1.0
- python version: 3.7.10

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ShaliniIruvuru** [comment]
Working as Expected in the latest version of Superset 2.1.0.
Loom video:-
https://www.loom.com/share/e021697ce8054ec789ae1a58e3f3823f
