### ISSUE TITLE
Unable to add Snowflake as database

### ISSUE THREAD

**Issue by salano21** [apache/superset#15556]
Unable to add Snowflake as datasource using SQLAlchemy URI

### Expected results

Connection establishes successfully.

### Actual results

Getting errors
   ```
         superset_app            | Traceback (most recent call last):
      superset_app            |   File "/usr/local/lib/python3.7/site-packages/snowflake/connector/network.py", line 934, in _request_exec
      superset_app            |     auth=SnowflakeAuth(token),
      superset_app            |   File "/usr/local/lib/python3.7/site-packages/snowflake/connector/vendored/requests/sessions.py", line 542, in request
      superset_app            |     resp = self.send(prep, **send_kwargs)
      superset_app            |   File "/usr/local/lib/python3.7/site-packages/snowflake/connector/vendored/requests/sessions.py", line 655, in send
      superset_app            |     r = adapter.send(request, **kwargs)
      superset_app            |   File "/usr/local/lib/python3.7/site-packages/snowflake/connector/vendored/requests/adapters.py", line 516, in send
      superset_app            |     raise ConnectionError(e, request=request)
      superset_app            | snowflake.connector.vendored.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='%7brl52352%7d.snowflakecomputing.com', port=443): Max retries exceeded with url: /session/v1/login-request?request_id=c1a69d7d-29da-4fef-901b-a41f5b72e044&databaseName=dev_db&request_guid=6b03223f-8441-4e98-b998-e5bb6a44eff9 (Caused by NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7f9d1787e910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

### Environment

(please complete the following information):

- superset version: `superset version`
   ```
            # superset version
            Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
            logging was configured successfully
            2021-07-06 18:43:45,142:INFO:superset.utils.logging_configurator:logging was configured successfully
            2021-07-06 18:43:45,153:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
            /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:202: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
              "Flask-Caching: CACHE_TYPE is set to null, "
            -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
            Superset 0.999.0dev
            -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```
- python version: `python --version`
   ```
            # python --version
            Python 3.7.9
   ```

- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Unable to establish SQLAlchemy connection, seeing following errors.

```
        superset_app            | Traceback (most recent call last):
        superset_app            |   File "/usr/local/lib/python3.7/site-packages/snowflake/connector/network.py", line 934, in _request_exec
        superset_app            |     auth=SnowflakeAuth(token),
        superset_app            |   File "/usr/local/lib/python3.7/site-packages/snowflake/connector/vendored/requests/sessions.py", line 542, in request
        superset_app            |     resp = self.send(prep, **send_kwargs)
        superset_app            |   File "/usr/local/lib/python3.7/site-packages/snowflake/connector/vendored/requests/sessions.py", line 655, in send
        superset_app            |     r = adapter.send(request, **kwargs)
        superset_app            |   File "/usr/local/lib/python3.7/site-packages/snowflake/connector/vendored/requests/adapters.py", line 516, in send
        superset_app            |     raise ConnectionError(e, request=request)
        superset_app            | snowflake.connector.vendored.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='%7brl52352%7d.snowflakecomputing.com', port=443): Max retries exceeded with url: /session/v1/login-request?request_id=c1a69d7d-29da-4fef-901b-a41f5b72e044&databaseName=dev_db&request_guid=6b03223f-8441-4e98-b998-e5bb6a44eff9 (Caused by NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7f9d1787e910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

## Dependencies:
```
          Package                    Version      Location
          -------------------------- ------------ --------
          aiohttp                    3.7.2
          alembic                    1.4.3
          amqp                       2.6.1
          apache-superset            0.999.0.dev0 /app
          apispec                    3.3.2
          asn1crypto                 1.4.0
          async-timeout              3.0.1
          attrs                      20.2.0
          azure-common               1.1.27
          azure-core                 1.16.0
          azure-storage-blob         12.8.1
          Babel                      2.8.0
          backoff                    1.10.0
          billiard                   3.6.3.0
          bleach                     3.3.0
          boto3                      1.16.10
          botocore                   1.19.10
          Brotli                     1.0.9
          cached-property            1.5.2
          cachelib                   0.1.1
          celery                     4.4.7
          certifi                    2020.6.20
          cffi                       1.14.3
          chardet                    3.0.4
          click                      7.1.2
          colorama                   0.4.4
          contextlib2                0.6.0.post1
          convertdate                2.3.0
          cron-descriptor            1.2.24
          croniter                   0.3.36
          cryptography               3.3.2
          decorator                  4.4.2
          defusedxml                 0.6.0
          Deprecated                 1.2.11
          deprecation                2.1.0
          dnspython                  2.0.0
          email-validator            1.1.1
          et-xmlfile                 1.0.1
          Flask                      1.1.2
          Flask-AppBuilder           3.3.0
          Flask-Babel                1.0.0
          Flask-Caching              1.10.1
          Flask-Compress             1.8.0
          Flask-Cors                 3.0.9
          Flask-JWT-Extended         3.24.1
          Flask-Login                0.4.1
          Flask-Migrate              2.5.3
          Flask-OpenID               1.2.5
          Flask-SQLAlchemy           2.4.4
          flask-talisman             0.7.0
          Flask-WTF                  0.14.3
          future                     0.18.2
          geographiclib              1.50
          geopy                      2.0.0
          gevent                     20.9.0
          graphlib-backport          1.0.3
          greenlet                   0.4.17
          gunicorn                   20.0.4
          holidays                   0.10.3
          humanize                   3.1.0
          idna                       2.10
          ijson                      3.1.2.post0
          importlib-metadata         2.1.1
          isodate                    0.6.0
          itsdangerous               1.1.0
          jdcal                      1.4.1
          Jinja2                     2.11.3
          jmespath                   0.10.0
          jsonlines                  1.2.0
          jsonschema                 3.2.0
          kombu                      4.6.11
          korean-lunar-calendar      0.2.1
          linear-tsv                 1.1.0
          Mako                       1.1.3
          Markdown                   3.3.3
          MarkupSafe                 1.1.1
          marshmallow                3.9.0
          marshmallow-enum           1.5.1
          marshmallow-sqlalchemy     0.23.1
          msgpack                    1.0.0
          msrest                     0.6.21
          multidict                  5.0.0
          mysqlclient                1.4.2.post1
          natsort                    7.0.1
          numpy                      1.19.4
          oauthlib                   3.1.1
          openpyxl                   3.0.5
          oscrypto                   1.2.1
          packaging                  20.4
          pandas                     1.2.2
          parsedatetime              2.6
          pathlib2                   2.3.5
          pgsanity                   0.2.9
          Pillow                     7.2.0
          pip                        21.0.1
          polyline                   1.4.0
          prison                     0.1.3
          psycopg2-binary            2.8.6
          py                         1.9.0
          pyarrow                    4.0.1
          pycparser                  2.20
          pycryptodomex              3.10.1
          pydruid                    0.6.1
          PyGithub                   1.54.1
          PyHive                     0.6.3
          PyJWT                      1.7.1
          PyMeeus                    0.3.7
          pyOpenSSL                  20.0.1
          pyparsing                  2.4.7
          pyrsistent                 0.16.1
          python-dateutil            2.8.1
          python-dotenv              0.15.0
          python-editor              1.0.4
          python-geohash             0.8.5
          python3-openid             3.2.0
          pytz                       2020.4
          PyYAML                     5.4.1
          redis                      3.5.3
          requests                   2.24.0
          requests-oauthlib          1.3.0
          retry                      0.9.2
          rfc3986                    1.4.0
          s3transfer                 0.3.3
          sasl                       0.2.1
          selenium                   3.141.0
          setuptools                 53.0.0
          simplejson                 3.17.2
          six                        1.15.0
          slackclient                2.5.0
          snowflake-connector-python 2.4.6
          snowflake-sqlalchemy       1.2.4
          SQLAlchemy                 1.3.20
          SQLAlchemy-Utils           0.36.8
          sqlparse                   0.3.0
          tableschema                1.20.0
          tabulator                  1.52.5
          thrift                     0.13.0
          thrift-sasl                0.4.2
          typing-extensions          3.7.4.3
          unicodecsv                 0.14.1
          urllib3                    1.25.11
          vine                       1.3.0
          webencodings               0.5.1
          Werkzeug                   1.0.1
          wheel                      0.36.2
          wrapt                      1.12.1
          WTForms                    2.3.3
          WTForms-JSON               0.3.3
          xlrd                       1.2.0
          yarl                       1.6.2
          zipp                       3.4.1
          zope.event                 4.5.0
          zope.interface             5.1.2
```

**Comment by salano21** [comment]
With latest version of Superset, this is no longer an issue. Closing this
