### ISSUE TITLE
error when trying to live on redhat openshift sandbox with gunicorn

### ISSUE THREAD

**Issue by Fluxystems** [apache/superset#15569]
Superset:
VERSION: 0.999.0dev
GIT SHA: 74348b96c5a69c1b2d6980c7ec219e4209b2f1db

Server:
Redhat Openshift Sandbox

Server Logs:

`/opt/app-root/lib64/python3.8/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '0.999.0dev' to '0.999.0.dev0'
  warnings.warn(
---> Serving application with gunicorn (-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
VERSION: 0.999.0dev
GIT SHA: 74348b96c5a69c1b2d6980c7ec219e4209b2f1db
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
apache-superset) ...
[2021-07-07 09:44:12 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2021-07-07 09:44:12 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-07-07 09:44:12 +0000] [1] [INFO] Using worker: sync
[2021-07-07 09:44:12 +0000] [40] [INFO] Booting worker with pid: 40
[2021-07-07 09:44:12 +0000] [40] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-\nVERSION'
[2021-07-07 09:44:12 +0000] [40] [INFO] Worker exiting (pid: 40)
[2021-07-07 09:44:12 +0000] [41] [INFO] Booting worker with pid: 41
[2021-07-07 09:44:12 +0000] [41] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-\nVERSION'
[2021-07-07 09:44:12 +0000] [41] [INFO] Worker exiting (pid: 41)
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>`

gunicorn configs:
`gunicorn \
    --bind  "0.0.0.0:${SUPERSET_PORT}" \
    --access-logfile '-' \
    --error-logfile '-' \
    --workers 1 \
    --worker-class gthread \
    --threads 8 \
    --timeout 60 \
    --limit-request-line 0 \
    --limit-request-field_size 0 \
    "${FLASK_APP}"`

**Comment by cl8790** [comment]
i am facing the same issue. Thank you for raising it.

**Comment by rusackas** [comment]
Closing this as stale since it's been untouched for so long, but I encourage anyone still facing this to join the `#deploying-superset` channel on Slack _or_ open a Q&A thread on Discussions above.
