### ISSUE TITLE
This session is in 'prepared' state; no further SQL can be emitted within this transaction.

### ISSUE THREAD

**Issue by TottiRed777** [apache/superset#16011]
我在退出superset页面后，重新打开dashboard时会报如下错误。
等待2~3分钟后刷新，恢复正常。
我使用的版本是0.38.0。
个人猜测是session复用了，但我不知道如何修改superset的源代码。

}
```
Sorry, something went wrong
500 - Internal Server Error
Stacktrace
        Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/decorators.py", line 78, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/views/core.py", line 1657, in dashboard
    dashboard_data = dash.data
  File "/usr/local/lib/python3.8/site-packages/superset/models/dashboard.py", line 238, in data
    "slices": [slc.data for slc in self.slices],
  File "/usr/local/lib/python3.8/site-packages/superset/models/dashboard.py", line 238, in <listcomp>
    "slices": [slc.data for slc in self.slices],
  File "/usr/local/lib/python3.8/site-packages/superset/models/slice.py", line 191, in data
    f"{owner.first_name} {owner.last_name}" for owner in self.owners
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 275, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 674, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 707, in _load_for_state
    return self._emit_lazyload(
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 848, in _emit_lazyload
    q(session)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 477, in all
    return list(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 380, in __iter__
    return q._execute_and_instances(context)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3102, in _execute_and_instances
    conn = self._get_bind_args(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3110, in _get_bind_args
    return fn(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3096, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1117, in connection
    return self._connection_for_bind(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1125, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 401, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 275, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
 ```

**Comment by junlincc** [comment]
Please fill out the issue template :)
