### ISSUE TITLE
Dataclasses module missing from pip package

### ISSUE THREAD

**Issue by jberkus** [apache/superset#16130]
I installed Superset using the pip package today following the "Install from Scratch" instructions.   Superset fails with a missing module error.

### Expected results

`superset` commands should work

### Actual results

All `superset` commands error with the following:

```
Traceback (most recent call last):
  File "/root/venv/bin/superset", line 11, in <module>
    load_entry_point('apache-superset==0.38.1', 'console_scripts', 'superset')()
  File "/root/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/root/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/root/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/venv/lib64/python3.6/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/root/venv/lib64/python3.6/site-packages/superset/app.py", line 45, in <module>
    from superset.security import SupersetSecurityManager
  File "/root/venv/lib64/python3.6/site-packages/superset/security/__init__.py", line 17, in <module>
    from superset.security.manager import SupersetSecurityManager  # noqa: F401
  File "/root/venv/lib64/python3.6/site-packages/superset/security/manager.py", line 44, in <module>
    from superset import sql_parse
  File "/root/venv/lib64/python3.6/site-packages/superset/sql_parse.py", line 18, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

This is because the 'dataclasses' module is apparently missing as a requirement from the python packaging.

#### How to reproduce the bug

1. Install Superset on a clean CentOS machine following the "Install from scratch" instructions
2. Try to run any `superset` command

### Environment

(please complete the following information):

- superset version: 0.38.1
- python version: 3.6.8
- node.js version:  not installed

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
`dataclasses` was added to the python core lib in 3.7. Looks like you're running 3.6.8. Newer versions of superset specify python version >= 3.7. https://github.com/apache/superset/blob/28c383af68d92bdbfe69fe8c90f8f6a769985b2b/setup.py#L156

I'd suggest your upgrade your python version as well as superset.
