### ISSUE TITLE
Unable to use create database via API: `The CSRF token is missing.`

### ISSUE THREAD

**Issue by buremba** [apache/superset#16398]
### Expected results

`POST /api/v1/database` endpoint should work because it's in the documentation.

### Actual results

When I use the Swagger client embedded into the application (`/swagger/v1`), the API throws the following exception:

```
The CSRF token is missing.
```

Here is a snippet that reproduces the same issue as well:

```
token_request = requests.get("{}/api/v1/security/csrf_token".format(self.superset_url),
                     headers={'Authorization': 'Bearer {}'.format(self.current_access_token)})
if token_request.status_code != 200:
       raise Exception("Unable to get CSRF token: {}".format(token_request.text))
csrf_token = token_request.json().get('result')

r = requests.post("{}/api/v1/database".format(self.superset_url),
                  json={
                      "allow_csv_upload": False,
                      "allow_ctas": True,
                      "allow_cvas": False,
                      "allow_dml": False,
                      "allow_multi_schema_metadata_fetch": True,
                      "allow_run_async": True,
                      "database_name": database_name,
                      "expose_in_sqllab": True,
                      "sqlalchemy_uri": "presto://.."
                  },
                  headers={'Authorization': 'Bearer {}'.format(self.current_access_token), "X-CSRFToken": csrf_token})
```

#### Screenshots

<img width="1336" alt="CleanShot 2021-08-23 at 16 39 28@2x" src="https://user-images.githubusercontent.com/82745/130457225-9266547a-5505-4391-a517-a3bc0861e77c.png">

Environment:

superset version: superset version `1.2.0`
python version: python --version: `python-3.7.10`
node.js version: node -v: not relevant

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by youngsol** [comment]
yea I have same problem.
Temporary solution is register those API to CSRF exempt list.

**Comment by buremba** [comment]
Eventually, I had to mimic the users by creating session cookie and using the internal APIs. :(

**Comment by youngsol** [comment]
@buremba 
yea WTForms requires csrf token in the session.

**Comment by youngsol** [comment]
solution: use requests.session not just request.get/post/put (well get is ok)
```
session = request.Session()
session.get(CSRF TOKEN)
session.post(CREATE DATABASE, headers = {BEARER,X-CSRFTOKEN})
```

**Comment by buremba** [comment]
@youngsol Here is how it works in our case: https://github.com/metriql/metriql-superset/blob/main/metriql2superset/superset.py#L21

**Comment by hitzelc** [comment]
> @youngsol Here is how it works in our case: https://github.com/metriql/metriql-superset/blob/main/metriql2superset/superset.py#L21

You're my hero!

**Comment by lziosi** [comment]
I am using Superset 1.5.0. I have attempted to use the REST APIs for login and for obtaining the CSRF token. 

When I attempt to create a database,  providing the Authorization header and the X-CSRFToken headers, I get:

```{"errors": [{"message": "400 Bad Request: The CSRF session token is missing.", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}```


```
import requests
import json


BASE_URL = ...
USERNAME = ...
PASSWORD = ...
SUPERSET_DB_NAME = ...
DB_NAME = ...
DB_PORT = ...
DB_HOST = ...
DB_USER = ...
DB_PASSWORD = ...


def login(base_url, username, password):
    url = base_url + 'api/v1/security/login'
    payload = {'password': password, 'provider': 'ldap', 'refresh': 'true', 'username': username}
    payload_json = json.dumps(payload)
    headers = {'Content-Type': 'application/json'}
    try:
        # TODO: import the certificate instead of using verify=False
        res = requests.post(url, data=payload_json,
                            verify=False, headers=headers)
        res.raise_for_status()
        access_token = res.json()['access_token']
        refresh_token = res.json()['refresh_token']
        return access_token, refresh_token

    except requests.exceptions.RequestException as err:
        print("Request Exception:", err)


def get_csrf_token(base_url, access_token):
    url = base_url + 'api/v1/security/csrf_token'
    # Construct the Authorization header of the form Bearer access_token
    headers = {'Authorization': 'Bearer ' + access_token}

    try:
        # TODO: import the certificate instead of using verify=False
        res = requests.get(url, verify=False, headers=headers)
        res.raise_for_status()
        csrf_token = res.json()['result']
        return csrf_token

    except requests.exceptions.RequestException as err:
        print("Request Exception:", err)


def create_database(base_url, access_token, csrf_token,
                    superset_database_name, database_name, database_port, database_host,
                    database_user, database_password):
    url = base_url + 'api/v1/database'

    payload = {
        "database_name": superset_database_name,
        "engine": "postgresql",
        "configuration_method": "sqlalchemy_form",
        "sqlalchemy_uri": "postgresql+psycopg2://{}:{}@{}:{}/{}".\
            format(database_user, database_password, database_host, database_port, database_name)
        }
    payload_json = json.dumps(payload)
    #headers = {'Content-Type': 'application/json', 'Authorization': 'Bearer ' + access_token, 'X-CSRFToken': csrf_token}
    try:
        session = requests.Session()
        session.headers['X-CSRFToken'] = csrf_token
        session.headers['Authorization'] = 'Bearer ' + access_token
        session.headers['Content-Type'] = 'application/json'

        # TODO: import the certificate instead of using verify=False
        res = session.post(url, data=payload_json, verify=False)
        print(res.text)
        res.raise_for_status()


    except requests.exceptions.RequestException as err:
        print("Request Exception:", err)



if __name__ == '__main__':
    access_token, refresh_token = login(BASE_URL, USERNAME, PASSWORD)
    csrf_token = get_csrf_token(BASE_URL, access_token)
    create_database(BASE_URL, access_token, csrf_token, SUPERSET_DB_NAME, DB_NAME, DB_PORT, DB_HOST,
                    DB_USER, DB_PASSWORD)
```

**Comment by lziosi** [comment]
In case this helps anyone else, the problem with the above code is that the CSRF token must be obtained in the same session as where it is used, because there is a session cookie added by the call that creates the CSRF token. 
This became evident after reading:
https://github.com/wtforms/flask-wtf/blob/4b90067908f0ab42bf25f4bc580a4367e09e27dd/src/flask_wtf/csrf.py#L66
However, after fixing that, I got the new error:
`400 Bad Request: The referrer header is missing.`
The fix for this second error must take into account the fact that Referrer header should be misspelled as Referer:
https://flask.palletsprojects.com/en/2.1.x/api/#flask.Request.referrer

In the end this code worked fine:
```

import requests
import json
import os

BASE_URL = os.getenv("BASE_URL")
USERNAME = os.getenv("USERNAME")
PASSWORD = os.getenv('PASSWORD')
SUPERSET_DB_NAME = os.getenv('SUPERSET_DB_NAME')
DB_NAME = os.getenv('DB_NAME')
DB_PORT = os.getenv('DB_PORT')
DB_HOST = os.getenv('DB_HOST')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

# https://levelup.gitconnected.com/solve-the-dreadful-certificate-issues-in-python-requests-module-2020d922c72f
# The CA_BUNDLE variable contains the absolute path of a file that has the root-ca, intermediate-ca and site-cert
# The 3 certs can be exported by Google Chrome as individual Base 64 encoded CER files
# Then manually chained into a single file
# When working in a test environment, you can set CA_BUNDLE to False
CA_BUNDLE=False

def login(base_url, username, password):
    url = base_url + 'api/v1/security/login'
    payload = {'password': password, 'provider': 'ldap', 'refresh': 'true', 'username': username}
    payload_json = json.dumps(payload)
    headers = {'Content-Type': 'application/json'}
    try:
        res = requests.post(url, data=payload_json,
                            verify=CA_BUNDLE, headers=headers)
        res.raise_for_status()
        access_token = res.json()['access_token']
        refresh_token = res.json()['refresh_token']
        return access_token, refresh_token

    except requests.exceptions.RequestException as err:
        print("Request Exception:", err)
    except requests.exceptions.HTTPError as errh:
        print("Http Error:", errh)
    except requests.exceptions.ConnectionError as errc:
        print("Error Connecting:", errc)
    except requests.exceptions.Timeout as errt:
        print("Timeout Error:", errt)


def create_database(base_url, access_token,
                    superset_database_name, database_name, database_port, database_host,
                    database_user, database_password):
    csrf_url = base_url + 'api/v1/security/csrf_token'
    # Construct the Authorization header of the form Bearer access_token
    headers = {'Authorization': 'Bearer ' + access_token}

    url = base_url + 'api/v1/database'

    payload = {
        "database_name": superset_database_name,
        "engine": "postgresql",
        "configuration_method": "sqlalchemy_form",
        "sqlalchemy_uri": "postgresql+psycopg2://{}:{}@{}:{}/{}".\
            format(database_user, database_password, database_host, database_port, database_name)
        }
    payload_json = json.dumps(payload)
    try:
        session = requests.Session()
        session.headers['Authorization'] = 'Bearer ' + access_token
        session.headers['Content-Type'] = 'application/json'
        # Note: it is mandatory that the csrf token be obtained in the same session where it will be used
        csrf_res = session.get(csrf_url, verify=CA_BUNDLE)
        # Note that Referrer must be misspelled as Referer, see:
        # https://flask.palletsprojects.com/en/2.1.x/api/#flask.Request.referrer
        # The Referer[sic] request - header field allows the client to specify,
        # for the server’s benefit, the address (URI) of the resource from which the Request-URI was obtained
        # (the “referrer”, although the header field is misspelled).
        session.headers['Referer']= csrf_url
        session.headers['X-CSRFToken'] = csrf_res.json()['result']
        res = session.post(url, data=payload_json, verify=CA_BUNDLE)
        res.raise_for_status()

    except requests.exceptions.RequestException as err:
        print("Request Exception:", err)
    except requests.exceptions.HTTPError as errh:
        print("Http Error:", errh)
    except requests.exceptions.ConnectionError as errc:
        print("Error Connecting:", errc)
    except requests.exceptions.Timeout as errt:
        print("Timeout Error:", errt)


if __name__ == '__main__':
    access_token, refresh_token = login(BASE_URL, USERNAME, PASSWORD)
    create_database(BASE_URL, access_token, SUPERSET_DB_NAME, DB_NAME, DB_PORT, DB_HOST,
                    DB_USER, DB_PASSWORD)
```

**Comment by 1c7** [comment]
@lziosi Very helpful! works for me!

shorter example
```python
def add_dataset(database_id, schema: 'mp_analytic', table_name):
  payload = {
    "database": database_id, # 数据库的 ID
    "schema": schema,
    "table_name": table_name # 数据库表名
  }
  url = f"{base}/api/v1/dataset/"

  session = requests.Session()
  session.headers['Authorization'] = 'Bearer ' + get_access_token()
  session.headers['Content-Type'] = 'application/json'

  csrf_url = f"{base}/api/v1/security/csrf_token/"
  csrf_res = session.get(csrf_url)
  csrf_token = csrf_res.json()['result']

  session.headers['Referer']= csrf_url
  session.headers['X-CSRFToken'] = csrf_token
  
  payload_json = json.dumps(payload)

  r = session.post(url, data=payload_json)
  return r.json()
```

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.

**Comment by Alejandroid17** [comment]
I have the same problem.

When I try to do it from a script, some endpoints don't work, but it works from Postman.

Superset version: 4.1.0

Script:
```python
with requests.Session() as session:
    # ---- LOGIN ----
    url = urllib.parse.urljoin(self.base_url, '/api/v1/security/login')
    payload = {
        "username": self.username,
        "password": self.password,
        "provider": "db",
        "refresh": True,
    }

    response = session.post(url, json=payload)
    response.raise_for_status()

    access_token = response.json()["access_token"]

    # ---- AUTH HEADER ----
    session.headers.update(
        {
            "Authorization": f"Bearer {access_token}",
        }
    )

    # ---- CSRF ----
    csrf_url = urllib.parse.urljoin(self.base_url, '/api/v1/security/csrf_token/')
    csrf_res = session.get(csrf_url)
    csrf_res.raise_for_status()

    csrf_token = csrf_res.json()["result"]

    session.headers.update({"X-CSRFToken": csrf_token})

    print("Cookies:", session.cookies.get_dict())
    print("CSRF:", session.headers.get("X-CSRFToken"))

    # Users - OK
    url = urllib.parse.urljoin(self.base_url, '/api/v1/security/users')
    users_res = session.get(url)
    users_res.raise_for_status()
    print("Users:", users_res.json())

    # Databse - FAIL -> Missing CSRF token
    url = urllib.parse.urljoin(self.base_url, '/api/v1/database/')
    res = session.post(url, json=data)
    res.raise_for_status()
```

Output:
```bash
Cookies: {'session': '63-FMavKIPpx1yPVLucJ......DZ1OLxA-KLDpXHnqo'}
JWT: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI......LA4XQR7rANbqiY
CSRF: IjUyNmY3NTFjODkyZmIxY2JmZmY5MTllNTA3YTcyYjFkYTczODg3NmIi.aY3Pjw.x4vEM5JM92cdFKod8RH6QY1Jm_U
Users: {'count': 2, 'description_columns': {}, .....
```

Trace:
```bash
superset_app          | During handling of the above exception, another exception occurred:
superset_app          | 
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1482, in full_dispatch_request
superset_app          |     rv = self.preprocess_request()
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1974, in preprocess_request
superset_app          |     rv = self.ensure_sync(before_func)()
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
superset_app          |     self.protect()
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask_wtf/csrf.py", line 264, in protect
superset_app          |     self._error_response(e.args[0])
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask_wtf/csrf.py", line 307, in _error_response
superset_app          |     raise CSRFError(reason)
superset_app          | flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
```

Perhaps, related settings:
```python
WTF_CSRF_ENABLED = True

WTF_CSRF_EXEMPT_LIST = [
    "superset.views.core.log",
    "superset.views.core.explore_json",
    "superset.charts.data.api.data",
    "superset.dashboards.api.cache_dashboard_screenshot",
]

 ```

Postman (The bd already exists, but the call is correct.)

<img width="1083" height="903" alt="Image" src="https://github.com/user-attachments/assets/dba264f0-7b49-4759-b014-6e008c4e75c0" />
