### ISSUE TITLE
While deployment facing trouble with “sqlalchemy.exc.InvalidRequestError:”

### ISSUE THREAD

**Issue by amkaushik** [apache/superset#16542]
**SUPERSET_VERSION=0.38.0**

127.0.0.1 - - [30/Aug/2021 07:12:15] "GET /health HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2021 07:12:15] "GET /health HTTP/1.1" 500 -
INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
INFO:superset.utils.logging_configurator:logging was configured successfully
ERROR:superset.app:Failed to create app
Traceback (most recent call last):
  File "/app/superset/app.py", line 62, in create_app
    app_initializer.init_app()
  File "/app/superset/app.py", line 552, in init_app
    self.init_app_in_ctx()
  File "/app/superset/app.py", line 521, in init_app_in_ctx
    self.configure_fab()
  File "/app/superset/app.py", line 592, in configure_fab
    appbuilder.init_app(self.flask_app, db.session)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/base.py", line 202, in init_app
    self.sm = self.security_manager_class(self)
  File "/app/superset/custom_apis/base/custom_main.py", line 29, in __init__
    super(CustomSecurityManager, self).__init__(appbuilder)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/sqla/manager.py", line 55, in __init__
    user_datamodel = SQLAInterface(self.user_model)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 62, in __init__
    for prop in sa.orm.class_mapper(obj).iterate_properties:
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 451, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 430, in _inspect_mapped_class
    mapper._configure_all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1352, in _configure_all
    configure_mappers()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3295, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Alert->alerts'. Original exception was: When initializing mapper mapped class Alert->alerts, expression 'Slice' failed to locate a name ('Slice'). If this is a class name, consider adding this relationship() to the <class 'superset.models.alerts.Alert'> class after both dependent classes have been defined.

**Comment by IKNikolov** [comment]
I have the same issue.

**Comment by rusackas** [comment]
Closing as stale, but happy to re-open if folks are still encountering this.
