### ISSUE TITLE
docker-compose does not work on MacOS OSX

### ISSUE THREAD

**Issue by nabinkhadka** [apache/superset#16579]
There are many github issues created about this. But it seems there is no proper solution. Ideally, the superset should be ready to use with simply `docker-compose up`.  

I have 9 GB and 3 cores allocated to docker. superset_node crashes with the following error:

```
npm ERR! code EIO
npm ERR! syscall rename
npm ERR! path /app/superset-frontend/node_modules/sha.js
npm ERR! dest /app/superset-frontend/node_modules/.sha.js-sPyHcmzN
npm ERR! errno -5
npm ERR! EIO: i/o error, rename '/app/superset-frontend/node_modules/sha.js' -> '/app/superset-frontend/node_modules/.sha.js-sPyHcmzN'
```
This happens at master branch
And on 1.3.0
```
dev@npl:(Downloads/superset) % docker logs -f superset_node

/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@7.22.0
added 70 packages from 27 contributors, removed 250 packages and updated 187 packages in 66.372s
npm WARN using --force Recommended protections disabled.

added 123 packages, and audited 124 packages in 24s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm WARN using --force Recommended protections disabled.

added 67 packages, removed 7 packages, changed 54 packages, and audited 4515 packages in 3m

1 package is looking for funding
  run `npm fund` for details

81 vulnerabilities (11 low, 23 moderate, 47 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
Running frontend

> superset@1.3.0 dev
> webpack --mode=development --colors --debug --watch

/app/superset-frontend/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module './lib/compiler'
Require stack:
- /app/superset-frontend/node_modules/snapdragon/index.js
- /app/superset-frontend/node_modules/braces/lib/braces.js
- /app/superset-frontend/node_modules/braces/index.js
- /app/superset-frontend/node_modules/micromatch/index.js
- /app/superset-frontend/node_modules/findup-sync/index.js
- /app/superset-frontend/node_modules/webpack-cli/bin/utils/convert-argv.js
- /app/superset-frontend/node_modules/webpack-cli/bin/cli.js
- /app/superset-frontend/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/app/superset-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/app/superset-frontend/node_modules/snapdragon/index.js:5:16)
    at Module._compile (/app/superset-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/app/superset-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/app/superset-frontend/node_modules/braces/lib/braces.js:4:18)
    at Module._compile (/app/superset-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/app/superset-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/app/superset-frontend/node_modules/braces/index.js:17:14)
    at Module._compile (/app/superset-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/app/superset-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/app/superset-frontend/node_modules/micromatch/index.js:8:14)
    at Module._compile (/app/superset-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/superset-frontend/node_modules/snapdragon/index.js',
    '/app/superset-frontend/node_modules/braces/lib/braces.js',
    '/app/superset-frontend/node_modules/braces/index.js',
    '/app/superset-frontend/node_modules/micromatch/index.js',
    '/app/superset-frontend/node_modules/findup-sync/index.js',
    '/app/superset-frontend/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/app/superset-frontend/node_modules/webpack-cli/bin/cli.js',
    '/app/superset-frontend/node_modules/webpack/bin/webpack.js'
  ]
}
```

**Comment by nabinkhadka** [comment]
Isn't this something people do like every second around the world?

**Comment by mpope9** [comment]
Have you tried using the non-dev file?

`docker-compose -f docker-compose-non-dev.yml`

**Comment by nabinkhadka** [comment]
@mpope9 I am trying to do dev work, so I am not using that. I believe the non-dev version is only for setting up for a demo or something.

**Comment by vivek-kandhvar** [comment]
Same issue here.. Dev mode is broken in 1.3.0. I had no issues on my MAC M1 running for v1.2.0.
Also when can we expect arm64 compatible images?

**Comment by ashin-krj** [comment]
Facing the same issue here.
`docker-compose up` doesn't work. Shows error on accessing the application.
But the non-dev -dev docker compose is working fine.
![Screenshot 2021-09-22 at 11 43 34 AM](https://user-images.githubusercontent.com/45310108/134292341-51695bab-712f-4182-99cc-48207fc83943.png)

**Comment by qstevens** [comment]
Any news on support for arm64 platform?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and arm64 builds are supported. We're trying to steer toward a more actionable Issues backlog, so if people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
