### ISSUE TITLE
Docker: Error: `prophet` package not installed

### ISSUE THREAD

**Issue by frafra** [apache/superset#16782]
### Expected results

Being able to "Enable forecast" on the `Time-series Line Chart`.

### Actual results
```
Unexpected error

Error: `prophet` package not installed
```

#### How to reproduce the bug

1. Create a "Time-series Line Chart"
2. Click on "Enable forecast"
3. Click on "Run"

### Environment

Docker. Using today's `apache/superset:latest-dev`.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
try and the line` fbprophet` or `prophet`  to your docker/requirements-local.txt file ?

**Comment by frafra** [comment]
Installing `prophet` fixes the issue.

**Comment by frafra** [comment]
Please note that installing prophet via pip seems to not install all its dependencies, due to a known issue in prophet.

**Comment by bbarclay** [comment]
How are you installing prophet, I added to my local.txt nothing must installing, because when I docker-compose down, docker-compose up. It's still not available. Is there something else ˆ need to do .

**Comment by bbarclay** [comment]
ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hnc8oxmp
       cwd: /tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/
  Complete output (44 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/prophet
  creating build/lib/prophet/stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/setup.py", line 123, in <module>
      setup(
    File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/setup.py", line 48, in run
      build_models(target_dir)
    File "/tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/setup.py", line 36, in build_models
      from prophet.models import StanBackendEnum
    File "/tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/prophet/__init__.py", line 8, in <module>
      from prophet.forecaster import Prophet
    File "/tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/prophet/forecaster.py", line 17, in <module>
      from prophet.make_holidays import get_holiday_names, make_holidays_df
    File "/tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/prophet/make_holidays.py", line 14, in <module>
      import prophet.hdays as hdays_part2
    File "/tmp/pip-install-tg4qdtej/prophet_3f1aabcb05dd4d309dec8ab00206b434/prophet/hdays.py", line 14, in <module>
      from lunarcalendar import Lunar, Converter
  ModuleNotFoundError: No module named 'lunarcalendar'
  ----------------------------------------
  ERROR: Failed building wheel for prophet

**Comment by frafra** [comment]
> How are you installing prophet, I added to my local.txt nothing must installing, because when I docker-compose down, docker-compose up. It's still not available. Is there something else ˆ need to do .

Have you read the comment before yours?

> Please note that installing prophet via pip seems to not install all its dependencies, due to a known issue in prophet.
