### ISSUE TITLE
Import of datasources (`superset import-datasources`) fails

### ISSUE THREAD

**Issue by maxcapraro** [apache/superset#17049]
The import of datasources (e.g. the connection to a PostgreSQL database) fails when using `superset import-datasources`. 

#### How to reproduce the bug

First, I performed an export of a database connection:

1. Spin up a new docker container (from my own image which is basically `superset/latest` + my config file)
1. Log into the application and navigate to `databaseview/list`
1. Create a new database by clicking on `+ DATABASE` (for reproduction, I created a new PostgreSQL connection named `db-for-debugging-import`)
1. Export the database by Clicking the Export-Icon in the database list (resulting in this ZIP file: [database_export_20211009T125106.zip](https://github.com/apache/superset/files/7315592/database_export_20211009T125106.zip))

Subsequently, I attempted to import the file: 

1. Unzip the exported datasource, replace the `xxxxxxx...` with the actual password (in this case a throw-away password), make a new zip archive (resulting in this ZIP file: [database_export_20211009T125106.zip](https://github.com/apache/superset/files/7315599/database_export_20211009T125106.zip))
1. Spin up a new docker container
1. Import the ZIP file by executing `superset import-datasources -p ...` in the container's shell

### Expected results

I expected the database to show up under `databaseview/list` and e.g. being able to use it when creating a new dataset (selecting the database, a schema, and a table). 

### Actual results

When importing via `superset import-datasources -p`, the logs contained the following:
````
superset@kolabri-dashboard-deployment-dd8dd7754-p5sq5:/app$ superset import_datasources -p /kolabri-assets/database_export_20211009T125106.zip
Loaded your LOCAL configuration at [/kolabri-assets/superset_config.py]
logging was configured successfully
2021-10-09 13:27:15,936:INFO:superset.utils.logging_configurator:logging was configured successfully
2021-10-09 13:27:15,946:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/usr/local/lib/python3.8/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
Command failed validation
2021-10-09 13:27:17,396:INFO:superset.datasets.commands.importers.dispatcher:Command failed validation
There was an error when importing the dataset(s), please check the exception traceback in the log
Traceback (most recent call last):
  File "/app/superset/cli.py", line 384, in import_datasources
    ImportDatasetsCommand(contents, overwrite=True).run()
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 64, in run
    raise exc
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/importers/v1/__init__.py", line 63, in run
    self.validate()
  File "/app/superset/commands/importers/v1/__init__.py", line 146, in validate
    raise exception
superset.commands.exceptions.CommandInvalidError: Error importing dataset
2021-10-09 13:27:17,396:ERROR:superset.cli:There was an error when importing the dataset(s), please check the exception traceback in the log
Traceback (most recent call last):
  File "/app/superset/cli.py", line 384, in import_datasources
    ImportDatasetsCommand(contents, overwrite=True).run()
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 64, in run
    raise exc
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/importers/v1/__init__.py", line 63, in run
    self.validate()
  File "/app/superset/commands/importers/v1/__init__.py", line 146, in validate
    raise exception
superset.commands.exceptions.CommandInvalidError: Error importing dataset
````

### Environment

(please complete the following information):

- browser type and version: `Version 94.0.4606.71 (x86_64)`
- superset version: `0.0.0dev` (last pull of the base image was a on October 4th)
- python version: `Python 3.8.12`
- node.js version: No node.js installed
- any feature flags active:
  - `'VERSIONED_EXPORT' : True`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

Regarding the second checkbox: I am happy to reproduce this with another "proper" version if this helps, but from [this](https://hub.docker.com/r/apache/superset) I am not 100% sure this is possible yet using the docker images :-)

### Additional context

- When importing the ZIP-file via the UI, the import succeeds. Though, an error message appears when trying to edit the database connection: `ERROR: Please re-enter the password`. I am not sure if this is the expected behaviour or part of the issue.
- It appears to me (from my outsider's perspective) that this bug is not identical to #16858 and #16848

I am happy to help if any additional info / debugging is useful and thanks in advance for the help :)

**Comment by andrzejmartyna** [comment]
I experienced the same inconsistency between importing from file and entering from UI.
"Please re-enter the password" is especially irritating because:
- the connection does not work in dashboards unless you... re-enter the password
- you cannot enter the password just by modifying connection string because it says again "re-enter the password"
	- workaround 1 [failed]: trying to change the password, save, and then change to the correct password ("save" not allowed as it is not a valid collection - should it be allowed? I believe a very valid situation may be that the database is not available at the time of configuration)
	- workaround 2 (succeeded): enter valid, **_but different_**, connection string, save, go back and enter correct connection string, save

**Comment by rusackas** [comment]
I'm hesitant to close this issue as stale, but a little tempted ;)

Can anyone confirm or deny whether or not this remains an issue in Superset 2.0.1? Thanks in advance!

**Comment by carusooo** [comment]
Yes, I am able to repro this in `2.0.1`.

Importing via the command line

```
superset import_datasources -p datasource.zip
```

Fails with:
```
Command failed validation
2023-02-16 01:21:29,301:INFO:superset.datasets.commands.importers.dispatcher:Command failed validation
There was an error when importing the dataset(s), please check the exception traceback in the log
Traceback (most recent call last):
  File "/app/superset/cli/importexport.py", line 193, in import_datasources
    ImportDatasetsCommand(contents, overwrite=True).run()
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 64, in run
    raise exc
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/importers/v1/__init__.py", line 64, in run
    self.validate()
  File "/app/superset/commands/importers/v1/__init__.py", line 95, in validate
    raise exception
superset.commands.exceptions.CommandInvalidError: Error importing dataset
2023-02-16 01:21:29,301:ERROR:superset.cli.importexport:There was an error when importing the dataset(s), please check the exception traceback in the log
Traceback (most recent call last):
  File "/app/superset/cli/importexport.py", line 193, in import_datasources
    ImportDatasetsCommand(contents, overwrite=True).run()
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 64, in run
    raise exc
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/importers/v1/__init__.py", line 64, in run
    self.validate()
  File "/app/superset/commands/importers/v1/__init__.py", line 95, in validate
    raise exception
superset.commands.exceptions.CommandInvalidError: Error importing dataset
```

It's also unclear because [the documentation] mentions that YAML files are supported for import but the output of `superset import_datasources --help` shows that only ZIP is supported:
```
Usage: superset import-datasources [OPTIONS]

  Import datasources from ZIP file

Options:
  -p, --path TEXT  Path to a single ZIP file
  --help           Show this message and exit.
  ```

**Comment by sebastianliebscher** [comment]
I can reproduce this with [latest master](https://github.com/apache/superset/tree/71d0543f28711ed70fcfb8086489661596aa2075) branch in dev environment (docker-compose.yaml).

steps to reproduce:

1. `docker-compose up`
2. `superset load-examples -f`
3. `superset export-datasources -f export.zip`
4. `unzip export.zip` and replace XXXX with `superset` in examples database yaml
5. `zip -r export.zip dataset_export_20230522T165815`
6. `superset import-datasources -p export.zip`

the import fails with:

```bash
2023-05-22 17:00:45,370:ERROR:superset.datasets.commands.importers.dispatcher:Error running import command
Traceback (most recent call last):
  File "/app/superset/commands/importers/v1/__init__.py", line 78, in run
    self._import(db.session, self._configs, self.overwrite)
  File "/app/superset/datasets/commands/importers/v1/__init__.py", line 59, in _import
    database = import_database(session, config, overwrite=False)
  File "/app/superset/databases/commands/importers/v1/utils.py", line 35, in import_database
    can_write = ignore_permissions or security_manager.can_access(
  File "/app/superset/security/manager.py", line 351, in can_access
    user = g.user
  File "/usr/local/lib/python3.9/site-packages/flask/ctx.py", line 52, in __getattr__
    raise AttributeError(name) from None
AttributeError: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/importers/v1/__init__.py", line 85, in run
    raise self.import_error() from ex
superset.datasets.commands.exceptions.DatasetImportError: Import dataset failed for an unknown reason
2023-05-22 17:00:45,371:ERROR:superset.cli.importexport:There was an error when importing the dataset(s), please check the exception traceback in the log
Traceback (most recent call last):
  File "/app/superset/commands/importers/v1/__init__.py", line 78, in run
    self._import(db.session, self._configs, self.overwrite)
  File "/app/superset/datasets/commands/importers/v1/__init__.py", line 59, in _import
    database = import_database(session, config, overwrite=False)
  File "/app/superset/databases/commands/importers/v1/utils.py", line 35, in import_database
    can_write = ignore_permissions or security_manager.can_access(
  File "/app/superset/security/manager.py", line 351, in can_access
    user = g.user
  File "/usr/local/lib/python3.9/site-packages/flask/ctx.py", line 52, in __getattr__
    raise AttributeError(name) from None
AttributeError: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/cli/importexport.py", line 193, in import_datasources
    ImportDatasetsCommand(contents, overwrite=True).run()
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 68, in run
    raise exc
  File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/importers/v1/__init__.py", line 85, in run
    raise self.import_error() from ex
superset.datasets.commands.exceptions.DatasetImportError: Import dataset failed for an unknown reason

```

**Comment by toch** [comment]
I'm experimenting the same issue. I also tried several versions as @carusooo and @sebastianliebscher and got the same trace logs than the ones they respectively shared.

**Comment by ddxv** [comment]
I'm also encountering this issue. Did anyone ever understand what causes this or how it should be worked around? 

My flow:

1. Docker Compose up
2. Inside Docker: `superset export_datasources -f myexport.zip`
3. Docker copy to a local directory
4. Docker compose down
5. Docker compose up with` superset import_datasources -p /myexport.zip` at the end of my init file.

**Comment by ddxv** [comment]
OK, a bit more reading of the stack trace and we get to here:

https://github.com/apache/superset/blob/3.1.0/superset/commands/dataset/importers/v1/utils.py
```py
def import_dataset(
    session: Session,
    config: dict[str, Any],
    overwrite: bool = False,
    force_data: bool = False,
    ignore_permissions: bool = False,
) -> SqlaTable:
    can_write = ignore_permissions or security_manager.can_access(
        "can_write",
        "Dataset",
    )
```

`security_manager` is the one who tries `g.user` which fails. I've seen @betodealmeida might know more about this, is the check for security_manager needed here for import_dataset? I see other functions in the `cli/importexport.py` use the `g.user = security_manager.find_user(username="admin")` which might need to be set earlier in the `import_datasources`, do you think that is appropriate?

**Comment by mannbl** [comment]
I am still facing this issue even with -u admin

**Comment by yalattas** [comment]
still facing same issue. Should I mount any volume to the pods ??
Is it saving dashboards locally within the pod ?

**Comment by fertek** [comment]
I'm sharing my experience. I couldn't import dashboards and other assets due to the **DB_CONNECTION_MUTATOR** setting. It was difficult to debug because I didn't expect that DB_CONNECTION_MUTATOR would play any role when importing a ZIP file with YAML configurations.

I tried different import options:

```
superset import-dashboards --path PATH_TO_ZIP_FILE --username admin
superset-cli -u "admin" -p "admin" http://localhost:8088 import-assets PATH_TO_DIR
curl --request POST "http://localhost:8088/api/v1/dashboard/import/" …
```

**Comment by driucorado** [comment]
still having the same issue. as @fertek  is there any update on this? and also can you shared an script that works? like a python script that does the call to the endpoint? i try many ways but still does not work. Thanks in advance.

**Comment by fertek** [comment]
@driucorado 

I use this bash script `import_dashboards.sh`:

```
#!/bin/bash
set -e

ZIP_FILE="$HOME/path_to/assets.zip"

echo "Importing dashboards from $ZIP_FILE..."
export FLASK_APP=superset SUPERSET_CONFIG_PATH=./superset_config.py
uv run superset import-dashboards --path "$ZIP_FILE" --username admin

echo "Import completed successfully!"
```
