### ISSUE TITLE
Can't sort by timestamp column

### ISSUE THREAD

**Issue by gabrielpeixoto** [apache/superset#17122]
#### How to reproduce the bug

1. Create a Mysql query with a timestamp column on result
2. Click on Explore
3. Try to sort by the timestamp column

### Expected results

The chart sorted by timestamp

### Actual results

Unexpected error
'data'

Log file:
```
Traceback (most recent call last):

File "/app/superset/views/base.py", line 204, in wraps

return f(self, *args, **kwargs)

File "/app/superset/utils/log.py", line 242, in wrapper

value = f(*args, **kwargs)

File "/app/superset/utils/cache.py", line 167, in wrapper

return f(*args, **kwargs)

File "/app/superset/views/utils.py", line 479, in wrapper

return f(*args, **kwargs)

File "/app/superset/views/core.py", line 678, in explore_json

return self.generate_json(viz_obj, response_type)

File "/app/superset/views/core.py", line 476, in generate_json

payload = viz_obj.get_payload()

File "/app/superset/viz.py", line 455, in get_payload

payload["data"] = self.get_data(df)

File "/app/superset/viz.py", line 1796, in get_data

row = df.groupby(self.groupby).sum()[sortby].copy()

File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__

indexer = self.columns.get_loc(key)

File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3083, in get_loc

raise KeyError(key) from err

KeyError: 'data'

2021-10-14 23:19:15,699:ERROR:superset.views.base:'data'

Traceback (most recent call last):

File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3081, in get_loc

return self._engine.get_loc(casted_key)

File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc

File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc

File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item

File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'data'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/app/superset/views/base.py", line 204, in wraps

return f(self, *args, **kwargs)

File "/app/superset/utils/log.py", line 242, in wrapper

value = f(*args, **kwargs)

File "/app/superset/utils/cache.py", line 167, in wrapper

return f(*args, **kwargs)

File "/app/superset/views/utils.py", line 479, in wrapper

return f(*args, **kwargs)

File "/app/superset/views/core.py", line 678, in explore_json

return self.generate_json(viz_obj, response_type)

File "/app/superset/views/core.py", line 476, in generate_json

payload = viz_obj.get_payload()

File "/app/superset/viz.py", line 455, in get_payload

payload["data"] = self.get_data(df)

File "/app/superset/viz.py", line 1796, in get_data

row = df.groupby(self.groupby).sum()[sortby].copy()

File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__

indexer = self.columns.get_loc(key)
```

#### Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/3699061/137409262-6e7e3411-1f65-4d99-b9bb-ddc3ec8320de.png)

![Screenshot_2](https://user-images.githubusercontent.com/3699061/137409265-86998cb7-33dd-489f-890f-c4633869382a.png)

### Environment

- Docker: apache/superset:latest-dev

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Seems to be working just fine in current-era Superset. Closing as resolved.
