### ISSUE TITLE
importlib_metadata.PackageNotFoundError: No package metadata was found for apache-superset

### ISSUE THREAD

**Issue by CWJ-NB** [apache/superset#18022]
`superset init` error:
```
(superset) cwj0@ubuntu:~/anaconda3/envs/superset/lib/python3.7/site-packages/incubator-superset$ superset init
Traceback (most recent call last):
  File "/home/cwj0/anaconda3/envs/superset/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/home/cwj0/anaconda3/envs/superset/bin/superset", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/home/cwj0/anaconda3/envs/superset/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 951, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/cwj0/anaconda3/envs/superset/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 542, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for apache-superset
```
`superset db migrate` and `superset db upgrade` also getting the same error. How to solve this problem? Thanks！

**Comment by CWJ-NB** [comment]
Solved.
Because this is the need to refresh the permissions after I add a new page, I don't know why the dependencies are missing, and the installation is solved.

`pip install -r requirements/local.txt`，`pip install -e .`
```bash
(superset) cwj0@ubuntu:~/anaconda3/envs/superset/lib/python3.7/site-packages/incubator-superset$ pip install -r requirements/local.txt

(superset) cwj0@ubuntu:~/anaconda3/envs/superset/lib/python3.7/site-packages/incubator-superset$ pip install -e .

(superset) cwj0@ubuntu:~/anaconda3/envs/superset/lib/python3.7/site-packages/incubator-superset$ superset init
Loaded your LOCAL configuration at [/home/cwj0/anaconda3/envs/superset/lib/python3.7/site-packages/incubator-superset/superset_config.py]
logging was configured successfully
2022-01-14 08:45:43,385:INFO:superset.utils.logging_configurator:logging was configured successfully
2022-01-14 08:45:43,428:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Syncing role definition
2022-01-14 08:45:48,268:INFO:superset.security.manager:Syncing role definition
Syncing Admin perms
2022-01-14 08:45:48,296:INFO:superset.security.manager:Syncing Admin perms
Syncing Alpha perms
2022-01-14 08:45:48,538:INFO:superset.security.manager:Syncing Alpha perms
Syncing Gamma perms
2022-01-14 08:45:48,784:INFO:superset.security.manager:Syncing Gamma perms
Syncing granter perms
2022-01-14 08:45:49,031:INFO:superset.security.manager:Syncing granter perms
Syncing sql_lab perms
2022-01-14 08:45:49,270:INFO:superset.security.manager:Syncing sql_lab perms
Fetching a set of all perms to lookup which ones are missing
2022-01-14 08:45:49,498:INFO:superset.security.manager:Fetching a set of all perms to lookup which ones are missing
Creating missing datasource permissions.
2022-01-14 08:45:49,723:INFO:superset.security.manager:Creating missing datasource permissions.
Creating missing database permissions.
2022-01-14 08:45:49,752:INFO:superset.security.manager:Creating missing database permissions.
Cleaning faulty perms
2022-01-14 08:45:49,756:INFO:superset.security.manager:Cleaning faulty perms
```
