### ISSUE TITLE
Apache Superset schedule email reports issue

### ISSUE THREAD

**Issue by kyarali** [apache/superset#18030]
Hello

When I create a new email reports from Apache Superset schedule mail, I'm getting the following OS errors from Celery worker.

How can I solve that issue?

[2022-01-13 17:21:19,871: ERROR/ForkPoolWorker-4] Task email_reports.send[dd4bbba5-cfc4-4b2f-858d-2f3d8fa0a473] raised unexpected: OSError()
Traceback (most recent call last):
  File "/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/python3.8/site-packages/superset/initialization/__init__.py", line 103, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/python3.8/site-packages/superset/tasks/schedules.py", line 528, in schedule_email_report
    deliver_slice(
  File "/python3.8/site-packages/superset/tasks/schedules.py", line 460, in deliver_slice
    report_content = _get_slice_data(slc, delivery_type, session)
  File "/python3.8/site-packages/superset/tasks/schedules.py", line 342, in _get_slice_data
    response = opener.open(slice_url)
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
OSError

Thanks

**Comment by geido** [comment]
Hello @kyarali please provide the Superset version that you are running and any other useful information to reproduce the issue. Thank you

**Comment by kyarali** [comment]
Hello 

Apache superset version: 1.3.2
Python version: 3.8
OS Type: RHEL8

Thanks
