### ISSUE TITLE
Apache superset SMTP issue (535, b'5.7.3 Authentication unsuccessful') 

### ISSUE THREAD

**Issue by kyarali** [apache/superset#18044]
Hello

I'm facing Authentication unsuccessful error when I try to send mail from Apache Superset.

I checked the document's SMTP integration chapter:

https://apache-superset.readthedocs.io/en/latest/installation.html

EMAIL_NOTIFICATIONS = True

SMTP_HOST = "email-smtp.eu-west-1.amazonaws.com"
SMTP_STARTTLS = True
SMTP_SSL = False
SMTP_USER = "smtp_username"
SMTP_PORT = 25
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD")
SMTP_MAIL_FROM = "insights@komoot.com"

I changed SMTP_PASSWORD parameter and I entered password manually in my config.py file like SMTP_PASSWORD = "'xxx!!'" (I added '' because my password includes special character like '!'. Also, I tried SMTP_PASSWORD="xx!!" but also I'm getting error. 

[2022-01-14 12:12:29,794: ERROR/ForkPoolWorker-4] Task email_reports.send[719c1c3a-c463-4fac-84ac-c026087eb072] raised unexpected: SMTPAuthenticationError(535, b'5.7.3 Authentication unsuccessful')
Traceback (most recent call last):
  File "python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "python3.8/site-packages/superset/initialization/__init__.py", line 103, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "python3.8/site-packages/superset/tasks/schedules.py", line 528, in schedule_email_report
    deliver_slice(
  File "python3.8/site-packages/superset/tasks/schedules.py", line 473, in deliver_slice
    _deliver_email(
  File "python3.8/site-packages/superset/tasks/schedules.py", line 141, in _deliver_email
    send_email_smtp(
  File "python3.8/site-packages/superset/utils/core.py", line 959, in send_email_smtp
    send_mime_email(smtp_mail_from, recipients, msg, config, dryrun=dryrun)
  File "python3.8/site-packages/superset/utils/core.py", line 985, in send_mime_email
    smtp.login(smtp_user, smtp_password)
  File "/usr/lib64/python3.8/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/lib64/python3.8/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib64/python3.8/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.3 Authentication unsuccessful')

I can login with my SMTP user via browser (Exchange). Could you please help me to solve this issue?

Apache Superset version:  1.3.2
Python version:3.8
OS version: RHEL 8

Thanks

**Comment by ad-m** [comment]
@kyarali, could you try connect to Exchange via SMTP eg. via Thunderbird / CURL ( https://everything.curl.dev/usingcurl/smtp )? 

See also https://mkerala.com/solution-535-5-7-3-authentication-unsuccessful-office-365-smtp-error/ :
> The error usually occur when SMTP is not enabled in Office 365 for the affected.
