### ISSUE TITLE
Invalid decryption key issue

### ISSUE THREAD

**Issue by curious86** [apache/superset#18077]
When starting superset using docker-compose up in local, I am seeing the following error:

```
superset_init            | Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
superset_init            | Traceback (most recent call last):
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
superset_init            |     decrypted = decrypted.decode('utf-8')
superset_init            | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: invalid start byte
superset_init            | 
superset_init            | During handling of the above exception, another exception occurred:
superset_init            | 
superset_init            | Traceback (most recent call last):
superset_init            |   File "/usr/local/bin/superset", line 33, in <module>
superset_init            |     sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
superset_init            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
superset_init            |     return self.main(*args, **kwargs)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
superset_init            |     return super(FlaskGroup, self).main(*args, **kwargs)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
superset_init            |     rv = self.invoke(ctx)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
superset_init            |     return _process_result(sub_ctx.command.invoke(sub_ctx))
superset_init            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
superset_init            |     return ctx.invoke(self.callback, **ctx.params)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
superset_init            |     return callback(*args, **kwargs)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
superset_init            |     return f(get_current_context(), *args, **kwargs)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
superset_init            |     return __ctx.invoke(f, *args, **kwargs)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
superset_init            |     return callback(*args, **kwargs)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
superset_init            |     return f(get_current_context(), *args, **kwargs)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
superset_init            |     return __ctx.invoke(f, *args, **kwargs)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
superset_init            |     return callback(*args, **kwargs)
superset_init            |   File "/app/superset/cli.py", line 93, in init
superset_init            |     security_manager.sync_role_definitions()
superset_init            |   File "/app/superset/security/manager.py", line 704, in sync_role_definitions
superset_init            |     self.create_missing_perms()
superset_init            |   File "/app/superset/security/manager.py", line 646, in create_missing_perms
superset_init            |     merge_pv("datasource_access", datasource.get_perm())
superset_init            |   File "/app/superset/connectors/sqla/models.py", line 636, in get_perm
superset_init            |     return f"[{self.database}].[{self.table_name}](id:{self.id})"
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 294, in __get__
superset_init            |     return self.impl.get(instance_state(instance), dict_)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 730, in get
superset_init            |     value = self.callable_(state, passive)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 759, in _load_for_state
superset_init            |     return self._emit_lazyload(
superset_init            |   File "<string>", line 1, in <lambda>
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 847, in _emit_lazyload
superset_init            |     q(session)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 615, in _load_on_pk_identity
superset_init            |     result = list(bq.for_session(self.session).params(**params))
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
superset_init            |     cursor.close()
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
superset_init            |     compat.raise_(
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
superset_init            |     raise exception
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
superset_init            |     rows = [proc(row) for row in fetch]
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
superset_init            |     rows = [proc(row) for row in fetch]
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 579, in _instance
superset_init            |     _populate_full(
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
superset_init            |     dict_[key] = getter(row)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 1278, in process
superset_init            |     return process_value(impl_processor(value), dialect)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 477, in process_result_value
superset_init            |     value = super().process_result_value(value=value, dialect=dialect)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 422, in process_result_value
superset_init            |     decrypted_value = self.engine.decrypt(value)
superset_init            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 130, in decrypt
superset_init            |     raise ValueError('Invalid decryption key')
superset_init            | ValueError: Invalid decryption key
```

I have no idea what is a decryption key? And why I am getting this:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: invalid start byte`

How can I fix it?

**Comment by curious86** [comment]
This issue is now resolved, thanks to this post:
https://github.com/apache/superset/issues/8538#issuecomment-922061313

Additionally, I needed to get the Postgres metadata host db running (examples) inside docker container. So, I had to run these below commands to get the correct Postgres host ipv4 address (superset_app -> superset container name, superset_db -> Postgres container name) to construct the final uri.
docker network connect NETWORK_NAME superset_app
docker network connect NETWORK_NAME superset_db
docker inspect NETWORK_NAME
