### ISSUE TITLE
An error occurred while creating datasets: Fatal error

### ISSUE THREAD

**Issue by balsilliy** [apache/superset#18954]
Envs: docker superset 1.4.1  + clickhouse
when add dataset from clickhouse, An error occurred while creating datasets: Fatal error
clickhouse database created by :  MaterializeMySQL from mysql

2022-02-27 10:53:51,412:ERROR:root:'NoneType' object has no attribute 'reflect'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 85, in wraps
    raise ex
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 82, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/core.py", line 1468, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/log.py", line 242, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/datasets/api.py", line 252, in post
    new_model = CreateDatasetCommand(g.user, item).run()
  File "/usr/local/lib/python3.8/site-packages/superset/datasets/commands/create.py", line 46, in run
    self.validate()
  File "/usr/local/lib/python3.8/site-packages/superset/datasets/commands/create.py", line 86, in validate
    if database and not DatasetDAO.validate_table_exists(
  File "/usr/local/lib/python3.8/site-packages/superset/datasets/dao.py", line 81, in validate_table_exists
    database.get_table(table_name, schema=schema)
  File "/usr/local/lib/python3.8/site-packages/superset/models/core.py", line 645, in get_table
    return Table(
  File "<string>", line 2, in __new__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 563, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 558, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 647, in _init
    self._autoload(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 670, in _autoload
    autoload_with.run_callable(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2212, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1653, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 829, in reflecttable
    self._reflect_engine(connection, table.name, table)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 841, in _reflect_engine
    engine = engine_cls.reflect(table, **e)
AttributeError: 'NoneType' object has no attribute 'reflect'

**Comment by balsilliy** [comment]
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/26002425/156109399-0e36652d-806b-437a-8123-53c06805d229.png">

**Comment by balsilliy** [comment]
^_^

**Comment by doowonee** [comment]
Hey Did you solved the problem? Could I know how?

**Comment by ss2495** [comment]
I am also facing the same problem but instead of fatal error I am getting 422 status (Unprocessable Entity).

**Comment by zangjietutu** [comment]
如何解决的啊？求解决方案

**Comment by zangjietutu** [comment]
How to solve it? I also encountered this problem

**Comment by Brillianttyagi** [comment]
@balsilliy How did you solve this problem?
