### ISSUE TITLE
dashboard export not working with latest 1.4.1

### ISSUE THREAD

**Issue by pavlozt** [apache/superset#19089]
Something strange with versions and images in dockerhub.

#### How to reproduce the bug
```
git checkout 1.4.1
TAG=1.4.1 docker-compose -f docker-compose-non-dev.yml up -d
docker exec superset_app superset export_dashboards

```
### Actual results
```
Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.27.1 (/usr/local/lib/python3.8/site-packages), Requirement.parse('requests==2.26.0'), {'apache-superset'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 527, in get_command
    self._load_plugin_commands()
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 517, in _load_plugin_commands
    import pkg_resources
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests==2.26.0' distribution was not found and is required by apache-superset

```

### Environment

- superset version: 1.4.1 
### Checklist

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Problem is easy to get around by adding "requests==2.26.0" to  to the file docker/requirements-local.txt
What would break down could not be found.

**Comment by ephod** [comment]
I had the same problem, this solved my issue. I don't have enough time to create a patch, but this is the change might help you.

```python
for slc in dashboard.slices: 
    if slc.datasource is None: 
        logger.info("Datasource is none") 
        continue
```

https://github.com/apache/superset/blob/d645579cdd64b7fe7f9dde4a8da000dd7db51ce9/superset/models/dashboard.py#L374

**Comment by rusackas** [comment]
Pinging @hughhhh sine he knows his way around this pretty well. I don't see _this_ error happening in the current `master` branch here. If this is no longer an issue, let's close it. Or if we need to add that dependency as suggested above, @hughhhh, that works too!

**Comment by sfirke** [comment]
`requests` is currently required and I am able to export a dashboard in Superset version 3.0.0.  Given that, and the age of this issue, I'm going to close it.
