### ISSUE TITLE
Not able to Export Dashboard, 

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#19124]
Hi Team,

I am trying to export dashboard from superset, But one or two reports not importing. Keep on shows processing.

![image](https://user-images.githubusercontent.com/88739186/157889335-8280f2b5-e29a-4b83-adb3-2e59c8183c01.png)

Regards,
Naren

**Comment by mdiep-cese** [comment]
I have the same issue with this. This seems to happen only with the dashboard that I created; and not with the example dashboards (e.g., the one that comes with docker build).

**Comment by eschutho** [comment]
Hi @Narendra678 do you have any logs that you can share?

**Comment by Narendra678** [comment]
> Hi @Narendra678 do you have any logs that you can share?

Traceback (most recent call last):
File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask_appbuilder/api/init.py", line 85, in wraps
return f(self, *args, **kwargs)
File "/workspace/superset/views/base_api.py", line 85, in wraps
raise ex
File "/workspace/superset/views/base_api.py", line 82, in wraps
duration, response = time_function(f, self, *args, **kwargs)
File "/workspace/superset/utils/core.py", line 1429, in time_function
response = func(*args, **kwargs)
File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask_appbuilder/api/init.py", line 155, in wraps
return f(self, *args, **kwargs)
File "/workspace/superset/utils/log.py", line 241, in wrapper
value = f(*args, **kwargs)
File "/workspace/superset/dashboards/api.py", line 718, in export
requested_ids
File "/workspace/superset/commands/export.py", line 61, in run
for file_name, file_content in self._export(model):
File "/workspace/superset/dashboards/commands/export.py", line 140, in _export
target["datasetUuid"] = str(dataset.uuid)
AttributeError: 'NoneType' object has no attribute 'uuid'

**Comment by eschutho** [comment]
Thank you. @Narendra678 what version are you on?

**Comment by eschutho** [comment]
Closing this since we need more information, but just reply to this thread if you'd like to reopen it.
