### ISSUE TITLE
Import is not working: An error occurred while importing dashboard: Import dashboard failed for an unknown reason

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#19222]
Hi Team,

I am trying to import dashboard getting below error.
An error occurred while importing dashboard: Import dashboard failed for an unknown reason

Note: when try to import i can see dataset added
when i try to import chart it is working.
I am able to import other reports

Regards,
Naren

**Comment by AAfghahi** [comment]
Hello! Could you take some screenshots of what you are experiencing?

**Comment by Narendra678** [comment]
![image](https://user-images.githubusercontent.com/88739186/158947761-8b49b19d-c2f4-40e9-b8fe-0ea8a47365eb.png)

**Comment by Narendra678** [comment]
2022-03-18 07:29:47 default[1-3-1qa]  Error running import command
2022-03-18 07:29:47 default[1-3-1qa]  Traceback (most recent call last):    File "/workspace/superset/commands/importers/v1/__init__.py", line 67, in run      self._import(db.session, self._configs, self.overwrite)    File "/workspace/superset/dashboards/commands/importers/v1/__init__.py", line 126, in _import      config = update_id_refs(config, chart_ids, dataset_info)    File "/workspace/superset/dashboards/commands/importers/v1/utils.py", line 85, in update_id_refs      for old_id, columns in metadata["filter_scopes"].items()    File "/workspace/superset/dashboards/commands/importers/v1/utils.py", line 85, in <dictcomp>      for old_id, columns in metadata["filter_scopes"].items()  KeyError: 580
2022-03-18 07:29:47 default[1-3-1qa]
2022-03-18 07:29:47 default[1-3-1qa]  During handling of the above exception, another exception occurred:
2022-03-18 07:29:47 default[1-3-1qa]
2022-03-18 07:29:47 default[1-3-1qa]  Traceback (most recent call last):    File "/workspace/superset/dashboards/commands/importers/dispatcher.py", line 58, in run      command.run()    File "/workspace/superset/commands/importers/v1/__init__.py", line 71, in run      raise self.import_error()  superset.dashboards.commands.exceptions.DashboardImportError: Import dashboard failed for an unknown reason
2022-03-18 07:29:47 default[1-3-1qa]  2022-03-18 07:29:47,754:ERROR:superset.dashboards.commands.importers.dispatcher:Error running import command
2022-03-18 07:29:47 default[1-3-1qa]  Traceback (most recent call last):    File "/workspace/superset/commands/importers/v1/__init__.py", line 67, in run      self._import(db.session, self._configs, self.overwrite)    File "/workspace/superset/dashboards/commands/importers/v1/__init__.py", line 126, in _import      config = update_id_refs(config, chart_ids, dataset_info)    File "/workspace/superset/dashboards/commands/importers/v1/utils.py", line 85, in update_id_refs      for old_id, columns in metadata["filter_scopes"].items()    File "/workspace/superset/dashboards/commands/importers/v1/utils.py", line 85, in <dictcomp>      for old_id, columns in metadata["filter_scopes"].items()  KeyError: 580
2022-03-18 07:29:47 default[1-3-1qa]
2022-03-18 07:29:47 default[1-3-1qa]  During handling of the above exception, another exception occurred:
2022-03-18 07:29:47 default[1-3-1qa]
2022-03-18 07:29:47 default[1-3-1qa]  Traceback (most recent call last):    File "/workspace/superset/dashboards/commands/importers/dispatcher.py", line 58, in run      command.run()    File "/workspace/superset/commands/importers/v1/__init__.py", line 71, in run      raise self.import_error()  superset.dashboards.commands.exceptions.DashboardImportError: Import dashboard failed for an unknown reason
2022-03-18 07:29:47 default[1-3-1qa]  Import dashboard failed for an unknown reason
2022-03-18 07:29:47 default[1-3-1qa]  2022-03-18 07:29:47,755:WARNING:superset.views.base:Import dashboard failed for an unknown reason

**Comment by AAfghahi** [comment]
So you get this toast before you upload a dashboard or after you put in a dashboard and then press import.

**Comment by Narendra678** [comment]
Export(Download)working in first environment and **then importing(Upload) in to second environment.**

I am getting error in "then importing(Upload) in to second environment."

**Comment by karyan40024** [comment]
I am facing the same issue... but this happens only in case of multiple datasets

**Comment by Narendra678** [comment]
> ok makes sense, I will try to replicate this bug today. Could you tell me what engines you were running and if it is agnostic of the chart/viz types involved.

Below is the latest error logs. ERROR:root:'NoneType' object has no attribute 'uuid'

2022-03-22 10:14:04 default[1-3-1noimc]  "GET /api/v1/dashboard/export/?q=!(14)&token=zVVSihwxp HTTP/1.1" 500
2022-03-22 10:14:05 default[1-3-1noimc]  2022-03-22 10:14:05,189:**ERROR:root:'NoneType' object has no attribute 'uuid'**
2022-03-22 10:14:05 default[1-3-1noimc]  Traceback (most recent call last):    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps      return f(self, *args, **kwargs)    File "/workspace/superset/views/base_api.py", line 85, in wraps      raise ex    File "/workspace/superset/views/base_api.py", line 82, in wraps      duration, response = time_function(f, self, *args, **kwargs)    File "/workspace/superset/utils/core.py", line 1429, in time_function      response = func(*args, **kwargs)    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 155, in wraps      return f(self, *args, **kwargs)    File "/workspace/superset/utils/log.py", line 241, in wrapper      value = f(*args, **kwargs)    File "/workspace/superset/dashboards/api.py", line 718, in export      requested_ids    File "/workspace/superset/commands/export.py", line 61, in run      for file_name, file_content in self._export(model):    File "/workspace/superset/dashboards/commands/export.py", line 140, in _export      target["datasetUuid"] = str(dataset.uuid)  AttributeError: 'NoneType' object has no attribute 'uuid'
2022-03-22 10:14:44 default[1-3-1noimc]  "GET /dashboard/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc&viewMode=table HTTP/1.1" 200
2022-03-22 10:14:46 default[1-3-1noimc]  "GET /api/v1/dashboard/related/created_by?q=() HTTP/1.1" 200
2022-03-22 10:14:46 default[1-3-1noimc]  "GET /api/v1/dashboard/related/owners?q=() HTTP/1.1" 200
2022-03-22 10:14:47 default[1-3-1noimc]  "GET /api/v1/dashboard/?q=(order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:25) HTTP/1.1" 200
2022-03-22 10:14:48 default[1-3-1noimc]  "GET /api/v1/dashboard/_info?q=(keys:!(permissions)) HTTP/1.1" 200
2022-03-22 10:14:48 default[1-3-1noimc]  "GET /static/assets/images/favicon.png HTTP/1.1" 304
2022-03-22 10:14:48 default[1-3-1noimc]  "GET /api/v1/dashboard/favorite_status/?q=!(47,50,52,48,41,55,10,29,14,59,56,6,53,51,46,11,42,43,45,33,19,44,40,38,20) HTTP/1.1" 200

**Comment by smetirem** [comment]
I am having the same issue. I am getting the same error when trying to import even a single datasets. Importing a chart (when the linked dataset is exists) is not possible either.

**Comment by Narendra678** [comment]
recreated report then it is working for me.

**Comment by yiyux** [comment]
Hello, trying to import datasets via UI from dev env (superset 1.5.0) to a new hosts with 2.0.0rc2
Same error here

`superset_app             | 2022-07-08 21:14:09,879:INFO:superset.datasets.commands.importers.v0:Importing dataset from file 20220708_200853.yaml
superset_app             | Error running import command
superset_app             | Traceback (most recent call last):
superset_app             |   File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
superset_app             |     command.run()
superset_app             |   File "/app/superset/datasets/commands/importers/v0.py", line 266, in run
superset_app             |     params = json.loads(dataset["params"])
superset_app             | KeyError: 'params'
superset_app             | 2022-07-08 21:14:09,880:ERROR:superset.datasets.commands.importers.dispatcher:Error running import command
superset_app             | Traceback (most recent call last):
superset_app             |   File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
superset_app             |     command.run()
superset_app             |   File "/app/superset/datasets/commands/importers/v0.py", line 266, in run
superset_app             |     params = json.loads(dataset["params"])
superset_app             | KeyError: 'params'
superset_app             | 'params'
superset_app             | Traceback (most recent call last):
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
superset_app             |     rv = self.dispatch_request()
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
superset_app             |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 89, in wraps
superset_app             |     return f(self, *args, **kwargs)
superset_app             |   File "/app/superset/views/base_api.py", line 113, in wraps
superset_app             |     raise ex
superset_app             |   File "/app/superset/views/base_api.py", line 110, in wraps
superset_app             |     duration, response = time_function(f, self, *args, **kwargs)
superset_app             |   File "/app/superset/utils/core.py", line 1507, in time_function
superset_app             |     response = func(*args, **kwargs)
superset_app             |   File "/app/superset/utils/log.py", line 245, in wrapper
superset_app             |     value = f(*args, **kwargs)
superset_app             |   File "/app/superset/views/base_api.py", line 98, in wraps
superset_app             |     return f(self, *args, **kwargs)
superset_app             |   File "/app/superset/datasets/api.py", line 766, in import_
superset_app             |     command.run()
superset_app             |   File "/app/superset/datasets/commands/importers/dispatcher.py", line 68, in run
superset_app             |     raise exc
superset_app             |   File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
superset_app             |     command.run()
superset_app             |   File "/app/superset/datasets/commands/importers/v0.py", line 266, in run
superset_app             |     params = json.loads(dataset["params"])
superset_app             | KeyError: 'params'
superset_app             | 2022-07-08 21:14:09,881:ERROR:superset.views.base:'params'
superset_app             | Traceback (most recent call last):
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
superset_app             |     rv = self.dispatch_request()
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
superset_app             |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 89, in wraps
superset_app             |     return f(self, *args, **kwargs)
superset_app             |   File "/app/superset/views/base_api.py", line 113, in wraps
superset_app             |     raise ex
superset_app             |   File "/app/superset/views/base_api.py", line 110, in wraps
superset_app             |     duration, response = time_function(f, self, *args, **kwargs)
superset_app             |   File "/app/superset/utils/core.py", line 1507, in time_function
superset_app             |     response = func(*args, **kwargs)
superset_app             |   File "/app/superset/utils/log.py", line 245, in wrapper
superset_app             |     value = f(*args, **kwargs)
superset_app             |   File "/app/superset/views/base_api.py", line 98, in wraps
superset_app             |     return f(self, *args, **kwargs)
superset_app             |   File "/app/superset/datasets/api.py", line 766, in import_
superset_app             |     command.run()
superset_app             |   File "/app/superset/datasets/commands/importers/dispatcher.py", line 68, in run
superset_app             |     raise exc
superset_app             |   File "/app/superset/datasets/commands/importers/dispatcher.py", line 57, in run
superset_app             |     command.run()
superset_app             |   File "/app/superset/datasets/commands/importers/v0.py", line 266, in run
superset_app             |     params = json.loads(dataset["params"])
superset_app             | KeyError: 'params'`

**Comment by lanzhenw** [comment]
Having the same issue here

**Comment by wulfuric** [comment]
We are trying to build automation to promote dashboards between environments and we're also seeing dashboard import failures. Ours turned out to be due to the `expanded_slices` key that the importer couldn't handle, in our case it was pointing at a chart no longer part of the dashboard.  No idea how it got there, maybe through the ui. Ultimately if we unzipped the dashboards, removed the key `yq -i e 'del(.metadata.expanded_slices)' $f` it would import.

This lead to this super hacky snippet in our pipeline, to unzip, remove expanded_slices, then reupload.  Ultimately the right fix will be for the upload to either ignore or handle the expanded_slices field.
```
          cd assets/dashboards
          if [[ ! -f *.zip ]] ; then
            echo 'no dashboards marked for upload'
            exit
          fi
          unzip '*.zip'
          rm -rf *.zip
          # rm -rf ./*/databases
          ls
          yq --help
          yq --version
          for f in ./*/dashboards/*.yaml; do
            yq -i e 'del(.metadata.expanded_slices)' $f
          done
          for f in ./*/; do
              if [ -d "$f" ]; then
                  # Will not run if no directories are available
                  echo $f
                  zip -r "${f%/}.zip" "$f"
              fi
```

**Comment by terrancesnyder** [comment]
same issue, simple export from dashboard and then using CLI to import fails, makes it hard to get devops and CI working.

**Comment by andy-clapson** [comment]
I am also seeing this issue when importing both charts and dashboards, I'm unclear on the precise cause (not much that is useful from the logs I can see).

I will note that I have a CI script that manages imports via the REST API and that has continued to work just fine. For anyone building automation around data/dashboard loading I would recommend that approach.

**Comment by pyryjook** [comment]
@andy-clapson Could you share the script or the main parts of it with us too, thanks?

**Comment by rusackas** [comment]
Hey folks, I see this went silent around the time 3.0 came out. Is this still an issue?

**Comment by pyryjook** [comment]
Hi @rusackas,

Actually I tested it with version 3.0.0 back then, and the problem was still there. 

There was also some recent discussion regarding this in Slack: https://apache-superset.slack.com/archives/C015WAZL0KH/p1695889915182819

**Comment by butuzov** [comment]
Try now with `3.1`, I wasn't able to even track `DashboardImportError` as it looks like a dead code now...

**Comment by Davidkramer1999** [comment]
I'm expericing the sam issue here

**Comment by malikvashu29** [comment]
I'm experiencing the same issue. Getting error "An error occurred while importing dataset: Could not find a valid command to import file. Please re-export your file and try importing again"

**Comment by rusackas** [comment]
Is anyone experiencing this able to make an example export to share here that we can troubleshoot with? I haven't been able to reproduce the issue. It seems like if you make a virtual dataset that generates the data as part of the query, you might be safe to share the export? CC @betodealmeida in case they have any idea how to troubleshoot/repro/fix this.

**Comment by marituhone** [comment]
@rusackas  i get the same issue in 4.0.0

**Comment by 1yuv** [comment]
Hi @rusackas ,  I was able to reproduce this today as well, from 1.3 to 4.0.
**Steps:**
1. Export multiple datasets (physical/virtual) from older version, this gives you an yaml file. 
2. Try importing that data sets on 4.0 superset. 
3. You see an error like this:

<img width="737" alt="image" src="https://github.com/apache/superset/assets/6102813/af91105f-f85b-4d4b-97e7-c7e0168ce950">

<details>
  <summary>View Logs</summary>

```
Importing dataset from file 20240425_165955.yaml
2024-04-25 17:09:48,511:INFO:superset.commands.dataset.importers.v0:Importing dataset from file 20240425_165955.yaml
Error running import command
Traceback (most recent call last):
  File "/app/superset/commands/dataset/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/dataset/importers/v0.py", line 255, in run
    params = json.loads(dataset["params"])
KeyError: 'params'
2024-04-25 17:09:48,511:ERROR:superset.commands.dataset.importers.dispatcher:Error running import command
Traceback (most recent call last):
  File "/app/superset/commands/dataset/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/dataset/importers/v0.py", line 255, in run
    params = json.loads(dataset["params"])
KeyError: 'params'
'params'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1463, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 108, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/datasets/api.py", line 926, in import_
    command.run()
  File "/app/superset/commands/dataset/importers/dispatcher.py", line 68, in run
    raise exc
  File "/app/superset/commands/dataset/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/dataset/importers/v0.py", line 255, in run
    params = json.loads(dataset["params"])
KeyError: 'params'
2024-04-25 17:09:48,511:ERROR:superset.views.base:'params'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1463, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 108, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/datasets/api.py", line 926, in import_
    command.run()
  File "/app/superset/commands/dataset/importers/dispatcher.py", line 68, in run
    raise exc
  File "/app/superset/commands/dataset/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/dataset/importers/v0.py", line 255, in run
    params = json.loads(dataset["params"])
KeyError: 'params'
```
</details>

**Comment by constantin-huetterer** [comment]
We had the same issue. Downgrading to 4.0.0 fixed the problem for us:
```bash
export TAG=4.0.0
docker compose -f docker-compose-image-tag.yml up
```

Here are two example Dashboards, one created with the latest version of Superset and one after the fix with tag 4.0.

[Broken export in latest Superset version](https://github.com/apache/superset/files/15485762/dashboard_export_20240529T110715.zip)

[Working export (v. 4.0)](https://github.com/apache/superset/files/15485767/dashboard_export_clustering_template_20240529T114255.zip)

**Comment by rusackas** [comment]
@dosu-bot

**Comment by SteveKhoa** [comment]
@wardsi Hi, some dashboards can work with this workaround, some do not.

**Comment by devikaaaa33** [comment]
Hello @, I am also facing same issue. I am using version 4.1.1.  I tried the steps below, but they did not work. Developer tools show the error as "{

{
    "errors": [
        {
            "message": "Import dashboard failed for an unknown reason",
            "error_type": "GENERIC_COMMAND_ERROR",
            "level": "error",
            "extra": {
                "issue_codes": [
                    {
                        "code": 1010,
                        "message": "Issue 1010 - Superset encountered an error while running a command."
                    }
                ]
            }
        }
    ]
}"

1. > Hi - I know this is probably really old, however, I made this work :- importing and export from v4.01 to 4.1rc2. Simply by moving all the files in the nested directory from the export zip to the root, then zipping and uploading to superset.. Hope this helps others. This attempted is a direct result from the helpful code above (Dosu).
2. https://github.com/apache/superset/issues/19222#issuecomment-2340944113

Can someone look into this and provide a solution?

**Comment by rusackas** [comment]
This hasn't been updated since April, and it's a tough one to figure out how to move foward. Some people are trying to migrate from VERY old versions of Superset to more recent versions (but still unsupported, now that we're in 5.0-land). 

The import/export formats DID change during one of those major versions... it was considered a breaking change (thus the major versions, following semVer policies). 

People can try the Preset CLI to migrate from old versions to new versions as one potential alternative (I'm not sure if that would work or not, depending on versions in play). 

This might be closed as not-planned, if we're talking about importing pre-zip exports into the modern zip file world. Thoughts @betodealmeida @mistercrunch ?

**Comment by amirhosseinkabiri** [comment]
read this article. it may help
https://medium.com/@amirhosseikabiri/solving-the-superset-import-export-issue-a-step-by-step-guide-35f16451b196

**Comment by rusackas** [comment]
This issue has been open for over three years and has collected reports from many users with different underlying causes (legacy v0 YAML format compatibility, `filter_scopes` key mismatches, database connectivity errors, etc.). These are distinct problems that are difficult to track and fix in a single issue.

If you are still experiencing an import failure, please open a new issue with:
- The exact Superset version you are exporting *from* and importing *into*
- Whether you are using the `.zip` export format (recommended) or an older `.yaml` format
- The full error message and stack trace from the Superset logs

Note that importing exports from versions older than 2.0 (pre-zip format) into modern Superset is not guaranteed to work, as the import/export format changed as a breaking change during a major version bump.
