### ISSUE TITLE
Not able to export few reports

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#19221]
Hi Team,

I am not able to export few reports.

Got below error log. Can someone please advise.

Version 1.3.1
It has multiple datasets

Traceback (most recent call last):
File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
return f(self, *args, **kwargs)
File "/workspace/superset/views/base_api.py", line 85, in wraps
raise ex
File "/workspace/superset/views/base_api.py", line 82, in wraps
duration, response = time_function(f, self, *args, **kwargs)
File "/workspace/superset/utils/core.py", line 1429, in time_function
response = func(*args, **kwargs)
File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 155, in wraps
return f(self, *args, **kwargs)
File "/workspace/superset/utils/log.py", line 241, in wrapper
value = f(*args, **kwargs)
File "/workspace/superset/dashboards/api.py", line 718, in export
requested_ids
File "/workspace/superset/commands/export.py", line 61, in run
for file_name, file_content in self._export(model):
File "/workspace/superset/dashboards/commands/export.py", line 140, in _export
target["datasetUuid"] = str(dataset.uuid)
AttributeError: 'NoneType' object has no attribute 'uuid'

Regards,
Naren

**Comment by AAfghahi** [comment]
What format were you importing the reports in? Did you check if it has a uuid column?

**Comment by Narendra678** [comment]
Importing with YAML zip file. We do not have any column called 'uuid'

**Comment by rusackas** [comment]
@AAfghahi @Narendra678 is anyone able to confirm that this is still an issue in Superset 2.0.1, or shall we close it since it's been inactive for upward of a year?
