### ISSUE TITLE
Fails to load "SQL editor" with React error

### ISSUE THREAD

**Issue by andyphilipp** [apache/superset#19249]
Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.

Console output:
```
vendors.1434c823515e5a8ce076.entry.js:2 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xi (vendors.1434c823515e5a8ce076.entry.js:2:2217585)
    at vendors.1434c823515e5a8ce076.entry.js:2:2222443
    at To (vendors.1434c823515e5a8ce076.entry.js:2:2231854)
    at bl (vendors.1434c823515e5a8ce076.entry.js:2:2271975)
    at hu (vendors.1434c823515e5a8ce076.entry.js:2:2262744)
    at du (vendors.1434c823515e5a8ce076.entry.js:2:2262669)
    at ru (vendors.1434c823515e5a8ce076.entry.js:2:2259699)
    at Ql (vendors.1434c823515e5a8ce076.entry.js:2:2256467)
    at Vu (vendors.1434c823515e5a8ce076.entry.js:2:2277682)
    at vendors.1434c823515e5a8ce076.entry.js:2:2278891
nl @ vendors.1434c823515e5a8ce076.entry.js:2
n.callback @ vendors.1434c823515e5a8ce076.entry.js:2
hi @ vendors.1434c823515e5a8ce076.entry.js:2
ll @ vendors.1434c823515e5a8ce076.entry.js:2
gu @ vendors.1434c823515e5a8ce076.entry.js:2
t.unstable_runWithPriority @ vendors.1434c823515e5a8ce076.entry.js:2
Za @ vendors.1434c823515e5a8ce076.entry.js:2
mu @ vendors.1434c823515e5a8ce076.entry.js:2
ru @ vendors.1434c823515e5a8ce076.entry.js:2
Ql @ vendors.1434c823515e5a8ce076.entry.js:2
Vu @ vendors.1434c823515e5a8ce076.entry.js:2
(anonymous) @ vendors.1434c823515e5a8ce076.entry.js:2
iu @ vendors.1434c823515e5a8ce076.entry.js:2
Uu @ vendors.1434c823515e5a8ce076.entry.js:2
t.render @ vendors.1434c823515e5a8ce076.entry.js:2
70182 @ sqllab.d998a340f0b4a9aae45c.entry.js:379
o @ sqllab.d998a340f0b4a9aae45c.entry.js:379
(anonymous) @ sqllab.d998a340f0b4a9aae45c.entry.js:379
o.O @ sqllab.d998a340f0b4a9aae45c.entry.js:379
t @ sqllab.d998a340f0b4a9aae45c.entry.js:379
(anonymous) @ vendors.1434c823515e5a8ce076.entry.js:2
vendors.1434c823515e5a8ce076.entry.js:2 Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xi (vendors.1434c823515e5a8ce076.entry.js:2:2217585)
    at vendors.1434c823515e5a8ce076.entry.js:2:2222443
    at To (vendors.1434c823515e5a8ce076.entry.js:2:2231854)
    at bl (vendors.1434c823515e5a8ce076.entry.js:2:2271975)
    at hu (vendors.1434c823515e5a8ce076.entry.js:2:2262744)
    at du (vendors.1434c823515e5a8ce076.entry.js:2:2262669)
    at ru (vendors.1434c823515e5a8ce076.entry.js:2:2259699)
    at Ql (vendors.1434c823515e5a8ce076.entry.js:2:2256467)
    at Vu (vendors.1434c823515e5a8ce076.entry.js:2:2277682)
    at vendors.1434c823515e5a8ce076.entry.js:2:2278891
xi @ vendors.1434c823515e5a8ce076.entry.js:2
(anonymous) @ vendors.1434c823515e5a8ce076.entry.js:2
To @ vendors.1434c823515e5a8ce076.entry.js:2
bl @ vendors.1434c823515e5a8ce076.entry.js:2
hu @ vendors.1434c823515e5a8ce076.entry.js:2
du @ vendors.1434c823515e5a8ce076.entry.js:2
ru @ vendors.1434c823515e5a8ce076.entry.js:2
Ql @ vendors.1434c823515e5a8ce076.entry.js:2
Vu @ vendors.1434c823515e5a8ce076.entry.js:2
(anonymous) @ vendors.1434c823515e5a8ce076.entry.js:2
iu @ vendors.1434c823515e5a8ce076.entry.js:2
Uu @ vendors.1434c823515e5a8ce076.entry.js:2
t.render @ vendors.1434c823515e5a8ce076.entry.js:2
70182 @ sqllab.d998a340f0b4a9aae45c.entry.js:379
o @ sqllab.d998a340f0b4a9aae45c.entry.js:379
(anonymous) @ sqllab.d998a340f0b4a9aae45c.entry.js:379
o.O @ sqllab.d998a340f0b4a9aae45c.entry.js:379
t @ sqllab.d998a340f0b4a9aae45c.entry.js:379
(anonymous) @ vendors.1434c823515e5a8ce076.entry.js:2
```

**Comment by srinify** [comment]
Hey @andyphilipp do you need debugging help with a customization you made or are you running into this issue with the default Superset experience? I'm not able to replicate this so I'm curious

**Comment by andyphilipp** [comment]
Hi @srinify . I'm running the latest helm release. I managed to fix the issue by cleaning the local storage, didn't dump the data first unfortunately, so not sure what corrupt data might cause this.
