### ISSUE TITLE
got an error when save query as a virtual dataset

### ISSUE THREAD

**Issue by xiamicpp** [apache/superset#19609]
`2022-04-08 08:00:45,691:ERROR:superset.views.base:Can't generate DDL for NullType(); did you forget to specify a type on this Column?
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 133, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 2121, in sqllab_viz
    db.session.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 248, in save_obj
    _finalize_insert_update_commands(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1432, in _finalize_insert_update_commands
    mapper.dispatch.after_insert(mapper, connection, state)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/events.py", line 731, in wrap
    fn(*arg, **kw)
  File "/app/superset/connectors/sqla/models.py", line 2021, in after_insert
    SqlaTable.write_shadow_dataset(target, database, session)
  File "/app/superset/connectors/sqla/models.py", line 2375, in write_shadow_dataset
    tables = load_or_create_tables(
  File "/app/superset/connectors/sqla/utils.py", line 229, in load_or_create_tables
    columns = [
  File "/app/superset/connectors/sqla/utils.py", line 232, in <listcomp>
    type=str(column["type"]),
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 623, in __str__
    return str(self.compile())
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 606, in compile
    return dialect.type_compiler.process(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 402, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 3478, in visit_null
    raise exc.CompileError(
sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?`

**Comment by mjcc007** [comment]
@xiamicpp I have the same problem，Have you solved it yet！

**Comment by villebro** [comment]
@xiamicpp @mjcc007 thanks for reporting this. Can you specify which version of Superset (or SHA if you're running master) you're using?
