### ISSUE TITLE
Blank Page + Error when trying to add chart

### ISSUE THREAD

**Issue by Max-Jesch** [apache/superset#19682]
#### How to reproduce the bug

1. run superset locally on WSL2 using docker following: https://hub.docker.com/r/apache/superset
2. connect to local MySQL instance 
3. Navigate to "Charts" -> click "+ CHART"

### Expected results

opening of a GUI that guides me through creating a chart

### Actual results

A blank page and two errors in the console 

vendors.f9c3fd7027468531bc17.entry.js:2 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at r (3389.e322f34f3c49e199e320.entry.js:166:8112)
    at R (6052.cd8224a03af27b29c66e.entry.js:669:580)
    at Ko (vendors.f9c3fd7027468531bc17.entry.js:2:2260208)
    at bl (vendors.f9c3fd7027468531bc17.entry.js:2:2306170)
    at hu (vendors.f9c3fd7027468531bc17.entry.js:2:2298946)
    at du (vendors.f9c3fd7027468531bc17.entry.js:2:2298871)
    at ru (vendors.f9c3fd7027468531bc17.entry.js:2:2295901)
    at Ql (vendors.f9c3fd7027468531bc17.entry.js:2:2292669)
    at Vu (vendors.f9c3fd7027468531bc17.entry.js:2:2313884)

vendors.f9c3fd7027468531bc17.entry.js:2 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at r (3389.e322f34f3c49e199e320.entry.js:166:8112)
    at R (6052.cd8224a03af27b29c66e.entry.js:669:580)
    at Ko (vendors.f9c3fd7027468531bc17.entry.js:2:2260208)
    at bl (vendors.f9c3fd7027468531bc17.entry.js:2:2306170)
    at hu (vendors.f9c3fd7027468531bc17.entry.js:2:2298946)
    at du (vendors.f9c3fd7027468531bc17.entry.js:2:2298871)
    at ru (vendors.f9c3fd7027468531bc17.entry.js:2:2295901)
    at Ql (vendors.f9c3fd7027468531bc17.entry.js:2:2292669)
    at Vu (vendors.f9c3fd7027468531bc17.entry.js:2:2313884)

#### Screenshots

![image](https://user-images.githubusercontent.com/23448917/163105952-5ea4063f-6bad-4a44-aecf-7902c6ebbf35.png)

### Environment

- browser type and version: latest Chrome
- superset version: `superset version` latest
- python version: `python --version` doesnt matter, runs in docker container
- node.js version: `node -v` doesnt matter, runs in docker container
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by 7vikpeculiar** [comment]
@if54uran Same issue here, any luck resolving it ?

**Comment by rusackas** [comment]
Closing as stale. Doesn't sound like there's much outrage here, so I'm hoping everyone found a way forward. Happy to revisit/reopen if needed.
