### ISSUE TITLE
AttributeError: 'Select' object has no attribute '_simple_int_clause'

### ISSUE THREAD

**Issue by azadsagar** [apache/superset#20168]
Trying to use dataset via Athena Database. Using the latest docker image. I am getting below error and 500 on UI page.

#### How to reproduce the bug

1. Go to Datasets
2. Click on +Datasets
3. Select athena as database and select appropriate schema and table.
4. Click on newly created dataset. you should see error.

### Expected results

Should be able to create chart from newaly added dataset (athena)

### Actual results

500 Internal server error.
`
'Select' object has no attribute '_simple_int_clause'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 133, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 888, in explore
    datasource_data = datasource.data if datasource else dummy_datasource_data
  File "/app/superset/connectors/sqla/models.py", line 871, in data
    data_ = super().data
  File "/app/superset/connectors/base/models.py", line 293, in data
    "select_star": self.select_star,
  File "/app/superset/connectors/sqla/models.py", line 860, in select_star
    return self.database.select_star(
  File "/app/superset/models/core.py", line 485, in select_star
    return self.db_engine_spec.select_star(
  File "/app/superset/db_engine_specs/base.py", line 1129, in select_star
    sql = database.compile_sqla_query(qry)
  File "/app/superset/models/core.py", line 465, in compile_sqla_query
    sql = str(qry.compile(engine, compile_kwargs={"literal_binds": True}))
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 487, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 592, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 322, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 352, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2201, in visit_select
    text = self._compose_select_body(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2320, in _compose_select_body
    text += self.limit_clause(select, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyathena/sqlalchemy_athena.py", line 90, in limit_clause
    if limit_clause is not None and select._simple_int_clause(limit_clause):
AttributeError: 'Select' object has no attribute '_simple_int_clause'
2022-05-24 06:46:36,378:ERROR:superset.views.base:'Select' object has no attribute '_simple_int_clause'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 133, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 888, in explore
    datasource_data = datasource.data if datasource else dummy_datasource_data
  File "/app/superset/connectors/sqla/models.py", line 871, in data
    data_ = super().data
  File "/app/superset/connectors/base/models.py", line 293, in data
    "select_star": self.select_star,
  File "/app/superset/connectors/sqla/models.py", line 860, in select_star
    return self.database.select_star(
  File "/app/superset/models/core.py", line 485, in select_star
    return self.db_engine_spec.select_star(
  File "/app/superset/db_engine_specs/base.py", line 1129, in select_star
    sql = database.compile_sqla_query(qry)
  File "/app/superset/models/core.py", line 465, in compile_sqla_query
    sql = str(qry.compile(engine, compile_kwargs={"literal_binds": True}))
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 487, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 592, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 322, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 352, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2201, in visit_select
    text = self._compose_select_body(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2320, in _compose_select_body
    text += self.limit_clause(select, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyathena/sqlalchemy_athena.py", line 90, in limit_clause
    if limit_clause is not None and select._simple_int_clause(limit_clause):
AttributeError: 'Select' object has no attribute '_simple_int_clause'
`

#### Screenshots

![2022-05-24 12-27-51](https://user-images.githubusercontent.com/8531843/169968430-9a78d1e1-496f-421a-bddc-884e000a6d44.png)

### Environment

- browser type and version: Chrome
- superset version: `superset version` : Docker Image digest : 1d0a0c2923e5
- python version: `python --version`  : Python 3.8.12
- node.js version: `node -v` : NA
- any feature flags active: NA

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Browser Endpoint : superset/explore/table/154/

Let me know if additional information is required from metadata db.

Code Snipet from SQLAlchemy:
<code>
    def limit_clause(self, select, **kw):
        text = []
        offset_clause = select._offset_clause
        if offset_clause is not None and select._simple_int_clause(offset_clause):
            text.append(
                f" OFFSET {self.process(offset_clause.render_literal_execute(), **kw)}"
            )
        limit_clause = select._limit_clause
        if limit_clause is not None and select._simple_int_clause(limit_clause):
            text.append(
                f" LIMIT {self.process(limit_clause.render_literal_execute(), **kw)}"
            )
        return "\n".join(text)
</code>

**Comment by azadsagar** [comment]
Yes, This worked Thank you @czammar.

**Comment by cbuffevant** [comment]
Hi @azadsagar I'm facing the same error with Superset .
I've tried adding
```
"PyAthena[SQLAlchemy]>=1.0.0, <2.0.0" 
```
in my helm chart values for config `bootstrapScript` but I got some errors about version mismatch with PyAthena (2.9.2). Then I changed it to 
```
"SQLAlchemy>=1.0.0, <2.0.0" 
```
Per the documentation https://pypi.org/project/pyathena/#sqlalchemy... the package was installed successfully but still getting the error with helm chart 0.6.1.

Did you have to do something else to make it work?

Thanks in advance!
