### ISSUE TITLE
After upgrade from a very old version - not able to perform custom login  

### ISSUE THREAD

**Issue by lalwanim** [apache/superset#20176]
Hello friends 
I upgraded superset from 0.35 → 1.4.0. There were few obvious changes that I performed like in entry point script:

```
celery worker --app=superset.sql_lab:celery_app --pool=gevent -Ofair &
exec gunicorn  --bind  0.0.0.0:8088 \
    --workers 15 \
    --timeout 60 \
    --limit-request-line 0 \
    --limit-request-field_size 0 \
    superset:app

```

-->

```
celery worker --app=superset.tasks.celery_app:app -Ofair &
exec gunicorn --bind  0.0.0.0:8088 \
    --workers 10 \
    --timeout 60 \
    --limit-request-line 0 \
    --limit-request-field_size 0 \
	 "superset.app:create_app()"


```

with these changes I am sure there are changes required in custom security, I need your help guys to point me right direction for that.

Error in custom security:

Found but failed to import local superset_config
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/superset/config.py", line 1298, in <module>
    import superset_config  # pylint: disable=import-error
  File "/etc/superset/superset_config.py", line 85, in <module>
    from custom_security import CustomSecurityManager
  File "/etc/superset/custom_security.py", line 16, in <module>
    class CustomAuthDBView(AuthDBView):
  File "/etc/superset/custom_security.py", line 92, in CustomAuthDBView
    **@app.before_request**
  File "/usr/local/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python3.8/site-packages/flask/globals.py", line 52, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
**RuntimeError: Working outside of application context.**

**Comment by lalwanim** [comment]
opening a discussion instead.
