### ISSUE TITLE
Docker installation mount volume

### ISSUE THREAD

**Issue by shawnngtq** [apache/superset#20207]
I install superset using docker instead of docker-compose. It don't work if I include volume.

#### How to reproduce the bug

```
docker run -d --name='superset' --net='bridge' -p '8088:8088/tcp' -v '/mnt/user/appdata/superset':'/app':'rw' 'apache/superset'
```

### Expected results

Docker works

### Actual results

It stopped with this log

```
[2022-05-27 08:54:33 +0800] [8] [INFO] Starting gunicorn 20.1.0
[2022-05-27 08:54:33 +0800] [8] [INFO] Listening at: http://0.0.0.0:8088 (8)
[2022-05-27 08:54:33 +0800] [8] [INFO] Using worker: gthread
[2022-05-27 08:54:33 +0800] [10] [INFO] Booting worker with pid: 10
[2022-05-27 08:54:33 +0800] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
super().init_process()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
mod = importlib.import_module(module)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'superset'
[2022-05-27 08:54:33 +0800] [10] [INFO] Worker exiting (pid: 10)
[2022-05-27 08:54:33 +0800] [8] [INFO] Shutting down: Master
[2022-05-27 08:54:33 +0800] [8] [INFO] Reason: Worker failed to boot.
```

### Environment

(please complete the following information):

- browser type and version: NA
- superset version: `superset version`: latest (https://hub.docker.com/layers/apache/superset/latest/images/sha256-603eb1c35cd1b51937e7934535f5061b15b7eae6543a076bf9e860417e82dc1c?context=explore)
- python version: `python --version`: NA, using docker
- node.js version: `node -v`: NA, using docker
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cjwin2000** [comment]
Just want to confirm that I am also experiencing this bug. I'm using Unraid and can't map `/app` at all, meaning any time I restart the container I lose all data. Would love to see this fixed so I can try this image out :)

**Comment by nytai** [comment]
You’re trying to replace the entire /app dir in the container, which includes all superset code, with your empty directory.

**Comment by nytai** [comment]
You’ll want to only mount the data directory, which is configured like this 
https://github.com/apache/superset/blob/b6d39d194c90dbbf0050bb3d32d2e1a513dfc0a6/superset/config.py#L88

**Comment by nytai** [comment]
You can try mounting `/home/.superset/` instead

**Comment by gfixlabs** [comment]
See a similar issue and my response at https://stackoverflow.com/a/76886733/4301979. Hope this helps someone in the future.

**Comment by gotounix** [comment]
@shawnngtq Do you solve this?

**Comment by gotounix** [comment]
> You can try mounting `/app/superset_home/.superset` instead

Mount the `/app/superset_home/.superset` directory failed, after mounting, the host directory is empty.

**Comment by rusackas** [comment]
Docker has been overhauled quite a bit since this thread was last touched. I'll optimistically close this, assuming all is well, and the comments above have helped, thus the radio silence. If you still have trouble here, we can easily reopen/revisit this as warranted.
