### ISSUE TITLE
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server

### ISSUE THREAD

**Issue by khanh78180** [apache/superset#20319]
#### How to reproduce the bug

1. Go to '.Data ..'
2. Click on '.Databases...'
3. Scroll down to '....'  Trying to list database
perset_app            | 81.220.237.14 - - [08/Jun/2022:20:04:52 +0000] "GET /static/assets/images/filter-results.svg HTTP/1.1" 404 0 "https://superset.kdinh.fr/databaseview/list/?pageIndex=0&sortColumn=expose_in_sqllab&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0"
superset_app            | 81.220.237.14 - - [08/Jun/2022:20:04:54 +0000] "GET /api/v1/database/?q=(order_column:expose_in_sqllab,order_direction:asc,page:0,page_size:25) HTTP/1.1" 200 529 "https://superset.kdinh.fr/databaseview/list/?pageIndex=0&sortColumn=expose_in_sqllab&sortOrder=asc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0"
superset_app            | HTTPException
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
superset_app            |     rv = self.dispatch_request()
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
superset_app            |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 515, in <lambda>
superset_app            |     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/scaffold.py", line 332, in send_static_file
superset_app            |     return send_from_directory(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 700, in send_from_directory
superset_app            |     return werkzeug.utils.send_from_directory(  # type: ignore
superset_app            |   File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 847, in send_from_directory
superset_app            |     raise NotFound()
superset_app            | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
superset_app            | 2022-06-08 20:04:54,173:WARNING:superset.views.base:HTTPException
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
superset_app            |     rv = self.dispatch_request()
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
superset_app            |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 515, in <lambda>
superset_app            |     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/scaffold.py", line 332, in send_static_file
superset_app            |     return send_from_directory(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 700, in send_from_directory
superset_app            |     return werkzeug.utils.send_from_directory(  # type: ignore
superset_app            |   File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 847, in send_from_directory
superset_app            |     raise NotFound()
superset_app            | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### Expected results

what you expected to happen.
It should list database defined
### Actual results

no databases listed
what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Always-prog** [comment]
I have the same error.
Every-single request raises that exception.
Due to this exception I can't login, can't logout.

I have changed config.py and superset_config.py, and running my flask server at my local from docker-compose.yml/

![image](https://user-images.githubusercontent.com/66589759/179295689-6ae97cf4-e56c-4864-921a-96699dbbf638.png)

**Comment by khanh78180** [comment]
Hi,

Thank a lot
I change the parameter SESSION_COOKIE_SAMESITE and it is OK now

**Comment by JunTech** [comment]
i tried to change features SESSION_COOKIE_SAMESITE to Lax,but not work,it still cause error not found.
GET /ws HTTP/1.1[/home/ryan/anaconda3/envs/superset/lib/python3.8/site-packages/werkzeug/routing.py>>>path_info:[/ws],>>>[None]]>>>[True]>>>[None]>>>[None]
[/home/ryan/anaconda3/envs/superset/lib/python3.8/site-packages/werkzeug/routing.py>>>path:[|/ws]]
2022-07-22 09:28:35,152:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
  File "/home/ryan/anaconda3/envs/superset/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ryan/anaconda3/envs/superset/lib/python3.8/site-packages/flask/app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/ryan/anaconda3/envs/superset/lib/python3.8/site-packages/flask/app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/ryan/anaconda3/envs/superset/lib/python3.8/site-packages/flask/ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/ryan/anaconda3/envs/superset/lib/python3.8/site-packages/werkzeug/routing.py", line 2048, in match
    raise NotFound()

**Comment by akzarma** [comment]
SESSION_COOKIE_SAMESITE was set to "Lax" for me, setting it to None worked for me.

**Comment by sagar-appperfect** [comment]
We are facing same issue, these are the steps that we followed 
1. Clone Superset's GitHub repository `git clone https://github.com/apache/superset.git`
2. Updated config.py
`# Uncomment to setup Public role name, no authentication needed`
`AUTH_ROLE_PUBLIC = 'Public'`
3. Docker compose (tried it with dev)
DEV
`docker compose build`
`docker-compose up -d`

I have tried to set `SESSION_COOKIE_SAMESITE=None` but issue is same.
Please let me know if I am missing something, any help would be appreciated.
Thanks

**Comment by eghazal-b-yond-full** [comment]
Having the same issue here, regardless of the value of SESSION_COOKIE_SAMESITE, "Lax" or None, I'm still facing the same issue.

**Comment by falgunifb** [comment]
Facing same as mentioned by @eghazal-b-yond-full

**Comment by kokiers** [comment]
> Having the same issue here, regardless of the value of SESSION_COOKIE_SAMESITE, "Lax" or None, I'm still facing the same issue.

I too

**Comment by apole** [comment]
Login works but get this error and I am logged out immediately. These are logs on superset. Anyone found the fix?

![image](https://user-images.githubusercontent.com/6283545/224776041-78a3ce50-c4f2-4500-b48d-ced520c6785b.png)

This is my superset_config.py 
![image](https://user-images.githubusercontent.com/6283545/224776939-6b3fa4c2-4337-4989-9fb1-ef1da77d1b2f.png)

**Comment by mdmatin4** [comment]
> Login works but get this error and I am logged out immediately. These are logs on superset. Anyone found the fix?

Change the SESSION_COOKIE_HTTPONLY value in your superset_config.py file to True. 
`SESSION_COOKIE_HTTPONLY = True`

It'll solve the login issue. But the main issue will still remain same.

**Comment by zhengcan** [comment]
Any process here?

**Comment by hsravidatta** [comment]
it is the same issue "There was an error loading the tables"

**Comment by dmitry-novoselov** [comment]
> If I try to access it via the IP address on another computer, it stays on the login page indefinitely.

I am having the same issue.

**Comment by texnder** [comment]
i'm facing same issue. 

File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1770, in raise_routing_exception
superset_app          |     raise request.routing_exception  # type: ignore
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask/ctx.py", line 351, in match_request
superset_app          |     result = self.url_adapter.match(return_rule=True)  # type: ignore
superset_app          |   File "/usr/local/lib/python3.9/site-packages/werkzeug/routing/map.py", line 652, in match
superset_app          |     raise NotFound() from None
superset_app          | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.


also in browser console i got:

Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'self' 'strict-dynamic' 'nonce-ikm_zo32ANd93_gYSIMQvGbEeCkSoVmQ'". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.


why is this? can anyone knows the trick. this issue cost me a lot. please, any urgent solution.

**Comment by sherlock30** [comment]
Any resolution yet?. I'm facing the same issue

**Comment by sherlock30** [comment]
Solved.
This problem occurs due to static files not getting loaded while loading the dashboard.
Missed due to cluttered documentation
> cd ~/superset/superset-frontend/
> npm install
> npm run build

**Comment by bui-theanh** [comment]
> 

hello,I'm having the same problem too.How did you handle it?

**Comment by ramrajneogrowth** [comment]
So this is a workaround if anyone wants to try. ( At least it worked for me. )
I copied the whole superset folder to another path ( cp -R ) and magically the error got resolved in the new path.
Still nor sure of root cause. But in the copied folder it works and in original it doesn't.

**Comment by andreiaionitoaie** [comment]
Any solutions around this? I tried everything and I have same issue

**Comment by Ingmarman** [comment]
facing same issue
`HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing/map.py", line 652, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`

Python 3.9.17
Flask 2.2.5
Werkzeug 2.3.3

Superset 3.0.0

**Comment by jaihind213** [comment]
on mac m1:

faced the same exception which was giving me a bad rendering:
---
```
2023-09-29 11:26:34,361:WARNING:superset.views.base:HTTPException
superset_app           | Traceback (most recent call last):
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset_app           |     rv = self.dispatch_request()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1788, in dispatch_request
superset_app           |     self.raise_routing_exception(req)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1770, in raise_routing_exception
superset_app           |     raise request.routing_exception  # type: ignore
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/ctx.py", line 351, in match_request
superset_app           |     result = self.url_adapter.match(return_rule=True)  # type: ignore
superset_app           |   File "/usr/local/lib/python3.9/site-packages/werkzeug/routing/map.py", line 652, in match
superset_app           |     raise NotFound() from None
superset_app           | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

```
---

I did the following and it worked for me:
```
git clone https://github.com/apache/superset
#installed node npm with versions v18.16.0/ 9.5.1 respectively.
npm install cross-env
npm install -f --no-optional --global webpack webpack-cli; 
npm run build
#create virtual env of 3.9 and activate
mamba create -n superset python=3.9 ; mamba activate superset; 
pip install -r requirements/testing.txt;
pip install -e .;
superset db upgrade;
superset fab create-admin;
superset init;
superset load-examples;
export SUPERSET_SECRET_KEY=D1acauGDSStiNuu2O1ZmK9E59QUPkRfB_some_key
export TALISMAN_ENABLED="False"
FLASK_ENV=development superset run -p 8088 --with-threads --reload --debugger
```

hope this helps.

**Comment by vndroid** [comment]
I'm facing the same issue. I installed it through the official Scratch method.

**Comment by cbrianbet** [comment]
Any help please

**Comment by cloudcheflabs** [comment]
As @jaihind213 said, set env `TALISMAN_ENABLED` to `FALSE` works fine for me.

**Comment by jiayouchongmingniao** [comment]
export TALISMAN_ENABLED="False"
SESSION_COOKIE_SAMESITE,  Lax/None/Strict 

doesn't work for me

**Comment by jiayouchongmingniao** [comment]
sudo docker compose -f docker-compose-non-dev.yml up

problem solved

**Comment by jiayouchongmingniao** [comment]
![1702824892472](https://github.com/apache/superset/assets/55178588/78e9bd01-ecae-42e9-9822-c5ac19b31f68)

**Comment by tmnvanderberg** [comment]
Having the same issue...

**Comment by sandeepr43** [comment]
Still having this issue ...werkzeug exception always pops up in my superset.log

**Comment by rusackas** [comment]
Just for fun, I'm curious what @dosu-bot thinks.

**Comment by alivalizadakaseya** [comment]
Having the same issue, it is sad that this issue has been persistent so long :(

**Comment by sandeepr43** [comment]
+1 
Having the same issue :(

**Comment by khushal786** [comment]
anything mention above is also not working for me too.

**Comment by edwardzhanged** [comment]
```
cd /your_superset_path/superset-frontend
npm install 
npm run build
```
Then solved. Make sure you are in inactive docker compose mode.

**Comment by arm-moodys** [comment]
I had try all the workarounds  above and nothing worked I created a new issue with focus on the behavior I've see in our environments https://github.com/apache/superset/issues/31025

**Comment by rusackas** [comment]
While this thread was once a hotbed of activity, it seems to have gone silent for several months. Perhaps the issue worked itself out somewhere along the line? Let us know if this is still persistent in 4.1.2/5.0.0rc2, or it might be closed due to inactivity eventually.

If any of the fixes along the way have helped, updates to the docs would be appreciated. All I can say personally is that I haven't run into this, and it hasn't been an issue on the SaaS version of Superset I work with day to day ;)

**Comment by aieng-imran** [comment]
still facing same issue

**Comment by kito-arch** [comment]
In my case, loader didn't go away after login. 
Here is what fixed it: 
1. Go to frontend directory: `cd superset-frontend`
2. Delete node modules: `rm -rf node_modules`
3. Delete package-lock.json file
4. `npm cache clean --force`
5. `npm i`
6. `npm run build`

Loader was still there, so I tried changing the port: 
`superset run -p <some other port than 8088> --with-threads --reload --debugger --debug`

And then it worked.

**Comment by rusackas** [comment]
This issue has accumulated reports of many different configuration problems over three years, with most being resolved through environment-specific fixes (frontend build, nginx websocket proxy, session cookie settings, etc.) rather than a bug in Superset itself.

These are setup and configuration concerns best addressed through:
- The [Superset installation documentation](https://superset.apache.org/docs/installation/docker-compose)
- The [Apache Superset Slack community](https://communityinviter.com/apps/apache-superset/apache-superset)
- The [GitHub Discussions](https://github.com/apache/superset/discussions) section

If you have identified a specific, reproducible bug in Superset's code (not a configuration issue), please open a new focused issue with your Superset version, deployment method, and minimal reproduction steps.
