### ISSUE TITLE
Error: No such command 're-encrypt-secrets'.

### ISSUE THREAD

**Issue by Rabbit-st** [apache/superset#20422]
#### How to reproduce the bug

Upgrade superset from 1.3.2 to 1.5.1 using Helm，values.yaml init config：
```yaml
...
configOverrides:
  my_override: |
    PREVIOUS_SECRET_KEY = '<old_secret_key >'
    SECRET_KEY = 'wl/gRcQF/xkVCm9HyFWb2Uil0fzJ8K9OBnQrUusn/AyWw/8T/stLkRfi'
...
init:
 ...
  command:
    - "/bin/sh"
    - "-c"
    - ". {{ .Values.configMountPath }}/superset_bootstrap.sh; superset re-encrypt-secrets; . {{ .Values.configMountPath }}/superset_init.sh"
```
helm upgrade：
```bash
helm upgrade --install superset -n superset --values custom-values.yaml ./superset
```

### Actual results
superset-init-db job logs output：
```yaml
logging was configured successfully
2022-06-17 08:47:00,991:INFO:superset.utils.logging_configurator:logging was configured successfully
2022-06-17 08:47:01,002:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
Usage: superset [OPTIONS] COMMAND [ARGS]...
Try 'superset --help' for help.
Error: No such command 're-encrypt-secrets'.
Upgrading DB schema...
logging was configured successfully
2022-06-17 08:47:06,149:INFO:superset.utils.logging_configurator:logging was configured successfully
2022-06-17 08:47:06,160:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
INFO [alembic.runtime.migration] Context impl MySQLImpl.
INFO [alembic.runtime.migration] Will assume transactional DDL.
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
Initializing roles...
logging was configured successfully
2022-06-17 08:47:11,671:INFO:superset.utils.logging_configurator:logging was configured successfully
2022-06-17 08:47:11,681:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Syncing role definition
2022-06-17 08:47:15,220:INFO:superset.security.manager:Syncing role definition
Syncing Admin perms
2022-06-17 08:47:15,235:INFO:superset.security.manager:Syncing Admin perms
Syncing Alpha perms
2022-06-17 08:47:15,734:INFO:superset.security.manager:Syncing Alpha perms
Syncing Gamma perms
2022-06-17 08:47:16,255:INFO:superset.security.manager:Syncing Gamma perms
Syncing granter perms
2022-06-17 08:47:16,795:INFO:superset.security.manager:Syncing granter perms
Syncing sql_lab perms
2022-06-17 08:47:17,314:INFO:superset.security.manager:Syncing sql_lab perms
Fetching a set of all perms to lookup which ones are missing
2022-06-17 08:47:17,816:INFO:superset.security.manager:Fetching a set of all perms to lookup which ones are missing
Creating missing datasource permissions.
2022-06-17 08:47:18,531:INFO:superset.security.manager:Creating missing datasource permissions.
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
decrypted = decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 1: invalid continuation byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/bin/superset", line 33, in <module>
sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
return super(FlaskGroup, self).main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
return __ctx.invoke(f, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
return __ctx.invoke(f, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/app/superset/cli.py", line 91, in init
security_manager.sync_role_definitions()
File "/app/superset/security/manager.py", line 704, in sync_role_definitions
self.create_missing_perms()
File "/app/superset/security/manager.py", line 646, in create_missing_perms
merge_pv("datasource_access", datasource.get_perm())
File "/app/superset/connectors/sqla/models.py", line 636, in get_perm
return f"[{self.database}].[{self.table_name}](id:{self.id})"
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 294, in __get__
return self.impl.get(instance_state(instance), dict_)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 730, in get
value = self.callable_(state, passive)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 759, in _load_for_state
return self._emit_lazyload(
File "<string>", line 1, in <lambda>
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 847, in _emit_lazyload
q(session)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 615, in _load_on_pk_identity
result = list(bq.for_session(self.session).params(**params))
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
cursor.close()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
compat.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
rows = [proc(row) for row in fetch]
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
rows = [proc(row) for row in fetch]
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 579, in _instance
_populate_full(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
dict_[key] = getter(row)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 1278, in process
return process_value(impl_processor(value), dialect)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 477, in process_result_value
value = super().process_result_value(value=value, dialect=dialect)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 422, in process_result_value
decrypted_value = self.engine.decrypt(value)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 130, in decrypt
raise ValueError('Invalid decryption key')
ValueError: Invalid decryption key
```

### Environment

(please complete the following information):

- browser type and version:
- superset version:  1.5.1
- python version: 3.8
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
