### ISSUE TITLE
Postgres timestamp with timezone causes error

### ISSUE THREAD

**Issue by dheardal** [apache/superset#20450]
#### How to reproduce the bug

1. Setup a postgres table with a timestamp with time zone (timstamptz) column
2. Query that column using sql editor or consume that column in a chart
3. See error

### Expected results

Be able to see the column

### Actual results

```
superset_1        | Traceback (most recent call last):
superset_1        |   File "/app/superset/views/base.py", line 211, in wraps
superset_1        |     return f(self, *args, **kwargs)
superset_1        |   File "/app/superset/utils/log.py", line 245, in wrapper
superset_1        |     value = f(*args, **kwargs)
superset_1        |   File "/app/superset/views/core.py", line 2574, in sql_json
superset_1        |     command_result: CommandResult = command.run()
superset_1        |   File "/app/superset/sqllab/command.py", line 104, in run
superset_1        |     raise ex
superset_1        |   File "/app/superset/sqllab/command.py", line 96, in run
superset_1        |     status = self._run_sql_json_exec_from_scratch()
superset_1        |   File "/app/superset/sqllab/command.py", line 138, in _run_sql_json_exec_from_scratch
superset_1        |     raise ex
superset_1        |   File "/app/superset/sqllab/command.py", line 133, in _run_sql_json_exec_from_scratch
superset_1        |     return self._sql_json_executor.execute(
superset_1        |   File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
superset_1        |     raise SupersetErrorsException(
superset_1        | superset.exceptions.SupersetErrorsException: [SupersetError(message="'+00'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'PostgreSQL', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```

#### Screenshots

<img width="1004" alt="Screenshot 2022-06-21 at 11 28 46" src="https://user-images.githubusercontent.com/56386166/174778852-49154faa-bc43-4478-a6b4-136a2c44ca7e.png">

### Environment

(please complete the following information):

- browser type and version: Chrome 102
- superset version: 1.5.1
- python version:  3.8
- node.js version: none
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This was not an issue in the 1.4.2.
May be similar to #19995

**Comment by dheardal** [comment]
Duplicate of #20155
