### ISSUE TITLE
current_user not working in DB_CONNECTION_MUTATOR while in SqlLab

### ISSUE THREAD

**Issue by mariovor** [apache/superset#20455]
### Following Setup
- Superset 1.5.0 running in docker.
- Postgres database 13 running in trust mode accepting connections from Superset host
- Authentication via Keycloak, custom SecurityManager created for user authentication.
- DB_CONNECTION_MUTATOR used to modify the username of the database connection (see [here](https://github.com/apache/superset/issues/17074) from where I took inspiration) 

**What do I want to achieve?**

The postgres database is configured with row security. Roles can access certain rows, user and roles are synced via AD. In order to use this permissioning on the rows, each DB connection started from a user inside Superset should use the username. A password is not required because the superset host is registered as trustet host in postgres. 

DB_CONNECTION_MUTATOR
```
def DB_CONNECTION_MUTATOR(uri, params, username, security_manager, source):
    uri.username = security_manager.current_user.username
    return uri, params
```

### Expected results:
- On each database call, the username of the logged-in user is used as connection parameter for the database. 

### Actual results
- It **does** work for  creating charts. 
- If fails when running a query in SqlLab
```
[SupersetError(message="'_AppCtxGlobals' object has no attribute 'user'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'PostgreSQL', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 211, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 2574, in sql_json
    command_result: CommandResult = command.run()
  File "/app/superset/sqllab/command.py", line 104, in run
    raise ex
  File "/app/superset/sqllab/command.py", line 96, in run
    status = self._run_sql_json_exec_from_scratch()
  File "/app/superset/sqllab/command.py", line 138, in _run_sql_json_exec_from_scratch
    raise ex
  File "/app/superset/sqllab/command.py", line 133, in _run_sql_json_exec_from_scratch
    return self._sql_json_executor.execute(
  File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
    raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message="'_AppCtxGlobals' object has no attribute 'user'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'PostgreSQL', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```

The object `security_manager.current_user` is available when creating charts, but not in the SqlLab. 

Looking at the source code of [BaseSecurityManager](https://github.com/dpgaspar/Flask-AppBuilder/blob/357c8100e96034c736860737a41c2004aa4e993b/flask_appbuilder/security/manager.py#L493)
```
@property
    def current_user(self):
        if current_user.is_authenticated:
            return g.user
        elif current_user_jwt:
            return current_user_jwt
```
it seems that `g` does not have a `user` property.

Is it somehow expected that SqlLab behaves differently?

**Comment by rickysaltzer** [comment]
Looking into this issue a bit further, and it appears that the issue is hit upon accessing the user from the SAM (not even setting). 

```python
def DB_CONNECTION_MUTATOR(uri, params, username, security_manager, source):
    # The following just accesses the user from the SAM, but does not actually set it.
    # - the same behavior occurs if you access `g` directly. 
    accessing_user_tmp = security_manager.current_user.username
    return uri, params
```

Resulting in:
```python
'_AppCtxGlobals' object has no attribute 'user'
```

**Comment by rickysaltzer** [comment]
I think the following is a suitable workaround:

`models/core.py#392` 
```python
        if DB_CONNECTION_MUTATOR:
            if not source and request and request.referrer:
                if "/superset/dashboard/" in request.referrer:
                    source = utils.QuerySource.DASHBOARD
                elif "/superset/explore/" in request.referrer:
                    source = utils.QuerySource.CHART
                elif "/superset/sqllab/" in request.referrer:
                    source = utils.QuerySource.SQL_LAB

            if source == utils.QuerySource.SQL_LAB:
                effective_username = user_name

            # if SQL_LAB is set, use the user_name
            sqlalchemy_url, params = DB_CONNECTION_MUTATOR(
                sqlalchemy_url, params, effective_username, security_manager, source
            )
```

`DB_CONNECTION_MUTATOR`
```python
def DB_CONNECTION_MUTATOR(uri, params, username, security_manager, source):
    # The following just accesses the user from the SAM, but does not actually set it.
    # - the same behavior occurs if you access `g` directly.
    if username and source is QuerySource.SQL_LAB:
        user = security_manager.find_user(username=username)
    else:
        user = security_manager.current_user
    if user:
        uri.username = user.username
        uri.password = "password"
    return uri, params
```

The key is that `user_name` is passed to the model when the user hits the `Run` box, and can be passed to the mutator for a user lookup...as the `current_user` is unavailable to the mutator when `Run` is clicked. I've only tested this locally, but it appears to work 😄

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)

**Comment by divick-vama** [comment]
@dosu using the following code:

```
def DB_CONNECTION_MUTATOR(uri, params, username, security_manager, source):
    if username and source is QuerySource.SQL_LAB:
        user = security_manager.find_user(username=username)
    else:
        user = security_manager.current_user
    if user:
        uri.username = user.username
        uri.password = "password"
    return uri, params
```

superset is giving error: 

```
File "/app/pythonpath/superset_config.py", line 19, in db_connection_mutator
uri.username = user.email
AttributeError: can't set attribute
```

**Comment by divick-vama** [comment]
@dosu I also notice that security_manager.current_user returns None in custom db_connection_mutator when the running query from sqllab. This is causing the following stacktrace:

```
Traceback (most recent call last):
File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/.venv/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
return f(self, *args, **kwargs)
File "/app/superset/views/base_api.py", line 120, in wraps
duration, response = time_function(f, self, *args, **kwargs)
File "/app/superset/utils/core.py", line 1369, in time_function
response = func(*args, **kwargs)
File "/app/superset/views/base_api.py", line 92, in wraps
return f(self, *args, **kwargs)
File "/app/superset/utils/log.py", line 304, in wrapper
value = f(*args, **kwargs)
File "/app/superset/sqllab/api.py", line 409, in execute_sql_query
command_result: CommandResult = command.run()
File "/app/superset/utils/decorators.py", line 266, in wrapped
return on_error(ex)
File "/app/superset/utils/decorators.py", line 236, in on_error
raise ex
File "/app/superset/utils/decorators.py", line 259, in wrapped
result = func(*args, **kwargs)
File "/app/superset/commands/sql_lab/execute.py", line 105, in run
status = self._run_sql_json_exec_from_scratch()
File "/app/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
return self._sql_json_executor.execute(
File "/app/superset/sqllab/sql_json_executer.py", line 110, in execute
raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message='Authentication required.', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'ClickHouse Connect (Superset)', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```
