### ISSUE TITLE
Impala DatabaseRestApi.table_metadata.error

### ISSUE THREAD

**Issue by msestak** [apache/superset#20682]
OS: RHEL 8.6
Python: 3.8.12
Superset: 1.5.1 (also 1.4.1)
impyla: impyla-0.16.3

![superset_fetch_metadata](https://user-images.githubusercontent.com/5228178/178494872-a34ee86a-4624-467e-b119-df66f1b54124.png)

When tying to fetch metadata for a impala table following error occurs (in a SQL LAb):

```
2022-07-12 14:35:01,195:DEBUG:impala.hiveserver2:Attempting to open transport (tries_left=3)
2022-07-12 14:35:01,195:DEBUG:impala.hiveserver2:Transport opened
2022-07-12 14:35:01,195:DEBUG:impala.hiveserver2:CloseSession: resp=TCloseSessionResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None))
2022-07-12 14:35:01,195:DEBUG:impala.hiveserver2:Closing HS2 connection
2022-07-12 14:35:01,195:DEBUG:impala.hiveserver2:close_service: client=<thriftpy2.thrift.TClient object at 0x7f24d5a2fdf0>
2022-07-12 14:35:01,195:DEBUG:superset.stats_logger:ESC[36m[stats_logger] (incr) DatabaseRestApi.table_metadata.errorESC[0m
2022-07-12 14:35:01,195:ERROR:root:'VARCHAR'
Traceback (most recent call last):
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/superset/views/base_api.py", line 112, in wraps
    raise ex
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/superset/views/base_api.py", line 109, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/superset/utils/core.py", line 1468, in time_function
    response = func(*args, **kwargs)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/superset/databases/api.py", line 522, in table_metadata
    table_info = get_table_metadata(database, table_name, schema_name)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/superset/databases/utils.py", line 66, in get_table_metadata
    columns = database.get_columns(table_name, schema_name)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/superset/models/core.py", line 687, in get_columns
    return self.db_engine_spec.get_columns(self.inspector, table_name, schema)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/superset/db_engine_specs/base.py", line 1043, in get_columns
    return inspector.get_columns(table_name, schema)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 390, in get_columns
    col_defs = self.dialect.get_columns(
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/impala/sqlalchemy.py", line 215, in get_columns
    'type': _impala_type_to_sqlalchemy_type[col[1]],
KeyError: 'VARCHAR'
2022-07-12 14:35:01,198:INFO:werkzeug:10.1.44.18 - - [12/Jul/2022 14:35:01] "ESC[35mESC[1mGET /api/v1/database/1/table/f_internal_reporting_mon_pnd/alm/ HTTP/1.1ESC[0m" 500 -
2022-07-12 14:35:01,269:ERROR:superset.views.base:'queryEditorId'
Traceback (most recent call last):
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 190, in wraps
    return f(self, *args, **kwargs)
  File "/opt/pydev/py38-superset-1.5.1/lib/python3.8/site-packages/superset/views/sql_lab.py", line 272, in post
    TableSchema.tab_state_id == table["queryEditorId"],
KeyError: 'queryEditorId'

```
Running query in a query window runs fine.

**Comment by msestak** [comment]
Updating impyla to 0.17 and installing kerberos python package fixed it for me.
