### ISSUE TITLE
installation problem  unexpected keyword argument 'exclude_patterns'

### ISSUE THREAD

**Issue by lfzCarlosC** [apache/superset#20788]
After I tried to install required libraries for superset and run the command:

superset run -p 8088 --with-threads --reload --debugger

I got this error: 

```
Traceback (most recent call last):
  File "/Users/fangzhouli/git/venv/bin/superset", line 21, in <module>
    superset()
  File "/Users/fangzhouli/git/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fangzhouli/git/venv/lib/python3.9/site-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/Users/fangzhouli/git/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/fangzhouli/git/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fangzhouli/git/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fangzhouli/git/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fangzhouli/git/venv/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/fangzhouli/git/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fangzhouli/git/venv/lib/python3.9/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
TypeError: run_simple() got an unexpected keyword argument 'exclude_patterns'
```

I think this may be a library version issue. Does anyone know which libraries is incompatible?

Flask==2.1.3
Flask-AppBuilder==4.1.3
Flask-Babel==2.0.0
Flask-Caching==2.0.0
Flask-Compress==1.12
Flask-JWT-Extended==4.4.2
Flask-Login==0.6.1
Flask-Migrate==3.1.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.15.1
superset==0.30.1

**Comment by PatraTapan** [comment]
i am getting the same issue

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
