### ISSUE TITLE
superset db upgrade is not working (ImportError: cannot import name 'parse_human_timedelta' from 'superset.utils.core')

### ISSUE THREAD

**Issue by veeru-initiator** [apache/superset#20935]
(superset) C:\Users\Veeru>superset db upgra
----------------------------------------------------------------------------------
                                    WARNING
--------------------------------------------------------------------------------

Trying to setup superset in windows system using conda environment, following the steps mentioned in superset website while "superset db upgrade". I have following error, here is the log

A Default SECRET_KEY was detected, please use superset_config.py to override it.
Use a strong complex alphanumeric string and use a tool to help you generate
a sufficiently random sequence, ex: openssl rand -base64 42
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
logging was configured successfully
2022-08-01 21:28:00,559:INFO:superset.utils.logging_configurator:logging was configured successfully
2022-08-01 21:28:00,606:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
2022-08-01 21:28:00,606:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
2022-08-01 21:28:00,622:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
No PIL installation found
2022-08-01 21:28:00,760:INFO:superset.utils.screenshots:No PIL installation found
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 1e2841a4128 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 1a48a5411020 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 12d55656cbca is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 18e88e1cc004 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 1d2ddd543133 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 1226819ee0e3 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 1296d28ec131 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 19a814813610 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 130915240929 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 1d9e835a84f9 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 0c5070e96b57 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 1a1d627ebd8e is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 0b1f1ab473c0 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 18dc26817ad2 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 190188938582 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 11c737c17cc6 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 1495eb914ad3 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 21e88bc06c02 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 258b5280a45e is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 2591d77e9831 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 27ae655e4247 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 289ce07647b is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 2929af7925ed is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 2fcdcb35e487 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 30bb17c0dc76 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 315b3f4da9b0 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 33d996bcc382 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 3b626e2a6783 is present more than once
  util.warn(
c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py:195: UserWarning: Revision 3c3ffe173e4f is present more than once
  util.warn(
Traceback (most recent call last):
  File "C:\Users\Veeru\AppData\Local\Programs\Python\Python38\Scripts\superset-script.py", line 33, in <module>
    sys.exit(load_entry_point('apache-superset==2.0.0', 'console_scripts', 'superset')())
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\flask\cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\flask\cli.py", line 407, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\flask_migrate\cli.py", line 149, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\flask_migrate\__init__.py", line 98, in wrapped
    f(*args, **kwargs)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\flask_migrate\__init__.py", line 185, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\command.py", line 322, in upgrade
    script.run_env()
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\util\pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\util\pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\superset\extensions\../migrations\env.py", line 126, in <module>
    run_migrations_online()
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\superset\extensions\../migrations\env.py", line 118, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\runtime\environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\runtime\migration.py", line 611, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\command.py", line 311, in upgrade
    return script._upgrade_revs(revision, rev)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\base.py", line 443, in _upgrade_revs
    for script in reversed(list(revs))
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py", line 799, in iterate_revisions
    revisions, heads = fn(
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py", line 1426, in _collect_upgrade_revisions
    for rev in self._parse_upgrade_target(
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py", line 1218, in _parse_upgrade_target
    return self.get_revisions(target)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py", line 529, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py", line 753, in _resolve_revision_number
    self._revision_map
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\revision.py", line 191, in _revision_map
    for revision in self._generator():
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\base.py", line 140, in _load_revisions
    script = Script._from_filename(self, vers, file_)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\script\base.py", line 1013, in _from_filename
    module = util.load_python_file(dir_, filename)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\util\pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\alembic\util\pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\superset\migrations\versions\3dda56f1c4c6_migrate_num_period_compare_and_period_.py", line 36, in <module>
    from superset.utils.core import parse_human_timedelta
ImportError: cannot import name 'parse_human_timedelta' from 'superset.utils.core' (c:\users\veeru\appdata\local\programs\python\python38\lib\site-packages\superset\utils\core.py)

Please help me...

**Comment by Lemmynjash** [comment]
I am facing the same issue 
Were you able to find a solution?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

... also, it looks like you're using Windows, which is not officially supported.
