### ISSUE TITLE
Cannot delete database

### ISSUE THREAD

**Issue by labros-zotos** [apache/superset#21106]
On a fresh installation, I create a new BigQuery database. I can connect to the database just fine.
However, if I try to delete it, I get the following error:
`Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context self.dialect.do_execute( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute cursor.execute(statement, parameters) psycopg2.errors.UndefinedColumn: column report_schedule.extra_json does not exist`

I have run `superset db upgrade` and `superset db init`.

The problem seems to be that the columns of `report_schedule` table are not what the source code is expecting.

#### How to reproduce the bug

1. Install the latest version Apache Superset using the Docker image
2. Login with an admin user.
3. Create a BigQuery database following superset instructions
4. Delete the database you created on step 3

### Expected results

The database I created to be deleted.

### Actual results

Error: _There was an issue deleting Google BigQuery: Fatal error_
Error on logs: Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context self.dialect.do_execute( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute cursor.execute(statement, parameters) psycopg2.errors.UndefinedColumn: column report_schedule.extra_json does not exist

### Environment

(please complete the following information):

- browser type and version: Chrome latest
- superset version: `2.0.0`
- python version: `3.8`
- node.js version: `-`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Docker container is running on Cloud Run. The database used is PostgreSQL 14

**Comment by labros-zotos** [comment]
Looking at the superset db heads I get the `e09b4ae78457` as the head even though there are many more migration files after it, including one that creates the extra_json column.
Running superset db upgrade doesn't change anything.

**Comment by labros-zotos** [comment]
There was a mismatch between the version of superset I used to create the database and the version of superset in the docker container I had in production.
