### ISSUE TITLE
[SupersetError(message="'dict' object has no attribute 'set'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>

### ISSUE THREAD

**Issue by anilkumar000** [apache/superset#21122]
Hello, im trying to use  "SQLLAB_BACKEND_PERSISTENCE": True for caching sqllab_query_results. But the feature is failing to return response of queried result back to superset and throwing below Error logs. Could please correct and help me on this feature.

**Superset version -** v2.0
**Superset instance -** On Kubernetes container using Helm
**Feature Flag configuration** in superset_config.py -
 ```
   FEATURE_FLAGS = {
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,
    "DASHBOARD_RBAC": True,
    "VERSIONED_EXPORT": True,
    "GENERIC_CHART_AXES": True,
    "SQLLAB_BACKEND_PERSISTENCE": True
    }
```
**Expected :** to get queried result in sqllab tab.
**Actual Error Logs :** 
```
[SupersetError(message="'dict' object has no attribute 'set'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Trino', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 207, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 2395, in sql_json
    command_result: CommandResult = command.run()
  File "/app/superset/sqllab/command.py", line 114, in run
    raise ex
  File "/app/superset/sqllab/command.py", line 98, in run
    status = self._run_sql_json_exec_from_scratch()
  File "/app/superset/sqllab/command.py", line 151, in _run_sql_json_exec_from_scratch
    raise ex
  File "/app/superset/sqllab/command.py", line 146, in _run_sql_json_exec_from_scratch
    return self._sql_json_executor.execute(
  File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
    raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message="'dict' object has no attribute 'set'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Trino', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
2022-08-18 09:12:41,251:WARNING:superset.views.base:[SupersetError(message="'dict' object has no attribute 'set'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Trino', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```

**Comment by anilkumar000** [comment]
It is the same issue with older verison (1.5.1) also.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)
