### ISSUE TITLE
superset init command fails at version 2.0.0

### ISSUE THREAD

**Issue by fgomezotero** [apache/superset#21242]
When I run `#superset init` command at the console of Superset UI container it fails

#### How to reproduce the bug

1. Go to Superset UI container console 
2. Run `#superset db upgrade` - *finish successfully*
3. Then when I run `#superset init`and get an error

### Expected results

The command completes without errors

### Actual results

I got an SQL error.

#### Screenshots

``` bash
$ superset init
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
2022-08-29 15:04:50,882:INFO:superset.utils.logging_configurator:logging was configured successfully
2022-08-29 15:04:50,887:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
2022-08-29 15:04:55,390:INFO:superset.security.manager:Syncing role definition
2022-08-29 15:04:55,403:INFO:superset.security.manager:Syncing Admin perms
2022-08-29 15:04:55,605:INFO:superset.security.manager:Syncing Alpha perms
2022-08-29 15:04:55,807:INFO:superset.security.manager:Syncing Gamma perms
2022-08-29 15:04:56,018:INFO:superset.security.manager:Syncing granter perms
2022-08-29 15:04:56,214:INFO:superset.security.manager:Syncing sql_lab perms
2022-08-29 15:04:56,422:INFO:superset.security.manager:Copy/Merge True to Public
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: operator does not exist: character varying = boolean
LINE 3: WHERE ab_role.name = true
                           ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 445, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 445, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/superset/cli/main.py", line 62, in init
    security_manager.sync_role_definitions()
  File "/app/superset/security/manager.py", line 725, in sync_role_definitions
    self.copy_role(
  File "/app/superset/security/manager.py", line 782, in copy_role
    role_from_permissions = list(self.find_role(role_from_name).permissions)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/sqla/manager.py", line 308, in find_role
    self.get_session.query(self.role_model).filter_by(name=name).one_or_none()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: character varying = boolean
LINE 3: WHERE ab_role.name = true
                           ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT ab_role.id AS ab_role_id, ab_role.name AS ab_role_name 
FROM ab_role 
WHERE ab_role.name = true]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

### Environment

- deployed on the Openshift 3.11 platform, using dockerhub's *apache/superset:2.0.0* as a base image
- superset version: **2.0.0**
- python version: Python 3.8.12
- Postgresql version: 12
- any feature flags active:
	- "DASHBOARD_CACHE": True,
    - "GLOBAL_ASYNC_QUERIES": True,
    - "DASHBOARD_CROSS_FILTERS": True,
    - "DASHBOARD_NATIVE_FILTERS_SET": True,
    - "ALERT_REPORTS": True,
    - "ENABLE_EXPLORE_DRAG_AND_DROP": True,
    - "ENABLE_DND_WITH_CLICK_UX": True,

**Comment by rdubois** [comment]
I'm wondering if the issue doesn't come from the configuration. It looks like you defined `PUBLIC_ROLE_LIKE` to `True` while the name of an existing role is expected (eg. `Gamma`). The boolean value was for the previous deprecated configuration variable `PUBLIC_ROLE_LIKE_GAMMA`.

**Comment by fgomezotero** [comment]
You are right, thanks for your suggestion and help
