### ISSUE TITLE
Error to exec query with set options

### ISSUE THREAD

**Issue by Felipevalera1** [apache/superset#21265]
Hello, i'cant set params like "set odps.sql.hive.compatible=true;" from execution query on odps. I receve two kinds type errors.

DB engine Error
Only SELECT statements are allowed against this database.

if don't pass param receved:
base error: ODPS-0123131: InstanceId: 20220831040625809g647p83
ODPS-0123131:User defined function exception - internal error - Fatal Error Happended
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.aliyun.odps.hive.wrapper.HiveInputFormatWrapper
	at com.aliyun.odps.udf.HiveReaderHandler.<init>(HiveReaderHandler.java:78)
	at com.aliyun.odps.udf.runtime.ObjectCreatorForEE.create(ObjectCreatorForEE.java:100)
Caused by: java.lang.ClassNotFoundException: com.aliyun.odps.hive.wrapper.HiveInputFormatWrapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.alibaba.apsara.sandking.SandboxLauncher$AppClassLoader.loadClass(SandboxLauncher.java:250)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.aliyun.odps.udf.impl.ImplUtils.loadClassByName(ImplUtils.java:77)
	at com.aliyun.odps.udf.HiveReaderHandler.<init>(HiveReaderHandler.java:64)
	... 1 more

This may be triggered by:
Issue 1002 - The database returned an unexpected error. 

I think I just need to pass this guy so he can run the queries on MaxComputer on Alibaba Cloud.

Thanks.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
