### ISSUE TITLE
Lost top app-menu bar in public-welcome, login, list users, list roles... pages

### ISSUE THREAD

**Issue by hungpv29** [apache/superset#21477]
Lost top app-menu bar in public-welcome, login, list users, list roles... pages

![image](https://user-images.githubusercontent.com/64894530/190306627-44db7e5c-838d-429a-8eb1-e11272b93549.png)

Error message
```
vendors.bcc40b00aee47a3bf22c.entry.js:2 TypeError: Cannot read properties of null (reading 'store')
    at vendors.bcc40b00aee47a3bf22c.entry.js:2:2301504
    at O (6052.4524fb0b983b459dad6c.entry.js:628:101)
    at Gi (vendors.bcc40b00aee47a3bf22c.entry.js:2:2224002)
    at bl (vendors.bcc40b00aee47a3bf22c.entry.js:2:2269964)
    at hu (vendors.bcc40b00aee47a3bf22c.entry.js:2:2262740)
    at du (vendors.bcc40b00aee47a3bf22c.entry.js:2:2262665)
    at ru (vendors.bcc40b00aee47a3bf22c.entry.js:2:2259695)
    at Ql (vendors.bcc40b00aee47a3bf22c.entry.js:2:2256463)
    at Vu (vendors.bcc40b00aee47a3bf22c.entry.js:2:2277678)
    at vendors.bcc40b00aee47a3bf22c.entry.js:2:2278887
    
vendors.bcc40b00aee47a3bf22c.entry.js:2 Uncaught TypeError: Cannot read properties of null (reading 'store')
    at vendors.bcc40b00aee47a3bf22c.entry.js:2:2301504
    at O (6052.4524fb0b983b459dad6c.entry.js:628:101)
    at Gi (vendors.bcc40b00aee47a3bf22c.entry.js:2:2224002)
    at bl (vendors.bcc40b00aee47a3bf22c.entry.js:2:2269964)
    at hu (vendors.bcc40b00aee47a3bf22c.entry.js:2:2262740)
    at du (vendors.bcc40b00aee47a3bf22c.entry.js:2:2262665)
    at ru (vendors.bcc40b00aee47a3bf22c.entry.js:2:2259695)
    at Ql (vendors.bcc40b00aee47a3bf22c.entry.js:2:2256463)
    at Vu (vendors.bcc40b00aee47a3bf22c.entry.js:2:2277678)
    at vendors.bcc40b00aee47a3bf22c.entry.js:2:2278887
```

#### How to reproduce the bug
Lost top app-menu bar when access following paths:
- /superset/welcome/ (public welcome page)
- /login/ (login page)
- /superset/sqllab/
- Any pages accessed from `Settings` (like /users/list/, /roles/list/ ...)
![image](https://user-images.githubusercontent.com/64894530/190305925-5abaccb4-f5d3-4791-bba3-69ed0ad6e05d.png)

### Environment
- browser type and version: Chorme (Version 105.0.5195.102) | Safari
- superset version: `1.5.1`
- python version: `3.8.12`
- node.js version: `16.9.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by hungpv29** [comment]
.
