### ISSUE TITLE
Database connectivity problem: {"cache_timeout":["Not a valid integer."]}

### ISSUE THREAD

**Issue by sfirke** [apache/superset#21554]
I don't have this fully figured out but opening to establish a record for others.

#### How to reproduce the bug

Go to Databases -> Edit database -> Performance.  Leave the first two cache timeouts blank (chart, schema) and put 3600 for the last one.  Click Finish.

### Expected results

Values save.

### Actual results

Error on screen: 
![image](https://user-images.githubusercontent.com/7569808/191824454-890ba934-5921-4ca8-bf02-dc86a110036c.png)

Accompanied by a PUT request resulting in 400 in the logs.

### Workaround

Put values of 300, 300 (in one instance Superset changed this to 299??) and 14400 for the cache timeout values.  Those are accepted.

### Environment
-Superset 2.0.0, docker-compose deployed
-MSSQL database

### Additional context
I was troubleshooting a problem where my table list wouldn't refresh, despite being able to query a new table in SQL Lab.  First the table list didn't refresh, then I changed a timeout setting and afterward would get this error when it tried to list tables:
```
2022-09-22 18:19:59,211:ERROR:superset.views.base:value is not an integer or out of range
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 185, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 175, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 1122, in tables
    for datasource_name in database.get_all_table_names_in_schema(
  File "/app/superset/utils/cache.py", line 146, in wrapped_f
    cache.set(cache_key, obj, timeout=kwargs.get("cache_timeout"))
  File "/usr/local/lib/python3.8/site-packages/flask_caching/__init__.py", line 267, in set
    return self.cache.set(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_caching/backends/rediscache.py", line 163, in set
    result = self._write_client.setex(
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1822, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: value is not an integer or out of range
```

**Comment by mayurnewase** [comment]
couldn't reproduce with latest master (last commit sha `31895f412eba60e274c7158a39cf0a8455ffd671`)
able to save that timeout for postgre db.
