### ISSUE TITLE
ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine' in 2.0.0 docker-compose build?

### ISSUE THREAD

**Issue by d1rewolf** [apache/superset#21609]
I'm trying to build the new 2.0.0 release with docker-compose on Ubuntu 22.04.01 LTS.

No matter what I do, the superset_app keeps restarting with::

```
superset_init            | Traceback (most recent call last):                                                                                       superset_init            |   File "/usr/local/bin/superset", line 33, in <module>                                                                   superset_init            |     sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
superset_init            |   File "/usr/local/bin/superset", line 25, in importlib_load_entry_point                                                 superset_init            |     return next(matches).load()                                                                                          superset_init            |   File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load                                                superset_init            |     module = import_module(match.group('module'))                                                                        superset_init            |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module                                      superset_init            |     return _bootstrap._gcd_import(name[level:], package, level)                                                          superset_init            |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                        superset_init            |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                      superset_init            |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
superset_init            |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                           superset_init            |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                        superset_init            |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                      superset_init            |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
superset_init            |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_init            |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
superset_init            |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
superset_init            |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
superset_init            |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
superset_init            |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
superset_init            |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_init            |   File "/app/superset/__init__.py", line 21, in <module>
superset_init            |     from superset.app import create_app
superset_init            |   File "/app/superset/app.py", line 23, in <module>
superset_init            |     from superset.initialization import SupersetAppInitializer
superset_init            |   File "/app/superset/initialization/__init__.py", line 33, in <module>
superset_init            |     from superset.extensions import (
superset_init            |   File "/app/superset/extensions/__init__.py", line 33, in <module>
superset_init            |     from superset.utils.encrypt import EncryptedFieldFactory
superset_init            |   File "/app/superset/utils/encrypt.py", line 23, in <module>
superset_init            |     from sqlalchemy.engine import Connection, Dialect, RowProxy
superset_init            | ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine' (/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py)
```

Any ideas why this would happen?

Thanks in advance!

**Comment by d1rewolf** [comment]
Never mind....I need to learn to follow directions. Using the following works:

```
docker-compose -f docker-compose-non-dev.yml pull
docker-compose -f docker-compose-non-dev.yml up
```

My mistake....I was simply using "docker-compose -f docker-compose.yml up"

**Comment by nytai** [comment]
Closing as this is specific to your environment

**Comment by nytai** [comment]
This is usually due to a mismatch between the container you are running and the code that's volume mounted in. All the dependencies are installed in the container, but the code might be expecting a different dependency. You should always run `docker-compose pull` to ensure you are running the latest image. If you still have issues then look into updating the image somehow to make sure the installed dependencies match the code

**Comment by gforien** [comment]
Same happened to me when I checkout tag `1.5.1` and forgot to run docker-compose with the right TAG
`TAG=1.5.1 docker-compose up`
