### ISSUE TITLE
Installation Error on MacBook Pro (16-inch, 2021) - Apple M1 Max Chip 

### ISSUE THREAD

**Issue by kousikan** [apache/superset#21686]
I was trying to install Superset as per the instructions on the page -- https://superset.apache.org/docs/installation/installing-superset-from-scratch on my MacBook Pro (16-inch, 2021) - Apple M1 Max Chip and ran into the error. I tried reinstaling all the prerequisites and repated the steps but still ended up with the same error message.

#### How to reproduce the bug

1. mkdir pysuperset
2. cd pysuperset
3. pipenv --python 3.8
4. pipenv shell 
5. xcode-select --install
6. brew install readline pkg-config libffi openssl mysql postgres
7. pip install --upgrade setuptools pip
8. export LDFLAGS="-L$(brew --prefix openssl)/lib"
9. export CFLAGS="-I$(brew --prefix openssl)/include"
10. pip install apache-superset
11. superset db upgrade

### Expected results
Successful Completion of DB upgrade. All steps completed successfully until step 10. 

### Actual results
superset db upgrade - command threw this error message
Traceback (most recent call last):
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/superset/initialization/__init__.py", line 33, in <module>
    from superset.extensions import (
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/superset/extensions/__init__.py", line 32, in <module>
    from superset.utils.cache_manager import CacheManager
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/superset/utils/cache_manager.py", line 24, in <module>
    from superset.utils.core import DatasourceType
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/superset/utils/core.py", line 75, in <module>
    from cryptography.hazmat.backends.openssl.x509 import _Certificate
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/kousikan.veeramuthu/code/pysuperset/.venv/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (_ffi_prep_closure)
what actually happens.

### Environment

(please complete the following information):

- browser type and version: NA
- superset version: apache-superset-2.0.0
- python version: Python 3.8.13
- node.js version: v18.9.1
- any feature flags active: NA

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cass-simplelegal** [comment]
Have you tried cloning the Superset Repo locally?

**Comment by ohadch** [comment]
Still reproduced as of March 2023 with Python 3.8.12 and Python 3.9.16. And yes, I am working with a local clone of Superset :(
