### ISSUE TITLE
Error executing the command docker-compose up

### ISSUE THREAD

**Issue by julemole** [apache/superset#21742]
When running docker-compose up the console keeps loading and localhost:8088 does not load. But running the command to run superset on non-dev does work, but I need to run it in developer mode to see my local changes.

**Comment by zhaorui2022** [comment]
I also ran into issues where docker-compose stops working locally after pulling the latest changes. But mine shows an error where it failed to load "slack_sdk". I did try to reinstall the dependencies with pip, and verified I have a "slack-sdk" installed with the correct version. However, when running it with docker-compose, it's not happy with the underscore. I ended up checking out this commit as the HEAD: f784455264b9376a20f05760bf6d90d1dc1e7010, which is the commit before slack_sdk was introduced. After that, it works for me.

**Comment by BowenXiao1999** [comment]
Do you solve this? I get similar problems: the superset-websocket fail when use `docker-compose up`.

**Comment by gangtao** [comment]
yes, I hit the issue as well
```
2023-06-22 22:12:27 
2023-06-22 22:12:27 > superset-websocket@0.0.1 start
2023-06-22 22:12:27 > node dist/index.js start
2023-06-22 22:12:27 
2023-06-22 22:12:27 {"date":"Fri Jun 23 2023 05:12:27 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Please provide a JWT secret at least 32 bytes long\nError: Please provide a JWT secret at least 32 bytes long\n    at Object.<anonymous> (/home/superset-websocket/dist/index.js:75:11)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:22:47","os":{"loadavg":[1.38,1.78,2.61],"uptime":20568},"process":{"argv":["/usr/local/bin/node","/home/superset-websocket/dist/index.js","start"],"cwd":"/home/superset-websocket","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":341576,"external":1562460,"heapTotal":21794816,"heapUsed":15975536,"rss":59805696},"pid":18,"uid":1000,"version":"v16.20.1"},"stack":"Error: Please provide a JWT secret at least 32 bytes long\n    at Object.<anonymous> (/home/superset-websocket/dist/index.js:75:11)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:22:47","trace":[{"column":11,"file":"/home/superset-websocket/dist/index.js","function":null,"line":75,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1198,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1252,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1076,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":911,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":22,"method":null,"native":false}]}
2023-06-22 22:12:27 config.json file not found
2023-06-22 22:12:30 npm notice 
2023-06-22 22:12:30 npm notice New major version of npm available! 8.19.4 -> 9.7.2
2023-06-22 22:12:30 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.2>
2023-06-22 22:12:30 npm notice Run `npm install -g npm@9.7.2` to update!
2023-06-22 22:12:30 npm notice 

```

**Comment by luy710** [comment]
Do you solve this? I get similar problems: the superset-websocket fail when use docker-compose up.

**Comment by luy710** [comment]
> Does anyone have the fix for this?

cp superset-websocket/config.exmpole.json superset-websocket/config.json
jwtSecret:"123123123123123123123123123123123123123123123123123123123123123123123123123123"

**Comment by hk-the-analyst** [comment]
Hit the issue now with a fresh clone! Does anyone have a fix?
`"message":"uncaughtException: Please provide a JWT secret at least 32 bytes long\nError: Please provide a JWT secret at least 32 bytes long`

**Comment by akshayjain3450** [comment]
@rusackas 
This issue I have opened in discussion and it is also logged here. We have no update on this or a good fix. Can you help out?

**Comment by rusackas** [comment]
A few things to disambiguate.... we might be dealing with multiple things here, so let's try to stay on one thread
• Is this happening on an official release, or on master? 
• If this is happening on `superset-websocket`, should we treat that as a separate issue, or are these directly related?
• Does the message about providing a secret go away if you... provide a secret?
• If this thread is about starting superset itself (is it, anymore?) then what are the errors people are encountering?
• If you start docker in non-dev mode, what developer processes are blocked? You can at least still run the frontend with hot-reloading in a separate thread... not sure about backend changes.

**Comment by butuzov** [comment]
> Does the message about providing a secret go away if you... provide a secret?
Yes. After adding content to `superset-websocket/config.json#jwtSecret` (a copy of `superset-websocket/config.example.json`)
 its gone...
