### ISSUE TITLE
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' after upgrade

### ISSUE THREAD

**Issue by yanickrochon** [apache/superset#21983]
After performing `pip install apache-superset --upgrade`, the command terminated successfully and `pipdeptree` shows all dependencies met correctly.

However trying to start superset I get

```
Traceback (most recent call last):
  File "/path/to/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/path/to/lib/python3.8/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/path/to/lib/python3.8/site-packages/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/path/to/lib/python3.8/site-packages/superset/initialization/__init__.py", line 26, in <module>
    from flask_appbuilder import expose, IndexView
  File "/path/to/lib/python3.8/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
  File "/path/to/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 24, in <module>
    from ..baseviews import AbstractViewApi
  File "/path/to/lib/python3.8/site-packages/flask_appbuilder/baseviews.py", line 22, in <module>
    from .forms import GeneralModelConverter
  File "/path/to/lib/python3.8/site-packages/flask_appbuilder/forms.py", line 3, in <module>
    from flask_wtf import FlaskForm
  File "/path/to/lib/python3.8/site-packages/flask_wtf/__init__.py", line 3, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "/path/to/lib/python3.8/site-packages/flask_wtf/csrf.py", line 10, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/path/to/lib/python3.8/site-packages/werkzeug/security.py)
```

#### How to reproduce the bug

1. Upgrade to Superset 2.0.0
2. Start superset

### Expected results

No error.

### Actual results

Cannot import name `safe_str_cmp` from `werkzeug.security` because of deprecation of [`pbkdf2_hex`, `pbkdf2_bin`, and `safe_str_cmp`](https://blog.appseed.us/how-to-fix-cannot-import-safe_str_cmp-from-werkzeug/)

### Environment

(please complete the following information):

- superset version: `2.0.0`
- python version: `3.8.2`
- node.js version: n/a
- any feature flags active: n/a

### Checklist

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The issue also happens when running `superset db upgrade`.

**Comment by yanickrochon** [comment]
Solved by doing 

```
pip install flask_wtf --upgrade
pip install flask_login --upgrade
```

etc.

**Comment by sdezza** [comment]
> 

Got the same error and solved the same way
Thank you!
