### ISSUE TITLE
Import "wtforms.ext.sqlalchemy.fields" could not be resolved (requirements/testing.txt does not support Python 3.10)

### ISSUE THREAD

**Issue by rickspencer3** [apache/superset#22026]
Summary of the issue in case anyone finds this via Google having the same problem.

The issue was simply that I was running Python version 3.10 on my laptop, but the Google Bigquery python library im the requirements/testing.txt file is restricted to versions less than 3.10, causing, causing ```pip install -r requirements/testing.txt``` to fail. To work around it, I used ```pip install -r requirements/local.txt``` instead.

____
When following the instructions for setting up a local development environment:
https://github.com/apache/superset/blob/master/CONTRIBUTING.md

The instructions fail at this step:

```bash
# Initialize the database
superset db upgrade
```
with errors such as:

```bash
ModuleNotFoundError: No module named 'wtforms.ext'
```

#### How to reproduce the bug

1. Confirm that you have a supported python version
3. Follow all steps for setting up the [OS dependencies](https://superset.apache.org/docs/installation/installing-superset-from-scratch/#os-dependencies).
4. create and clone a clean fork of superset
5. Skip to the[ Flask Server instructions  ](export LDFLAGS="-L$(brew --prefix openssl)/lib"
export CFLAGS="-I$(brew --prefix openssl)/include")
6. Follow the steps:

```# Create a virtual environment and activate it (recommended)
python3 -m venv venv # setup a python3 virtualenv
source venv/bin/activate

# Install external dependencies
pip install -r requirements/testing.txt

# Install Superset in editable (development) mode
pip install -e .

# Initialize the database
superset db upgrade
```

### Expected results

what you expected to happen.

### Actual results
When installing requirements/testing.txt the following errors are observed:
```bash 
Collecting google-auth-oauthlib==0.4.6
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
ERROR: Ignored the following versions that require a different python version: 1.3.0 Requires-Python ~=2.7,~=3.5; 2.10.0 Requires-Python >=3.6, <3.10; 2.11.0 Requires-Python >=3.6, <3.10; 2.12.0 Requires-Python >=3.6, <3.10; 2.13.0 Requires-Python >=3.6, <3.10; 2.13.1 Requires-Python >=3.6, <3.10; 2.14.0 Requires-Python >=3.6, <3.10; 2.15.0 Requires-Python >=3.6, <3.10; 2.16.0 Requires-Python >=3.6, <3.10; 2.16.1 Requires-Python >=3.6, <3.10; 2.17.0 Requires-Python >=3.6, <3.10; 2.18.0 Requires-Python >=3.6, <3.10; 2.19.0 Requires-Python >=3.6, <3.10; 2.20.0 Requires-Python >=3.6, <3.10; 2.21.0 Requires-Python >=3.6, <3.10; 2.22.0 Requires-Python >=3.6, <3.10; 2.22.1 Requires-Python >=3.6, <3.10; 2.23.0 Requires-Python >=3.6, <3.10; 2.23.1 Requires-Python >=3.6, <3.10; 2.23.2 Requires-Python >=3.6, <3.10; 2.23.3 Requires-Python >=3.6, <3.10; 2.24.0 Requires-Python >=3.6, <3.10; 2.24.1 Requires-Python >=3.6, <3.10; 2.25.0 Requires-Python >=3.6, <3.10; 2.25.1 Requires-Python >=3.6, <3.10; 2.25.2 Requires-Python >=3.6, <3.10; 2.26.0 Requires-Python >=3.6, <3.10; 2.27.0 Requires-Python >=3.6, <3.10; 2.27.1 Requires-Python >=3.6, <3.10; 2.28.0 Requires-Python >=3.6, <3.10; 2.28.1 Requires-Python >=3.6, <3.10; 2.29.0 Requires-Python >=3.6, <3.10; 2.6.2 Requires-Python >=3.6, <3.9; 2.7.0 Requires-Python >=3.6, <3.10; 2.8.0 Requires-Python >=3.6, <3.10; 2.9.0 Requires-Python >=3.6, <3.10
ERROR: Could not find a version that satisfies the requirement google-cloud-bigquery[bqstorage,pandas]==2.29.0 (from versions: 0.20.0, 0.21.0, 0.22.0, 0.22.1, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.12.0, 1.12.1, 1.12.2, 1.13.0, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.17.0, 1.17.1, 1.18.0, 1.18.1, 1.19.0, 1.19.1, 1.20.0, 1.21.0, 1.22.0, 1.23.0, 1.23.1, 1.24.0, 1.25.0, 1.26.0, 1.26.1, 1.27.2, 1.28.0, 1.28.1, 1.28.2, 2.0.0, 2.1.0, 2.2.0, 2.3.1, 2.4.0, 2.5.0, 2.6.0, 2.6.1, 2.30.0, 2.30.1, 2.31.0, 2.32.0, 2.33.0, 2.34.0, 2.34.1, 2.34.2, 2.34.3, 2.34.4, 3.0.0b1, 3.0.0, 3.0.1, 3.1.0, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.5)
ERROR: No matching distribution found for google-cloud-bigquery[bqstorage,pandas]==2.29.0
```
Running ```superset db upgrade``` results in the following errors:
```bash
 % superset db upgrade
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
--------------------------------------------------------------------------------
                                    WARNING
--------------------------------------------------------------------------------
A Default SECRET_KEY was detected, please use superset_config.py to override it.
Use a strong complex alphanumeric string and use a tool to help you generate 
a sufficiently random sequence, ex: openssl rand -base64 42
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
logging was configured successfully
2022-11-03 09:45:54,756:INFO:superset.utils.logging_configurator:logging was configured successfully
2022-11-03 09:45:54,770:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
We haven't found any Content Security Policy (CSP) defined in the configurations. Please make sure to configure CSP using the TALISMAN_CONFIG key or any other external software. Failing to configure CSP have serious security implications. Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information. You can disable this warning using the CONTENT_SECURITY_POLICY_WARNING key.
2022-11-03 09:45:54,771:WARNING:superset.initialization:We haven't found any Content Security Policy (CSP) defined in the configurations. Please make sure to configure CSP using the TALISMAN_CONFIG key or any other external software. Failing to configure CSP have serious security implications. Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information. You can disable this warning using the CONTENT_SECURITY_POLICY_WARNING key.
Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
2022-11-03 09:45:54,773:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `FILTER_STATE_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
2022-11-03 09:45:54,781:WARNING:superset.utils.cache_manager:Falling back to the built-in cache, that stores data in the metadata database, for the following cache: `EXPLORE_FORM_DATA_CACHE_CONFIG`. It is recommended to use `RedisCache`, `MemcachedCache` or another dedicated caching backend for production deployments
No PIL installation found
2022-11-03 09:45:55,190:INFO:superset.utils.screenshots:No PIL installation found
Failed to create app
Traceback (most recent call last):
  File "/Users/rickspencer/superset/superset/app.py", line 37, in create_app
    app_initializer.init_app()
  File "/Users/rickspencer/superset/superset/initialization/__init__.py", line 473, in init_app
    self.init_app_in_ctx()
  File "/Users/rickspencer/superset/superset/initialization/__init__.py", line 420, in init_app_in_ctx
    self.configure_data_sources()
  File "/Users/rickspencer/superset/superset/initialization/__init__.py", line 493, in configure_data_sources
    __import__(module_name, fromlist=class_names)
  File "/Users/rickspencer/superset/superset/connectors/sqla/__init__.py", line 17, in <module>
    from . import models, views
  File "/Users/rickspencer/superset/superset/connectors/sqla/views.py", line 28, in <module>
    from wtforms.ext.sqlalchemy.fields import QuerySelectField
ModuleNotFoundError: No module named 'wtforms.ext'
2022-11-03 09:45:55,273:ERROR:superset.app:Failed to create app
Traceback (most recent call last):
  File "/Users/rickspencer/superset/superset/app.py", line 37, in create_app
    app_initializer.init_app()
  File "/Users/rickspencer/superset/superset/initialization/__init__.py", line 473, in init_app
    self.init_app_in_ctx()
  File "/Users/rickspencer/superset/superset/initialization/__init__.py", line 420, in init_app_in_ctx
    self.configure_data_sources()
  File "/Users/rickspencer/superset/superset/initialization/__init__.py", line 493, in configure_data_sources
    __import__(module_name, fromlist=class_names)
  File "/Users/rickspencer/superset/superset/connectors/sqla/__init__.py", line 17, in <module>
    from . import models, views
  File "/Users/rickspencer/superset/superset/connectors/sqla/views.py", line 28, in <module>
    from wtforms.ext.sqlalchemy.fields import QuerySelectField
ModuleNotFoundError: No module named 'wtforms.ext'
Traceback (most recent call last):
  File "/Users/rickspencer/superset/venv/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/flask/cli.py", line 354, in decorator
    app = __ctx.ensure_object(ScriptInfo).load_app()
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/flask/cli.py", line 237, in locate_app
    return find_app_by_string(module, app_name)
  File "/Users/rickspencer/superset/venv/lib/python3.10/site-packages/flask/cli.py", line 165, in find_app_by_string
    app = attr(*args, **kwargs)
  File "/Users/rickspencer/superset/superset/app.py", line 44, in create_app
    raise ex
  File "/Users/rickspencer/superset/superset/app.py", line 37, in create_app
    app_initializer.init_app()
  File "/Users/rickspencer/superset/superset/initialization/__init__.py", line 473, in init_app
    self.init_app_in_ctx()
  File "/Users/rickspencer/superset/superset/initialization/__init__.py", line 420, in init_app_in_ctx
    self.configure_data_sources()
  File "/Users/rickspencer/superset/superset/initialization/__init__.py", line 493, in configure_data_sources
    __import__(module_name, fromlist=class_names)
  File "/Users/rickspencer/superset/superset/connectors/sqla/__init__.py", line 17, in <module>
    from . import models, views
  File "/Users/rickspencer/superset/superset/connectors/sqla/views.py", line 28, in <module>
    from wtforms.ext.sqlalchemy.fields import QuerySelectField
ModuleNotFoundError: No module named 'wtforms.ext'

```

- python version: Python 3.10.8
- node.js version: v16.14.0

**Comment by rickspencer3** [comment]
I ran:
```
pip install pillow
```

To remove the PIL-related errors/warnings:
```No PIL installation found
2022-11-03 09:45:55,190:INFO:superset.utils.screenshots:No PIL installation found
```

**Comment by rickspencer3** [comment]
Ok, I traced it down to incorrect imports, I think. After making this change, it seems to build:

```
% git diff
diff --git a/superset/connectors/sqla/views.py b/superset/connectors/sqla/views.py
index 7133cdfab..158903130 100644
--- a/superset/connectors/sqla/views.py
+++ b/superset/connectors/sqla/views.py
@@ -25,7 +25,8 @@ from flask_appbuilder.fieldwidgets import Select2Widget
 from flask_appbuilder.models.sqla.interface import SQLAInterface
 from flask_appbuilder.security.decorators import has_access
 from flask_babel import lazy_gettext as _
-from wtforms.ext.sqlalchemy.fields import QuerySelectField
+
+from wtforms_sqlalchemy.fields import QuerySelectField
 from wtforms.validators import DataRequired, Regexp
 
 from superset import app, db
diff --git a/superset/views/database/forms.py b/superset/views/database/forms.py
index a44a412b4..615870d48 100644
--- a/superset/views/database/forms.py
+++ b/superset/views/database/forms.py
@@ -28,7 +28,7 @@ from wtforms import (
     SelectField,
     StringField,
 )
-from wtforms.ext.sqlalchemy.fields import QuerySelectField
+from wtforms_sqlalchemy.fields import QuerySelectField
 from wtforms.validators import DataRequired, Length, NumberRange, Optional, Regexp
 
 from superset import app, db, security_manager
```

**Comment by rickspencer3** [comment]
here is the output of pip freeze
```certifi==2022.9.24
charset-normalizer==2.1.1
idna==3.4
influxdb-client==1.33.0
protobuf==4.21.9
psycopg2-binary==2.9.4
python-dateutil==2.8.2
reactivex==4.0.4
requests==2.28.1
six==1.16.0
typing_extensions==4.4.0
urllib3==1.26.12
```

**Comment by rickspencer3** [comment]
Ok, so it looks like the problem was that I am running Python 3.10, and bigquery requires <3.10. When I used requirments/local.text everything started working

**Comment by eschutho** [comment]
@rickspencer3 is there anything else that you need on this issue? It sounds like you got it resolved?

**Comment by rickspencer3** [comment]
I don't personally need anything, but it seems like the upstream project would probably want to support Python 3.10 by default. Feel free to close, though, as I did get it working as described perviously.

**Comment by liprais** [comment]
I am using python 3.8.5 and also encountered this issue .
I installed superset using pip,version is 2.0.1

**Comment by mgromis** [comment]
> I am using python 3.8.5 and also encountered this issue . I installed superset using pip,version is 2.0.1

I am also having this issue with python 3.8.8

**Comment by lincmba** [comment]
I found this comment on wtform repository https://github.com/wtforms/wtforms/pull/202#issuecomment-118543433 .
the ext module is not supported on wtforms 3.x. Pinning the installed version of wtforms to < 3.x works.
In my case I pinned the version of wtforms to `2.3.3`

**Comment by xiaotiao** [comment]
> I found this comment on wtform repository [wtforms/wtforms#202 (comment)](https://github.com/wtforms/wtforms/pull/202#issuecomment-118543433) . The ext module is not supported on wtforms 3.x, which appears to be a version that superset installs by default. Pinning the installed version of wtforms to < 3.x fixes the issue. In my case I pinned the version of wtforms to `2.3.3`

it works for me,  execute pip list show wtforms version is 3.0.1

**Comment by EMCP** [comment]
I can confirm with the base.txt trick I get the installation going with v2.0.1 and ubuntu 20.04 py38

```
pip install --upgrade pip
sudo -u ubuntu pip install --upgrade pip --no-warn-script-location
sudo -u ubuntu pip install testresources --no-warn-script-location
sudo -u ubuntu pip install aiohttp==3.8.1 aiosignal==1.2.0 alembic==1.6.5 amqp==5.1.0 apispec[yaml]==3.3.2 async-timeout==4.0.2 attrs==21.2.0 babel==2.9.1 backoff==1.11.1 billiard==3.6.4.0 bleach==3.3.1 brotli==1.0.9 cachelib==0.4.1 celery==5.2.2 cffi==1.14.6 charset-normalizer==2.0.4 click==8.0.4 click-didyoumean==0.3.0 click-plugins==1.1.1 click-repl==0.2.0 colorama==0.4.4 convertdate==2.4.0 cron-descriptor==1.2.24 croniter==1.0.15 cryptography==3.4.7 deprecation==2.1.0 dnspython==2.1.0 email-validator==1.1.3 flask==2.0.3 flask-appbuilder==4.1.3 flask-babel==1.0.0 flask-caching==1.10.1 flask-compress==1.10.1 flask-jwt-extended==4.3.1 flask-login==0.4.1 flask-migrate==3.1.0 flask-sqlalchemy==2.5.1 flask-talisman==0.8.1 flask-wtf==0.14.3 frozenlist==1.3.0 func-timeout==4.3.5 geographiclib==1.52 geopy==2.2.0 graphlib-backport==1.0.3 gunicorn==20.1.0 hashids==1.3.1 holidays==0.14.2 humanize==3.11.0 idna==3.2 isodate==0.6.0 itsdangerous==2.1.1 jinja2==3.0.3 jsonschema==3.2.0 kombu==5.2.4 korean-lunar-calendar==0.2.1 mako==1.1.4 markdown==3.3.4 markupsafe==2.0.1 marshmallow==3.13.0 marshmallow-enum==1.5.1 marshmallow-sqlalchemy==0.23.1 msgpack==1.0.2 multidict==5.1.0 numpy==1.22.1 packaging==21.3 pandas==1.3.4 parsedatetime==2.6 pgsanity==0.2.9 polyline==1.4.0 prison==0.2.1 prompt-toolkit==3.0.28 pyarrow==5.0.0 pycparser==2.20 pyjwt==2.4.0 pymeeus==0.5.11 pyparsing==3.0.6 pyrsistent==0.16.1 python-dateutil==2.8.2 python-dotenv==0.19.0 python-editor==1.0.4 python-geohash==0.8.5 pytz==2021.3 pyyaml==5.4.1 redis==3.5.3 selenium==3.141.0 simplejson==3.17.3 six==1.16.0 slackclient==2.5.0 sqlalchemy==1.3.24 sqlalchemy-utils==0.37.8 sqlparse==0.3.0 tabulate==0.8.9 typing-extensions==3.10.0.0 urllib3==1.26.6 vine==5.0.0 wcwidth==0.2.5 webencodings==0.5.1 werkzeug==2.0.3 wtforms==2.3.3 wtforms-json==0.3.3 yarl==1.6.3 --no-warn-script-location
sudo -u ubuntu pip install psycopg2-binary pillow gunicorn gevent --no-warn-script-location
sudo -u ubuntu pip install requests --upgrade --no-warn-script-location
sudo -u ubuntu pip install trino thrift pyhive --no-warn-script-location

status-set maintenance "About to pip install apache-superset $(date +"%H:%M")"
juju-log -l "WARNING" "About to pip install apache-superset"
sudo -u ubuntu pip install apache-superset --no-warn-script-location
```

notice

```
wtforms==2.3.3 wtforms-json==0.3.3 
```

**Comment by rusackas** [comment]
I'm not sure if anything on this thread is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
