### ISSUE TITLE
TypeError while trying to save a SQLLab query to a dataset

### ISSUE THREAD

**Issue by npc2kor** [apache/superset#22100]
We had ran a custom query on the SQL Lab window on superset and the query seem to execute fine. Once we try to save the result as a dataset, we are getting an unknown error:  `TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given`

The pod logs are as follows:
`TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given
2022-11-11 14:11:06,433:ERROR:superset.views.base:__init__() takes from 2 to 4 positional arguments but 6 were given
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 133, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 244, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 2134, in sqllab_viz
    db.session.commit()
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1435, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3367, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3507, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3467, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 253, in save_obj
    _finalize_insert_update_commands(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1566, in _finalize_insert_update_commands
    mapper.dispatch.after_insert(mapper, connection, state)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/events.py", line 743, in wrap
    fn(*arg, **kw)
  File "/app/superset/connectors/sqla/models.py", line 2340, in after_insert
    sqla_table.write_shadow_dataset()
  File "/app/superset/connectors/sqla/models.py", line 2564, in write_shadow_dataset
    referenced_tables = extract_table_references(
  File "/app/superset/sql_parse.py", line 778, in extract_table_references
    return {
  File "/app/superset/sql_parse.py", line 779, in <setcomp>
    Table(*[part["value"] for part in table["name"][::-1]])
TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given`

**Comment by rusackas** [comment]
Haven't heard any complaints. Closing!
