### ISSUE TITLE
I am installing Apache-Superset after installation getting this error

### ISSUE THREAD

**Issue by hassan-turi** [apache/superset#22221]
I installed apache-superset and when try to initialize the db with command `superset db upgrade` I prompts this error how can I resolve this issue? I also asked  on `stackoverflow ` but since yesterday no one answered please help.

```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Apache\apache\Scripts\superset.exe\__main__.py", line 4, in <module>
  File "C:\Apache\apache\lib\site-packages\superset\__init__.py", line 18, in <module>
    from flask import current_app, Flask
  File "C:\Apache\apache\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
  File "C:\Apache\apache\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Apache\apache\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Apache\apache\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Apache\apache\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Apache\apache\lib\site-packages\markupsafe\__init__.py)

```

**Comment by rusackas** [comment]
Closing this as it's a help request rather than a bug report. Not to diminish your problem though, I'd be happy to move this to a Q&A discussion if you'd like, or I welcome you to bring the conversation to the #debug-together channel on [Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-1jp6hjzrq-H0PlFtToyLWuPiJDuRWCNw)
