### ISSUE TITLE
Unable to Edit Clickhouse Database Settings in Superset

### ISSUE THREAD

**Issue by programmeddeath1** [apache/superset#22237]
#### How to reproduce the bug

1. Go to Databases and go to Actions for existing Clickhouse Database
2. Click on the edit icon under actions.
3. It fails with "An error ocurred while fetching the databases" as shown in screenshot.
4. See error popup at the bottom and nothing shows up in the edit database window.

### Expected results

It should show the edit database options to change the IP or port etc.

### Actual results

It shows a blank edit database screen
![ClickhouseSupersetError](https://user-images.githubusercontent.com/44861370/204212506-d2e98de2-204a-4011-910f-ca4fe25abbaa.png)

### Environment
Superset docker setup 
(please complete the following information):

- browser type and version:
- superset version: `latest-dev`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [√] I have checked the superset logs for python stacktraces and included it here as text if there are any.
```_delta_humanized&sortOrder=desc" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
superset_app            | Object of type immutabledict is not JSON serializable
superset_app            | Traceback (most recent call last):
superset_app            |   File "/app/superset/views/base.py", line 210, in wraps
superset_app            |     return f(self, *args, **kwargs)
superset_app            |   File "/app/superset/views/base_api.py", line 409, in get_headless
superset_app            |     duration, response = time_function(super().get_headless, pk, **kwargs)
superset_app            |   File "/app/superset/utils/core.py", line 1555, in time_function
superset_app            |     response = func(*args, **kwargs)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 1398, in get_headless
superset_app            |     return self.response(200, **_response)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 704, in response
superset_app            |     _ret_json = jsonify(kwargs)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 361, in jsonify
superset_app            |     f"{dumps(data, indent=indent, separators=separators)}\n",
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 139, in dumps
superset_app            |     rv = _json.dumps(obj, **kwargs)
superset_app            |   File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
superset_app            |     return cls(
superset_app            |   File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
superset_app            |     chunks = self.iterencode(o, _one_shot=True)
superset_app            |   File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
superset_app            |     return _iterencode(o, 0)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 57, in default
superset_app            |     return super().default(o)
superset_app            |   File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
superset_app            |     raise TypeError(f'Object of type {o.__class__.__name__} '
superset_app            | TypeError: Object of type immutabledict is not JSON serializable
superset_app            | 2022-11-28 07:03:55,630:ERROR:superset.views.base:Object of type immutabledict is not JSON serializable
```
- [√] I have reproduced the issue with at least the latest released version of superset.
- [√] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by eloymc98** [comment]
I'm facing the same issue

**Comment by rusackas** [comment]
Just to confirm, @programmeddeath1 and @eloymc98, are you seeing this as a clickhouse-specific issue, or is this occurring with other database types as well?

**Comment by betodealmeida** [comment]
Upgrade `clickhouse-connect` should fix this.

**Comment by rusackas** [comment]
Closing this issue, since the update PR has merged. Thanks Beto! @programmeddeath1 holler if this doesn't fully resolve this issue, and we'll re-open if needed.
