### ISSUE TITLE
Unable to upgrade from 1.5.2 to 2.0.1rc4 on Kubernetes

### ISSUE THREAD

**Issue by dpeer6** [apache/superset#22271]
#### How to reproduce the bug

Upgrade Superset version 1.5.2 to 2.0.1rc4 using Helm chart 0.7.7 fails with the following error:
```
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
slices updated with no time_range_endpoints: 0
>> Copy 79 physical tables to sl_tables...
>> Copy 220 SqlaTable to sl_datasets...
   Copy dataset owners...
   Link physical datasets with tables...
>> Copy 6,849 table columns to sl_columns...
   Link all columns to sl_datasets...
>> Copy 245 metrics to sl_columns...
   Link metric columns to datasets...
>> Run postprocessing on 7,094 columns
   [Column 1 to 7,094] 6,871 may be updated
   Assign table column relations...
>> Run postprocessing on 220 datasets
   Process dataset 1~220...                              
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 445, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/cli.py", line 149, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 98, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 185, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/superset/extensions/../migrations/env.py", line 126, in <module>
    run_migrations_online()
  File "/app/superset/extensions/../migrations/env.py", line 118, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
    step.migration_fn(**kw)
  File "/app/superset/migrations/versions/2022-04-01_14-38_a9422eeaae74_new_dataset_models_take_2.py", line 884, in upgrade
    postprocess_datasets(session)
  File "/app/superset/migrations/versions/2022-04-01_14-38_a9422eeaae74_new_dataset_models_take_2.py", line 601, in postprocess_datasets
    table_refrences = extract_table_references(
  File "/app/superset/sql_parse.py", line 780, in extract_table_references
    return {
  File "/app/superset/sql_parse.py", line 781, in <setcomp>
    Table(*[part["value"] for part in table["name"][::-1]])
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given
```

The error comes from the superset-init-db job.
What is the recommended way to upgrade Superset on Kubernetes?

In the above example I tried to use helm after postgres DB dump and restore did not work.
Past versions, DB dump and restore did work, following the "superset db upgrade" & "superset init" commands.  

Thank you!
David

**Comment by rusackas** [comment]
Pinging @eschutho and @AAfghahi as release managers, in case this is a 2.0.1rcX issue that needs to be addressed. If this is a Kubernetes-specific issue, I'm hopeful that we/they can steer you in the right direction to some K8s-savvy folks that might be able to assist.

**Comment by dpeer6** [comment]
@rusackas thank you for that.
I'm not sure that the issue relates only to Kubernetes, but to the upgrade process or DB upgrade process between versions.
Maybe I miss something regarding the upgrade process, helm should be easy but it is not covered anywhere. The only thing cloud dig was the DB dump and restore

**Comment by francoisauclair911** [comment]
Facing the same issues here, is there any updates on this ?

**Comment by eschutho** [comment]
Right now, we don't release helm charts with the package releases, so I would advise picking a helm release closer to the 2.0 release in mid July of 2022. Maybe 0.6.4. We'll try to add in to our release process to align them in the future.

**Comment by dpeer6** [comment]
Hello again.
I tried your suggestion but nothing works.
I am trying to understand what to expect... if I have superset version, like 1.1.0 and I want to upgrade and/or migrate the data, there is no option to do so?

I have a deployment, with 100+ of users, and I'm looking for a way to upgrade/migrate superset to a newer version.
pg_dump and restore are not working, even after schema drop & restore. Later the superset db upgrade and superset init fails.

Would love to understand the options and what should we expect.

Thank you!

**Comment by chaucv** [comment]
Facing the same issues here, is there any updates on this ?

**Comment by rusackas** [comment]
Closing this out as we're now on 3.1 and we're on the verge of 4.0. If there are still issues with helm charts on current versions, we can re-open this, but it might be even better to open a fresh Issue.
