### ISSUE TITLE
[Bar chart] Error saying dataset no longer exists after updating chart

### ISSUE THREAD

**Issue by yunchanggou** [apache/superset#22299]
there is an error when I attemp to create a Bar Chart, it point ' Missing dataset,The dataset associated with this chart no longer exists'

#### How to reproduce the bug

1. select a Bar chart
2. set the DIMENSIONS and METRICS
3. clict to 'UPDATE CHART'

### Expected results
output the Bar Chart  i want 

### Actual results
point the error:

#### Screenshots
Missing dataset,The dataset associated with this chart no longer exists

![图片](https://user-images.githubusercontent.com/85088515/205006847-951ef57c-a12c-4c41-9277-d27ae504027d.png)

### Environment

(please complete the following information):

- browser type and version:google  89.0.4389.90 （32 ） 
- superset version: `2.0`
- python version: `python --3.8`
- node.js version: `node -v`
- any feature flags active:

### Checklist
Make sure to follow these steps before submitting your issue - thank you!

- I have checked the superset logs for python stacktraces and included it here as text if there are any.
-  I have reproduced the issue with at least the latest released version of superset.
-  I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

2022-12-01 16:49:25,493:INFO:werkzeug:63.221.140.231 - - [01/Dec/2022 16:49:25] "POST /superset/log/?explode=events HTTP/1.1" 200 -
2022-12-01 16:49:37,145:INFO:werkzeug:63.221.140.231 - - [01/Dec/2022 16:49:37] "POST /superset/log/?explode=events HTTP/1.1" 200 -
SupersetSecurityException
Traceback (most recent call last):
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 486, in check_datasource_perms
    datasource_id, datasource_type = get_datasource_info(
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 273, in get_datasource_info
    raise SupersetException(
superset.exceptions.SupersetException: The dataset associated with this chart no longer exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/base.py", line 207, in wraps
    return f(self, *args, **kwargs)
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/utils/cache.py", line 226, in wrapper
    response = f(*args, **kwargs)
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 443, in wrapper
    check_perms(*args, **kwargs)
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 490, in check_datasource_perms
    raise SupersetSecurityException(
superset.exceptions.SupersetSecurityException: The dataset associated with this chart no longer exists
2022-12-01 16:49:41,515:WARNING:superset.views.base:SupersetSecurityException
Traceback (most recent call last):
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 486, in check_datasource_perms
    datasource_id, datasource_type = get_datasource_info(
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 273, in get_datasource_info
    raise SupersetException(
superset.exceptions.SupersetException: The dataset associated with this chart no longer exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/base.py", line 207, in wraps
    return f(self, *args, **kwargs)
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/utils/cache.py", line 226, in wrapper
    response = f(*args, **kwargs)
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 443, in wrapper
    check_perms(*args, **kwargs)
  File "/home/zte/workspace/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 490, in check_datasource_perms
    raise SupersetSecurityException(
superset.exceptions.SupersetSecurityException: The dataset associated with this chart no longer exists
2022-12-01 16:49:41,517:INFO:werkzeug:63.221.140.231 - - [01/Dec/2022 16:49:41] "GET /superset/explore_json/ HTTP/1.1" 403 -

**Comment by rusackas** [comment]
Hi @yunchanggou, and thanks for the report. Just to confirm, you're running on the 2.0 release? 

The repro steps you suggest have been thoroughly tested on that release. The bar chart being one of the most used charts, there would be a large outcry if the bug is this easy to run into! :)

Are you sure the dataset (and underlying database connection) does indeed exist and is working? Can you access it via SQL Lab? Can you build any other charts with it? Does it work with Bar Chart V2, if this is the legacy bar chart?

Hoping we can help resolve, but this probably requires a little more digging.

**Comment by yunchanggou** [comment]
> Hoping we can help resolve, but this probably requires a little more digging.
thanks your replay very much !
my database is connecting successed! and I can use the SQL LAB run the correct result and to create  the dateset, also the Bar chart V2  and other chart，the screenshot as follows：
![图片](https://user-images.githubusercontent.com/85088515/205417709-795c59f7-1474-4d78-b7ac-ebe163897aae.png)
![图片](https://user-images.githubusercontent.com/85088515/205417805-932d27c5-8f9f-461b-a151-39c32ef7e30a.png)
![图片](https://user-images.githubusercontent.com/85088515/205417951-057e40a5-880e-40f2-a455-6663cd90f3ba.png)

in addition，I have some other question，I print the log  when I creat the Bar Chart, I find the code ,I want konw the datasource_id means,can you help me? 
![图片](https://user-images.githubusercontent.com/85088515/205418143-0b430cfc-6efc-4fff-8550-08ea10fdf965.png)
![图片](https://user-images.githubusercontent.com/85088515/205418149-ce3be186-7be0-4cba-8aa9-95c913fbdbb9.png)
The  foll0ws screenshot is the error when I attemp to use the Bar chart:
![图片](https://user-images.githubusercontent.com/85088515/205418152-bd6f1e8f-854a-4bea-b491-5f0b7c1cece5.png)
Looking forward to your reply,thanks!

**Comment by eschutho** [comment]
> in addition，I have some other question，I print the log when I creat the Bar Chart, I find the code ,I want konw the datasource_id means,can you help me?

The datasource_id is the idea of either the dataset or query, depending on how you created the chart. The datasource type will show in the top left corner of the explore page.

**Comment by yunchanggou** [comment]
> 

HI，thanks 
I have tested the bar chart with your URL，it   can be created  sucessfully.
other more ,my environment is superset 2.0.0 ,python 3.8 , when I updated my python 3.8 to 3.9,the bar chart issue  nolonger reproduce , it be solved miraculously!

**Comment by rusackas** [comment]
Glad to hear your issue is solved @yunchanggou! Please let us know if you see further difficulties with this, and we'll keep digging!
