### ISSUE TITLE
Fail to login via LDAP: werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server

### ISSUE THREAD

**Issue by josechudev** [apache/superset#22290]
#### How to reproduce the bug

1. pull the v0.7.7 of the helm chart
2. apply the next ldap configs:
```

bootstrapScript: |
  #!/bin/bash
  rm -rf /var/lib/apt/lists/* && \
  apt-get update -y && apt-get install -y python3-dev libldap2-dev libsasl2-dev ldap-utils tox lcov valgrind
  pip install python-ldap==3.4.3 \
  pip install \
    psycopg2-binary==2.9.1 \
    redis==3.5.3 && \
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi


configOverrides:

  enable_ldap: |
  
      from flask_appbuilder.security.manager import AUTH_LDAP
      SESSION_COOKIE_SAMESITE = 'None'
      AUTH_TYPE = AUTH_LDAP
      AUTH_USER_REGISTRATION = False
      AUTH_LDAP_USE_TLS = False
      AUTH_LDAP_SERVER = "ldap://host:port"
      AUTH_LDAP_BIND_USER = "CN=bind user,OU=Devops,DC=xx,DC=xx,DC=xx,DC=xx,DC=io"
      AUTH_LDAP_BIND_PASSWORD = "pass"
      AUTH_LDAP_UID_FIELD = "sAMAccountName"
      AUTH_LDAP_SEARCH_FILTER = "(sAMAccountName=%s)"
      AUTH_LDAP_SEARCH = "OU=Devops,DC=xx,DC=az,DC=platform,DC=xx,DC=io"
      AUTH_LDAP_FIRSTNAME_FIELD = "givenName"
      AUTH_LDAP_LASTNAME_FIELD = "sn"
      AUTH_LDAP_EMAIL_FIELD = "mail"

      AUTH_ROLES_SYNC_AT_LOGIN = True
      
      AUTH_LDAP_GROUP_FIELD = "memberOf"
      AUTH_ROLES_MAPPING = {
          "CN=devops_admins,OU=devops,DC=xx,DC=xx,DC=xx,DC=xx,DC=io": ["Admin"],
          "*": ["Viewer"]
       }
      
```

### Expected results

Successful login

### Actual results

```
[01/Dec/2022:00:29:20 +0000] "POST /login/ HTTP/1.1" 302 220 "https://host/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0"
[01/Dec/2022:00:29:20 +0000] "GET /login/ HTTP/1.1" 200 25343 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0"
[01/Dec/2022:00:29:22 +0000] "GET /static/assets/theme.18064043eb90700c676a.entry.css.map HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0"
HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask/scaffold.py", line 332, in send_static_file
    return send_from_directory(
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 700, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 847, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2022-12-01 00:29:22,369:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask/scaffold.py", line 332, in send_static_file
    return send_from_directory(
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 700, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 847, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[01/Dec/2022:00:29:22 +0000] "GET /static/appbuilder/css/bootstrap.min.css.map HTTP/1.1" 404 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0"
```

### Environment

(please complete the following information):

- browser type and version: Mozilla Firefox107.0 (64-bit)
- superset helm v0.7.7

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

- Add any other context about the problem here.
- We are currently running superset on a Rancher cluster
- We have already configured Grafana with the same LDAP values and it has worked
- I have installed python-ldap already
- I have tried reinstalling gunicorn

Thanks

**Comment by parkjiyeon0** [comment]
I had the same problem as you. Have you solved it now?

@josechudev

**Comment by josechudev** [comment]
@parkjiyeon0 I finally solved it by reinstalling gunicorn in the bootstrapScript.and adding AUTH_LDAP_ALLOW_SELF_SIGNED= True to my ldap config. You can check the config [here](https://community.cloudera.com/t5/Support-Questions/How-to-configure-Superset-to-use-LDAP/m-p/283060/highlight/true)

**Comment by dpgaspar** [comment]
Great! you found your issue. Closing this, feel free to reopen if needed

**Comment by cnwyc** [comment]
@josechudev 方便发一下您那边处理的步骤吗，我现在也是卡在这里

**Comment by josechudev** [comment]
@cnwyc sry, for the late reply.
In your values file add 
```
bootstrapScript: |
  #!/bin/bash
  rm -rf /var/lib/apt/lists/* && \
  apt-get update -y && apt-get install -y python3-dev libldap2-dev libsasl2-dev ldap-utils tox lcov valgrind \
  pip install --upgrade --force-reinstall gunicorn \
  pip install python-ldap==3.4.3 \
  pip install \
    psycopg2-binary==2.9.1 \
    redis==3.5.3 && \
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
```

And for the ldap  this is my config  but you can find the guide [here](https://community.cloudera.com/t5/Support-Questions/How-to-configure-Superset-to-use-LDAP/m-p/283060/highlight/true)

```

configOverrides:

  enable_ldap: |
  
      from flask_appbuilder.security.manager import AUTH_LDAP
      SESSION_COOKIE_SAMESITE = 'None'
      AUTH_TYPE = AUTH_LDAP
      AUTH_USER_REGISTRATION = False
      AUTH_LDAP_USE_TLS = False
      AUTH_LDAP_SERVER = "ldap://host:port"
      AUTH_LDAP_BIND_USER = "CN=bind user,OU=Devops,DC=xx,DC=xx,DC=xx,DC=xx,DC=io"
      AUTH_LDAP_BIND_PASSWORD = "pass"
      AUTH_LDAP_UID_FIELD = "sAMAccountName"
      AUTH_LDAP_SEARCH_FILTER = "(sAMAccountName=%s)"
      AUTH_LDAP_SEARCH = "OU=Devops,DC=xx,DC=az,DC=platform,DC=xx,DC=io"
      AUTH_LDAP_ALLOW_SELF_SIGNED= True
      AUTH_APPEND_DOMAIN = False, AUTH_LDAP_USE_TLS=False
      AUTH_LDAP_FIRSTNAME_FIELD = "givenName"
      AUTH_LDAP_LASTNAME_FIELD = "sn"
      AUTH_LDAP_EMAIL_FIELD = "mail"

      AUTH_ROLES_SYNC_AT_LOGIN = True
      
      AUTH_LDAP_GROUP_FIELD = "memberOf"
      AUTH_ROLES_MAPPING = {
          "CN=devops_admins,OU=devops,DC=xx,DC=xx,DC=xx,DC=xx,DC=io": ["Admin"],
          "*": ["Viewer"]
       }
      
```
