### ISSUE TITLE
Adding DataSet failing (NotImplementedError)

### ISSUE THREAD

**Issue by ASchmidtGit** [apache/superset#22495]
I want to add a dataset but get an exception

#### How to reproduce the bug

1. Go to Dataset
2. + Dataset
3. chose source and view
4. click add

### Expected results

The Dataset should be added

### Actual results

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 112, in wraps

    raise ex
  File "/app/superset/views/base_api.py", line 109, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1468, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 82, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/datasets/api.py", line 257, in post
    new_model = CreateDatasetCommand(g.user, item).run()
  File "/app/superset/datasets/commands/create.py", line 51, in run
    dataset.fetch_metadata(commit=False)
  File "/app/superset/connectors/sqla/models.py", line 1752, in fetch_metadata
    new_columns = self.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 735, in external_metadata
    return get_physical_table_metadata(
  File "/app/superset/connectors/sqla/utils.py", line 61, in get_physical_table_metadata
    database.has_table_by_name(table_name=table_name, schema=_schema_name)
  File "/app/superset/models/core.py", line 760, in has_table_by_name
    return engine.has_table(table_name, schema)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2331, in has_table
    connection = engine.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2212, in run_callable
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1653, in run_callable
    )
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/interfaces.py", line 479, in has_table
    published so that third-party dialects may provide an
NotImplementedError
```

### Environment

- browser type: Chrome 108
- superset version: 1.5.0
- python version: 3.8.12
- sqlalchemy: 1.4.45
- clickhouse-sqlalchemy: 0.2.3

**Comment by ASchmidtGit** [comment]
Got it to work with ODBC instead of arrow flight
