### ISSUE TITLE
Init superset fail with error 'No module named 'cryptography.hazmat.backends.openssl.x509''

### ISSUE THREAD

**Issue by chick26** [apache/superset#22619]
### Process

1. Using Ubuntu 22.04.5, MiniConda, Python3.8
2. install superset
3. superset db upgrade

### Actual results

```shell
Traceback (most recent call last):
  File "/home/chick/miniconda3/envs/py38/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/initialization/__init__.py", line 33, in <module>
    from superset.extensions import (
  File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/extensions/__init__.py", line 32, in <module>
    from superset.utils.cache_manager import CacheManager
  File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/utils/cache_manager.py", line 24, in <module>
    from superset.utils.core import DatasourceType
  File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/utils/core.py", line 76, in <module>
    from cryptography.hazmat.backends.openssl.x509 import _Certificate
ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.x509'
```

### Environment

- Ubuntu 22.04.5,
- MiniConda, 
- Python3.8

**Comment by sfirke** [comment]
Duplicate of https://github.com/apache/superset/issues/22571?

**Comment by chick26** [comment]
> Duplicate of #22571?

Thanks，it works.
