### ISSUE TITLE
cryptography >=39 is incompatible with superset

### ISSUE THREAD

**Issue by Germandrummer92** [apache/superset#22743]
#### How to reproduce the bug

```bash
> python -m venv venv
> pip install -e .
> python -c "from superset import *"
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ddraper/dev/superset/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/Users/ddraper/dev/superset/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/Users/ddraper/dev/superset/superset/initialization/__init__.py", line 32, in <module>
    from superset.extensions import (
  File "/Users/ddraper/dev/superset/superset/extensions/__init__.py", line 32, in <module>
    from superset.utils.async_query_manager import AsyncQueryManager
  File "/Users/ddraper/dev/superset/superset/utils/async_query_manager.py", line 26, in <module>
    from superset.utils.core import get_user_id
  File "/Users/ddraper/dev/superset/superset/utils/core.py", line 79, in <module>
    from cryptography.hazmat.backends.openssl.x509 import _Certificate
ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.x509'
```

### Expected results

No errors

### Actual results

```> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ddraper/dev/superset/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/Users/ddraper/dev/superset/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/Users/ddraper/dev/superset/superset/initialization/__init__.py", line 32, in <module>
    from superset.extensions import (
  File "/Users/ddraper/dev/superset/superset/extensions/__init__.py", line 32, in <module>
    from superset.utils.async_query_manager import AsyncQueryManager
  File "/Users/ddraper/dev/superset/superset/utils/async_query_manager.py", line 26, in <module>
    from superset.utils.core import get_user_id
  File "/Users/ddraper/dev/superset/superset/utils/core.py", line 79, in <module>
    from cryptography.hazmat.backends.openssl.x509 import _Certificate
ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.x509'
```

### Environment

(please complete the following information):

- python version: `python --version`

´``❯ python --version
Python 3.11.1
```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

**Comment by rusackas** [comment]
Thank you for opening the PR to address this!
