### ISSUE TITLE
Can't start apache superset using docker-compose

### ISSUE THREAD

**Issue by nilaymk** [apache/superset#22777]
#### How to reproduce the bug
I am trying to start a local instance of Superset with `docker-compose` using instructions from here: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

Steps:
```
git checkout 1.5.3
TAG=1.5.3 docker-compose -f docker-compose-non-dev.yml pull
TAG=1.5.5 docker-compose -f docker-compose-non-dev.yml up
```

### Expected results
The docker orchestration to succeed and launch Superset so that I can connect on `localhost:8088`

### Actual results
- Connection to `localhost:8088` times out.
- `docker-compose` keeps trying to launch `superset_worker` and `superset_worker_beat` and fails on everyr retry. Console logs has these errors:
```
superset_worker       | Starting Celery worker...
superset_app          | [2023-01-18 14:21:23 +0000] [14] [ERROR] Exception in worker process
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
superset_app          |     worker.init_process()
superset_app          |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
superset_app          |     super().init_process()
superset_app          |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
superset_app          |     self.load_wsgi()
superset_app          |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
superset_app          |     self.wsgi = self.app.wsgi()
superset_app          |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
superset_app          |     self.callable = self.load()
superset_app          |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
superset_app          |     return self.load_wsgiapp()
superset_app          |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
superset_app          |     return util.import_app(self.app_uri)
superset_app          |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
superset_app          |     mod = importlib.import_module(module)
superset_app          |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
superset_app          |     return _bootstrap._gcd_import(name[level:], package, level)
superset_app          |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
superset_app          |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
superset_app          |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
superset_app          |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_app          |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
superset_app          |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
superset_app          |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
superset_app          |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
superset_app          |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
superset_app          |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_app          |   File "/app/superset/__init__.py", line 21, in <module>
superset_app          |     from superset.app import create_app
superset_app          |   File "/app/superset/app.py", line 23, in <module>
superset_app          |     from superset.initialization import SupersetAppInitializer
superset_app          |   File "/app/superset/initialization/__init__.py", line 33, in <module>
superset_app          |     from superset.extensions import (
superset_app          |   File "/app/superset/extensions/__init__.py", line 33, in <module>
superset_app          |     from superset.utils.encrypt import EncryptedFieldFactory
superset_app          |   File "/app/superset/utils/encrypt.py", line 23, in <module>
superset_app          |     from sqlalchemy.engine import Connection, Dialect, RowProxy
superset_app          | ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine' (/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py)
superset_app          | [2023-01-18 14:21:23 +0000] [14] [INFO] Worker exiting (pid: 14)
superset_app          | [2023-01-18 14:21:23 +0000] [12] [INFO] Shutting down: Master
superset_app          | [2023-01-18 14:21:23 +0000] [12] [INFO] Reason: Worker failed to boot.
superset_app exited with code 3
superset_worker_beat  | Traceback (most recent call last):
superset_worker_beat  |   File "/usr/bin/celery", line 8, in <module>
superset_worker_beat  |     sys.exit(main())
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
superset_worker_beat  |     _main()
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
superset_worker_beat  |     cmd.execute_from_commandline(argv)
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
superset_worker_beat  |     super(CeleryCommand, self).execute_from_commandline(argv)))
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 289, in execute_from_commandline
superset_worker_beat  |     argv = self.setup_app_from_commandline(argv)
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 509, in setup_app_from_commandline
superset_worker_beat  |     self.app = self.find_app(app)
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 531, in find_app
superset_worker_beat  |     return find_app(app, symbol_by_name=self.symbol_by_name)
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/celery/app/utils.py", line 373, in find_app
superset_worker_beat  |     sym = symbol_by_name(app, imp=imp)
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 534, in symbol_by_name
superset_worker_beat  |     return imports.symbol_by_name(name, imp=imp)
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
superset_worker_beat  |     module = imp(module_name, package=package, **kwargs)
superset_worker_beat  |   File "/usr/local/lib/python3.8/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
superset_worker_beat  |     return imp(module, package=package)
superset_worker_beat  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
superset_worker_beat  |     return _bootstrap._gcd_import(name[level:], package, level)
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
superset_worker_beat  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
superset_worker_beat  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_worker_beat  |   File "/app/superset/__init__.py", line 21, in <module>
superset_worker_beat  |     from superset.app import create_app
superset_worker_beat  |   File "/app/superset/app.py", line 23, in <module>
superset_worker_beat  |     from superset.initialization import SupersetAppInitializer
superset_worker_beat  |   File "/app/superset/initialization/__init__.py", line 33, in <module>
superset_worker_beat  |     from superset.extensions import (
superset_worker_beat  |   File "/app/superset/extensions/__init__.py", line 33, in <module>
superset_worker_beat  |     from superset.utils.encrypt import EncryptedFieldFactory
superset_worker_beat  |   File "/app/superset/utils/encrypt.py", line 23, in <module>
superset_worker_beat  |     from sqlalchemy.engine import Connection, Dialect, RowProxy
superset_worker_beat  | ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine' (/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py)
superset_worker       | Traceback (most recent call last):
superset_worker       |   File "/usr/bin/celery", line 8, in <module>
superset_worker       |     sys.exit(main())
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
superset_worker       |     _main()
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
superset_worker       |     cmd.execute_from_commandline(argv)
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
superset_worker       |     super(CeleryCommand, self).execute_from_commandline(argv)))
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 289, in execute_from_commandline
superset_worker       |     argv = self.setup_app_from_commandline(argv)
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 509, in setup_app_from_commandline
superset_worker       |     self.app = self.find_app(app)
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 531, in find_app
superset_worker       |     return find_app(app, symbol_by_name=self.symbol_by_name)
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/celery/app/utils.py", line 373, in find_app
superset_worker       |     sym = symbol_by_name(app, imp=imp)
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 534, in symbol_by_name
superset_worker       |     return imports.symbol_by_name(name, imp=imp)
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
superset_worker       |     module = imp(module_name, package=package, **kwargs)
superset_worker       |   File "/usr/local/lib/python3.8/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
superset_worker       |     return imp(module, package=package)
superset_worker       |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
superset_worker       |     return _bootstrap._gcd_import(name[level:], package, level)
superset_worker       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
superset_worker       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
superset_worker       |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
superset_worker       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_worker       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
superset_worker       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
superset_worker       |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
superset_worker       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_worker       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
superset_worker       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
superset_worker       |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
superset_worker       |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
superset_worker       |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
superset_worker       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
superset_worker       |   File "/app/superset/__init__.py", line 21, in <module>
superset_worker       |     from superset.app import create_app
superset_worker       |   File "/app/superset/app.py", line 23, in <module>
superset_worker       |     from superset.initialization import SupersetAppInitializer
superset_worker       |   File "/app/superset/initialization/__init__.py", line 33, in <module>
superset_worker       |     from superset.extensions import (
superset_worker       |   File "/app/superset/extensions/__init__.py", line 33, in <module>
superset_worker       |     from superset.utils.encrypt import EncryptedFieldFactory
superset_worker       |   File "/app/superset/utils/encrypt.py", line 23, in <module>
superset_worker       |     from sqlalchemy.engine import Connection, Dialect, RowProxy
superset_worker       | ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine' (/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py)
superset_worker_beat exited with code 1
superset_worker exited with code 1
```

### Environment

(please complete the following information):

- browser type and version: NA
- superset version: `1.5.3`
- python version: `3.9.5` (shouldn't matter though as it will be whatever is in the docker images)
- node.js version: node.js is not installed.
- any feature flags active: na

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [y] I have reproduced the issue with at least the latest released version of superset.
- [y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bobhenkel** [comment]
I had this issue today and for me, it was some SQL that didn't like Postgres 14. When I downgraded the Postgres image tag to 10 things at least started up.

**Comment by bobhenkel** [comment]
Here's the error I saw in the postgres container.
2023-01-20 01:23:23.992 UTC [1] FATAL:  database files are incompatible with server
2023-01-20 01:23:23.992 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 14.6 (Debian 14.6-1.pgdg110+1).

**Comment by bobhenkel** [comment]
All my issues went away just using git tag 1.5.3.

**Comment by rusackas** [comment]
Glad this is fixed! Closing :)
