### ISSUE TITLE
upgrade to , something error in sqllab

### ISSUE THREAD

**Issue by chiweng2009** [apache/superset#23048]
upgrade from apache/superset:c2c8efc3c431cc81bdc93d3595c5c582eb721090  to apache/superset:b94052e438944b34ef30681e976bf1842ba4e0a5, some error in sqllab. help~

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 175, in wraps
    return f(self, *args, **kwargs)
  File "/home/admin/fire-insight-analysis-ding/superset/views/sql_lab/views.py", line 219, in put
    db.session.query(TabState).filter_by(id=tab_state_id).update(fields)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3294, in update
    result = self.session.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`fire-insight-ding`.`tab_state`, CONSTRAINT `tab_state_latest_query_id_fkey` FOREIGN KEY (`latest_query_id`) REFERENCES `query` (`client_id`) ON DELETE SET NULL)')
[SQL: UPDATE tab_state SET changed_on=%s, latest_query_id=%s, changed_by_fk=%s WHERE tab_state.id = %s]
[parameters: (datetime.datetime(2023, 2, 9, 9, 27, 32, 260966), 'Mvni5_2n7', 1, 22)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

![FE55E0FC-6F63-4CD1-97C5-C108F811B965](https://user-images.githubusercontent.com/6847398/217777448-1b6e2485-8721-4f8c-9397-b4b71fe74b91.png)

**Comment by chiweng2009** [comment]
{"errors": [{"message": "(MySQLdb._exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`superset-0822`.`tab_state`, CONSTRAINT `tab_state_latest_query_id_fkey` FOREIGN KEY (`latest_query_id`) REFERENCES `query` (`client_id`) ON DELETE SET NULL)')\n[SQL: UPDATE tab_state SET changed_on=%s, latest_query_id=%s, changed_by_fk=%s WHERE tab_state.id = %s]\n[parameters: (datetime.datetime(2023, 2, 9, 9, 53, 16, 276885), 'hClMJDKPx', 1, 5)]\n(Background on this error at: https://sqlalche.me/e/14/gkpj)", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}

**Comment by chiweng2009** [comment]
after 'superset init', it works.
I thought 'superset init' was only used for new environments.

--- from baidu translation

**Comment by chiweng2009** [comment]
my first issue

**Comment by chiweng2009** [comment]
my first issus

**Comment by chiweng2009** [comment]
close again

**Comment by chiweng2009** [comment]
close again

**Comment by chanrithdeepsearch** [comment]
@chiweng2009 i got this issue too. But isn't running `superset init` reset all the existing database?

**Comment by tooptoop4** [comment]
superset init didn't help
