### ISSUE TITLE
Running pip-compile-multi fails on 2.0.1

### ISSUE THREAD

**Issue by SatvikNema** [apache/superset#23136]
Running `pip install --upgrade pip` on [superset v2.0.1](https://github.com/apache/superset/releases/tag/2.0.1) is giving an error: 
`ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars'`

#### How to reproduce the bug

1. Go to [superset v2.0.1](https://github.com/apache/superset/releases/tag/2.0.1) and download the source in local
2. `pip install -r requirements/testing.txt`
3. `pip install -e .`
4. run `pip-compile-multi`

I was just playing around with local setup, and had added some dependencies in `requirements/testing.in`, but when running `pip-compile-multi`, it was giving me this error.

### Expected results

to get a compiled `requirements/testing.txt` or equivalent.

### Actual results

```python
Locking requirements/base.in to requirements/base.txt. References: []
ERROR executing /Users/s0n02qm/practise/superset-2.0.1/venv/bin/python -m piptools compile --no-header --verbose --rebuild --upgrade --no-emit-index-url --output-file requirements/base.txt requirements/base.in
Exit code: 1
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/piptools/__main__.py", line 3, in <module>
    from piptools.scripts import compile, sync
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/piptools/scripts/compile.py", line 20, in <module>
    from ..repositories import LocalRequirementsRepository, PyPIRepository
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/piptools/repositories/__init__.py", line 1, in <module>
    from .local import LocalRequirementsRepository
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/piptools/repositories/local.py", line 14, in <module>
    from .pypi import PyPIRepository
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars' (/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py)

Traceback (most recent call last):
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/actions.py", line 30, in recompile
    compile_topologically(env_confs, deduplicator)
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/actions.py", line 39, in compile_topologically
    if env.maybe_create_lockfile():
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/environment.py", line 51, in maybe_create_lockfile
    self.create_lockfile()
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/environment.py", line 83, in create_lockfile
    raise RuntimeError("Failed to pip-compile {0}".format(self.infile))
RuntimeError: Failed to pip-compile requirements/base.in

```

### Environment

- superset version: `2.0.1`
- python version: `3.8.13`
- node.js version: `NA`
- pip version: `23.0.1`
- I am on mac `12.6.2`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

I have gone though similar issues on the internet and found a solution to downgrade pip as follows `pip install pip==21.2`.
But after doing that, I am getting a different error
```python
Finding the best candidates:
  found candidate aiohttp==3.8.4 (constraint was >3.5.2)
  found candidate alembic==1.9.4 (constraint was >=1.9.0)
  found candidate -e file:. (constraint was ==2.0.1)
  found candidate apispec[yaml]==5.2.2 (constraint was >=3.3,<6)
  found candidate async-timeout==4.0.2 (constraint was >=4.0.2)
  found candidate backoff==2.2.1 (constraint was >=1.8.0)
  found candidate billiard==3.6.4.0 (constraint was >=3.6.4.0,<4.0)
  found candidate bleach==3.3.1 (constraint was >=3.0.2,<4.0.0)
  found candidate brotli==1.0.9 (constraint was <any>)
Could not find a version that matches cachelib<0.10.0,<0.5,>=0.4.1,>=0.9.0 (from apache-superset==2.0.1->-r requirements/base.in (line 19))
Tried: 0.1, 0.1, 0.1.1, 0.1.1, 0.2.0, 0.2.0, 0.3.0, 0.3.0, 0.4.0, 0.4.0, 0.4.1, 0.4.1, 0.5.0, 0.5.0, 0.6.0, 0.6.0, 0.7.0, 0.7.0, 0.8.0, 0.8.0, 0.9.0, 0.9.0, 0.10.0, 0.10.0, 0.10.1, 0.10.1, 0.10.2, 0.10.2
There are incompatible versions in the resolved dependencies:
  cachelib<0.10.0,>=0.9.0 (from flask-caching==2.0.2->apache-superset==2.0.1->-r requirements/base.in (line 19))
  cachelib<0.5,>=0.4.1 (from apache-superset==2.0.1->-r requirements/base.in (line 19))

Traceback (most recent call last):
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/actions.py", line 30, in recompile
    compile_topologically(env_confs, deduplicator)
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/actions.py", line 39, in compile_topologically
    if env.maybe_create_lockfile():
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/environment.py", line 51, in maybe_create_lockfile
    self.create_lockfile()
  File "/Users/s0n02qm/practise/superset-2.0.1/venv/lib/python3.8/site-packages/pipcompilemulti/environment.py", line 83, in create_lockfile
    raise RuntimeError("Failed to pip-compile {0}".format(self.infile))
RuntimeError: Failed to pip-compile requirements/base.in

```

I am using `pip-compile-multi` for the first time, so please correct me if am doing anything wrong.

**Comment by artemonsh** [comment]
still relevant
