### ISSUE TITLE
Raise InvalidRequestError in celery asynchronous mode

### ISSUE THREAD

**Issue by SbloodyS** [apache/superset#23169]
#### How to reproduce the bug

Executing the sql which contains chinese in sql lab, eg: SELECT '中文'. 
It can be run successfully in non-asynchronous mode. However, the execution fails in asynchronous mode via celey with redis backend. 

Celery start command:
`celery --app=superset.tasks.celery_app:app worker --pool=prefork -O fair -c 4`

The error log is as follows:
```
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]: During handling of the above exception, another exception occurred:
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]: Traceback (most recent call last):
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/superset/sql_lab.py", line 173, in get_sql_results
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return execute_sql_statements(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/superset/sql_lab.py", line 509, in execute_sql_statements
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     payload = handle_query_error(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/superset/sql_lab.py", line 108, in handle_query_error
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     errors = query.database.db_engine_spec.extract_errors(str(ex))
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 294, in __get__
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return self.impl.get(instance_state(instance), dict_)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 730, in get
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     value = self.callable_(state, passive)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 726, in _load_for_state
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     primary_key_identity = self._get_ident_for_use_get(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 773, in _get_ident_for_use_get
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return [
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 774, in <listcomp>
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     get_attr(state, dict_, self._equated_columns[pk], passive=passive)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2845, in _get_state_attr_by_column
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return state.manager[prop.key].impl.get(state, dict_, passive=passive)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 725, in get
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     value = state._load_expired(state, passive)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 652, in _load_expired
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     self.manager.deferred_scalar_loader(self, toload)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1006, in load_scalar_attributes
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     result = load_on_ident(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 200, in load_on_ident
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return load_on_pk_identity(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return q.one()
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3490, in one
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     ret = self.one_or_none()
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     ret = list(self)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return self._execute_and_instances(context)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     conn = self._get_bind_args(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return fn(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     conn = self.session.connection(**kw)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1142, in connection
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return self._connection_for_bind(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return self.transaction._connection_for_bind(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     self._assert_active()
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     raise sa_exc.InvalidRequestError(
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]: sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 'charmap' codec can't encode characters in position 8-9: character maps to <undefined> (Background on this error at: http://sqlalche.me/e/13/7s2a)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]: The above exception was the direct cause of the following exception:
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]: Traceback (most recent call last):
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     ret = target(*args, **kwargs)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/superset/sql_lab.py", line 149, in get_query
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     raise SqlLabException("Failed at getting query") from ex
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]: superset.sql_lab.SqlLabException: Failed at getting query
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]: During handling of the above exception, another exception occurred:
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]: Traceback (most recent call last):
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     R = retval = fun(*args, **kwargs)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/superset/initialization/__init__.py", line 105, in __call__
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return task_base.__call__(self, *args, **kwargs)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     return self.run(*args, **kwargs)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/superset/sql_lab.py", line 186, in get_sql_results
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     query = get_query(query_id, session)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/backoff/_sync.py", line 124, in retry
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     _call_handlers(on_backoff, **details, wait=seconds,
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/backoff/_sync.py", line 20, in _call_handlers
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     hdlr(details)
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:   File "/data/anaconda3/envs/python3.9/lib/python3.9/site-packages/superset/sql_lab.py", line 122, in get_query_backoff_handler
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]:     query_id = details["kwargs"]["query_id"]
Feb 23 16:24:44 ip-192-168-25-200 celery[15667]: KeyError: 'query_id'
```

### Expected results

Running successfully.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version: chrome 110.0.5481.177 (arm64)
- superset version:  2.0.1
- python version:  3.9.16

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
