### ISSUE TITLE
docker-compose up and can't open the UI

### ISSUE THREAD

**Issue by hantmac** [apache/superset#23304]
#### How to reproduce the bug
According [this doc](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/#1-install-a-docker-engine-and-docker-compose)
1.  git clone
2. cd superset
3. touch ./docker/requirements-local.txt and echo `clickhouse-connect` > ./docker/requirements-local.txt
4. docker-compose up

### Expected results

Open the superset in browser.

### Actual results

Can not open superset in browser like this:
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/7600925/223592578-18736dc4-91a4-4024-b3f1-51b23fcaf48d.png">

#### Screenshots

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/7600925/223592578-18736dc4-91a4-4024-b3f1-51b23fcaf48d.png">

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `the newest code`
- python version: `python3.9`
- node.js version: `v14.19.3`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

```
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
superset_app             | 172.19.0.1 - - [08/Mar/2023 01:11:59] "GET /static/assets/images/favicon.png HTTP/1.1" 404 -
superset_app             | 2023-03-08 01:11:59,855:INFO:werkzeug:172.19.0.1 - - [08/Mar/2023 01:11:59] "GET /static/assets/images/favicon.png HTTP/1.1" 404 -
superset_worker_beat     | [2023-03-08 01:12:00,094: INFO/MainProcess] Scheduler: Sending due task reports.scheduler (reports.scheduler)
superset_worker          | [2023-03-08 01:12:00,174: INFO/MainProcess] Task reports.scheduler[3626bbb8-062a-49e7-8f2a-033ed05decf9] received
superset_worker          | [2023-03-08 01:12:00,632: INFO/ForkPoolWorker-3] Task reports.scheduler[3626bbb8-062a-49e7-8f2a-033ed05decf9] succeeded in 0.4056195000000571s: None
superset_app             | 2023-03-08 01:12:00,899:WARNING:superset.views.base:HTTPException
superset_app             | Traceback (most recent call last):
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
superset_app             |     rv = self.dispatch_request()
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
superset_app             |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 509, in <lambda>
superset_app             |     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask/scaffold.py", line 322, in send_static_file
superset_app             |     return send_from_directory(
superset_app             |   File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 676, in send_from_directory
superset_app             |     return werkzeug.utils.send_from_directory(  # type: ignore
superset_app             |   File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 586, in send_from_directory
superset_app             |     raise NotFound()
superset_app             | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

```

**Comment by woozhijun** [comment]
The same problem.

**Comment by matiasomartin** [comment]
The same problem.

**Comment by artrusx** [comment]
i'm having this same issue

**Comment by matiasomartin** [comment]
I'm having te same problem.

**Comment by vitali-melnyk** [comment]
The same issue. Can't start in docker-compose

**Comment by zajcomm** [comment]
same here... any hits on what to do?

**Comment by ningaro** [comment]
I also faced with such problem, but deleting the old `node_modules` folders helped in my case. 
You may use one of this commands: 
 - `git clean -xdf`
 - `git reset --hard` **<- 🛑 DANGER, COMMIT LOCAL CHANGES BEFORE!**

**Comment by tmnvanderberg** [comment]
Having the same issue, none of the proposed solutions work for me... :(

**Comment by rusackas** [comment]
The original report is using node 14. Can you try with node 16? We're actually going to be on node 18 imminently, and moving to 20, so 14 is probably old enough to be quite problematic.

**Comment by UsenPang** [comment]
I have the same issue,you may need to wait a bit, after starting superset_node there are some packages to download.


![image](https://github.com/apache/superset/assets/87891272/f3dd9b4e-7744-451f-bbbd-995ef39ce8bc)

**Comment by Emily0330** [comment]
For me, follow the [QuickStart guide](https://superset.apache.org/docs/quickstart) and type `docker compose -f docker-compose-image-tag.yml up` rather than just `docker compose up` solves the problem!

**Comment by hossein-khalilian** [comment]
If you're adding new requirements to `requirements-local.txt` and using `docker-compose-image-tag.yml`, I encountered the same issue where `superset-init` couldn't complete its job. It turned out the script was trying to use `uv` to install the new requirements, but `uv` wasn’t available in the container.

To address this, I created a pull request to the project, which resolved the issue in commit `#33078`. Try pulling the latest version of the project and see if it works for you too.

**Comment by rusackas** [comment]
Assuming this is all well and good by now. Also noting that anyone reading this should be using `docker compose` rather than `docker-compose` these days.
