### ISSUE TITLE
Opening chart in embedded dashboard leads to error (GuestUser has no attribute get_user_id)

### ISSUE THREAD

**Issue by mbenz95** [apache/superset#23380]
I have an embedded superset dashboard in my application
When I click on the title of a chart (or on 'Edit Chart' in the three-dot menu) I expect it to open in superset or to to bring me to 
the login page of superset but the embedded UI only shows the error message  
`An error occurred while opening Explore` 
If I am logged in into superset on another browser tab, this works fine and a new tab opens with the chart (as the user logged in on the other tab).

The superset_app container throws the following error (if not logged-in in another tab):
```
2023-03-15 08:08:29,138:ERROR:root:'GuestUser' object has no attribute 'get_user_id'
2023-03-15T08:08:29.138837700Z Traceback (most recent call last):
2023-03-15T08:08:29.138840600Z   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 86, in wraps
2023-03-15T08:08:29.138842900Z     return f(self, *args, **kwargs)
2023-03-15T08:08:29.138844900Z   File "/app/superset/utils/log.py", line 245, in wrapper
2023-03-15T08:08:29.138846900Z     value = f(*args, **kwargs)
2023-03-15T08:08:29.138849100Z   File "/app/superset/views/base_api.py", line 83, in wraps
2023-03-15T08:08:29.138851200Z     return f(self, *args, **kwargs)
2023-03-15T08:08:29.138853300Z   File "/app/superset/explore/form_data/api.py", line 113, in post
2023-03-15T08:08:29.138855400Z     key = CreateFormDataCommand(args).run()
2023-03-15T08:08:29.138867600Z   File "/app/superset/explore/form_data/commands/create.py", line 57, in run
2023-03-15T08:08:29.138870100Z     "owner": get_owner(actor),
2023-03-15T08:08:29.138872100Z   File "/app/superset/key_value/utils.py", line 70, in get_owner
2023-03-15T08:08:29.138874100Z     return user.get_user_id() if not user.is_anonymous else None
2023-03-15T08:08:29.138876300Z AttributeError: 'GuestUser' object has no attribute 'get_user_id'
```

It looks like this action does not work for work for a guest user but I would at least expect superset to open a login page or similar to allow the user to log in.
I tried different roles for the guest user with the GUEST_ROLE_NAME config option.
I have the role set to 'Admin' which leads to the described error. I also tried to set the role to 'Gamma' which leads to a 404, presumably because editing the chart is not allowed for this role.
I also correctly set the user in the  `/api/v1/security/guest_token/` endpoint but for me it didn't have any effect which user I passed here.
This looks like a bug but its also possible that I am missing some configuration option.  
I appreciate any help on how to solve this on my side if possible.

Info:
Superset 2.0.1 running in docker-container (using docker-compose provided by this repo)
OS: Windows 10
Steps to reproduce:
- Create dashboard with any chart in superset
- Embed dashboard with superset-embedded-sdk
- Configure guest role with: GUEST_ROLE_NAME = "Admin"
- Click on chart title inside embedded dashboard (make sure to not be logged-in in superset in another tab)
- Check logs of the superset_app container to see the error

**Comment by mbenz95** [comment]
I gave it a try on superset 2.1.0rc2 and the error in the console was not shown but I also did not get the expected behavior. When clicking on edit chart (or on the chart title), the chart just disappeared and nothing else is shown (see gif)

![superset_bug](https://user-images.githubusercontent.com/11816786/226488308-0137f3ae-1ae9-4c81-8576-16aec9c3caa3.gif)

Even when logged in in another tab, it would not the open superset application (which it did in 2.0.1, it opened in another tab). 
While it did behave consistent whether I am logged in or not and the exception in the superset_app is not showing anymore, I still don't think thats the expected behavior but I am not entirely sure.

If anyone else tried this on 2.1.0 and got a different result, please let me know.

**Comment by gervarela** [comment]
Hello,

I'm seeing the same error, also with 2.0.1, but I'm getting it just by opening the dashboard embedded into other applications.

The dashboard works fine, reviewn with the 'developer tools of the browser', one off the calls gest a 500 error as response, and the logs shows thesse error:

`2023-04-18 07:11:53,745:ERROR:root:'GuestUser' object has no attribute 'get_user_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 86, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/dashboards/filter_state/api.py", line 98, in post
    return super().post(pk)
  File "/app/superset/views/base_api.py", line 83, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/temporary_cache/api.py", line 76, in post
    key = self.get_create_command()(args).run()
  File "/app/superset/temporary_cache/commands/create.py", line 35, in run
    return self.create(self._cmd_params)
  File "/app/superset/dashboards/filter_state/commands/create.py", line 41, in create
    entry: Entry = {"owner": get_owner(actor), "value": value}
  File "/app/superset/key_value/utils.py", line 70, in get_owner
    return user.get_user_id() if not user.is_anonymous else None
AttributeError: 'GuestUser' object has no attribute 'get_user_id'`ç

The call is a POST to: https://xxxxx.com/api/v1/dashboard/11/filter_state?tab_id=1

The error only happens the user is not logged in into the Superset instance in another browser tab. If the use is logged in, the request doesn't fails.

It looks like a bug when accesseing the dashboards with the GUEST user.

**Comment by manik-ushur** [comment]
@mbenz95 is this issue resolved? Any pointers what fixed it?

**Comment by mbenz95** [comment]
I was not able to fix the issue but I stopped using superset which is why I closed the issue.

**Comment by rusackas** [comment]
@manik-ushur what version are you on? We can reopen this if you're on 4.x.
