### ISSUE TITLE
v2.1.0rc3: AttributeError: module 'sqlalchemy' has no attribute '__all__'

### ISSUE THREAD

**Issue by xmnlab** [apache/superset#23478]
Hi everyone,

I am playing with v2.1.0rc3 but it is raising the following error when I execute "superset --version":

```
Traceback (most recent call last):
  File "/home/xmn/mambaforge/envs/superset-test/bin/superset", line 6, in <module>
    from superset.cli.main import superset
  File "/home/xmn/mambaforge/envs/superset-test/lib/python3.9/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/home/xmn/mambaforge/envs/superset-test/lib/python3.9/site-packages/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/home/xmn/mambaforge/envs/superset-test/lib/python3.9/site-packages/superset/initialization/__init__.py", line 33, in <module>
    from superset.extensions import (
  File "/home/xmn/mambaforge/envs/superset-test/lib/python3.9/site-packages/superset/extensions/__init__.py", line 119, in <module>
    db = SQLA()
  File "/home/xmn/mambaforge/envs/superset-test/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/xmn/mambaforge/envs/superset-test/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
```

it seems it was fixed here: https://github.com/pallets-eco/flask-sqlalchemy/pull/1123
which means that it is available in its version 3.0.2 ... and that depends on flask>=2.2 (https://github.com/pallets-eco/flask-sqlalchemy/blob/3.0.2/setup.py#L4)

but superset has an upper bond limit for flask <2.2

is there a way to workaround this problem?
thanks!

**Comment by mdeshmu** [comment]
@eschutho ^

**Comment by xmnlab** [comment]
maybe this is something that affects just `superset --version` ?

**Comment by nytai** [comment]
hmm, i don't seem to have this issue using the official `2.1.0rc3` docker image. How are you installing superset? It seems likely that pip just installed an incompatible version in your env.

**Comment by xmnlab** [comment]
I packaged that into a conda package. I will take a look to see if there is anything missing.

**Comment by krakzk** [comment]
Could you give the version change you made, i am facing the same error.
Having a requirement-local.txt with the following

`
SQLAlchemy==2.0.16
sqlalchemy-drill==1.1.2
SQLAlchemy-Utils==0.41.1
alembic==1.11.1
`

**Comment by mdeshmu** [comment]
Superset doesn't support SQLAlchemy 2.0.16. Please refer [setup.py](https://github.com/apache/superset/blob/master/setup.py)  for supported package versions.
