### ISSUE TITLE
superset db upgrade not working due to removal of FLAGS variable in sqlparse/kewords.py

### ISSUE THREAD

**Issue by LeonardSchuler** [apache/superset#23742]
In [superset/sql_parse.py](https://github.com/apache/superset/blob/master/superset/sql_parse.py#L67) sqlparse.keywords.FLAGS is used. However, sqlparse has removed the FLAGS variable from the code [sqlparse/kewords.py](https://github.com/andialbrecht/sqlparse/blob/0.4.4/sqlparse/keywords.py).
This leads to an AttributeError when running the CLI command
`$ superset db upgrade`
`AttributeError: module 'sqlparse.keywords' has no attribute 'FLAGS'`
I would recommend replacing the FLAGS dependency with the actual value
`re.IGNORECASE | re.UNICODE).match`
or fix the sqlparse version to "sqlparse==0.4.3" (not recommended as they fixed a security problem recently).

I have experienced this problem under python3.9 and python3.11

**Comment by Tafkas** [comment]
I have the same issue using Python 3.8.16.

**Comment by esevato** [comment]
Clean install Debian 11 fails @ "superset db upgrade" with
`AttributeError: module 'sqlparse.keywords' has no attribute 'FLAGS'`

**Comment by amilcarnetto** [comment]
downgrading to sqlparse 0.4.3 solve the problem for me

**Comment by MoronGamer** [comment]
> downgrading to sqlparse 0.4.3 solve the problem for me

Having same error, how do you downgrade sqlparse?

**Comment by HoncyLee** [comment]
> > downgrading to sqlparse 0.4.3 solve the problem for me
> 
> Having same error, how do you downgrade sqlparse?

pip install sqlparse=='0.4.3'

**Comment by Akshay577** [comment]
Yes, downgrading the sqlparse version to 0.4.3 fixed the issue for me.

**Comment by anishone** [comment]
Downgrading with `pip install sqlparse=='0.4.3'` works. Thanks!

**Comment by SUGAM-ARORA** [comment]
> downgrading to sqlparse 0.4.3 solve the problem for me

It didn't work for me .

**Comment by rohitkumar0613** [comment]
Same didn't work for me

**Comment by christianxiaobai** [comment]
Downgrading with pip install sqlparse=='0.4.3' works. Thanks!

**Comment by kits-ragh** [comment]
After downgrading sqlparse to 0.4.3 getting following error. 

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

**Comment by pierrelafortune** [comment]
+1 to the same FLASK APP error as @kits-ragh 

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

**Comment by prb219** [comment]
@LeonardSchuler Thanks for the suggestions. I tried your suggested changes on the following setup but it fails 
Superset version: 2.1.0
Python version: 3.8
SQLparse version: 0.4.4

No issue is observed during the db upgrade process. However, when we try to load the dashboards we see this error 
`2023-07-13 21:03:58,523:ERROR:superset.views.base:first argument must be string or compiled pattern
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 122, in wraps
    raise ex
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 113, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/core.py", line 1586, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/log.py", line 266, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/charts/data/api.py", line 255, in data
    return self._get_data_response(
  File "/usr/local/lib/python3.8/site-packages/superset/charts/data/api.py", line 411, in _get_data_response
    result = command.run(force_cached=force_cached)
  File "/usr/local/lib/python3.8/site-packages/superset/charts/data/commands/get_data_command.py", line 45, in run
    payload = self._query_context.get_payload(
  File "/usr/local/lib/python3.8/site-packages/superset/common/query_context.py", line 100, in get_payload
    return self._processor.get_payload(cache_query_context, force_cached)
  File "/usr/local/lib/python3.8/site-packages/superset/common/query_context_processor.py", line 477, in get_payload
    query_results = [
  File "/usr/local/lib/python3.8/site-packages/superset/common/query_context_processor.py", line 478, in <listcomp>
    get_query_results(
  File "/usr/local/lib/python3.8/site-packages/superset/common/query_actions.py", line 226, in get_query_results
    return result_func(query_context, query_obj, force_cached)
  File "/usr/local/lib/python3.8/site-packages/superset/common/query_actions.py", line 103, in _get_full
    payload = query_context.get_df_payload(query_obj, force_cached=force_cached)
  File "/usr/local/lib/python3.8/site-packages/superset/common/query_context.py", line 121, in get_df_payload
    return self._processor.get_df_payload(query_obj, force_cached)
  File "/usr/local/lib/python3.8/site-packages/superset/common/query_context_processor.py", line 136, in get_df_payload
    query_result = self.get_query_result(query_obj)
  File "/usr/local/lib/python3.8/site-packages/superset/common/query_context_processor.py", line 214, in get_query_result
    result = query_context.datasource.query(query_object.to_dict())
  File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 1903, in query
    query_str_ext = self.get_query_str_extended(query_obj)
  File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 884, in get_query_str_extended
    sqlaq = self.get_sqla_query(**query_obj)
  File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 1440, in get_sqla_query
    tbl, cte = self.get_from_clause(template_processor)
  File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 920, in get_from_clause
    from_sql = self.get_rendered_sql(template_processor)
  File "/usr/local/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 957, in get_rendered_sql
    sql = sqlparse.format(sql.strip("\t\r\n; "), strip_comments=True)
  File "/usr/local/lib/python3.8/site-packages/sqlparse/__init__.py", line 59, in format
    return ''.join(stack.run(sql, encoding))
  File "/usr/local/lib/python3.8/site-packages/sqlparse/engine/filter_stack.py", line 26, in run
    stream = lexer.tokenize(sql, encoding)
  File "/usr/local/lib/python3.8/site-packages/sqlparse/lexer.py", line 155, in tokenize
    return Lexer.get_default_instance().get_tokens(sql, encoding)
  File "/usr/local/lib/python3.8/site-packages/sqlparse/lexer.py", line 52, in get_default_instance
    cls._default_intance.default_initialization()
  File "/usr/local/lib/python3.8/site-packages/sqlparse/lexer.py", line 59, in default_initialization
    self.set_SQL_REGEX(keywords.SQL_REGEX)
  File "/usr/local/lib/python3.8/site-packages/sqlparse/lexer.py", line 78, in set_SQL_REGEX
    self._SQL_REGEX = [
  File "/usr/local/lib/python3.8/site-packages/sqlparse/lexer.py", line 79, in <listcomp>
    (re.compile(rx, FLAGS).match, tt)
  File "/usr/lib64/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.8/re.py", line 303, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern`

**Comment by enoxos** [comment]
If you downgraded to sqlparser=0.4.3 and you get the error:

 `_Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.`

then set the FLASK_APP as follows

`FLASK_APP=superset`

and then rerun the db initialization step.

**Comment by mdanishu** [comment]
I'm still getting this flags problem... why is this happening and how can we fix it? downgrading to lower versions didn't fix it

**Comment by WaluQ-iu** [comment]
> I'm still getting this flags problem... why is this happening and how can we fix it? downgrading to lower versions didn't fix it

Try export FLASK_APP=superset and then rerun

**Comment by helpwise** [comment]
/home/ubuntu/.local/bin# sudo -u ubuntu FLASK_APP=superset /home/ubuntu/.local/bin/superset db upgrade

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/initialization/__init__.py", line 33, in <module>
    from superset.extensions import (
  File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/extensions/__init__.py", line 32, in <module>
    from superset.utils.async_query_manager import AsyncQueryManager
  File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/utils/async_query_manager.py", line 26, in <module>
    from superset.utils.core import get_user_id
  File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/utils/core.py", line 106, in <module>
    from superset.sql_parse import sanitize_clause
  File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/sql_parse.py", line 67, in <module>
    re.compile(r"'(''|\\\\|\\|[^'])*'", sqlparse.keywords.FLAGS).match,
AttributeError: module 'sqlparse.keywords' has no attribute 'FLAGS'

FLASK_APP=superset  doesnt work for me either..

**Comment by WaluQ-iu** [comment]
> /home/ubuntu/.local/bin# sudo -u ubuntu FLASK_APP=superset /home/ubuntu/.local/bin/superset db upgrade
> 
> Traceback (most recent call last): File "/home/ubuntu/.local/bin/superset", line 5, in from superset.cli.main import superset File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/**init**.py", line 21, in from superset.app import create_app File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/app.py", line 23, in from superset.initialization import SupersetAppInitializer File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/initialization/**init**.py", line 33, in from superset.extensions import ( File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/extensions/**init**.py", line 32, in from superset.utils.async_query_manager import AsyncQueryManager File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/utils/async_query_manager.py", line 26, in from superset.utils.core import get_user_id File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/utils/core.py", line 106, in from superset.sql_parse import sanitize_clause File "/home/ubuntu/.local/lib/python3.10/site-packages/superset/sql_parse.py", line 67, in re.compile(r"'(''|\\|\|[^'])*'", sqlparse.keywords.FLAGS).match, AttributeError: module 'sqlparse.keywords' has no attribute 'FLAGS'

`AttributeError: module 'sqlparse.keywords' has no attribute 'FLAGS'` suggests a compatibility issue or version mismatch with the libraries or modules being used by Superset. Specifically, it mentions an AttributeError related to the FLAGS attribute in the sqlparse.keywords module. Comments above state that you need to downgrade sqlparse to a lower version, check comments above.

**Comment by EJ-Humn** [comment]
> In [superset/sql_parse.py](https://github.com/apache/superset/blob/master/superset/sql_parse.py#L67) sqlparse.keywords.FLAGS is used. However, sqlparse has removed the FLAGS variable from the code [sqlparse/kewords.py](https://github.com/andialbrecht/sqlparse/blob/0.4.4/sqlparse/keywords.py). This leads to an AttributeError when running the CLI command `$ superset db upgrade` `AttributeError: module 'sqlparse.keywords' has no attribute 'FLAGS'` I would recommend replacing the FLAGS dependency with the actual value `re.IGNORECASE | re.UNICODE).match` or fix the sqlparse version to "sqlparse==0.4.3" (not recommended as they fixed a security problem recently).
> 
> I have experienced this problem under python3.9 and python3.11

This worked for me:

`re.compile(r"'(''|\\\\|\\|[^'])*'", re.IGNORECASE | re.UNICODE).match,`
