### ISSUE TITLE
Union is not define while creating Athena connection

### ISSUE THREAD

**Issue by jalakiran** [apache/superset#23957]
#### How to reproduce the bug

1. Go to Connect Database
2.  Choose Aws Athena
I have prepared a connection string using the below code

from urllib.parse import quote_plus

conn_str = "awsathena+rest://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com:443/{schema_name}?s3_staging_dir={s3_staging_dir}"
               
print(conn_str.format(
      aws_access_key_id=quote_plus("xxxxx"),
      aws_secret_access_key=quote_plus("xxxx"),
      region_name="xxxx",
      schema_name="xxx",
      s3_staging_dir=quote_plus("s3://xxxx")))

the resulting sting when I am using I am getting union name is not defined, I have tried so many times, I didn't get it.

### Expected results

Connection should establish with Athena

### Actual results

getting error
#### Screenshots
![image](https://user-images.githubusercontent.com/127227983/236648468-8d377984-c882-4647-8574-9eaf8560e11e.png)

**Comment by mdeshmu** [comment]
Is the connection successfully established?
Do you know if other non-union queries are working?

**Comment by jalakiran** [comment]
> Is the connection successfully established? Do you know if other non-union queries are working?

No, the connection is not working, I am getting a "union" error.

I am new to the superset, yesterday I installed using an image from the docker hub.

is anything wrong with the connection string?

**Comment by jalakiran** [comment]
> 
These are the logs I have found in the docker logs


![image](https://user-images.githubusercontent.com/127227983/236664842-7ffac728-2690-4c83-8aca-c1473fe0f747.png)

**Comment by mdeshmu** [comment]
I haven't tried pyathenajdbc before. Make sure dependencies are installed as per https://pypi.org/project/pyathenajdbc/
You could also try just with pyathena.

**Comment by jalakiran** [comment]
> I haven't tried pyathenajdbc before. Make sure dependencies are installed as per https://pypi.org/project/pyathenajdbc/ You could also try just with pyathena.

SupersetErrorsException
Traceback (most recent call last):
  File "/app/superset/databases/commands/test_connection.py", line 134, in run
    with database.get_sqla_engine_with_context(
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/app/superset/models/core.py", line 411, in get_sqla_engine_with_context
    yield self._get_sqla_engine(
  File "/app/superset/models/core.py", line 503, in _get_sqla_engine
    raise self.db_engine_spec.get_dbapi_mapped_exception(ex)
  File "/app/superset/models/core.py", line 501, in _get_sqla_engine
    return create_engine(sqlalchemy_url, **params)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 534, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 661, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 330, in load
    return self.impls[name]()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/pyathena/sqlalchemy/rest.py", line 2, in <module>
    from pyathena.sqlalchemy.base import AthenaDialect
  File "/usr/local/lib/python3.8/site-packages/pyathena/sqlalchemy/base.py", line 861, in <module>
    class AthenaDialect(DefaultDialect):
  File "/usr/local/lib/python3.8/site-packages/pyathena/sqlalchemy/base.py", line 979, in AthenaDialect
    def _get_table(self, connection, table_name: str, schema: Optional[str] = None, **kw):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 198, in decorate
    decorated = _exec_code_in_env(code, env, fn.__name__)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 228, in _exec_code_in_env
    exec(code, env)
  File "<string>", line 1, in <module>
NameError: name 'Union' is not defined

**Comment by jalakiran** [comment]
I am exsting superset as below 


FROM apache/superset:latest
# Switching to root to install the required packages
USER root
# Example: installing the MySQL driver to connect to the metadata database
# if you prefer Postgres, you may want to use `psycopg2-binary` instead
RUN pip install PyAthenaJDBC
RUN pip install PyAthena
# Example: installing a driver to connect to Redshift
# Find which driver you need based on the analytics database
# you want to connect to here:
# https://superset.apache.org/installation.html#database-dependencies
# Switching back to using the `superset` user
USER superset

**Comment by Samuel-William** [comment]
I am also getting same error since Friday....Tried all the steps could not resolve it

**Comment by Samuel-William** [comment]
@jalakiran - Could you please let me know in which Machine you are getting this error? Is it in EC2 Instance or your laptop or which cloud environment.

**Comment by jalakiran** [comment]
> I am also getting the same error since Friday....Tried all the steps could not resolve it


It is in ec2 instace ubuntu.


I have tried these docker images 2.0.0, 2.0.1, 2.1.0,1.5,1.4

The Anthena connection working in 1.2.0 only.

in other images, I am getting the "VisibleType" not subscribable error

**Comment by Alvinspapa** [comment]
Got the same error and fixed.

Root cause is the version of PyAthena and SQLAlchemy are having conflicted references.

To fix it, in your Superset requirement_local.txt file, add the following lines to limit the PyAthena version.

`PyAthenaJDBC>1.0.9
PyAthena==2.25.0`

And make sure you used SQLAlchemy >=1.0.0, <2.0.0

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
