### ISSUE TITLE
A user with Gamma + sql_lab role cannot open a new editor tab

### ISSUE THREAD

**Issue by mdeshmu** [apache/superset#24228]
We did Superset upgrade from 1.5.3 version to 2.1.0 version. 
Post upgrade in version 2.1.0, a user with Gamma + sql_lab role cannot open a new editor tab

#### How to reproduce the bug

1. Go to 'SQL'
2. Click on 'SQL Lab' and then Click on 'Add a new tab'
3. See the error "unable to add a new table to the backend"

### Expected results
A new table should be added allowing to select databases to query

### Actual results

"unable to add a new table to the backend" error pops up

#### Screenshots

![image](https://github.com/apache/superset/assets/57723564/8a893919-4bf4-405c-8c7b-73445b2be6dc)

**Backend logs:**

Traceback (most recent call last):
--
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 181, in wraps
return f(self, *args, **kwargs)
File "/app/superset/views/sql_lab/views.py", line 150, in post
database_id=query_editor["dbId"],
KeyError: 'dbId'

### Environment

- browser type and version: 
- superset version: 2.1.0
- python version: 3.8
- node.js version: NA
- any feature flags active: 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

We are testing Superset upgrade from 1.5.3 version to 2.1.0 version

**Comment by mdeshmu** [comment]
@dpgaspar @eschutho can you please help me identify the root cause of this?

**Comment by mdeshmu** [comment]
User didn't had access to any database, hence superset wasn't able to map any dbId to editor. 
After giving `database access on xxxx`, the issue is resolved.
