### ISSUE TITLE
Getting error when running test connection -  ERROR: Invalid decryption key 

### ISSUE THREAD

**Issue by alberttwong** [apache/superset#24254]
```
2023-05-30 18:19:02,470:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.test_connection.error
superset_app           | 2023-05-30 18:19:02,471:ERROR:superset.views.base:Invalid decryption key
superset_app           | Traceback (most recent call last):
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 126, in decrypt
superset_app           |     decrypted = decrypted.decode('utf-8')
superset_app           | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 2: invalid continuation byte
superset_app           |
superset_app           | During handling of the above exception, another exception occurred:
superset_app           |
superset_app           | Traceback (most recent call last):
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset_app           |     rv = self.dispatch_request()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
superset_app           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset_app           |     return f(self, *args, **kwargs)
superset_app           |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app           |     raise ex
superset_app           |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app           |     duration, response = time_function(f, self, *args, **kwargs)
superset_app           |   File "/app/superset/utils/core.py", line 1596, in time_function
superset_app           |     response = func(*args, **kwargs)
superset_app           |   File "/app/superset/utils/log.py", line 266, in wrapper
superset_app           |     value = f(*args, **kwargs)
superset_app           |   File "/app/superset/views/base_api.py", line 93, in wraps
superset_app           |     return f(self, *args, **kwargs)
superset_app           |   File "/app/superset/databases/api.py", line 910, in test_connection
superset_app           |     TestConnectionDatabaseCommand(item).run()
superset_app           |   File "/app/superset/databases/commands/test_connection.py", line 72, in run
superset_app           |     self.validate()
superset_app           |   File "/app/superset/databases/commands/test_connection.py", line 232, in validate
superset_app           |     self._model = DatabaseDAO.get_database_by_name(database_name)
superset_app           |   File "/app/superset/databases/dao.py", line 79, in get_database_by_name
superset_app           |     db.session.query(Database)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
superset_app           |     return self._iter().one_or_none()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1405, in one_or_none
superset_app           |     return self._only_one_row(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 559, in _only_one_row
superset_app           |     row = onerow(hard_close=True)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1281, in _fetchone_impl
superset_app           |     return self._real_result._fetchone_impl(hard_close=hard_close)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1684, in _fetchone_impl
superset_app           |     row = next(self.iterator, _NO_ROW)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
superset_app           |     fetch = cursor._raw_all_rows()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
superset_app           |     return [make_row(row) for row in rows]
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
superset_app           |     return [make_row(row) for row in rows]
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 1681, in process
superset_app           |     return process_value(impl_processor(value), dialect)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 479, in process_result_value
superset_app           |     value = super().process_result_value(value=value, dialect=dialect)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 424, in process_result_value
superset_app           |     decrypted_value = self.engine.decrypt(value)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
superset_app           |     raise ValueError('Invalid decryption key')
superset_app           | ValueError: Invalid decryption key
```

**Comment by alberttwong** [comment]
issue was that I was running dev instance.  Need to run non-dev `docker-compose -f docker-compose-non-dev.yml pull`

**Comment by lllong33** [comment]
FYI https://github.com/apache/superset/issues/8538#issuecomment-1073039913
