### ISSUE TITLE
superset db upgrade crashes on fresh install

### ISSUE THREAD

**Issue by jwoehr** [apache/superset#24699]
#### How to reproduce the bug

1. Follow instructions for Linux* on https://superset.apache.org/docs/installation/installing-superset-from-scratch/
2. Install prerequistes
3. Create virtual environment and activate
4. Install Apache Superset in virt env
5. execute `superset db upgrade`

*Linux pop-os 6.2.6-76060206-generic #202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux

### Expected results

normal operation

### Actual results
_starting from final output of `pip install apache-superset`_
```
Successfully installed Flask-Babel-2.0.0 Flask-JWT-Extended-4.5.2 Flask-Limiter-3.3.1 Flask-SQLAlchemy-2.5.1 Mako-1.2.4 PyJWT-2.7.0 PySocks-1.7.1 Werkzeug-2.3.6 alembic-1.11.1 amqp-5.1.1 apache-superset-2.1.0 apispec-6.3.0 async-timeout-4.0.2 backoff-2.2.1 bcrypt-4.0.1 billiard-4.1.0 bleach-3.3.1 cachelib-0.4.1 celery-5.3.1 certifi-2023.5.7 click-8.1.5 click-didyoumean-0.3.0 click-plugins-1.1.1 click-repl-0.3.0 convertdate-2.4.0 cron-descriptor-1.4.0 croniter-1.4.1 cryptography-39.0.2 deprecated-1.2.14 deprecation-2.1.0 dnspython-2.3.0 email-validator-1.3.1 flask-2.1.3 flask-appbuilder-4.3.4 flask-caching-1.10.1 flask-compress-1.13 flask-login-0.6.0 flask-migrate-3.1.0 flask-talisman-1.0.0 flask-wtf-1.0.1 func_timeout-4.3.5 geographiclib-2.0 geopy-2.3.0 graphlib-backport-1.0.3 greenlet-2.0.2 gunicorn-20.1.0 h11-0.14.0 hashids-1.3.1 hijri-converter-2.3.1 holidays-0.17.2 humanize-4.7.0 importlib-resources-6.0.0 isodate-0.6.1 itsdangerous-2.1.2 kombu-5.3.1 korean-lunar-calendar-0.3.1 limits-3.5.0 markdown-3.4.3 markdown-it-py-3.0.0 marshmallow-sqlalchemy-0.26.1 mdurl-0.1.2 numpy-1.23.5 ordered-set-4.1.0 outcome-1.2.0 pandas-1.5.3 paramiko-3.2.0 parsedatetime-2.6 pgsanity-0.2.9 polyline-2.0.0 prison-0.2.1 prompt-toolkit-3.0.39 pyarrow-10.0.1 pygments-2.15.1 pymeeus-0.5.12 pyparsing-3.1.0 python-dotenv-1.0.0 python-geohash-0.8.5 redis-4.6.0 rich-13.4.2 selenium-4.10.0 simplejson-3.19.1 slack_sdk-3.21.3 sqlalchemy-1.4.49 sqlalchemy-utils-0.38.3 sqlparse-0.4.4 sshtunnel-0.4.0 tabulate-0.8.10 trio-0.22.2 trio-websocket-0.10.3 tzdata-2023.3 vine-5.0.0 wsproto-1.2.0 wtforms-2.3.3 wtforms-json-0.3.5 xlsxwriter-3.0.9
(superset_venv) jwoehr@pop-os:~/work/Apache$ superset db upgrade
Traceback (most recent call last):
  File "/home/jwoehr/work/Apache/superset_venv/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/home/jwoehr/work/Apache/superset_venv/lib/python3.10/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/home/jwoehr/work/Apache/superset_venv/lib/python3.10/site-packages/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/home/jwoehr/work/Apache/superset_venv/lib/python3.10/site-packages/superset/initialization/__init__.py", line 33, in <module>
    from superset.extensions import (
  File "/home/jwoehr/work/Apache/superset_venv/lib/python3.10/site-packages/superset/extensions/__init__.py", line 32, in <module>
    from superset.utils.async_query_manager import AsyncQueryManager
  File "/home/jwoehr/work/Apache/superset_venv/lib/python3.10/site-packages/superset/utils/async_query_manager.py", line 26, in <module>
    from superset.utils.core import get_user_id
  File "/home/jwoehr/work/Apache/superset_venv/lib/python3.10/site-packages/superset/utils/core.py", line 106, in <module>
    from superset.sql_parse import sanitize_clause
  File "/home/jwoehr/work/Apache/superset_venv/lib/python3.10/site-packages/superset/sql_parse.py", line 67, in <module>
    re.compile(r"'(''|\\\\|\\|[^'])*'", sqlparse.keywords.FLAGS).match,
AttributeError: module 'sqlparse.keywords' has no attribute 'FLAGS'
```

### Environment

(please complete the following information):

- browser type and version: n/a
- superset version: 2.1.0
- python version: 3.10.6
- node.js version: v18.16.1
- any feature flags active: n/a

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any. _Don't know where they are located_
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jwoehr** [comment]
Duplicate of  #23742
