### ISSUE TITLE
Superset REST API Bug with latest Helm Chart Deployment

### ISSUE THREAD

**Issue by keenborder786** [apache/superset#24800]
#### How to reproduce the bug

I am using the latest helm chart release to install the superset on my local machine. However, when I forward a GET request to the following endpoint: http://localhost:8088/api/v1/database/_info. I am getting the following error:

```
{error:"'encrypted_extra'"}
```

### Expected results

I tried other _info endpoints as well e.g http://localhost:8088/api/v1/dataset/_info and it works fine returning me the info about the CRUD model and security

### Environment

- browser type and version: FireFox 115.0.2 (64-bit)
- superset version: 2.1.0
- python version: 3.9.1.5
- node.js version: v12.22.9
- superset-helm-chart version: 0.10.5

### Additional context
Kubernetes Version: 
```json
{
  "clientVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.0",
    "gitCommit": "a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2",
    "gitTreeState": "clean",
    "buildDate": "2022-08-23T17:44:59Z",
    "goVersion": "go1.19",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.3",
    "gitCommit": "434bfd82814af038ad94d62ebe59b133fcb50506",
    "gitTreeState": "clean",
    "buildDate": "2022-10-12T10:49:09Z",
    "goVersion": "go1.19.2",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

```
helm version: v3.11.3

**Comment by keenborder786** [comment]
Just an update: I also tried the docker deployment and the same bug persist their as well.

**Comment by michael-s-molina** [comment]
@dpgaspar Could you check this? I can reproduce the error on master.

**Comment by rusackas** [comment]
Is anyone still facing this in supported versions of Superset (3.1/4.0) on newer Helm charts? This is at risk of being closed as stale/obsolete if not.

CC @villebro @craig-rueda like I always do for helm-related issues ;)

**Comment by snowch** [comment]
I have the same issue with docker compose:

- https://github.com/apache/superset/blob/master/docker-compose-image-tag.yml 
- 4.0.2

**Comment by rad-pat** [comment]
I just experienced this on 5.0.0RC1 using the swagger UI
Relevant Traceback:
```
2025-02-25 10:24:52,224:ERROR:superset.views.error_handling:'encrypted_extra'
Traceback (most recent call last):
  File "/app/superset/views/error_handling.py", line 101, in wraps
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/views/base_api.py", line 459, in info_headless
    duration, response = time_function(super().info_headless, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/superset/utils/core.py", line 1363, in time_function
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask_appbuilder/api/__init__.py", line 1380, in info_headless
    self.set_response_key_mappings(payload, self.info, rison_args, **rison_args)
  File "/app/.venv/lib/python3.11/site-packages/flask_appbuilder/api/__init__.py", line 753, in set_response_key_mappings
    v(self, response, **kwargs)
  File "/app/.venv/lib/python3.11/site-packages/flask_appbuilder/api/__init__.py", line 1273, in merge_add_field_info
    response[API_ADD_COLUMNS_RES_KEY] = self._get_fields_info(
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask_appbuilder/api/__init__.py", line 2045, in _get_fields_info
    model_schema.fields[col],
    ~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'encrypted_extra'
```

**Comment by rusackas** [comment]
Pinging @dosu for any helpful insight here.

**Comment by rusackas** [comment]
Closing this issue as PR #32339 (merged Feb 2025) addressed encrypted_extra schema handling, which appears to be the root cause of this bug.

If you're still experiencing this issue on Superset 5.x or 6.x, please open a new issue with reproduction steps and we'll investigate further.

Thanks for the report!
