### ISSUE TITLE
Regarding Secret Key updation in config.py

### ISSUE THREAD

**Issue by Vishnuv0595** [apache/superset#24822]
As we noted a vulnerability report to using the default secret key , so we have tried to change the same inside container and started the container and while click on the dashboard we have got issues. While check the databases nothing is visible there.

changed File:
superset/c

#### How to reproduce the bug

Just click any of the dashboard we will get error like "Error loading chart datasources. Filters may not work correctly" and not listing of already connected datasource/database.

what you expected to happen.

We expected to fix the vulnerability and load the pages post editing the config.py file .

### Actual results
We have changed the secret value in config.py as suggested in the installation which resulted in disconnection with already configured Database and Datasets

![image](https://github.com/apache/superset/assets/93530902/78134670-c3de-4072-b35c-f8aac0f543e1)

### Environment

(please complete the following information):

- browser type and version: chrome and Version 115.0.5790.110
- superset version: v0.0.0 dev

Below the logs from the superset-app container:

0.0..29.125 - - [27/Jul/2023:09:15:13 +0000] "GET /static/assets/741a23480265c33a0606.chunk.js HTTP/1.1" 200 7208 "https://supersets.example.com/savedqueryview/list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:13 +0000] "GET /api/v1/saved_query/distinct/schema?q=() HTTP/1.1" 200 262 "https://supersets.example.com/savedqueryview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
2023-07-27 09:15:13,656:ERROR:root:Invalid decryption key
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 126, in decrypt
    decrypted = decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 85, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 82, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1460, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 155, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 511, in related
    filters, order_column, order_direction, page=page, page_size=page_size
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 435, in query
    query_results = query.all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 588, in _instance
    populators,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1278, in process
    return process_value(impl_processor(value), dialect)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 469, in process_result_value
    value = super().process_result_value(value=value, dialect=dialect)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 414, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
    raise ValueError('Invalid decryption key')
ValueError: Invalid decryption key
0.0..29.125 - - [27/Jul/2023:09:15:13 +0000] "GET /api/v1/saved_query/related/database?q=() HTTP/1.1" 500 26 "https://supersets.example.com/savedqueryview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:13 +0000] "GET /api/v1/saved_query/_info?q=(keys:!(permissions)) HTTP/1.1" 200 41 "https://supersets.example.com/savedqueryview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:16 +0000] "GET /static/assets/93c392794861aae738ba.chunk.js HTTP/1.1" 200 816 "https://supersets.example.com/superset/sqllab/history/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:17 +0000] "GET /api/v1/saved_query/?q=(order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:25) HTTP/1.1" 200 12751 "https://supersets.example.com/savedqueryview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:20 +0000] "GET /superset/sqllab/history/ HTTP/1.1" 200 26288 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:21 +0000] "GET /static/assets/885a3e8b6bf6b030ad85.chunk.js HTTP/1.1" 200 5261 "https://supersets.example.com/superset/sqllab/history/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:21 +0000] "GET /api/v1/query/related/user?q=() HTTP/1.1" 200 304 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:21 +0000] "GET /api/v1/query/distinct/status?q=() HTTP/1.1" 200 169 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0Safari/537.36"
2023-07-27 09:15:21,788:ERROR:root:Invalid decryption key
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 126, in decrypt
    decrypted = decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 85, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 82, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1460, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 155, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 511, in related
    filters, order_column, order_direction, page=page, page_size=page_size
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 435, in query
    query_results = query.all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 588, in _instance
    populators,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1278, in process
    return process_value(impl_processor(value), dialect)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 469, in process_result_value
    value = super().process_result_value(value=value, dialect=dialect)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 414, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
    raise ValueError('Invalid decryption key')
ValueError: Invalid decryption key
0.0..29.125 - - [27/Jul/2023:09:15:21 +0000] "GET /api/v1/query/related/database?q=() HTTP/1.1" 500 26 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:21 +0000] "GET /api/v1/query/?q=(order_column:start_time,order_direction:desc,page:0,page_size:25) HTTP/1.1" 200 2693 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:22 +0000] "GET /static/assets/9e6404dbca5867ddf89e.chunk.js HTTP/1.1" 200 821 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:22 +0000] "GET /static/assets/8eebc49882389ea84e2c.chunk.js HTTP/1.1" 200 718 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
127.0.0.1 - - [27/Jul/2023:09:15:23 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.64.0"
0.0..29.125 - - [27/Jul/2023:09:15:28 +0000] "GET /superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc HTTP/1.1" 200 26289 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
2023-07-27 09:15:29,511:ERROR:root:Invalid decryption key
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 126, in decrypt
    decrypted = decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 85, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 82, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1460, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 155, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 511, in related
    filters, order_column, order_direction, page=page, page_size=page_size
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 435, in query
    query_results = query.all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 588, in _instance
    populators,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1278, in process
    return process_value(impl_processor(value), dialect)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 469, in process_result_value
    value = super().process_result_value(value=value, dialect=dialect)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 414, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
    raise ValueError('Invalid decryption key')
ValueError: Invalid decryption key
0.0..29.125 - - [27/Jul/2023:09:15:29 +0000] "GET /api/v1/query/related/database?q=() HTTP/1.1" 500 26 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:29 +0000] "GET /api/v1/query/distinct/status?q=() HTTP/1.1" 200 169 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:29 +0000] "GET /api/v1/query/related/user?q=() HTTP/1.1" 200 304 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.125 - - [27/Jul/2023:09:15:29 +0000] "GET /api/v1/query/?q=(order_column:start_time,order_direction:desc,page:0,page_size:25) HTTP/1.1" 200 2693 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.135 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.59 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.76 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.51 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.10 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.83 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.165 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.32 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.125 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.167 - - [27/Jul/2023:09:15:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.125 - - [27/Jul/2023:09:15:45 +0000] "GET /api/v1/query/distinct/status?q=(page:1) HTTP/1.1" 200 24 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
127.0.0.1 - - [27/Jul/2023:09:15:54 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.64.0"
0.0..29.125 - - [27/Jul/2023:09:16:02 +0000] "GET /api/v1/query/related/user?q=(page:1) HTTP/1.1" 200 317 "https://supersets.example.com/superset/sqllab/history/?pageIndex=0&sortColumn=start_time&sortOrder=desc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
0.0..29.135 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.59 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.76 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.51 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.10 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.83 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.165 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.32 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.125 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.167 - - [27/Jul/2023:09:16:12 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
127.0.0.1 - - [27/Jul/2023:09:16:24 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.64.0"
0.0..29.135 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.76 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.59 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.51 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.10 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.83 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.165 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.32 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.125 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
0.0..29.167 - - [27/Jul/2023:09:16:42 +0000] "GET / HTTP/1.1" 302 243 "-" "ELB-HealthChecker/2.0"
2023-07-27 09:16:48,191:ERROR:root:Invalid decryption key
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 126, in decrypt
    decrypted = decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 85, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 82, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1460, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 155, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 511, in related
    filters, order_column, order_direction, page=page, page_size=page_size
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 435, in query
    query_results = query.all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 588, in _instance
    populators,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1278, in process
    return process_value(impl_processor(value), dialect)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 469, in process_result_value
    value = super().process_result_value(value=value, dialect=dialect)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 414, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
    raise ValueError('Invalid decryption key')
ValueError: Invalid decryption key

From the logs removed the actual end point

**Comment by Vishnuv0595** [comment]
We are stuck on this issue in our production environment, please let me know is there any workaround to fix the mentioned issue.

**Comment by chandrasekharjandhyam** [comment]
@Vishnuv0595 please do this as mentioned in [https://superset.apache.org/docs/installation/configuring-superset/#specifying-a-secret_key].

**Comment by rusackas** [comment]
@Vishnuv0595 hopefully the advice from the last comment worked? Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
