### ISSUE TITLE
Guest token errors out for embeds when using dashboard slug

### ISSUE THREAD

**Issue by lindenh** [apache/superset#24869]
Guest tokens cause errors when created with the slug of a dashboard. The guest token is successfully created (when they wouldn't be for an invalid id or slug), but is somewhere being compared as an integer, causing an error on embeds.

#### How to reproduce the bug

1. Turn on embedded dashboards
2. Create a dashboard with a custom slug
3. Create a guest token for that dashboard using the slug
4. Embed a dashboard using the embed sdk using that guest token
5. See the error in place of the embed

### Expected results

Dashboard embed should load, guest token should work with slug if slug is allowed to be used to create the guest token.

### Actual results

"Unexpected error" box displays in place of embed, logs show up on superset:

```
superset_app           | [SQL: SELECT EXISTS (SELECT 1
superset_app           | FROM ab_permission_view JOIN ab_permission_view_role ON ab_permission_view.id = ab_permission_view_role.permission_view_id JOIN ab_role ON ab_role.id = ab_permission_view_role.role_id JOIN ab_permission ON ab_permission.id = ab_permission_view.permission_id JOIN ab_view_menu ON ab_view_menu.id = ab_permission_view.view_menu_id
superset_app           | WHERE ab_view_menu.name = %(name_1)s AND ab_permission.name = %(name_2)s AND ab_role.id IN (%(id_1_1)s)) AS anon_1]
superset_app           | [parameters: {'name_1': 'all_datasource_access', 'name_2': 'all_datasource_access', 'id_1_1': 6}]
superset_app           | (Background on this error at: https://sqlalche.me/e/14/2j85)
superset_app           | Traceback (most recent call last):
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
superset_app           |     self.dialect.do_execute(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
superset_app           |     cursor.execute(statement, parameters)
superset_app           | psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "demo-dash"
superset_app           | LINE 9: ...ar.class_name = 'Dashboard') OR dashboards.id IN ('demo-dash...
superset_app           |                                                              ^
superset_app           |
superset_app           |
superset_app           | The above exception was the direct cause of the following exception:
superset_app           |
superset_app           | Traceback (most recent call last):
superset_app           |   File "/app/superset/utils/cache.py", line 181, in wrapper
superset_app           |     raise_for_access(*args, **kwargs)
superset_app           |   File "/app/superset/dashboards/api.py", line 357, in <lambda>
superset_app           |     raise_for_access=lambda _self, id_or_slug: DashboardDAO.get_by_id_or_slug(
superset_app           |   File "/app/superset/daos/dashboard.py", line 75, in get_by_id_or_slug
superset_app           |     dashboard = query.one_or_none()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
superset_app           |     return self._iter().one_or_none()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
superset_app           |     result = self.session.execute(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
superset_app           |     result = conn._execute_20(statement, params or {}, execution_options)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
superset_app           |     return meth(self, args_10style, kwargs_10style, execution_options)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
superset_app           |     return connection._execute_clauseelement(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
superset_app           |     ret = self._execute_context(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
superset_app           |     self._handle_dbapi_exception(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
superset_app           |     util.raise_(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
superset_app           |     raise exception
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
superset_app           |     self.dialect.do_execute(
superset_app           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
superset_app           |     cursor.execute(statement, parameters)
superset_app           | sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "demo-dash"
superset_app           | LINE 9: ...ar.class_name = 'Dashboard') OR dashboards.id IN ('demo-dash...
```

#### Screenshots

Browser console:
<img width="788" alt="image" src="https://github.com/apache/superset/assets/23485913/b5e39f8a-1947-4502-a78d-69075b4cb75d">

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: EMBEDDED_SUPERSET

Tested off master pulled yesterday.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Seems like this was an issue in the Superset 2.0 era. Is it still an issue in 3.x?

**Comment by rusackas** [comment]
Closing as stale since we don't know if it was an issue in 3.0, much less 4.x which is what we'll be supporting upon the imminent release of 4.1. Happy to revisit/reopen if this is still an issue in newer versions.

**Comment by Alejandroid17** [comment]
Same problem in version 6.0.0
