### ISSUE TITLE
getting CSRF token issue while loading the superset using docker-compose

### ISSUE THREAD

**Issue by nk8291** [apache/superset#25079]
Dear Team,

I am trying to setup the superset on centos server. 

Below is the configurations and tools available on server:

python 3.7 
postgresql 14

used below command to setup superset:

git clone https://github.com/apache/superset.git
cd superset
docker-compose -f docker-compose-non-dev.yml pull
docker-compose -f docker-compose-non-dev.yml up

now when I try to login to superset url using admin / admin getting below error in terminal:

********************************************************** ERROR *************************************************
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in full_dispatch_request
superset_app            |     rv = self.preprocess_request()
superset_app            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2313, in preprocess_request
superset_app            |     rv = self.ensure_sync(before_func)()
superset_app            |   File "/usr/local/lib/python3.9/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
superset_app            |     self.protect()
superset_app            |   File "/usr/local/lib/python3.9/site-packages/flask_wtf/csrf.py", line 264, in protect
superset_app            |     self._error_response(e.args[0])
superset_app            |   File "/usr/local/lib/python3.9/site-packages/flask_wtf/csrf.py", line 307, in _error_response
superset_app            |     raise CSRFError(reason)
superset_app            | flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
superset_app            | Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
superset_app            | 174.112.226.87 - - [24/Aug/2023:20:31:13 +0000] "POST /login/ HTTP/1.1" 302 201 "http://20.246.16.88:8088/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
superset_app            | Unable to load SQLAlchemy dialect <class 'pydruid.db.sqlalchemy.DruidHTTPSDialect'>: No module named 'google'
superset_app            | 2023-08-24 20:31:13,406:WARNING:superset.db_engine_specs:Unable to load SQLAlchemy dialect <class 'pydruid.db.sqlalchemy.DruidHTTPSDialect'>: No module named 'google'
***************************************************************************************************************************************************

![image](https://github.com/apache/superset/assets/62594274/c84a58a0-6a71-4f6b-b8a2-5ff05ea3947c)

can someone assist in fixing this issues and understanding the root cause of the same.

**Comment by luongdolong** [comment]
@nk8291 I got the same error as you

**Comment by michael-s-molina** [comment]
Hi @nk8291. You're using the `master` version of Superset which requires Python 3.9. You can check the dependencies in [setup.py](https://github.com/apache/superset/blob/master/setup.py) file.

If you're interested in using Superset for production environments, I recommend using an official release. The latest one is 2.1.0 (2.1.1 and 3.0.0 are almost out). You can follow [this guide](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/#configuring-docker-compose) to do a `docker compose` using a specific tag.

**Comment by KSPT-taylorjohn** [comment]
Hi @michael-s-molina ,  I believe @nk8291 mistakenly wrote that it is python 3.7 .   He's running in docker and you see in the logs it is /usr/local/lib/python3.9.

I had the same problem running in docker and setting TALISMAN_ENABLED = False  in superset_config.py  is what worked for me.
I don't know the root cause.

**Comment by michael-s-molina** [comment]
> Hi @michael-s-molina , I believe @nk8291 mistakenly wrote that it is python 3.7 . He's running in docker and you see in the logs it is /usr/local/lib/python3.9.

Thank you @KSPT-taylorjohn for the eagle eyes! 

> I had the same problem running in docker and setting TALISMAN_ENABLED = False in superset_config.py is what worked for me.

@nk8291 I still recommend using an official release for production environments. If you do want to use the master version, @KSPT-taylorjohn's suggestion might be the solution. See https://github.com/apache/superset/issues/24579.

**Comment by anantmulchandani** [comment]
> Hi @michael-s-molina , I believe @nk8291 mistakenly wrote that it is python 3.7 . He's running in docker and you see in the logs it is /usr/local/lib/python3.9.
> 
> I had the same problem running in docker and setting TALISMAN_ENABLED = False in superset_config.py is what worked for me. I don't know the root cause.

Hi @KSPT-taylorjohn 

In the current master branch I don't find the variable TALISMAN_ENABLED. Can you please help in this regard?

**Comment by anantmulchandani** [comment]
> Hi @michael-s-molina , I believe @nk8291 mistakenly wrote that it is python 3.7 . He's running in docker and you see in the logs it is /usr/local/lib/python3.9.
> 
> I had the same problem running in docker and setting TALISMAN_ENABLED = False in superset_config.py is what worked for me. I don't know the root cause.

Hi @KSPT-taylorjohn 
I checked the boolean 'TALISMAN_ENABLED' in the Superset application container using the following commands:
`docker exec -it <superset_app's Container ID> /bin/bash
superset shell
>>> from flask import current_app
>>> print(current_app.config["TALISMAN_ENABLED"])`

This gave the value of TALISMAN_ENABLED as False. Yet I face the same above issue.
Can you please help in this regard?

**Comment by nk8291** [comment]
Hi, the issue is fixed.

I have updated below step in yml file to provide the stable superset container image, which 2.1

x-superset-image: &superset-image apache/superset:2.1.0

![image](https://github.com/apache/superset/assets/62594274/49022810-4410-4b9b-8c97-2fa3a8e99107)
