### ISSUE TITLE
Alerts and Reports giving an error when Message content is not the first created Dashboard

### ISSUE THREAD

**Issue by livwel-populus** [apache/superset#25188]
Docker logs giving Selenium timeout error when trying to run an alert or report on a dashboard which was not the first dashboard created

#### How to reproduce the bug

1. Create two different dashboards and populate with charts
2. Create an alert or report with the Message content being the second dashboard created
3. Trigger the alert or report

Note: This error does not occur if the Message content is the first dashboard created

### Expected results

The report should run without errors.

### Actual results

I get the following error in docker logs:
```
[2023-09-05 17:56:00,088: INFO/ForkPoolWorker-15] Running report schedule afac7fe8-789e-45f2-891c-030ad1f7fd18 as user admin
[2023-09-05 17:56:00,107: DEBUG/ForkPoolWorker-15] Init selenium driver
[2023-09-05 17:56:02,905: DEBUG/ForkPoolWorker-15] Sleeping for 3 seconds
[2023-09-05 17:56:05,909: DEBUG/ForkPoolWorker-15] Wait for the presence of standalone at url: https://dwap.populus.plus/superset/dashboard/836ef1d0-29b9-488d-baa1-ccafd4cfdc7f/?force=false&standalone=3
[2023-09-05 17:56:16,006: ERROR/ForkPoolWorker-15] Selenium timed out requesting url https://dwap.populus.plus/superset/dashboard/836ef1d0-29b9-488d-baa1-ccafd4cfdc7f/?force=false&standalone=3
Traceback (most recent call last):
  File "/app/superset/utils/webdriver.py", line 182, in get_screenshot
    element = WebDriverWait(driver, self._screenshot_locate_wait).until(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

[2023-09-05 17:56:16,381: INFO/ForkPoolWorker-15] Task reports.execute[afac7fe8-789e-45f2-891c-030ad1f7fd18] succeeded in 16.315064600999904s: None
[2023-09-05 17:57:00,051: INFO/MainProcess] Task reports.scheduler[c1bcaae5-f6db-4642-9714-f80205beb7c7] received
[2023-09-05 17:57:00,063: INFO/ForkPoolWorker-15] Task reports.scheduler[c1bcaae5-f6db-4642-9714-f80205beb7c7] succeeded in 0.01118651700016926s: None
```

Superset gives the following Error message:
`Report Schedule execution failed when generating a screenshot.`

### Environment

browser type and version: Chrome
superset version: 3.0.0rc3
python version: 3.11.4
node.js version: v18.16.0
any feature flags active:
FEATURE_FLAGS = {"ALERT_REPORTS": True}

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
I'm going to close this.  If you're able to replicate this on 3.0.0 (ideally) or at least provide the additional information above, this could be reopened.

**Comment by dongsheng88** [comment]
I meet the same bug。when I configure more than 1 alerts, except for the first alert,the others are not functioning properly.
superset show the error "Report Schedule execution failed when generating a screenshot." 
version：4.0.2
