### ISSUE TITLE
create chart api

### ISSUE THREAD

**Issue by HAsaad7** [apache/superset#25246]
DB engine Error

unhashable type: 'list'

This may be triggered by:
Issue 1011 - Superset encountered an unexpected error.

Please reach out to the Chart Owner for assistance.

Chart Owner: Superset Admin
#### How to reproduce the bug

1. using python code 
2. Create the payload [{'table': 'channels', 'columns': ['topic__creator', 'topic__value'], 'chart': {'viz_type': 'funnel', 'properties': {'name': ' Department', 'params': {'groupby': 'topic__creator', 'metric': [{'expressionType': 'SIMPLE', 'column': {'column_name': 'topic__value'}, 'aggregate': 'MAX', 'label': 'MAX(topic__value)'}]}}}}]
3. send it by an endpoint req.

### Expected results
chart created successfully
what you expected to happen.
open the localhost and found my chart

what actually happens.
engine Error

unhashable type: 'list'

This may be triggered by:
Issue 1011 - 
2023-09-10 12:05:16 Traceback (most recent call last):
2023-09-10 12:05:16   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023-09-10 12:05:16     rv = self.dispatch_request()
2023-09-10 12:05:16   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
2023-09-10 12:05:16     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-09-10 12:05:16   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
2023-09-10 12:05:16     return f(self, *args, **kwargs)
2023-09-10 12:05:16   File "/app/superset/views/base_api.py", line 127, in wraps
2023-09-10 12:05:16     raise ex
2023-09-10 12:05:16   File "/app/superset/views/base_api.py", line 121, in wraps
2023-09-10 12:05:16     duration, response = time_function(f, self, *args, **kwargs)
2023-09-10 12:05:16   File "/app/superset/utils/core.py", line 1525, in time_function
2023-09-10 12:05:16     response = func(*args, **kwargs)
2023-09-10 12:05:16   File "/app/superset/utils/log.py", line 255, in wrapper
2023-09-10 12:05:16     value = f(*args, **kwargs)
2023-09-10 12:05:16   File "/app/superset/charts/data/api.py", line 258, in data
2023-09-10 12:05:16     return self._get_data_response(
2023-09-10 12:05:16   File "/app/superset/charts/data/api.py", line 418, in _get_data_response
2023-09-10 12:05:16     result = command.run(force_cached=force_cached)
2023-09-10 12:05:16   File "/app/superset/charts/data/commands/get_data_command.py", line 45, in run
2023-09-10 12:05:16     payload = self._query_context.get_payload(
2023-09-10 12:05:16   File "/app/superset/common/query_context.py", line 100, in get_payload
2023-09-10 12:05:16     return self._processor.get_payload(cache_query_context, force_cached)
2023-09-10 12:05:16   File "/app/superset/common/query_context_processor.py", line 588, in get_payload
2023-09-10 12:05:16     query_results = [
2023-09-10 12:05:16   File "/app/superset/common/query_context_processor.py", line 589, in <listcomp>
2023-09-10 12:05:16     get_query_results(
2023-09-10 12:05:16   File "/app/superset/common/query_actions.py", line 225, in get_query_results
2023-09-10 12:05:16     return result_func(query_context, query_obj, force_cached)
2023-09-10 12:05:16   File "/app/superset/common/query_actions.py", line 103, in _get_full
2023-09-10 12:05:16     payload = query_context.get_df_payload(query_obj, force_cached=force_cached)
2023-09-10 12:05:16   File "/app/superset/common/query_context.py", line 121, in get_df_payload
2023-09-10 12:05:16     return self._processor.get_df_payload(
2023-09-10 12:05:16   File "/app/superset/common/query_context_processor.py", line 157, in get_df_payload
2023-09-10 12:05:16     query_result = self.get_query_result(query_obj)
2023-09-10 12:05:16   File "/app/superset/common/query_context_processor.py", line 235, in get_query_result
2023-09-10 12:05:16     result = query_context.datasource.query(query_object.to_dict())
2023-09-10 12:05:16   File "/app/superset/connectors/sqla/models.py", line 1178, in query
2023-09-10 12:05:16     query_str_ext = self.get_query_str_extended(query_obj)
2023-09-10 12:05:16   File "/app/superset/connectors/sqla/models.py", line 842, in get_query_str_extended
2023-09-10 12:05:16     sqlaq = self.get_sqla_query(**query_obj)
2023-09-10 12:05:16   File "/app/superset/models/helpers.py", line 1561, in get_sqla_query
2023-09-10 12:05:16     elif col in columns_by_name:
2023-09-10 12:05:16 TypeError: unhashable type: 'list'
2023-09-10 12:05:16 2023-09-10 10:05:16,512:ERROR:superset.views.base:unhashable type: 'list'
2023-09-10 12:05:16 Traceback (most recent call last):
2023-09-10 12:05:16   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023-09-10 12:05:16     rv = self.dispatch_request()
2023-09-10 12:05:16   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
2023-09-10 12:05:16     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-09-10 12:05:16   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
2023-09-10 12:05:16     return f(self, *args, **kwargs)
2023-09-10 12:05:16   File "/app/superset/views/base_api.py", line 127, in wraps
2023-09-10 12:05:16     raise ex
2023-09-10 12:05:16   File "/app/superset/views/base_api.py", line 121, in wraps
2023-09-10 12:05:16     duration, response = time_function(f, self, *args, **kwargs)
2023-09-10 12:05:16   File "/app/superset/utils/core.py", line 1525, in time_function
2023-09-10 12:05:16     response = func(*args, **kwargs)
2023-09-10 12:05:16   File "/app/superset/utils/log.py", line 255, in wrapper
2023-09-10 12:05:16     value = f(*args, **kwargs)
2023-09-10 12:05:16   File "/app/superset/charts/data/api.py", line 258, in data
2023-09-10 12:05:16     return self._get_data_response(
2023-09-10 12:05:16   File "/app/superset/charts/data/api.py", line 418, in _get_data_response
2023-09-10 12:05:16     result = command.run(force_cached=force_cached)
2023-09-10 12:05:16   File "/app/superset/charts/data/commands/get_data_command.py", line 45, in run
2023-09-10 12:05:16     payload = self._query_context.get_payload(
2023-09-10 12:05:16   File "/app/superset/common/query_context.py", line 100, in get_payload
2023-09-10 12:05:16     return self._processor.get_payload(cache_query_context, force_cached)
2023-09-10 12:05:16   File "/app/superset/common/query_context_processor.py", line 588, in get_payload
2023-09-10 12:05:16     query_results = [
2023-09-10 12:05:16   File "/app/superset/common/query_context_processor.py", line 589, in <listcomp>
2023-09-10 12:05:16     get_query_results(
2023-09-10 12:05:16   File "/app/superset/common/query_actions.py", line 225, in get_query_results
2023-09-10 12:05:16     return result_func(query_context, query_obj, force_cached)
2023-09-10 12:05:16   File "/app/superset/common/query_actions.py", line 103, in _get_full
2023-09-10 12:05:16     payload = query_context.get_df_payload(query_obj, force_cached=force_cached)
2023-09-10 12:05:16   File "/app/superset/common/query_context.py", line 121, in get_df_payload
2023-09-10 12:05:16     return self._processor.get_df_payload(
2023-09-10 12:05:16   File "/app/superset/common/query_context_processor.py", line 157, in get_df_payload
2023-09-10 12:05:16     query_result = self.get_query_result(query_obj)
2023-09-10 12:05:16   File "/app/superset/common/query_context_processor.py", line 235, in get_query_result
2023-09-10 12:05:16     result = query_context.datasource.query(query_object.to_dict())
2023-09-10 12:05:16   File "/app/superset/connectors/sqla/models.py", line 1178, in query
2023-09-10 12:05:16     query_str_ext = self.get_query_str_extended(query_obj)
2023-09-10 12:05:16   File "/app/superset/connectors/sqla/models.py", line 842, in get_query_str_extended
2023-09-10 12:05:16     sqlaq = self.get_sqla_query(**query_obj)
2023-09-10 12:05:16   File "/app/superset/models/helpers.py", line 1561, in get_sqla_query
2023-09-10 12:05:16     elif col in columns_by_name:
2023-09-10 12:05:16 TypeError: unhashable type: 'list'
#### Screenshots
![image](https://github.com/apache/superset/assets/139969563/cdd5cbe4-bd53-4c5a-9a38-48af02f06247)

### Environment
superset docker

- browser type and version: firefox
- python version: `python --3.11`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [. ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ .] I have reproduced the issue with at least the latest released version of superset.
- [ .] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
It's been a good long while since this was last touched. Anyone still facing this? If not, it'll be closed as stale. 

Meanwhile, maybe @dosu-bot has some ideas here :)

**Comment by rusackas** [comment]
Closing as stale, but happy to revisit/reopen if we can get some updated context here.
