### ISSUE TITLE
can't edit existing dataset to add a column "Multiple rows were found when one or none was required"

### ISSUE THREAD

**Issue by louisjanin** [apache/superset#25281]
As admin, I go to datasets, click on edit and sync columns from datasource which works well as I get notified metadata was synced and my new column wad added.
But when I save, I get this error "Multiple rows were found when one or none was required"

- superset version: 2.1.1

Any idea why ?
I can still query my new column from sql lab so I guess the db connection is ok
![Screenshot from 2023-09-13 12-22-46](https://github.com/apache/superset/assets/16646642/c9bc3f6b-6747-40eb-911b-27a5d2d92bd3)

```Multiple rows were found when one or none was required
Traceback (most recent call last):
  File "/home/louis/venv/lib/python3.9/site-packages/superset/views/base.py", line 250, in wraps
    return f(self, *args, **kwargs)
  File "/home/louis/venv/lib/python3.9/site-packages/superset/views/datasource/views.py", line 127, in save
    data = orm_datasource.data
  File "/home/louis/venv/lib/python3.9/site-packages/superset/connectors/sqla/models.py", line 794, in data
    data_ = super().data
  File "/home/louis/venv/lib/python3.9/site-packages/superset/connectors/base/models.py", line 271, in data
    "database": self.database.data,  # pylint: disable=no-member
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 487, in __get__
    return self.impl.get(state, dict_)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 959, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 995, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
    return self._emit_lazyload(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 996, in _emit_lazyload
    return loading.load_on_pk_identity(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1665, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2253, in _autoflush
    self.flush()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 253, in save_obj
    _finalize_insert_update_commands(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1568, in _finalize_insert_update_commands
    mapper.dispatch.after_update(mapper, connection, state)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 334, in __call__
    fn(*args, **kw)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/home/louis/venv/lib/python3.9/site-packages/superset/connectors/sqla/models.py", line 2282, in after_update
    session.query(NewDataset).filter_by(uuid=sqla_table.uuid).one_or_none()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1510, in one_or_none
    return self._only_one_row(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
2023-09-13 12:29:54,394:ERROR:superset.views.base:Multiple rows were found when one or none was required
Traceback (most recent call last):
  File "/home/louis/venv/lib/python3.9/site-packages/superset/views/base.py", line 250, in wraps
    return f(self, *args, **kwargs)
  File "/home/louis/venv/lib/python3.9/site-packages/superset/views/datasource/views.py", line 127, in save
    data = orm_datasource.data
  File "/home/louis/venv/lib/python3.9/site-packages/superset/connectors/sqla/models.py", line 794, in data
    data_ = super().data
  File "/home/louis/venv/lib/python3.9/site-packages/superset/connectors/base/models.py", line 271, in data
    "database": self.database.data,  # pylint: disable=no-member
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 487, in __get__
    return self.impl.get(state, dict_)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 959, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 995, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
    return self._emit_lazyload(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 996, in _emit_lazyload
    return loading.load_on_pk_identity(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1665, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2253, in _autoflush
    self.flush()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 253, in save_obj
    _finalize_insert_update_commands(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1568, in _finalize_insert_update_commands
    mapper.dispatch.after_update(mapper, connection, state)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 334, in __call__
    fn(*args, **kw)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/home/louis/venv/lib/python3.9/site-packages/superset/connectors/sqla/models.py", line 2282, in after_update
    session.query(NewDataset).filter_by(uuid=sqla_table.uuid).one_or_none()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1510, in one_or_none
    return self._only_one_row(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
2023-09-13 12:29:54,395:ERROR:root:DBEventLogger failed to log event(s)
2023-09-13 12:29:54,395:ERROR:root:This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Multiple rows were found when one or none was required (Background on this error at: https://sqlalche.me/e/14/7s2a)
Traceback (most recent call last):
  File "/home/louis/venv/lib/python3.9/site-packages/superset/utils/log.py", line 368, in log
    sesh.bulk_save_objects(logs)
  File "<string>", line 2, in bulk_save_objects
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3705, in bulk_save_objects
    self._bulk_save_mappings(
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3890, in _bulk_save_mappings
    transaction = self.begin(_subtrans=True)
  File "<string>", line 2, in begin
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1329, in begin
    trans = self._transaction._begin(nested=nested)
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 632, in _begin
    self._assert_active()
  File "/home/louis/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 604, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Multiple rows were found when one or none was required (Background on this error at: https://sqlalche.me/e/14/7s2a)
```
Thanks a lot ! Great tool otherwise

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. Hopefully it's resolved by now, but if it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
