### ISSUE TITLE
psycopg2.errors.ObjectInUse: cannot ALTER TABLE "slices" because it is being used by active queries in this session

### ISSUE THREAD

**Issue by abhinav-bureau** [apache/superset#25335]
I'm deploying superset using helm chart version  superset-0.10.4 and superset version 2.1.0, 
init db pod is failing while running DB migration.  

I have tried above with both standalone Postgres instance on cloud and on k8s well both place it is giving the same error.  

```INFO  [alembic.runtime.migration] Running upgrade 3317e9248280 -> 030c840e3a1c, Add query context to slices
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]

Cleaning up slice uuid from dashboard position json.. Done.

Updated 0 pie chart labels.
0 slices altered

Cleaning up slice uuid from dashboard position json.. Done.

Updated 0 native filter configurations.
Updated 0 filter sets with 0 filters.
Upgraded 0 filters and 0 filter sets.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ObjectInUse: cannot ALTER TABLE "slices" because it is being used by active queries in this session


The above exception was the direct cause of the following exception:
```

These are the package we are installing using pip 
sqlalchemy-redshift 
clickhouse-connect 
PyAthena==2.25.0
 dbapi 
 pyathenajdbc==3.0.1 
 SQLAlchemy==1.4.20 
 apache-superset[cors] 
 timedelta
 authlib

AnyIdea how to fix above issue.

**Comment by mdeshmu** [comment]
maybe there is a running query that has already locked your table and that's why your migration is stuck

SELECT
  activity.pid,
  activity.usename,
  activity.query,
  blocking.pid AS blocking_id,
  blocking.query AS blocking_query
 FROM pg_stat_activity AS activity
 JOIN pg_stat_activity AS blocking ON blocking.pid = ANY(pg_blocking_pids(activity.pid));

Analyze the output of this query to identify blocking queries
You will see one migration-related query blocked by another query (likely not a migration query) that ran before it
Kill non-migration-related query to unblock your migration https://linuxhint.com/postgres-kill-query-pid/

**Comment by abhinav-bureau** [comment]
Hi i tried running the query 
![Uploading Screenshot 2023-11-08 at 5.41.54 PM.png…]()

**Comment by mdeshmu** [comment]
not able to see your screenshot

**Comment by abhinav-bureau** [comment]
This was happening due to an old version of SQLAlchemy, we were using SQLAlchemy==1.4.20 because the newer version was having some issue with athena connector.
