### ISSUE TITLE
superset db upgrade error 

### ISSUE THREAD

**Issue by wwh131** [apache/superset#25365]
鲲鹏arm64机器
(venv) [root@localhost ~]# superset db upgrade
Traceback (most recent call last):
  File "/root/venv/bin/superset", line 11, in <module>
    load_entry_point('apache-superset==1.5.3', 'console_scripts', 'superset')()
  File "/root/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/root/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/root/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/venv/lib64/python3.7/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/root/venv/lib64/python3.7/site-packages/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/root/venv/lib64/python3.7/site-packages/superset/initialization/__init__.py", line 33, in <module>
    from superset.extensions import (
  File "/root/venv/lib64/python3.7/site-packages/superset/extensions/__init__.py", line 116, in <module>
    celery_app = celery.Celery()
  File "/root/venv/lib64/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/root/venv/lib64/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/root/venv/lib64/python3.7/site-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/root/venv/lib64/python3.7/site-packages/celery/utils/__init__.py", line 19, in <module>
    from .nodenames import nodename, nodesplit, worker_direct
  File "/root/venv/lib64/python3.7/site-packages/celery/utils/nodenames.py", line 9, in <module>
    from kombu.entity import Exchange, Queue
  File "/root/venv/lib64/python3.7/site-packages/kombu/entity.py", line 9, in <module>
    from .serialization import prepare_accept_content
  **File "/root/venv/lib64/python3.7/site-packages/kombu/serialization.py", line 456, in <module>
    for ep, args in entrypoints('kombu.serializers'):  # pragma: no cover
  File "/root/venv/lib64/python3.7/site-packages/kombu/utils/compat.py", line 93, in entrypoints
    for ep in importlib_metadata.entry_points().get(namespace, [])
AttributeError: 'EntryPoints' object has no attribute 'get'**
(venv) [root@localhost ~]# python3 --version
Python 3.7.9

**Comment by rusackas** [comment]
I think nobody has helped here because the Issue description template is not filled out, and we don't know how to help. I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
