### ISSUE TITLE
RedisSentinelCache not connecting after upgrade to 3.0

### ISSUE THREAD

**Issue by srinisubramanian** [apache/superset#25386]
I had an existing setup fo Superset 2.1 which I now upgraded to 3.0.  Upgrade was smooth.  Internally I had configured for the RedisSentinelCache.

The config for CACHE_CONFIG and DATA_CACHE_CONFIG are similar:

```
#CACHE_CONFIG = {
    'CACHE_TYPE': 'RedisSentinelCache',
    'CACHE_DEFAULT_TIMEOUT': 3600,
    'CACHE_KEY_PREFIX': 'ss_',
    'CACHE_REDIS_PASSWORD' : 'xxxxx',
    'CACHE_REDIS_DB' : 15,
    'CACHE_REDIS_SENTINELS': [('ip1',26379), ('ip2', 26379), ('ip3',26379)],
    'CACHE_REDIS_SENTINEL_MASTER' : 'mastername'
}
```
The above configuration was working perfectly in Superset 2.1.  However in Superset 3.0 I always get the error : redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.  Looks like Flask-caching is trying to connect to RedisCache on default localhost 6379 instead of RedisSentinelCache.

Exception:
```
Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/redis/connection.py", line 707, in connect
    sock = self.retry.call_with_retry(
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/redis/connection.py", line 708, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/redis/connection.py", line 1006, in _connect
    raise err
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/redis/connection.py", line 994, in _connect
    sock.connect(socket_address)
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/flask_caching/__init__.py", line 834, in decorated_function
    cache_key = decorated_function.make_cache_key(f, *args, **kwargs)
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/flask_caching/__init__.py", line 591, in make_cache_key
    fname, version_data = self._memoize_version(
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/flask_caching/__init__.py", line 541, in _memoize_version
    version_data_list = list(self.cache.get_many(*fetch_keys))
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/cachelib/redis.py", line 95, in get_many
    return [self.load_object(x) for x in self._client.mget(prefixed_keys)]
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/redis/commands/core.py", line 2002, in mget
    return self.execute_command("MGET", *args, **options)
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/redis/connection.py", line 1461, in get_connection
    connection.connect()
  File "/home/jenkinsci/.pyenv/versions/3.9.18/envs/superset3/lib/python3.9/site-packages/redis/connection.py", line 713, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

#### How to reproduce the bug

1. Enable RedisSentinelCache
2. Click on any dashboard
3. Error displayed

### Expected results

RedisSentinelCache should work

### Environment

(please complete the following information):

- browser type and version: Chrome latest
- superset version: 3.0-
- python version: 3.9.18 installed via pip
- node.js version: `node -v`
- any feature flags active: DRILL_BY, DRILL_TO_DETAIL

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
`flask-caching` was upgraded.
