### ISSUE TITLE
Issue while upgrading from 2.0.0 -> 3.0.0 superset

### ISSUE THREAD

**Issue by rohitpawar2811** [apache/superset#25415]
I have the old postgrease DB and other volumes of old 2.0.0 setup, 
but when I just try to upgrade using the 3.0.0 version I got some Issue in which :

1. In 2.0.0 postgres version was 10 but now it is 3.0.0 ,so I changed the **postgres version to 10** in docker-compose of 3.0.0V  : worked
2. I am getting errors related to description key and because of this in **Database-Connection panel** on Database is loading and SQL-Editore also not working 

```
[26/Sep/2023:11:26:21 +0000] "GET /api/v1/database/?q=(filters:!((col:allow_file_upload,opr:upload_is_enabled,value:!t))) HTTP/1.1" 200 521 "http://localhost:8088/databaseview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
superset_app          | Invalid decryption key
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 126, in decrypt
superset_app          |     decrypted = decrypted.decode('utf-8')
superset_app          | UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
superset_app          | 
superset_app          | During handling of the above exception, another exception occurred:
superset_app          | 
superset_app          | Traceback (most recent call last):
superset_app          |   File "/app/superset/views/base.py", line 253, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 487, in get_list_headless
superset_app          |     duration, response = time_function(super().get_list_headless, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1526, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 1603, in get_list_headless
superset_app          |     count, lst = self.datamodel.query(
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/models/sqla/interface.py", line 499, in query
superset_app          |     query_results = query.all()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2768, in all
superset_app          |     return self._iter().all()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1077, in all
superset_app          |     return self._allrows()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 401, in _allrows
superset_app          |     rows = self._fetchall_impl()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1696, in _fetchall_impl
superset_app          |     return list(self.iterator)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
superset_app          |     fetch = cursor._raw_all_rows()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
superset_app          |     return [make_row(row) for row in rows]
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
superset_app          |     return [make_row(row) for row in rows]
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 1681, in process
superset_app          |     return process_value(impl_processor(value), dialect)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 479, in process_result_value
superset_app          |     value = super().process_result_value(value=value, dialect=dialect)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 424, in process_result_value
superset_app          |     decrypted_value = self.engine.decrypt(value)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
superset_app          |     raise ValueError('Invalid decryption key')
superset_app          | ValueError: Invalid decryption key
superset_app          | 2023-09-26 11:26:21,479:ERROR:superset.views.base:Invalid decryption key
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 126, in decrypt
superset_app          |     decrypted = decrypted.decode('utf-8')
superset_app          | UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
superset_app          | 
superset_app          | During handling of the above exception, another exception occurred:
superset_app          | 
superset_app          | Traceback (most recent call last):
superset_app          |   File "/app/superset/views/base.py", line 253, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 487, in get_list_headless
superset_app          |     duration, response = time_function(super().get_list_headless, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1526, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 1603, in get_list_headless
superset_app          |     count, lst = self.datamodel.query(
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/models/sqla/interface.py", line 499, in query
superset_app          |     query_results = query.all()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2768, in all
superset_app          |     return self._iter().all()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1077, in all
superset_app          |     return self._allrows()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 401, in _allrows
superset_app          |     rows = self._fetchall_impl()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1696, in _fetchall_impl
superset_app          |     return list(self.iterator)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
superset_app          |     fetch = cursor._raw_all_rows()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
superset_app          |     return [make_row(row) for row in rows]
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
superset_app          |     return [make_row(row) for row in rows]
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 1681, in process
superset_app          |     return process_value(impl_processor(value), dialect)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 479, in process_result_value
superset_app          |     value = super().process_result_value(value=value, dialect=dialect)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 424, in process_result_value
superset_app          |     decrypted_value = self.engine.decrypt(value)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
superset_app          |     raise ValueError('Invalid decryption key')
superset_app          | ValueError: Invalid decryption key
superset_app          | 
superset_app          | 172.27.0.1 - - [26/Sep/2023:11:26:21 +0000] "GET /api/v1/database/?q=(order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:25) HTTP/1.1" 500 35 "http://localhost:8088/databaseview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36
```

Why is this problem I am getting, have I missed something to configure, Or has anyone faced the same problem?

**Comment by rohitpawar2811** [comment]
I got it what actually problem is and figure out its solution 

Its just because of SECRET_KEY in 2.0.0 I had used the default one and in 3.0.0 it is mandatored it would not be the default one, and my data is encrypted with old-default key so when I use new I got above error.
**Solution**
#### Rotating to a newer SECRET_KEY

If you wish to change your existing SECRET_KEY, add the existing SECRET_KEY to your `superset_config.py` file as
`PREVIOUS_SECRET_KEY = `and provide your new key as `SECRET_KEY =`. You can find your current SECRET_KEY with these
commands - if running Superset with Docker, execute from within the Superset application container:

```python
superset shell
from flask import current_app; print(current_app.config["SECRET_KEY"])
```

**Comment by aukfood** [comment]
@rohitpawar2811 I have the same problem from a migration from 2.0.1 to 3.0.1 and when I do <superset re-encrypt-secrets> I have some error 
```
superset re-encrypt-secrets
Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
logging was configured successfully
2023-11-23 20:52:31,802:INFO:superset.utils.logging_configurator:logging was configured successfully
2023-11-23 20:52:31,814:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
Collecting info for re encryption
2023-11-23 20:52:35,940:INFO:superset.utils.encrypt:Collecting info for re encryption
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 126, in decrypt
    decrypted = decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/superset/utils/encrypt.py", line 146, in _re_encrypt_row
    unencrypted_value = previous_encrypted_type.process_result_value(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 479, in process_result_value
    value = super().process_result_value(value=value, dialect=dialect)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 424, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 128, in decrypt
    raise ValueError('Invalid decryption key')
ValueError: Invalid decryption key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/superset/cli/update.py", line 119, in re_encrypt_secrets
    secrets_migrator.run()
  File "/app/superset/utils/encrypt.py", line 190, in run
    self._re_encrypt_row(conn, row, table_name, columns)
  File "/app/superset/utils/encrypt.py", line 163, in _re_encrypt_row
    raise Exception from exc
Exception
```

I use this in <superset_config.py> 
```
 54 PREVIOUS_SECRET_KEY = get_env_variable("PREVIOUS_SECRET_KEY")
 55 SECRET_KEY = get_env_variable("SUPERSET_SECRET_KEY")
```

I done an error ?

**Comment by rohitpawar2811** [comment]
PREVIOUS_SECRET_KEY = get_env_variable("PREVIOUS_SECRET_KEY")
SECRET_KEY = get_env_variable("SUPERSET_SECRET_KEY")

In above keys you have to set values like below of mine

PREVIOUS_SECRET_KEY = "CHANGE_ME_TO_A_COMPLEX_RANDOM_SECRET"
SECRET_KEY = "XYZE2/vFTS4I8ejw/YHTWz"

**Comment by aukfood** [comment]
Same results with 

```
PREVIOUS_SECRET_KEY = "Ji*************1Ief" # my secret in 2.0.1
SECRET_KEY = "bqnh6***************ltUjs4SAl" # my new secret en 3.0.1 
```

**Comment by rohitpawar2811** [comment]
According to your I can say you have not gave the **right previous key** that's it is not able to decode your data,
Other cases to check : 
1. it might possible that code has some kind of bug so go with 3.0.0, I am using it and on top that it is working.
2. Have you take migrate the postgrese data correctly as I know in 2.0.1 and 3.0.0 posgrease version is changed form 11->14.
