### ISSUE TITLE
Docker startup on Apple Silicon

### ISSUE THREAD

**Issue by atillier** [apache/superset#25434]
The current repo is unable to start docker on Apple Silicon (M1 Pro) 

#### How to reproduce the bug

1. Clone repo
2. Go to repo dir
3. docker compose up
4. See error:
`no matching manifest for linux/arm64/v8 in the manifest list entries
`
### Expected results

The start page on https://superset.apache.org/docs/installation/installing-superset-using-docker-compose doesn't have a disclaimer about Apple Silicon so I expect it to work. 

### Actual results

Unable to start Superset

### Environment

(please complete the following information):

- Apple M1 Pro on 13.4.1 
- superset version: master branch
- Docker version 4.23.0 with Engine 24.0.6

**Comment by zhaorui2022** [comment]
I also run into the same issue today with Mac OS 13.5.2

**Comment by zhaorui2022** [comment]
I tried this `export DOCKER_DEFAULT_PLATFORM=linux/x86_64/v8 ` and it seems working for me

**Comment by pgoultiaev** [comment]
This has worked for me: `export DOCKER_DEFAULT_PLATFORM=linux/amd64`

    Apple M2 Pro on 14.0
    superset version: master branch
    Docker version 4.23.0 with Engine 24.0.6

**Comment by atillier** [comment]
Thanks chaps.

I tried with the platform version update and it's progressing. But there is a dependency on Nginx which doesn't pass:
![image](https://github.com/apache/superset/assets/14177484/24ffeb93-b6a2-4643-9fc7-ef0ae1ac5a62)

So I guess I need to only set the variable in the docker-compose yml instead to avoid forcing my entire Docker to emulate. 

Anyhow, the documentation on https://superset.apache.org/docs/installation/installing-superset-using-docker-compose should be updated. If it's updated from the repo I am more than happy to raise a PR.

**Comment by atillier** [comment]
So after updating the docker-compose.yml file to lock the platform on the superset specific services it managed to start but the provisioning failed:

```
superset_db            | 2023-09-28 12:31:47.181 UTC [82] ERROR:  deadlock detected
superset_db            | 2023-09-28 12:31:47.181 UTC [82] DETAIL:  Process 82 waits for AccessExclusiveLock on relation 16404 of database 16384; blocked by process 83.
superset_db            | 	Process 83 waits for AccessShareLock on relation 16412 of database 16384; blocked by process 82.
superset_db            | 	Process 82: ALTER TABLE dashboard_roles DROP CONSTRAINT dashboard_roles_role_id_fkey
superset_db            | 	Process 83: SELECT count(ab_user.id) AS count_1
superset_db            | 	FROM ab_user
superset_db            | 2023-09-28 12:31:47.181 UTC [82] HINT:  See server log for query details.
superset_db            | 2023-09-28 12:31:47.181 UTC [82] STATEMENT:  ALTER TABLE dashboard_roles DROP CONSTRAINT dashboard_roles_role_id_fkey
superset_node          | Setting up glib-networking:arm64 (2.58.0-2+deb10u2) ...
```

Which then made the following statements to also fail:
```
superset_db            | 2023-09-28 12:32:00.192 UTC [88] STATEMENT:  SELECT report_schedule.created_on AS report_schedule_created_on, report_schedule.changed_on AS report_schedule_changed_on, report_schedule.extra_json AS report_schedule_extra_json, report_schedule.id AS report_schedule_id, report_schedule.type AS report_schedule_type, report_schedule.name AS report_schedule_name, report_schedule.description AS report_schedule_description, report_schedule.context_markdown AS report_schedule_context_markdown, report_schedule.active AS report_schedule_active, report_schedule.crontab AS report_schedule_crontab, report_schedule.creation_method AS report_schedule_creation_method, report_schedule.timezone AS report_schedule_timezone, report_schedule.report_format AS report_schedule_report_format, report_schedule.sql AS report_schedule_sql, report_schedule.chart_id AS report_schedule_chart_id, report_schedule.dashboard_id AS report_schedule_dashboard_id, report_schedule.database_id AS report_schedule_database_id, report_schedule.last_eval_dttm AS report_schedule_last_eval_dttm, report_schedule.last_state AS report_schedule_last_state, report_schedule.last_value AS report_schedule_last_value, report_schedule.last_value_row_json AS report_schedule_last_value_row_json, report_schedule.validator_type AS report_schedule_validator_type, report_schedule.validator_config_json AS report_schedule_validator_config_json, report_schedule.log_retention AS report_schedule_log_retention, report_schedule.grace_period AS report_schedule_grace_period, report_schedule.working_timeout AS report_schedule_working_timeout, report_schedule.force_screenshot AS report_schedule_force_screenshot, report_schedule.custom_width AS report_schedule_custom_width, report_schedule.custom_height AS report_schedule_custom_height, report_schedule.created_by_fk AS report_schedule_created_by_fk, report_schedule.changed_by_fk AS report_schedule_changed_by_fk
superset_db            | 	FROM report_schedule
superset_db            | 	WHERE report_schedule.active IS true
superset_worker        | [2023-09-28 12:32:00,196: ERROR/ForkPoolWorker-1] (psycopg2.errors.UndefinedTable) relation "report_schedule" does not exist
superset_worker        | LINE 2: FROM report_schedule
```

**Comment by MathenyCode** [comment]
@atillier saw the below as well when I forced everything in the docker compose to lock to `linux/amd64` 

```
superset_db            | 	FROM report_schedule
superset_db            | 	WHERE report_schedule.active IS true
superset_worker        | [2023-09-28 12:32:00,196: ERROR/ForkPoolWorker-1] (psycopg2.errors.UndefinedTable) relation "report_schedule" does not exist
superset_worker        | LINE 2: FROM report_schedule
```

**Comment by atillier** [comment]
So I stopped all containers, and restarted them again which seems to have triggered a valid migration.

So I am now able to log in the app but all the style is broken. I suspect it's to do with the WS app not starting with:
`2023-09-28 17:04:54 
2023-09-28 17:04:54 > superset-websocket@0.0.1 start
2023-09-28 17:04:54 > node dist/index.js start
2023-09-28 17:04:54 
2023-09-28 17:04:58 {"date":"Thu Sep 28 2023 16:04:58 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Please provide a JWT secret at least 32 bytes long\nError: Please provide a JWT secret at least 32 bytes long\n    at Object.<anonymous> (/home/superset-websocket/dist/index.js:75:11)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:22:47","os":{"loadavg":[2.78,2.5,1.68],"uptime":36163.12},"process":{"argv":["/usr/local/bin/node","/home/superset-websocket/dist/index.js","start"],"cwd":"/home/superset-websocket","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":327666,"external":1253424,"heapTotal":18362368,"heapUsed":13813856,"rss":0},"pid":22,"uid":1000,"version":"v16.20.2"},"stack":"Error: Please provide a JWT secret at least 32 bytes long\n    at Object.<anonymous> (/home/superset-websocket/dist/index.js:75:11)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:22:47","trace":[{"column":11,"file":"/home/superset-websocket/dist/index.js","function":null,"line":75,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1198,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1252,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1076,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":911,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":22,"method":null,"native":false}]}
2023-09-28 17:04:58 config.json file not found
2023-09-28 17:05:02 npm notice 
2023-09-28 17:05:02 npm notice New major version of npm available! 8.19.4 -> 10.1.0
2023-09-28 17:05:02 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.1.0>
2023-09-28 17:05:02 npm notice Run `npm install -g npm@10.1.0` to update!
2023-09-28 17:05:02 npm notice `

I can't say the current Docker approach is in a good working state I am afraid.

**Comment by MathenyCode** [comment]
@atillier I am not sure the style/UI being broken/incomplete is specific to the docker approach. I built from scratch using python 3.10 and everything was messed up: 
![Screenshot 2023-09-27 at 2 51 38 PM](https://github.com/apache/superset/assets/119812938/f19af0c4-7419-49ed-baec-d1701fac4419)
![Screenshot 2023-09-27 at 3 00 14 PM](https://github.com/apache/superset/assets/119812938/ebc6b3f2-d383-4937-852c-d845d80760ee)

**Comment by zhaorui2022** [comment]
UI is also broken for me

**Comment by Vitor-Avila** [comment]
I believe the UI issues are related with the CSP configuration. You could try disabling the CSP rules and check if that fixes it (setting `TALISMAN_ENABLED = False` in the `superset_config.py` file).

If that solves the issue, I **strongly recommend setting a proper CSP configuration rather than disabling it** in a Production environment. Further details on https://superset.apache.org/docs/security/#content-security-policy-csp

**Comment by zhugaopeng397** [comment]
> I've tried this `export DOCKER_DEFAULT_PLATFORM=linux/x86_64/v8 ` and it seems working for me



> This has worked for me: `export DOCKER_DEFAULT_PLATFORM=linux/amd64`
> 
> ```
> Apple M2 Pro on 14.0
> superset version: master branch
> Docker version 4.23.0 with Engine 24.0.6
> ```

Where did you put it exactly?

**Comment by tallpsmith** [comment]
At the risk of being _completely wrong here_ but having struggled with this same issue (M1 Pro, Sonoma, latest Docker Desktop) but not finding how any of the suggestions work I did some digging.

Now, I'm not a Docker expert, but it seems like Docker Compose setup is reliant heavily on a base layer that is published as part of the Github actions:

https://github.com/apache/superset/blob/53013395d7755eefafc8911cdbb129b8db1d20cf/docker-compose.yml#L17

If I understand correctly (and very possibly not), this layer seems to be produced during every commit, and built by Github action:

https://github.com/apache/superset/blob/master/.github/workflows/docker_build_push.sh

Various Docker-y layers/images are created here as part of the GitHub workflow and there are attempts to build pieces of it with varying architectures:

e.g. https://github.com/apache/superset/blob/53013395d7755eefafc8911cdbb129b8db1d20cf/.github/workflows/docker_build_push.sh#L57

There's a `for` loop that attempts to build multiple images: https://github.com/apache/superset/blob/53013395d7755eefafc8911cdbb129b8db1d20cf/.github/workflows/docker_build_push.sh#L113


HOWEVER,  a number of the images generated seem pinned to `amd64`.  
e.g: https://github.com/apache/superset/blob/53013395d7755eefafc8911cdbb129b8db1d20cf/.github/workflows/docker_build_push.sh#L72

(there's a few others)

If one inspects the published layer that I believe is the base used in docker compose:

```
 docker buildx imagetools inspect apachesuperset.docker.scarf.sh/apache/superset:latest
Name:      apachesuperset.docker.scarf.sh/apache/superset:latest
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:62bd5e816c87c2b70fe630ff28b8ad8d41cf96c057bb5906b0f3bb93dac0a1a5
           
Manifests: 
  Name:        apachesuperset.docker.scarf.sh/apache/superset:latest@sha256:f9585dbfa02291792b5388ad2ac11069cac23a3dda8d72ac5fbc713db19fa674
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    linux/amd64
               
  Name:        apachesuperset.docker.scarf.sh/apache/superset:latest@sha256:3e91051cc951ccd067cde5dec8189d78acf8784f98f3e24e61874e7d946a1e25
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations: 
    vnd.docker.reference.digest: sha256:f9585dbfa02291792b5388ad2ac11069cac23a3dda8d72ac5fbc713db19fa674
    vnd.docker.reference.type:   attestation-manifest
```

No `arm64` for us.

Is this at all part of the problem?  Or am I off track, majorly?

**Comment by tallpsmith** [comment]
Actually, another related problem might be this line:

  ARCHITECTURE_FOR_BUILD="linux/amd64,linux/arm64"
  
  If the `DOCKERHUB_TOKEN` is set during the build, then this line takes effect.  `bash` `for` loops won't iterate properly on the `,` - doesn't this need to be a space?

**Comment by artimath** [comment]
> > > I've tried this `export DOCKER_DEFAULT_PLATFORM=linux/x86_64/v8 ` and it seems working for me
> > 
> > 
> > > This has worked for me: `export DOCKER_DEFAULT_PLATFORM=linux/amd64`
> > > ```
> > > Apple M2 Pro on 14.0
> > > superset version: master branch
> > > Docker version 4.23.0 with Engine 24.0.6
> > > ```
> > 
> > 
> > @pgoultiaev Where did you put it exactly?
> 
> This is what I did. Stopped what was running and removed the images just to be sure.
> 
> ```
> $ docker-compose down && docker image prune -a 
> $ export DOCKER_DEFAULT_PLATFORM=linux/amd64
> $ docker-compose -f docker-compose-non-dev.yml up
> ```

This allowed me to progress further but then failed on redis

```
docker-compose down && docker image prune -a; export DOCKER_DEFAULT_PLATFORM=linux/amd64; docker-compose -f docker-compose-non-dev.yml up
WARN[0000] The "CYPRESS_CONFIG" variable is not set. Defaulting to a blank string.
WARN[0000] The "CYPRESS_CONFIG" variable is not set. Defaulting to a blank string.
service "mysql" has neither an image nor a build context specified: invalid compose project
[+] Running 20/20
 ✔ superset 16 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                            35.0s
   ✔ a803e7c4b030 Pull complete                                                                                             3.1s
   ✔ bf3336e84c8e Pull complete                                                                                             1.2s
   ✔ 3614ca5053cf Pull complete                                                                                             1.7s
   ✔ 7f93433c11f3 Pull complete                                                                                             2.1s
   ✔ 2fd2c896255c Pull complete                                                                                             2.7s
   ✔ 8b81383fdc00 Pull complete                                                                                             3.1s
   ✔ 90d1f6e369c2 Pull complete                                                                                             9.1s
   ✔ 99eab63d22a8 Pull complete                                                                                             4.1s
   ✔ cce4b191af09 Pull complete                                                                                             4.1s
   ✔ 20b8c2babf84 Pull complete                                                                                            14.7s
   ✔ a22fbe00ad47 Pull complete                                                                                             8.8s
   ✔ a25c3a526724 Pull complete                                                                                            10.7s
   ✔ 110e8713c243 Pull complete                                                                                            10.3s
   ✔ 5f9594584a41 Pull complete                                                                                            11.2s
   ✔ 9f5e78b7f00b Pull complete                                                                                            20.4s
   ✔ 4d4600a9d21e Pull complete                                                                                            13.5s
 ✔ superset-worker Pulled                                                                                                  35.0s
 ✔ superset-init Pulled                                                                                                    35.0s
 ✔ superset-worker-beat Pulled                                                                                             35.0s
[+] Building 0.0s (0/0)                                                                                     docker:desktop-linux
[+] Running 4/1
 ✔ Network superset_default         Created                                                                                 0.0s
 ✔ Volume "superset_db_home"        Created                                                                                 0.0s
 ✔ Volume "superset_superset_home"  Created                                                                                 0.0s
 ✔ Volume "superset_redis"          Created                                                                                 0.0s
 ⠋ Container superset_cache         Creating                                                                                0.0s
 ⠋ Container superset_db            Creating                                                                                0.0s
Error response from daemon: image with reference redis:7 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64
```

**Comment by atillier** [comment]
@artimath this would likely be because you forced `linux/amd64` for your entire Docker environment and you already have an arm64 version on your system.

The closer I could get was by updating the docker-compose.yml by specifying the platform at each service level for the Superset ones, for example:
```
  superset:
    platform: linux/amd64
    env_file: docker/.env
    image: *superset-image
```

But even then I faced a completely broken product as per my last update. I might give it another try later but for now it's clear the build is not stable enough for me (and I need a prod-ready one).

**Comment by linafei5006** [comment]
> > @artimath this would likely be because you forced `linux/amd64` for your entire Docker environment and you already have an arm64 version on your system.
> > The closer I could get was by updating the docker-compose.yml by specifying the platform at each service level for the Superset ones, for example:
> > ```
> > 
> >   superset:
> > 
> >     platform: linux/amd64
> > 
> >     env_file: docker/.env
> > 
> >     image: *superset-image
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But even then I faced a completely broken product as per my last update. I might give it another try later but for now it's clear the build is not stable enough for me (and I need a prod-ready one).
> 
> Good point!
> 
> I was actually able to get it to work for me today. (after many a hour)
> 
> I'll make a note to post my changes for other's reference. In case i forget:
> 
> I'm on a macbook pro m1, monterey i think.
> 
> basically, i fixed the comma issue mentioned above in my local repo.
> 
> then when the build complained about a particular service erroring, i just added the 'platform: linux/amd64' to that service, and repeated about 5 times... then it built!

I can pull the images ,but when i run "docker-compose -f docker-compose-non-dev.yml up" i got a error "standard_init_linux.go:228 exec user process caused:no such file or directory"

**Comment by Geometrein** [comment]
Had the same issue on M2 Max.
Adding `platform: linux/amd64` and platform: `platform: linux/amd64/v8` to all nodes in "superset" namespace inside the docker-compose.yml file solved it for me. 
Looks something like this:
```
  superset:
    platform: linux/x86_64/v8
    ...
  superset-websocket:
    platform: linux/amd64
    ...
  superset-init:
    platform: linux/x86_64/v8
    ...
   superset-node:
    platform: linux/x86_64/v8
    ...
   superset-worker:
    platform: linux/x86_64/v8
    ...
  superset-worker-beat:
    platform: linux/x86_64/v8
    ...
  superset-tests-worker:
    platform: linux/x86_64/v8
    ...
```

**Comment by Willie-The-Lord** [comment]
Data point: Got the same issue on M1 pro chip. Adding following lines to `docker-compose.yml` solve the problem.
```
superset:
    platform: linux/amd64/v8
...
superset-websocket:
    platform: linux/amd64
...
superset-init:
    platform: linux/amd64/v8
...
superset-node:
    platform: linux/amd64/v8
...
 superset-worker:
    platform: linux/amd64/v8
...
 superset-worker-beat:
    platform: linux/amd64/v8
...
superset-tests-worker:
    platform: linux/amd64/v8
```

**Comment by Tburm** [comment]
> Data point: Got the same issue on M1 pro chip. Adding following lines to `docker-compose.yml` solve the problem.
> 
> ```
> superset:
>     platform: linux/amd64/v8
> ...
> superset-websocket:
>     platform: linux/amd64
> ...
> superset-init:
>     platform: linux/amd64/v8
> ...
> superset-node:
>     platform: linux/amd64/v8
> ...
>  superset-worker:
>     platform: linux/amd64/v8
> ...
>  superset-worker-beat:
>     platform: linux/amd64/v8
> ...
> superset-tests-worker:
>     platform: linux/amd64/v8
> ```

This worked for me, thank you

**Comment by alberttwong** [comment]
it doesn't work. 
```
atwong@Albert-CelerData superset % export DOCKER_DEFAULT_PLATFORM=linux/x86_64/v8
atwong@Albert-CelerData superset % docker-compose up
WARN[0000] The "CYPRESS_CONFIG" variable is not set. Defaulting to a blank string.
WARN[0000] The "CYPRESS_CONFIG" variable is not set. Defaulting to a blank string.
[+] Running 51/9
 ! superset-websocket Warning                                              1.1s
 ✔ db 13 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                    15.5s
 ✔ superset-worker Pulled                                                 37.0s
 ✔ superset 15 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled            37.0s
 ✔ superset-init Pulled                                                   37.0s
 ✔ superset-tests-worker Pulled                                           37.0s
 ✔ redis 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                         13.8s
 ✔ superset-worker-beat Pulled                                            37.0s
 ✔ superset-node 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled               20.5s
[+] Building 5.7s (9/12)                                   docker:desktop-linux
 => [superset-websocket internal] load .dockerignore                       0.0s
 => => transferring context: 842B                                          0.0s
 => [superset-websocket internal] load build definition from Dockerfile    0.0s
 => => transferring dockerfile: 1.20kB                                     0.0s
 => [superset-websocket internal] load metadata for docker.io/library/nod  1.1s
 => [superset-websocket auth] library/node:pull token for registry-1.dock  0.0s
 => [superset-websocket internal] load build context                       0.0s
 => => transferring context: 581.99kB                                      0.0s
 => [superset-websocket build 1/4] FROM docker.io/library/node:16-alpine@  4.2s
 => => resolve docker.io/library/node:16-alpine@sha256:a1f9d027912b58a7c7  0.0s
 => => sha256:a1f9d027912b58a7c75be7716c97cfbc6d3099f3a97 1.43kB / 1.43kB  0.0s
 => => sha256:72e89a86be58c922ed7b1475e5e6f15153767647069 1.16kB / 1.16kB  0.0s
 => => sha256:2573171e0124bb95d14d128728a52a97bb917ef45d7 6.73kB / 6.73kB  0.0s
 => => sha256:7264a8db6415046d36d16ba98b79778e18accee6ffa 3.40MB / 3.40MB  1.2s
 => => sha256:eee371b9ce3ffdbb8aa703b9a14d318801ddc3468 36.63MB / 36.63MB  1.2s
 => => sha256:93b3025fe10392717d06ec0d012a9ffa2039d766a32 2.34MB / 2.34MB  1.2s
 => => extracting sha256:7264a8db6415046d36d16ba98b79778e18accee6ffa71850  0.1s
 => => sha256:d9059661ce70092af66d2773666584fc8addcb78a2be63f 452B / 452B  1.4s
 => => extracting sha256:eee371b9ce3ffdbb8aa703b9a14d318801ddc3468f096bb6  1.7s
 => => extracting sha256:93b3025fe10392717d06ec0d012a9ffa2039d766a322aac8  0.0s
 => => extracting sha256:d9059661ce70092af66d2773666584fc8addcb78a2be63f7  0.0s
 => [superset-websocket build 2/4] WORKDIR /home/superset-websocket        0.3s
 => [superset-websocket build 3/4] COPY . ./                               0.0s
 => ERROR [superset-websocket build 4/4] RUN npm ci &&   npm run build     0.0s
------
 > [superset-websocket build 4/4] RUN npm ci &&   npm run build:
------
failed to solve: no support for running processes with linux/amd64/v8 platform, supported:
```

**Comment by p1nox** [comment]
> Had the same issue on M2 Max. Adding `platform: linux/amd64` and platform: `platform: linux/amd64/v8` to all nodes in "superset" namespace inside the docker-compose.yml file solved it for me. Looks something like this:
> 
> ```
>   superset:
>     platform: linux/x86_64/v8
>     ...
>   superset-websocket:
>     platform: linux/amd64
>     ...
>   superset-init:
>     platform: linux/x86_64/v8
>     ...
>    superset-node:
>     platform: linux/x86_64/v8
>     ...
>    superset-worker:
>     platform: linux/x86_64/v8
>     ...
>   superset-worker-beat:
>     platform: linux/x86_64/v8
>     ...
>   superset-tests-worker:
>     platform: linux/x86_64/v8
>     ...
> ```

__TL;DR__

For me, having a Macbook Pro 16-inch 2023 with M2 Pro and Ventura 13.6.3, this was resolved by just adding `psycopg2==2.9.9` to `docker/requirements-local.txt`.

______

I tried this approach, changing the platform specifically for each container, but didn't work. I was researching a bit more about this and found [this comment](https://github.com/apache/superset/issues/21160#issuecomment-1736520181), where is mentioned that changing `psycopg2` version to `2.9.3` might help. I tried that version but didn't work, then I just tried changing the version to `2.9.9`, which is the [latest one](https://pypi.org/project/psycopg2/), and it did work. All this was performed having the specific platform referenced in Geometrein's comment, but then I removed the specific platform references in `docker-compose.yml` and it worked 👌 .

**Comment by jpasner** [comment]
Just dropping in to say that I'm also experiencing this issue and looking forward to being able to use superset some day. 

Macbook Pro M3 Pro. Followed original poster's steps and got the same error:

1. Clone repo
2. Go to repo dir
3. docker compose up
4. See error:
5. 'no matching manifest for linux/arm64/v8 in the manifest list entries'

**Comment by rusackas** [comment]
I think recent re-jiggering of github actions has largely resolved this. Can anyone confirm if we're all good here now?

**Comment by Laksh47** [comment]
Nope, still facing the same issue.

macOS: `13.5.1` M1 Pro

**Comment by stvncode** [comment]
> ```shell
> docker compose -f docker-compose-image-tag.yml up
> ```

You will need to add to the db 
`linux/amd64/v2`

**Comment by harksin** [comment]
noone dev on apple silicon ?
how to make the project compile with docker on this arch ?

**Comment by rusackas** [comment]
I use apple silicon, and it's entirely compatible. I just `docker-compose up` and I'm off to the races.

**Comment by stvncode** [comment]
> I use apple silicon, and it's entirely compatible. I just `docker-compose up` and I'm off to the races.

I'm using Mac M1 Sonoma 14.3.1, node version is `v20.11.0,` Docker version `25.0.2`.
Doing the `docker compose up`, it stop doing the npm run build and give me this error : `failed to solve: process "/bin/sh -c npm run ${BUILD_CMD}" did not complete successfully: exit code: 1`

**Comment by rusackas** [comment]
Ahh... that usually means you just need to throw more memory at it. Docker uses half your system's memory by default, but you can ramp it up in the Docker Desktop settings. Set it to like 12GB or so and I'll bet it works.
