### ISSUE TITLE
SMTP_SSL_SERVER_AUTH

### ISSUE THREAD

**Issue by Nikoslav** [apache/superset#25485]
```
[2023-10-02 15:20:00,086: INFO/ForkPoolWorker-1] session is validated: id 3, executionid: 38068d4f-bd59-4285-a1b7-050759c95b7e
Running report schedule 38068d4f-bd59-4285-a1b7-050759c95b7e as user admin
[2023-10-02 15:20:00,111: INFO/ForkPoolWorker-1] Running report schedule 38068d4f-bd59-4285-a1b7-050759c95b7e as user admin
Init selenium driver
[2023-10-02 15:20:00,479: INFO/ForkPoolWorker-1] Init selenium driver
Taking a PNG screenshot of url https://xxx:3448/superset/dashboard/64/?force=false&standalone=3 as user admin
[2023-10-02 15:20:21,055: INFO/ForkPoolWorker-1] Taking a PNG screenshot of url https://xxx:3448/superset/dashboard/64/?force=false&standalone=3 as user admin
SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)
[2023-10-02 15:20:22,165: WARNING/ForkPoolWorker-1] SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)
header_data in notifications for alerts and reports {'notification_type': 'Report', 'notification_source': <ReportSourceFormat.DASHBOARD: 'dashboard'>, 'notification_format': 'PNG', 'chart_id': None, 'dashboard_id': 64, 'owners': [Niko]}, taskid, 38068d4f-bd59-4285-a1b7-050759c95b7e
[2023-10-02 15:20:22,217: INFO/ForkPoolWorker-1] header_data in notifications for alerts and reports {'notification_type': 'Report', 'notification_source': <ReportSourceFormat.DASHBOARD: 'dashboard'>, 'notification_format': 'PNG', 'chart_id': None, 'dashboard_id': 64, 'owners': [Niko]}, taskid, 38068d4f-bd59-4285-a1b7-050759c95b7e
SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)
[2023-10-02 15:20:22,219: WARNING/ForkPoolWorker-1] SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)
SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)
[2023-10-02 15:20:22,219: WARNING/ForkPoolWorker-1] SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)
A downstream exception occurred while generating a report: 38068d4f-bd59-4285-a1b7-050759c95b7e. [SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)]
Traceback (most recent call last):
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/tasks/scheduler.py", line 87, in execute
    AsyncExecuteReportScheduleCommand(
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 719, in run
    raise ex
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 715, in run
    ReportScheduleStateMachine(
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 673, in run
    state_cls(
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 574, in next
    raise first_ex
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 543, in next
    self.send()
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 441, in send
    self._send(notification_content, self._report_schedule.recipients)
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 430, in _send
    raise ReportScheduleSystemErrorsException(errors=notification_errors)
superset.reports.commands.exceptions.ReportScheduleSystemErrorsException: [SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)]
[2023-10-02 15:16:24,339: ERROR/ForkPoolWorker-1] A downstream exception occurred while generating a report: 16c7f2af-b64f-4491-8812-dc538049a8ae. [SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)]
Traceback (most recent call last):
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/tasks/scheduler.py", line 87, in execute
    AsyncExecuteReportScheduleCommand(
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 719, in run
    raise ex
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 715, in run
    ReportScheduleStateMachine(
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 673, in run
    state_cls(
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 574, in next
    raise first_ex
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 543, in next
    self.send()
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 441, in send
    self._send(notification_content, self._report_schedule.recipients)
  File "/home/monitor/superset/superset/lib/python3.9/site-packages/superset/reports/commands/execute.py", line 430, in _send
    raise ReportScheduleSystemErrorsException(errors=notification_errors)
superset.reports.commands.exceptions.ReportScheduleSystemErrorsException: [SupersetError(message="'SMTP_SSL_SERVER_AUTH'", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra=None)]
```

#### How to reproduce the bug
OS: Debian GNU/Linux 11 (bullseye)
Python 3.9.1
Firefox: 115.3.1esr-1~deb11u1 amd64
Geckodriver: 0.33.0 (a80e5fd61076 2023-04-02 18:31 +0000)
Selenium 4.1.5
Superset: 2.1.0.

Email with screenshot is not sent, but it is generated.

When upgrading from a previous version, i left SMTP_SSL_SERVER_AUTH = False commented out and ran init. I have now noticed this setting and uncommented it and reran init.

Old reports that were not changed from previous version still send successfully. New reports trigger the above error.

**Comment by Nikoslav** [comment]
I have solved this. Had to clean celery worker tasks, changed reports a bit and saved, stopped using redis for celery tasks.
