### ISSUE TITLE
Documentation bug: "Installing from Scratch" instructions deficient at `superset init`

### ISSUE THREAD

**Issue by jwoehr** [apache/superset#25535]
Superset "Install from Scratch" documentation fails at `superset init`

#### How to reproduce the bug
1. Follow instructions [to install from scratch ](https://superset.apache.org/docs/installation/installing-superset-from-scratch/)
2. Get to the `superset init` instruction

### Expected results
`superset init` to work correctly.

### Actual results

```
$ superset init
Loaded your LOCAL configuration at [/home/jwoehr/work/ApacheSuperset/superset_config.py]
logging was configured successfully
2023-10-05 10:12:36,867:INFO:superset.utils.logging_configurator:logging was configured successfully
2023-10-05 10:12:36,873:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/flask_limiter/extension.py:336: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
Syncing role definition
2023-10-05 10:12:49,223:INFO:superset.security.manager:Syncing role definition
Syncing Admin perms
2023-10-05 10:12:49,544:INFO:superset.security.manager:Syncing Admin perms
Syncing Alpha perms
2023-10-05 10:12:49,682:INFO:superset.security.manager:Syncing Alpha perms
Syncing Gamma perms
2023-10-05 10:12:49,957:INFO:superset.security.manager:Syncing Gamma perms
Syncing sql_lab perms
2023-10-05 10:12:50,226:INFO:superset.security.manager:Syncing sql_lab perms
Fetching a set of all perms to lookup which ones are missing
2023-10-05 10:12:50,491:INFO:superset.security.manager:Fetching a set of all perms to lookup which ones are missing
Creating missing datasource permissions.
2023-10-05 10:12:50,568:INFO:superset.security.manager:Creating missing datasource permissions.
Traceback (most recent call last):
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: tables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jwoehr/work/ApacheSuperset/venv/bin/superset", line 8, in <module>
    sys.exit(superset())
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/flask/cli.py", line 358, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/flask/cli.py", line 358, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/superset/cli/main.py", line 65, in init
    security_manager.sync_role_definitions()
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/superset/security/manager.py", line 805, in sync_role_definitions
    self.create_missing_perms()
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/superset/security/manager.py", line 753, in create_missing_perms
    datasources = SqlaTable.get_all_datasources(self.get_session)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/superset/connectors/sqla/models.py", line 1377, in get_all_datasources
    return qry.all()
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/jwoehr/work/ApacheSuperset/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: tables
[SQL: SELECT tables.uuid AS tables_uuid, tables.created_on AS tables_created_on, tables.changed_on AS tables_changed_on, tables.id AS tables_id, tables.description AS tables_description, tables.default_endpoint AS tables_default_endpoint, tables.is_featured AS tables_is_featured, tables.filter_select_enabled AS tables_filter_select_enabled, tables."offset" AS tables_offset, tables.cache_timeout AS tables_cache_timeout, tables.params AS tables_params, tables.perm AS tables_perm, tables.schema_perm AS tables_schema_perm, tables.is_managed_externally AS tables_is_managed_externally, tables.external_url AS tables_external_url, tables.table_name AS tables_table_name, tables.main_dttm_col AS tables_main_dttm_col, tables.database_id AS tables_database_id, tables.fetch_values_predicate AS tables_fetch_values_predicate, tables.schema AS tables_schema, tables.sql AS tables_sql, tables.is_sqllab_view AS tables_is_sqllab_view, tables.template_params AS tables_template_params, tables.extra AS tables_extra, tables.normalize_columns AS tables_normalize_columns, tables.created_by_fk AS tables_created_by_fk, tables.changed_by_fk AS tables_changed_by_fk 
FROM tables 
WHERE tables.is_sqllab_view = 0]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Environment

(please complete the following information):

- browser type and version: n/a
- superset version: Superset 3.0.0
- python version: Python 3.10.12
- node.js version: n/a
- any feature flags active: n/a

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Documentation on "Installing from Scratch" is perfunctory.

**Comment by jwoehr** [comment]
got it running ... re-ran some commands and miraculously it works.
