### ISSUE TITLE
superset load_examples Error

### ISSUE THREAD

**Issue by vndroid** [apache/superset#25591]
When I deploy the superset, See the following error report.

#### How to reproduce the bug

```bash
$ superset load_examples
```

The Environment

- MySQL 5.7.42
- Superset 3.0.0
- Python 3.9.18

Error log

```
2023-10-10 17:20:28,509:INFO:superset.models.helpers:Importing new slices Quarterly Sales (By Product Line)
Importing new slices Most Dominant Platforms
2023-10-10 17:20:28,512:INFO:superset.models.helpers:Importing new slices Most Dominant Platforms
Importing new slices Total Items Sold
2023-10-10 17:20:28,514:INFO:superset.models.helpers:Importing new slices Total Items Sold
Importing new slices ✈️ Relocation ability
2023-10-10 17:20:28,517:INFO:superset.models.helpers:Importing new slices ✈️ Relocation ability
Traceback (most recent call last):
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/superset/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/opt/superset/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/superset/venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1366, "Incorrect string value: '\\xE2\\x9C\\x88\\xEF\\xB8\\x8F...' for column 'slice_name' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/superset/venv/lib/python3.9/site-packages/superset/commands/importers/v1/examples.py", line 72, in run
    self._import(
  File "/opt/superset/venv/lib/python3.9/site-packages/superset/commands/importers/v1/examples.py", line 164, in _import
    chart = import_chart(
  File "/opt/superset/venv/lib/python3.9/site-packages/superset/charts/commands/importers/v1/utils.py", line 60, in import_chart
    session.flush()
  File "<string>", line 2, in flush
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/opt/superset/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/superset/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/opt/superset/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/superset/venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1366, "Incorrect string value: '\\xE2\\x9C\\x88\\xEF\\xB8\\x8F...' for column 'slice_name' at row 1")
[SQL: INSERT INTO slices (uuid, created_on, changed_on, slice_name, datasource_id, datasource_type, datasource_name, viz_type, params, query_context, description, cache_timeout, perm, schema_perm, last_saved_at, last_saved_by_fk, certified_by, certification_details, is_managed_externally, external_url, created_by_fk, changed_by_fk) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (b'\xa6\xdd-Z,\xdc\xc8\xec\xf3\x0c\x85\x92\x0fO\x8ae', datetime.datetime(2023, 10, 10, 17, 20, 28, 518293), datetime.datetime(2023, 10, 10, 17, 20, 28, 518297), '✈️ Relocation ability', 19, 'table', 'FCC 2018 Survey', 'pie', '{"adhoc_filters": [{"clause": "WHERE", "comparator": "0", "expressionType": "SIMPLE", "filterOptionName": "filter_yccan09xctb_wjwt23qhknf", "isExtra" ... (433 characters truncated) ... cs"}, "row_limit": null, "show_labels": true, "show_legend": false, "slice_id": 1365, "time_range": "No filter", "url_params": {}, "viz_type": "pie"}', None, None, None, '[examples].[FCC 2018 Survey](id:19)', '[examples].[main]', None, None, None, None, 0, None, None, None)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/superset/venv/bin/superset", line 8, in <module>
    sys.exit(superset())
  File "/opt/superset/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/superset/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/superset/venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/superset/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/superset/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/superset/venv/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/superset/venv/lib/python3.9/site-packages/flask/cli.py", line 358, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/superset/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/superset/venv/lib/python3.9/site-packages/superset/cli/examples.py", line 113, in load_examples
    load_examples_run(load_test_data, load_big_data, only_metadata, force)
  File "/opt/superset/venv/lib/python3.9/site-packages/superset/cli/examples.py", line 87, in load_examples_run
    examples.load_examples_from_configs(force, load_test_data)
  File "/opt/superset/venv/lib/python3.9/site-packages/superset/examples/utils.py", line 42, in load_examples_from_configs
    command.run()
  File "/opt/superset/venv/lib/python3.9/site-packages/superset/commands/importers/v1/examples.py", line 81, in run
    raise self.import_error() from ex
superset.commands.exceptions.CommandException
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Environment

- browser type and version: none
- superset version: 3.0.0
- python version: 3.9.18
- node.js version:  none
- any feature flags active: none

**Comment by vndroid** [comment]
I also think it's a coding issue. Waiting for an update.

**Comment by sebastianliebscher** [comment]
Hi @vndroid I could not reproduce this error with Superset 3.0.1. Is it still an issue on your deployment? Can you confirm 3.0.1 resolves your issue?

**Comment by vndroid** [comment]
> Hi @vndroid I could not reproduce this error with Superset 3.0.1. Is it still an issue on your deployment? Can you confirm 3.0.1 resolves your issue?

Okey, I will test that version.

**Comment by vndroid** [comment]
Okay, it worked great for me. only some warning:

```
/opt/superset/venv/lib/python3.9/site-packages/superset/connectors/sqla/models.py:1495: SAWarning: Usage of the 'related attribute set' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
  self.database = session.query(Database).filter_by(id=self.database_id).one()
/opt/superset/venv/lib/python3.9/site-packages/superset/connectors/sqla/models.py:1495: SAWarning: Usage of the 'collection append' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
  self.database = session.query(Database).filter_by(id=self.database_id).one()
/opt/superset/venv/lib/python3.9/site-packages/superset/models/helpers.py:302: SAWarning: Attribute history events accumulated on 1 previously clean instances within inner-flush event handlers have been reset, and will not result in database updates. Consider using set_committed_value() within inner-flush event handlers to avoid this warning.
  obj = obj_query.one_or_none()
```
