### ISSUE TITLE
Unable to open user list

### ISSUE THREAD

**Issue by zhou-yi** [apache/superset#25631]
### Environment
- superset version: 3.0.0
- python version:  3.10.13
- node.js version:  16.20
### Checklist
<img width="859" alt="企业微信20231013-104455@2x" src="https://github.com/apache/superset/assets/13634569/058fdcd7-9999-42c1-898b-a043c4a3b2e0">

2023-10-13 10:47:44,033:ERROR:superset.views.base:not enough values to unpack (expected 4, got 3)
Traceback (most recent call last):
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 137, in wraps
    return f(self, *args, **kwargs)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask_appbuilder/views.py", line 555, in list
    return self.render_template(
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask_appbuilder/baseviews.py", line 343, in render_template
    return render_template(
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/ecs-user/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/program/superset-3.0.1rc1/superset/templates/appbuilder/general/model/list.html", line 20, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/mnt/program/superset-3.0.1rc1/superset/templates/superset/base.html", line 20, in top-level template code
    {% from 'superset/partials/asset_bundle.html' import css_bundle, js_bundle with context %}
  File "/mnt/program/superset-3.0.1rc1/superset/templates/appbuilder/baselayout.html", line 20, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 42, in top-level template code
    {% block body %}
  File "/mnt/program/superset-3.0.1rc1/superset/templates/appbuilder/baselayout.html", line 37, in block 'body'
    {% block content %}
  File "/mnt/program/superset-3.0.1rc1/superset/templates/appbuilder/general/model/list.html", line 26, in block 'content'
    {% block list_search scoped %}
  File "/mnt/program/superset-3.0.1rc1/superset/templates/appbuilder/general/model/list.html", line 27, in block 'list_search'
    {{ widgets.get('search')()|safe }}
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask_appbuilder/widgets.py", line 115, in __call__
    form_fields[col] = self.template_args["form"][col]()
  File "/home/ecs-user/.local/lib/python3.10/site-packages/wtforms/fields/core.py", line 176, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/wtforms/meta.py", line 64, in render_field
    return field.widget(field, **render_kw)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/flask_appbuilder/fieldwidgets.py", line 181, in __call__
    return super(Select2ManyWidget, self).__call__(field, **kwargs)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/wtforms/widgets/core.py", line 365, in __call__
    for val, label, selected, render_kw in field.iter_choices():
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by sfirke** [comment]
Can you try replicating this in Superset 3.0.2?  This should be resolved.  Flask-Appbuilder version is 4.3.10 for that version of Superset, and in 4.3.10 FAB has a workaround for this problem introduced in WTForms 3.1.0.

**Comment by rusackas** [comment]
This has gone months without a response, so it sounds like it's probably resolved.
