### ISSUE TITLE
WITH Clause with UNION is not supported

### ISSUE THREAD

**Issue by Scope0910** [apache/superset#25659]
#### How to reproduce the bug
1. Create a database Connection of type oracle (first qithout enable DML operations)
2. Open SQL Lab and run following sql
`<img width="1613" alt="Screenshot 2023-10-16 152915" src="https://github.com/apache/superset/assets/74256450/b1468d27-4e60-4ba8-bc84-a0797f6750a4"> `
3. an error occured, that the statement is not allowed
4. go to datasource settings and enable DML-Feature
5. run SQL again - it  works
6. if i want so save the dataset an error occured:
 value = f(*args, **kwargs)
File "/app/superset/views/base_api.py", line 93, in wraps
return f(self, *args, **kwargs)
File "/app/superset/datasets/api.py", line 315, in post
new_model = CreateDatasetCommand(item).run()
File "/app/superset/datasets/commands/create.py", line 50, in run
dataset.fetch_metadata(commit=False)
File "/app/superset/connectors/sqla/models.py", line 1247, in fetch_metadata
new_columns = self.external_metadata()
File "/app/superset/connectors/sqla/models.py", line 715, in external_metadata
return get_virtual_table_metadata(dataset=self)
File "/app/superset/connectors/sqla/utils.py", line 116, in get_virtual_table_metadata
raise SupersetSecurityException(
superset.exceptions.SupersetSecurityException: Only `SELECT` statements are allowed

### Expected results
Union-Statements within SQl WITH Clause should work properly. In best case if the DML feature would be disabled. 

### Actual results

Following Exception will raise: 
 value = f(*args, **kwargs)
File "/app/superset/views/base_api.py", line 93, in wraps
return f(self, *args, **kwargs)
File "/app/superset/datasets/api.py", line 315, in post
new_model = CreateDatasetCommand(item).run()
File "/app/superset/datasets/commands/create.py", line 50, in run
dataset.fetch_metadata(commit=False)
File "/app/superset/connectors/sqla/models.py", line 1247, in fetch_metadata
new_columns = self.external_metadata()
File "/app/superset/connectors/sqla/models.py", line 715, in external_metadata
return get_virtual_table_metadata(dataset=self)
File "/app/superset/connectors/sqla/utils.py", line 116, in get_virtual_table_metadata
raise SupersetSecurityException(
superset.exceptions.SupersetSecurityException: Only `SELECT` statements are allowed

#### Screenshots
see attachment

### Environment

(please complete the following information):

- browser type and version:
- superset version: superset 3.0.0
- python version: Python 3.9.18
- node.js version: v18.13.0
- any feature flags active: no

**Comment by rusackas** [comment]
Do you know if this is happening with other DBs, or if it's strictly an Oracle phenomenon? We don't have any oracle folks on the committer roster, so we could use help with an investigation/fix if you're open to it.

**Comment by rusackas** [comment]
Sadly, this is at risk of being closed as stale if nobody has interest in either reproducing or fixing the issue.

**Comment by rahmedrbx** [comment]
Can confirm that we are hitting a similar issue with a different DB (trino in our case)

**Comment by aleksei-perepelov** [comment]
@rahmedrbx Spent 2 hours trying to solve it. In my case enclosing CTEs with brackets helped, i.e.
```
with "a" as (),
"b" as (),
```
etc.
There a lot of issues that seem to be related to some one problem: https://github.com/apache/superset/issues/22704

**Comment by gulldan** [comment]
same with clickhouse

**Comment by Makarov-AA** [comment]
Same here, superset version 3.0.0, postgresql 16.8
I don't know why this issue is considered duplicate of https://github.com/apache/superset/issues/22704, can't see relation.
I use UNION in SQL Lab in request - everything is fine. As long as I use it in WITH AS statement - it breaks.

`SELECT * FROM a UNION SELECT * FROM b;` -- works fine.

```
WITH c AS (
	SELECT * FROM a UNION SELECT * FROM b
)
SELECT * FROM c;
```
breaks immediately with an error:

```
DB engine Error
Only SELECT statements are allowed against this database.

This may be triggered by:
Issue 1022 - Database does not allow data manipulation.
```

If I enable DML in dataset settings, everything works, but this is not an option.
Since UNION is not supported I have to come up with some weird ideas like OUTER JOIN ON FALSE to replace UNION

psql executes both requests just fine with read only user

**Comment by rusackas** [comment]
This may overlap with #22704 (SQL parsing/validation errors with complex queries), but the most recent comment suggests it may be distinct — the issue is specifically with `WITH ... AS` containing `UNION` failing at dataset save time, not at query execution time.

Before investing time in a fix, it would help to:
1. Confirm whether this still occurs on Superset 5.x (note: 3.0.0 is no longer supported)
2. Clarify whether the failure is during SQL parsing/validation (same root cause as #22704) or in a different code path

If you can reproduce on 5.x, please comment with the exact error message from the server logs.

**Comment by mason-gordon** [comment]
Using Superset 4.1.1 on a Postgres 17 database, I ran into a different stack trace that resulted in the same error while trying to save it as a dataset: Only `SELECT` statements are allowed.
```python
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 111, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 119, in wraps
superset_app          |     duration, response = time_function(f, self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1364, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/app/superset/utils/log.py", line 303, in wrapper
superset_app          |     value = f(*args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 91, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/datasets/api.py", line 337, in post
superset_app          |     new_model = CreateDatasetCommand(item).run()
superset_app          |   File "/app/superset/utils/decorators.py", line 266, in wrapped
superset_app          |     return on_error(ex)
superset_app          |   File "/app/superset/utils/decorators.py", line 236, in on_error
superset_app          |     raise ex
superset_app          |   File "/app/superset/utils/decorators.py", line 259, in wrapped
superset_app          |     result = func(*args, **kwargs)
superset_app          |   File "/app/superset/commands/dataset/create.py", line 51, in run
superset_app          |     dataset.fetch_metadata()
superset_app          |   File "/app/superset/connectors/sqla/models.py", line 1814, in fetch_metadata
superset_app          |     new_columns = self.external_metadata()
superset_app          |   File "/app/superset/connectors/sqla/models.py", line 1377, in external_metadata
superset_app          |     return get_virtual_table_metadata(dataset=self)
superset_app          |   File "/app/superset/connectors/sqla/utils.py", line 110, in get_virtual_table_metadata
superset_app          |     raise SupersetSecurityException(
superset_app          | superset.exceptions.SupersetSecurityException: Only `SELECT` statements are allowed
```

My query did not have a union, only CTEs. This suggestion from @rahmedrbx solved the problem.

> [@rahmedrbx](https://github.com/rahmedrbx) Spent 2 hours trying to solve it. In my case enclosing CTEs with brackets helped, i.e.
> 
> ```
> with "a" as (),
> "b" as (),
> ```
> 
> etc. There a lot of issues that seem to be related to some one problem: [#22704](https://github.com/apache/superset/issues/22704)
> 
> p.s. none of the things that have to do with TALISMAN or CSRF tokens helped.
