### ISSUE TITLE
Invalid token specified: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by philipchench** [apache/superset#26018]
We are using the npm package for superset-ui, and after trying to embed a dashboard, we get the following runtime error:

`
Uncaught runtime errors:
×
ERROR
Invalid token specified: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
InvalidTokenError
    at ./node_modules/jwt-decode/build/jwt-decode.esm.js (http://localhost:5001/static/js/bundle.js:6663:15)
    at options.factory (http://localhost:5001/static/js/bundle.js:42540:31)
    at __webpack_require__ (http://localhost:5001/static/js/bundle.js:41948:33)
    at fn (http://localhost:5001/static/js/bundle.js:42197:21)
    at ./node_modules/@superset-ui/embedded-sdk/lib/guestTokenRefresh.js (http://localhost:5001/static/js/bundle.js:693:41)
    at options.factory (http://localhost:5001/static/js/bundle.js:42540:31)
    at __webpack_require__ (http://localhost:5001/static/js/bundle.js:41948:33)
    at fn (http://localhost:5001/static/js/bundle.js:42197:21)
    at ./node_modules/@superset-ui/embedded-sdk/lib/index.js (http://localhost:5001/static/js/bundle.js:754:26)
    at options.factory (http://localhost:5001/static/js/bundle.js:42540:31)
`

Our code (our dashboards are named Inset but it's the same thing):

`
import { useEffect } from "react";
import { embedDashboard } from "@superset-ui/embedded-sdk";

export function SupersetDashboard(props) {
  useEffect(() => {

    const getGuestToken = async (token) => {
      const tokenRes = await fetch(
        `our api ... GetInsetBIToken?dashboardID=${token}`,
        {
          method: "POST",
          headers: {
            Accept: "*/*",
          },
        }
      );
      const tokenJSON = await tokenRes.json();
      console.log(tokenJSON.Data);
      return tokenJSON.Data;
    };

    embedDashboard({
      id: "sampleid"
      supersetDomain: "sampledomain",
      mountPoint: document.getElementById("inset-container"), // any html element that can contain an iframe
      fetchGuestToken: () => getGuestToken(),
      dashboardUiConfig: {
        hideTitle: true,
        hideTab: true,
        hideChartControls: false,
        filters: {
          expanded: true,
        },
      },
    });
  });

  return <div id="inset-container"></div>;
}

`

### Environment
- browser type and version: Google Chrome and Edge
- superset version: superset version 0.1.0-alpha.10 `
- node.js version: 16.20.2
- create-react-app: 5.0.1 (latest)

### Additional context
Note: all of this works if we use the SDK and an html page without React. We tried various environments, none worked if we use embedDashboard from the lib directory of the superset node module. The SDK works, but it produces errors in React so we could only use it in a pure html-js environment where there isn't any webpack/babel compilation.

**Comment by michael-s-molina** [comment]
Closing this issue given the version specified, 0.1.0-alpha.10, and assuming that the problem does not happen on current versions of Superset. Please reopen if that's not the case.
