### ISSUE TITLE
Database Error: Forbidden update upgrade to 3.0.1

### ISSUE THREAD

**Issue by xRomZak** [apache/superset#26030]
#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Execute any previously saved SQL 'SELECT' query
3. See error 'Database Error: Forbidden' on UI
4. FOREIGN KEY constraint failed in logs

```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: UPDATE tab_state SET changed_on=?, latest_query_id=?, changed_by_fk=? WHERE tab_state.id = ?]
```

Trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 177, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/superset/views/sql_lab/views.py", line 222, in put
    db.session.query(TabState).filter_by(id=tab_state_id).update(fields)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3306, in update
    result = self.session.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: UPDATE tab_state SET changed_on=?, latest_query_id=?, changed_by_fk=? WHERE tab_state.id = ?]
[parameters: ('2023-11-17 14:09:16.184557', 'JV-Xf8Vnh', 24, 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
(sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: UPDATE tab_state SET changed_on=?, sql=?, latest_query_id=?, changed_by_fk=? WHERE tab_state.id = ?]
[parameters: ('2023-11-17 14:09:29.701366', 'SELECT * from tender', 'Nz2KFFkbO', 6, 185)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: FOREIGN KEY constraint failed
```

### Expected results

Queries are executed as expected (before upgrade)

### Actual results

Failed to execute any query

#### Screenshots

![33AD301E-0D39-418B-A684-6C71EE5C0A4D](https://github.com/apache/superset/assets/1192819/6e3b435a-781b-4dcc-97c4-0183b3dd8f19)

### Environment
- superset 3.0.1
- deployment (as a container in OpenShift)
- database backend (sqlite - default setup)

<img width="201" alt="image" src="https://github.com/apache/superset/assets/1192819/3bf95277-1ada-4f6a-b85a-e9929b234bff">

![Screenshot2023_11_17_180445](https://github.com/apache/superset/assets/1192819/a60db4bc-eca1-41e0-887e-3ab6560c644f)

**Comment by michael-s-molina** [comment]
`latest_query_id` and `changed_by_fk` are foreign keys to other tables. The error happens because the value set for one of these columns is invalid. I bet is the `latest_query_id` which references `query.client_id` and that value might not exist anymore after the upgrade. To fix this, change your original query with a valid `query.client_id`.
