### ISSUE TITLE
StarRocks driver will not load: superset.databases.commands.exceptions.DatabaseTestConnectionDriverError: Could not load database driver: StarRocksEngineSpec

### ISSUE THREAD

**Issue by alberttwong** [apache/superset#26185]
using superset 3.0.2 with superset quickstart single image via https://superset.apache.org/docs/quickstart
```
2023-12-05 10:50:10 127.0.0.1 - - [05/Dec/2023:18:50:10 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.88.1"
2023-12-05 10:50:29 CommandException
2023-12-05 10:50:29 Traceback (most recent call last):
2023-12-05 10:50:29   File "/app/superset/databases/commands/test_connection.py", line 133, in run
2023-12-05 10:50:29     with database.get_sqla_engine_with_context(
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
2023-12-05 10:50:29     return next(self.gen)
2023-12-05 10:50:29   File "/app/superset/models/core.py", line 423, in get_sqla_engine_with_context
2023-12-05 10:50:29     yield self._get_sqla_engine(
2023-12-05 10:50:29   File "/app/superset/models/core.py", line 440, in _get_sqla_engine
2023-12-05 10:50:29     self.db_engine_spec.validate_database_uri(sqlalchemy_url)
2023-12-05 10:50:29   File "/app/superset/db_engine_specs/base.py", line 1920, in validate_database_uri
2023-12-05 10:50:29     sqlalchemy_uri.get_driver_name(), set()
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 624, in get_driver_name
2023-12-05 10:50:29     return self.get_dialect().driver
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 679, in get_dialect
2023-12-05 10:50:29     entrypoint = self._get_entrypoint()
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 661, in _get_entrypoint
2023-12-05 10:50:29     cls = registry.load(name)
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
2023-12-05 10:50:29     raise exc.NoSuchModuleError(
2023-12-05 10:50:29 sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:starrocks
2023-12-05 10:50:29 
2023-12-05 10:50:29 The above exception was the direct cause of the following exception:
2023-12-05 10:50:29 
2023-12-05 10:50:29 Traceback (most recent call last):
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023-12-05 10:50:29     rv = self.dispatch_request()
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
2023-12-05 10:50:29     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
2023-12-05 10:50:29     return f(self, *args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/views/base_api.py", line 127, in wraps
2023-12-05 10:50:29     raise ex
2023-12-05 10:50:29   File "/app/superset/views/base_api.py", line 121, in wraps
2023-12-05 10:50:29     duration, response = time_function(f, self, *args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/utils/core.py", line 1526, in time_function
2023-12-05 10:50:29     response = func(*args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/utils/log.py", line 255, in wrapper
2023-12-05 10:50:29     value = f(*args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/views/base_api.py", line 93, in wraps
2023-12-05 10:50:29     return f(self, *args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/databases/api.py", line 908, in test_connection
2023-12-05 10:50:29     TestConnectionDatabaseCommand(item).run()
2023-12-05 10:50:29   File "/app/superset/databases/commands/test_connection.py", line 178, in run
2023-12-05 10:50:29     raise DatabaseTestConnectionDriverError(
2023-12-05 10:50:29 superset.databases.commands.exceptions.DatabaseTestConnectionDriverError: Could not load database driver: StarRocksEngineSpec
2023-12-05 10:50:29 2023-12-05 18:50:29,545:WARNING:superset.views.base:CommandException
2023-12-05 10:50:29 Traceback (most recent call last):
2023-12-05 10:50:29   File "/app/superset/databases/commands/test_connection.py", line 133, in run
2023-12-05 10:50:29     with database.get_sqla_engine_with_context(
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
2023-12-05 10:50:29     return next(self.gen)
2023-12-05 10:50:29   File "/app/superset/models/core.py", line 423, in get_sqla_engine_with_context
2023-12-05 10:50:29     yield self._get_sqla_engine(
2023-12-05 10:50:29   File "/app/superset/models/core.py", line 440, in _get_sqla_engine
2023-12-05 10:50:29     self.db_engine_spec.validate_database_uri(sqlalchemy_url)
2023-12-05 10:50:29   File "/app/superset/db_engine_specs/base.py", line 1920, in validate_database_uri
2023-12-05 10:50:29     sqlalchemy_uri.get_driver_name(), set()
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 624, in get_driver_name
2023-12-05 10:50:29     return self.get_dialect().driver
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 679, in get_dialect
2023-12-05 10:50:29     entrypoint = self._get_entrypoint()
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 661, in _get_entrypoint
2023-12-05 10:50:29     cls = registry.load(name)
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
2023-12-05 10:50:29     raise exc.NoSuchModuleError(
2023-12-05 10:50:29 sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:starrocks
2023-12-05 10:50:29 
2023-12-05 10:50:29 The above exception was the direct cause of the following exception:
2023-12-05 10:50:29 
2023-12-05 10:50:29 Traceback (most recent call last):
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023-12-05 10:50:29     rv = self.dispatch_request()
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
2023-12-05 10:50:29     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-12-05 10:50:29   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
2023-12-05 10:50:29     return f(self, *args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/views/base_api.py", line 127, in wraps
2023-12-05 10:50:29     raise ex
2023-12-05 10:50:29   File "/app/superset/views/base_api.py", line 121, in wraps
2023-12-05 10:50:29     duration, response = time_function(f, self, *args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/utils/core.py", line 1526, in time_function
2023-12-05 10:50:29     response = func(*args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/utils/log.py", line 255, in wrapper
2023-12-05 10:50:29     value = f(*args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/views/base_api.py", line 93, in wraps
2023-12-05 10:50:29     return f(self, *args, **kwargs)
2023-12-05 10:50:29   File "/app/superset/databases/api.py", line 908, in test_connection
2023-12-05 10:50:29     TestConnectionDatabaseCommand(item).run()
2023-12-05 10:50:29   File "/app/superset/databases/commands/test_connection.py", line 178, in run
2023-12-05 10:50:29     raise DatabaseTestConnectionDriverError(
2023-12-05 10:50:29 superset.databases.commands.exceptions.DatabaseTestConnectionDriverError: Could not load database driver: StarRocksEngineSpec
2023-12-05 10:50:29 192.168.65.1 - - [05/Dec/2023:18:50:29 +0000] "POST /api/v1/database/test_connection/ HTTP/1.1" 422 265 "http://localhost:8080/databaseview/list/?pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
2023-12-05 10:50:41 127.0.0.1 - - [05/Dec/2023:18:50:41 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.88.1"
```

manually installed starrocks driver.
```
atwong@Albert-CelerData ~ % docker exec -it superset bash
superset@8a414c46c3de:/app$ pip install starrocks
Defaulting to user installation because normal site-packages is not writeable
Collecting starrocks
  Downloading starrocks-1.0.5-py3-none-any.whl (10 kB)
Requirement already satisfied: mysqlclient<3,>=2.1.0 in /usr/local/lib/python3.9/site-packages (from starrocks) (2.1.0)
Requirement already satisfied: sqlalchemy-utils<0.39,>=0.38.3 in /usr/local/lib/python3.9/site-packages (from starrocks) (0.38.3)
Requirement already satisfied: sqlalchemy<2,>=1.4 in /usr/local/lib/python3.9/site-packages (from starrocks) (1.4.36)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.9/site-packages (from sqlalchemy<2,>=1.4->starrocks) (3.0.1)
Installing collected packages: starrocks
Successfully installed starrocks-1.0.5

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
```

**Comment by alberttwong** [comment]
there was no instruction on how to load additional database drivers.   Had to use the docker-compose version.
