### ISSUE TITLE
Superset installation

### ISSUE THREAD

**Issue by duchuynh** [apache/superset#26241]
#### How to reproduce the bug

Run pip install apache-superset

### Expected results

installation of superset

### Actual results

ERROR: Exception:
Traceback (most recent call last):
  File "/home/vboxuser/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/vboxuser/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/vboxuser/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/vboxuser/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/home/vboxuser/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError

#### Screenshots

![image](https://github.com/apache/superset/assets/1304489/8e0c9fde-7dd3-44ab-ad82-6352589804d6)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by duchuynh** [comment]
Has anyone ever ran into this issue? I was able to download and install the program so many times before but this iteration it is not working for me.

**Comment by srinigup** [comment]
Try updating pip.

**Comment by BrunoMRTZ** [comment]
Try update pip to 23.3.1 
     pip install --upgrade pip, 
its working for me

**Comment by michael-s-molina** [comment]
Closing this assuming that upgrading pip will resolve the issue. Feel free to reopen if that's not the case.

**Comment by cozajeden** [comment]
I had the same problem today in Python 3.11
In Python 3.10 is working fine.

**Comment by RonyMacfly** [comment]
Its working. thx
```
python3.11 -m venv venv
source venv/bin/activate
pip install -U pip
pip install wheel apache-superset
```
