### ISSUE TITLE
Receiving:   werkzeug.exceptions.RequestEntityTooLarge: 413 Request Entity Too Large: The data value transmitted exceeds the capacity limit.

### ISSUE THREAD

**Issue by rabindragogoi** [apache/superset#26373]
When I am trying to add permissions to an existing role it is returning me 
 File "/opt/app-root/lib64/python3.11/site-packages/werkzeug/sansio/multipart.py", line 203, in next_event
    raise RequestEntityTooLarge()
werkzeug.exceptions.RequestEntityTooLarge: 413 Request Entity Too Large: The data value transmitted exceeds the capacity limit.

#### How to reproduce the bug

1. Go to 'Roles'
2. Click on 'any role that is created'
3. Add a policy
4. Click on Save

### Expected results

The role should get save properly with the new permission.

### Actual results

 File "/opt/app-root/lib64/python3.11/site-packages/werkzeug/sansio/multipart.py", line 203, in next_event
    raise RequestEntityTooLarge()
werkzeug.exceptions.RequestEntityTooLarge: 413 Request Entity Too Large: The data value transmitted exceeds the capacity limit.

### Additional context

By default the max decoded part what wrekzeug support is 1000. Since the size of the decoded part is more that 1000, it is throwing up the error.
https://forum.checkmk.com/t/request-entity-too-large-the-data-value-transmitted-exceeds-the-capacity-limit-web-log/40116

Superset Team: need a quick fix for this.

**Comment by pashtet04** [comment]
Do we need to increase `max_form_parts` for werkzeug? -- https://github.com/pallets/werkzeug/blob/817aac4d2c71b83752e451d23f96ac26cfd7bbcd/src/werkzeug/wrappers/request.py#L94

And how to achieve it?

**Comment by pashtet04** [comment]
I edit role directly in database

```
insert into ab_permission_view_role (id, permission_view_id, role_id)
values ('<id>', '<permission_view_id>', '<role_id>')
```

Where:
- <id> is a primary key
- <permission_view_id> is a id from `public.ab_permission_view`. You need to lookup for necessary pair of `permission_id` and `view_menu_id`, for example `permission_id = 121`, where `121 == can_execute_sql_query` and `view_menu_id = 4448`, where `4448 == SQLLab`
- <role_id> is a Role id in superset, you can view them from roles pages in url or in `ab_role` table

**Comment by dd-willgan** [comment]
For me, this was happening because we had too many users, but the number of permissions the role had was small. We patched our Superset changing this [line](https://github.com/apache/superset/blob/e0172a24b85f172b04cb37c4c94a5bb5e533e325/superset/security/manager.py#L144)

```
RoleModelView.edit_columns = ["name", "permissions", "user"]
```

to

```
RoleModelView.edit_columns = ["name", "permissions"]
```

Disables editing users in the List Roles page but let us edit the permissions again

**Comment by mertalpt** [comment]
@rusackas I am dealing with this now. Manual operations are a workaround but not a clean one. Do you know if there has been any development regarding this since the last update?

E: Stack trace if it helps:
```
2025-10-24T12:21:35.431Z [superset] 2025-10-24 12:21:35,418:WARNING:superset.views.error_handling:HTTPException
2025-10-24T12:21:35.431Z [superset] Traceback (most recent call last):
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1482, in full_dispatch_request
2025-10-24T12:21:35.431Z [superset]     rv = self.preprocess_request()
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1974, in preprocess_request
2025-10-24T12:21:35.431Z [superset]     rv = self.ensure_sync(before_func)()
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/flask_wtf/csrf.py", line 229, in csrf_protect
2025-10-24T12:21:35.431Z [superset]     self.protect()
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/flask_wtf/csrf.py", line 261, in protect
2025-10-24T12:21:35.431Z [superset]     validate_csrf(self._get_csrf_token())
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/flask_wtf/csrf.py", line 234, in _get_csrf_token
2025-10-24T12:21:35.431Z [superset]     base_token = request.form.get(field_name)
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/werkzeug/utils.py", line 107, in __get__
2025-10-24T12:21:35.431Z [superset]     value = self.fget(obj)  # type: ignore
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/werkzeug/wrappers/request.py", line 445, in form
2025-10-24T12:21:35.431Z [superset]     self._load_form_data()
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/flask/wrappers.py", line 114, in _load_form_data
2025-10-24T12:21:35.431Z [superset]     super()._load_form_data()
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/werkzeug/wrappers/request.py", line 271, in _load_form_data
2025-10-24T12:21:35.431Z [superset]     data = parser.parse(
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/werkzeug/formparser.py", line 242, in parse
2025-10-24T12:21:35.431Z [superset]     return parse_func(stream, mimetype, content_length, options)
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/werkzeug/formparser.py", line 267, in _parse_multipart
2025-10-24T12:21:35.431Z [superset]     form, files = parser.parse(stream, boundary, content_length)
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/werkzeug/formparser.py", line 413, in parse
2025-10-24T12:21:35.431Z [superset]     event = parser.next_event()
2025-10-24T12:21:35.431Z [superset]   File "/usr/local/lib/python3.10/dist-packages/werkzeug/sansio/multipart.py", line 205, in next_event
2025-10-24T12:21:35.431Z [superset]     raise RequestEntityTooLarge()
2025-10-24T12:21:35.431Z [superset] werkzeug.exceptions.RequestEntityTooLarge: 413 Request Entity Too Large: The data value transmitted exceeds the capacity limit.
2025-10-24T12:21:35.433Z [superset] 10.172.194.114 - - [24/Oct/2025:12:21:35 +0000] "POST /roles/edit/2 HTTP/1.1" 413 283 "https://superset.example.com/roles/edit/2" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
```

**Comment by kekwan** [comment]
+1. This is still an issue, at least on Superset 3.0.3. Have not tested on newer versions
