### ISSUE TITLE
Docker python requirements contains dependency conflicts (v2.1.3-3.x)

### ISSUE THREAD

**Issue by lucean** [apache/superset#26396]
When trying to install the dependencies listed in `requirements/docker.txt`, there is a conflict between event, greenlet and sqlalchemy - possibly missing the pinned greenlet version in `docker.in`?

#### How to reproduce the bug

1.) Checkout tag 2.1.3.
2.) Run the following command to install the python docker dependencies:

`pip install -r requirements/docker.txt`

### Expected results

All dependencies are resolved and installed.

### Actual results

The following error message is shown:

```
ERROR: Cannot install -r requirements/base.txt (line 262), gevent==21.8.0 and greenlet==2.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested greenlet==2.0.2
    sqlalchemy 1.4.36 depends on greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))
    gevent 21.8.0 depends on greenlet<2.0 and >=1.1.0; platform_python_implementation == "CPython"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### Environment

- browser type and version: N/A
- superset version: `2.1.3`
- python version: `3.9.18`
- node.js version: N/A
- any feature flags active: N/A

**Comment by rusackas** [comment]
Is this an issue in Superset 3.x? Tempted to close this since we don't actively support 2.x any more, but please advise.

**Comment by Sabutobi** [comment]
hey @rusackas . I've met that with the 3.0 version:
```

#0 27.67      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 41.5 MB/s eta 0:00:00
#0 27.70 INFO: pip is looking at multiple versions of pyhive to determine which version is compatible with other requirements. This could take a while.
#0 27.70 INFO: pip is looking at multiple versions of apispec to determine which version is compatible with other requirements. This could take a while.
#0 27.70 INFO: pip is looking at multiple versions of trino[sqlalchemy] to determine which version is compatible with other requirements. This could take a while.
#0 27.72 INFO: pip is looking at multiple versions of httpx to determine which version is compatible with other requirements. This could take a while.
#0 27.73 Collecting httpx<0.24.0,>=0.23.0
#0 27.74   Downloading httpx-0.23.2-py3-none-any.whl (86 kB)
#0 27.74      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.2/86.2 kB 253.2 MB/s eta 0:00:00
#0 27.80   Downloading httpx-0.23.1-py3-none-any.whl (84 kB)
#0 27.81      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 kB 255.8 MB/s eta 0:00:00
#0 27.88   Downloading httpx-0.23.0-py3-none-any.whl (84 kB)
#0 27.88      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 126.6 MB/s eta 0:00:00
#0 27.92 Collecting httpcore<0.16.0,>=0.15.0
#0 27.92   Downloading httpcore-0.15.0-py3-none-any.whl (68 kB)
#0 27.93      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.4/68.4 kB 240.5 MB/s eta 0:00:00
#0 27.96 INFO: pip is looking at multiple versions of greenlet to determine which version is compatible with other requirements. This could take a while.
#0 27.97 Collecting greenlet!=0.4.17
#0 27.98   Downloading greenlet-3.0.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (647 kB)
#0 27.98      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 647.6/647.6 kB 325.7 MB/s eta 0:00:00
#0 28.19 INFO: pip is looking at multiple versions of httpx to determine which version is compatible with other requirements. This could take a while.
#0 28.21   Downloading greenlet-3.0.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (647 kB)
#0 28.21      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 647.4/647.4 kB 277.4 MB/s eta 0:00:00
#0 28.44   Downloading greenlet-3.0.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (647 kB)
#0 28.44      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 647.2/647.2 kB 296.0 MB/s eta 0:00:00
#0 28.52 INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
#0 28.66   Downloading greenlet-2.0.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (607 kB)
#0 28.67      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 607.6/607.6 kB 206.6 MB/s eta 0:00:00
#0 28.89   Downloading greenlet-2.0.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (526 kB)
#0 28.90      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.1/526.1 kB 337.9 MB/s eta 0:00:00
#0 29.12   Downloading greenlet-2.0.0.post0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (523 kB)
#0 29.12      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 523.4/523.4 kB 275.8 MB/s eta 0:00:00
#0 29.35   Downloading greenlet-2.0.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (523 kB)
#0 29.36      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 523.3/523.3 kB 264.8 MB/s eta 0:00:00
#0 29.60 INFO: pip is looking at multiple versions of greenlet to determine which version is compatible with other requirements. This could take a while.
#0 29.61   Downloading greenlet-1.1.3.post0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (155 kB)
#0 29.62      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 282.5 MB/s eta 0:00:00
#0 29.84   Downloading greenlet-1.1.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (155 kB)
#0 29.84      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 294.6 MB/s eta 0:00:00
#0 30.06   Downloading greenlet-1.1.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (154 kB)
#0 30.07      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.8/154.8 kB 292.8 MB/s eta 0:00:00
#0 30.29   Downloading greenlet-1.1.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (148 kB)
#0 30.29      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.2/148.2 kB 287.2 MB/s eta 0:00:00
#0 30.52   Downloading greenlet-1.1.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (163 kB)
#0 30.53      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.2/163.2 kB 303.1 MB/s eta 0:00:00
#0 30.73 INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
#0 30.75   Downloading greenlet-1.0.0-cp39-cp39-manylinux2014_aarch64.whl (162 kB)
#0 30.75      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.9/162.9 kB 288.3 MB/s eta 0:00:00
#0 31.00   Downloading greenlet-0.4.16.tar.gz (60 kB)
#0 31.00      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 242.9 MB/s eta 0:00:00
#0 31.02   Preparing metadata (setup.py): started
#0 31.21   Preparing metadata (setup.py): finished with status 'done'
#0 31.42   Downloading greenlet-0.4.15.tar.gz (59 kB)
#0 31.43      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 216.2 MB/s eta 0:00:00
#0 31.44   Preparing metadata (setup.py): started
#0 31.61   Preparing metadata (setup.py): finished with status 'done'
#0 31.83   Downloading greenlet-0.4.14.tar.gz (59 kB)
#0 31.83      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 kB 213.5 MB/s eta 0:00:00
#0 31.85   Preparing metadata (setup.py): started
#0 32.02   Preparing metadata (setup.py): finished with status 'done'
#0 32.24   Downloading greenlet-0.4.13.tar.gz (58 kB)
#0 32.24      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.4/58.4 kB 120.3 MB/s eta 0:00:00
#0 32.27   Preparing metadata (setup.py): started
#0 32.45   Preparing metadata (setup.py): finished with status 'done'
#0 32.67   Downloading greenlet-0.4.12.tar.gz (57 kB)
#0 32.67      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 127.6 MB/s eta 0:00:00
#0 32.69   Preparing metadata (setup.py): started
#0 32.87   Preparing metadata (setup.py): finished with status 'done'
#0 33.09   Downloading greenlet-0.4.11.zip (82 kB)
#0 33.10      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.9/82.9 kB 235.0 MB/s eta 0:00:00
#0 33.11   Preparing metadata (setup.py): started
#0 33.28   Preparing metadata (setup.py): finished with status 'done'
#0 33.50   Downloading greenlet-0.4.10.zip (82 kB)
#0 33.50      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.6/82.6 kB 238.0 MB/s eta 0:00:00
#0 33.51   Preparing metadata (setup.py): started
#0 33.69   Preparing metadata (setup.py): finished with status 'done'
#0 33.93   Downloading greenlet-0.4.9.zip (78 kB)
#0 33.93      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.1/78.1 kB 222.2 MB/s eta 0:00:00
#0 33.94   Preparing metadata (setup.py): started
#0 34.12   Preparing metadata (setup.py): finished with status 'done'
#0 34.33   Downloading greenlet-0.4.7.zip (77 kB)
#0 34.33      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.5/77.5 kB 234.2 MB/s eta 0:00:00
#0 34.34   Preparing metadata (setup.py): started
#0 34.52   Preparing metadata (setup.py): finished with status 'done'
#0 34.74   Downloading greenlet-0.4.6.zip (77 kB)
#0 34.75      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 110.6 MB/s eta 0:00:00
#0 34.76   Preparing metadata (setup.py): started
#0 34.94   Preparing metadata (setup.py): finished with status 'done'
#0 35.17   Downloading greenlet-0.4.5.zip (77 kB)
#0 35.17      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 133.7 MB/s eta 0:00:00
#0 35.18   Preparing metadata (setup.py): started
#0 35.36   Preparing metadata (setup.py): finished with status 'done'
#0 35.62   Downloading greenlet-0.4.4.zip (76 kB)
#0 35.62      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 127.2 MB/s eta 0:00:00
#0 35.64   Preparing metadata (setup.py): started
#0 35.83   Preparing metadata (setup.py): finished with status 'done'
#0 36.10   Downloading greenlet-0.4.3.zip (76 kB)
#0 36.12      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.5/76.5 kB 145.4 MB/s eta 0:00:00
#0 36.13   Preparing metadata (setup.py): started
#0 36.32   Preparing metadata (setup.py): finished with status 'done'
#0 36.54   Downloading greenlet-0.4.2.zip (74 kB)
#0 36.55      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 211.8 MB/s eta 0:00:00
#0 36.56   Preparing metadata (setup.py): started
#0 36.74   Preparing metadata (setup.py): finished with status 'done'
#0 36.97   Downloading greenlet-0.4.1.zip (75 kB)
#0 36.97      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.7/75.7 kB 240.9 MB/s eta 0:00:00
#0 36.98   Preparing metadata (setup.py): started
#0 37.20   Preparing metadata (setup.py): finished with status 'done'
#0 37.41   Downloading greenlet-0.4.0.zip (72 kB)
#0 37.42      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.8/72.8 kB 216.1 MB/s eta 0:00:00
#0 37.43   Preparing metadata (setup.py): started
#0 37.60   Preparing metadata (setup.py): finished with status 'done'
#0 37.82   Downloading greenlet-0.3.4.zip (63 kB)
#0 37.82      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB 226.3 MB/s eta 0:00:00
#0 37.83   Preparing metadata (setup.py): started
#0 38.01   Preparing metadata (setup.py): finished with status 'done'
#0 38.22   Downloading greenlet-0.3.3.zip (65 kB)
#0 38.22      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.6/65.6 kB 191.9 MB/s eta 0:00:00
#0 38.24   Preparing metadata (setup.py): started
#0 38.42   Preparing metadata (setup.py): finished with status 'done'
#0 38.63   Downloading greenlet-0.3.2.zip (50 kB)
#0 38.63      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.3/50.3 kB 194.3 MB/s eta 0:00:00
#0 38.64   Preparing metadata (setup.py): started
#0 38.81   Preparing metadata (setup.py): finished with status 'done'
#0 39.06   Downloading greenlet-0.3.1.tar.gz (39 kB)
#0 39.07   Preparing metadata (setup.py): started
#0 39.25   Preparing metadata (setup.py): finished with status 'done'
#0 39.46   Downloading greenlet-0.3.tar.gz (37 kB)
#0 39.47   Preparing metadata (setup.py): started
#0 39.64   Preparing metadata (setup.py): finished with status 'done'
#0 39.85   Downloading greenlet-0.2.tar.gz (22 kB)
#0 39.85   Preparing metadata (setup.py): started
#0 39.99   Preparing metadata (setup.py): finished with status 'error'
#0 40.00   error: subprocess-exited-with-error
#0 40.00   
#0 40.00   × python setup.py egg_info did not run successfully.
#0 40.00   │ exit code: 1
#0 40.00   ╰─> [9 lines of output]
#0 40.00       Traceback (most recent call last):
#0 40.00         File "<string>", line 2, in <module>
#0 40.00         File "<pip-setuptools-caller>", line 34, in <module>
#0 40.00         File "/tmp/pip-install-b59uf0b5/greenlet_341b387606bf4c97840227c86d05e1e4/setup.py", line 3, in <module>
#0 40.00           import ez_setup
#0 40.00         File "/tmp/pip-install-b59uf0b5/greenlet_341b387606bf4c97840227c86d05e1e4/ez_setup/__init__.py", line 98
#0 40.00           except pkg_resources.VersionConflict, e:
#0 40.00                                               ^
#0 40.00       SyntaxError: invalid syntax
#0 40.00       [end of output]
#0 40.00   
#0 40.00   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 40.00 error: metadata-generation-failed
#0 40.00 
#0 40.00 × Encountered error while generating package metadata.
#0 40.00 ╰─> See above for output.
#0 40.00 
#0 40.00 note: This is an issue with the package mentioned above, not pip.
#0 40.00 hint: See above for details.
#0 40.10 
#0 40.10 [notice] A new release of pip is available: 23.0.1 -> 24.0
#0 40.10 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:101
--------------------
 100 |     
 101 | >>> RUN mkdir -p superset/static \
 102 | >>>     && touch superset/static/version_info.json \
 103 | >>>     && pip install --no-cache-dir -r requirements/local.txt
 104 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir -p superset/static     && touch superset/static/version_info.json     && pip install --no-cache-dir -r requirements/local.txt" did not complete successfully: exit code: 1

Exited with code exit status 1
```

**Comment by rusackas** [comment]
CC @mistercrunch who is probably more up-to-speed on these platform dependency issues in docker than most folks.

**Comment by mistercrunch** [comment]
Hoping this may be the longer term solution -> https://github.com/apache/superset/pull/27465

In the meantime personally won't spend cycles towards 2.x, got my eyes on 4.x more than 2.x...

G'luck!

**Comment by rusackas** [comment]
Right... just seeking tips (and leaving this open) since it's a 3.x issue as well. I'll adjust the title so it doesn't dissuade others.

**Comment by rusackas** [comment]
I don't think this is relevant any more since there is no longer a `requirements/docker.txt`. Correct me if I'm wrong, and help me understand if there are issues still pertaining to 3.1/4.0/4.1.
