### ISSUE TITLE
Superset 3.0.2 Public Googlesheet can be read without service account credentials but throws error when you add creds

### ISSUE THREAD

**Issue by rajivpatki** [apache/superset#26452]
#### How to reproduce the bug

1. Create a public google sheet
2. Add the google sheet as database to your Superset 3.0.2. It works just fine and data show up
3. Now delete this and this time when adding google sheet database select Public and Private Sheets and provide your service account credentials (by file or by text, doesn't matter)

### Expected results

Since sheet is public it should be read no matter the credentials. 

### Actual results

On adding the credentials, you see on the interface The URL could not be identified. Please check for typos and make sure that ‘Type of Google Sheets allowed’ selection matches the input
![image](https://github.com/apache/superset/assets/54361216/05d7f955-2dba-45c2-86dd-88abbf8ff4cf)

In superset logs you see:
```
superset              | 2024-01-10 15:10:23,177:WARNING:superset.views.base:SupersetErrorsException
superset              | Traceback (most recent call last):
superset              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset              |     rv = self.dispatch_request()
superset              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
superset              |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset              |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset              |     return f(self, *args, **kwargs)
superset              |   File "/app/superset/views/base_api.py", line 127, in wraps
superset              |     raise ex
superset              |   File "/app/superset/views/base_api.py", line 121, in wraps
superset              |     duration, response = time_function(f, self, *args, **kwargs)
superset              |   File "/app/superset/utils/core.py", line 1526, in time_function
superset              |     response = func(*args, **kwargs)
superset              |   File "/app/superset/utils/log.py", line 255, in wrapper
superset              |     value = f(*args, **kwargs)
superset              |   File "/app/superset/views/base_api.py", line 93, in wraps
superset              |     return f(self, *args, **kwargs)
superset              |   File "/app/superset/databases/api.py", line 1433, in validate_parameters
superset              |     command.run()
superset              |   File "/app/superset/databases/commands/validate.py", line 72, in run
superset              |     raise InvalidParametersError(errors)
superset              | superset.databases.commands.exceptions.InvalidParametersError: [SupersetError(message='The URL could not be identified. Please check for typos and make sure that ‘Type of Google Sheets allowed’ selection matches the input.', error_type=<SupersetErrorType.TABLE_DOES_NOT_EXIST_ERROR: 'TABLE_DOES_NOT_EXIST_ERROR'>, level=<ErrorLevel.WARNING: 'warning'>, extra={'catalog': {'idx': 0, 'url': True}, 'issue_codes': [{'code': 1003, 'message': 'Issue 1003 - There is a syntax error in the SQL query. Perhaps there was a misspelling or a typo.'}, {'code': 1005, 'message': 'Issue 1005 - The table was deleted or renamed in the database.'}]})]
```

### Environment
browser type and version: Microsoft Edge Version 120.0.2210.91 (Official build) (64-bit)
superset version: 3.0.2 from official docker image
any feature flags active:
```TALISMAN_ENABLED = True
SECRET_KEY = "SUPERSET_SECRET_KEY"
WTF_CSRF_ENABLED = True

FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [✓] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [✓] I have reproduced the issue with at least the latest released version of superset.
- [✓] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

- It seems that the credentials are not being properly read by `superset/db_engine_specs/gsheets.py`
- In python, json.loads on this json does not work because it cannot read `\n` characters. 
- I tried to replace `gsheets.py` with `strict = False` for `json.loads` but that did not work
- I also tried replacing `\n` with `\\n` but that too throws the same error

**Comment by rusackas** [comment]
Are you still facing this? Tempted to close as stale, assuming you figured something out. I know we're using a ton of google sheets with credentials at Preset, so I suspect there's something in the credentials causing a problem (maybe a character like an @ or something), or this was an intermittent bug that came and went. As a side note, you should set a new secret key, too ;)

Let's see if our shiny new bot has more advice:

@dosu-bot

**Comment by rajivpatki** [comment]
> Are you still facing this? Tempted to close as stale, assuming you figured something out. I know we're using a ton of google sheets with credentials at Preset, so I suspect there's something in the credentials causing a problem (maybe a character like an @ or something), or this was an intermittent bug that came and went. As a side note, you should set a new secret key, too ;)
> 
> Let's see if our shiny new bot has more advice:
> 
> @dosu-bot

This issue still exists for me in Superset 3.1.2. Our "workaround" is not ideal, we have to schedule a script to regularly update another database with the googlesheet contents

If I don't provide any credentials.json for a pulicly shared sheet, the connection works fine. As soon as credentials are specified I get the error "The URL could not be identified. Please check for typos and make sure that ‘Type of Google Sheets allowed’ selection matches the input." which is the same error that I get for private sheets. 

1. These credentials work with a python script using gspread so there are no auth or access issues
2. I have tried using the credentials.json file as is as downloaded when the key is created for the service account
3. I have also tried to escape /n as //n but that does not work either. It works in the python script either way

**Comment by rajivpatki** [comment]
@dosu 

I also tested using a public google sheet that was also shared with the service account email address. The connection works fine without the credentials. If I supply any credentials, the error that I mentioned earlier shows up.

**Comment by dmuldoonadl** [comment]
Seeing this behavior on 4.0.2 as well.

**Comment by rusackas** [comment]
I don't see _this_ error, but I am seeing other bugs when I try to reproduce it (i.e. the connection fails but the UI tries (and fails) to move along as if it didn't. @betodealmeida would be most qualified to take a look here, but @sadpandajoe may be interested to try as well.

**Comment by farovictor** [comment]
I have the exact same error.

When trying to create a database and specify a sheet url:

![Image](https://github.com/user-attachments/assets/63e56c97-bfcd-46e0-bf0d-a81228b8ccb3)

When checking servers logs:

![Image](https://github.com/user-attachments/assets/af733ff3-a973-41a8-9df3-ac4b30066f07)

So, I added the connection with no sheets register to it. When opening SQL Lab, selecting my gsheet database and performing a sql over my sheet, I get this:

![Image](https://github.com/user-attachments/assets/9592e784-7706-4d32-a405-68ab0ecaf939)

**Comment by betodealmeida** [comment]
I can't repro this with a personal access token. Can someone who has a service account help me troubleshoot? Run this Python script and then copy-and-past the stack trace:

```python
from shillelagh.backends.apsw.db import connect

if __name__ == "__main__":
    connection = connect(
        ":memory:",
        adapter_kwargs={
            "gsheetsapi": {
                "service_account_file": "/path/to/your/service_account.json",
            }
        },
    )
    cursor = connection.cursor()

    SQL = """
    SELECT *
    FROM "https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/edit#gid=1648320094"
    """
    for row in cursor.execute(SQL):
        print(row)
```

**Comment by min-awm** [comment]
You must use a Google Workspace account and configure Domain-Wide Delegation if you use subject. For regular (personal) Google accounts, just delete the subject in file superset/db_engine_specs/gsheets.py.
<img width="1227" height="476" alt="Image" src="https://github.com/user-attachments/assets/1dba0a8a-8712-44b3-8fc6-aa15f5f2144a" />

**Comment by dennispan** [comment]
Running into the same. Exact same error as mentioned in https://github.com/apache/superset/issues/26452#issuecomment-2832793804

We are on `4.1.2`.

**Comment by dennispan** [comment]
@betodealmeida Here's the error I get when running your test script

```
Traceback (most recent call last):
  File "/Users/dennis.pan/code/tmp/.venv/lib/python3.11/site-packages/shillelagh/backends/apsw/db.py", line 202, in execute
    self._cursor.execute(operation, parameters)
  File "src/cursor.c", line 1062, in APSWCursor_execute.sqlite3_prepare_v3
apsw.SQLError: no such table: https://docs.google.com/spreadsheets/d/1Rn6gQOwfGJiN......2ba3mWc/edit?usp=sharing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dennis.pan/code/tmp/test.py", line 18, in <module>
    for row in cursor.execute(SQL):
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/dennis.pan/code/tmp/.venv/lib/python3.11/site-packages/shillelagh/db.py", line 84, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dennis.pan/code/tmp/.venv/lib/python3.11/site-packages/shillelagh/backends/apsw/db.py", line 213, in execute
    self._create_table(uri)
  File "/Users/dennis.pan/code/tmp/.venv/lib/python3.11/site-packages/shillelagh/backends/apsw/db.py", line 276, in _create_table
    adapter, args, kwargs = find_adapter(uri, self._adapter_kwargs, self._adapters)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dennis.pan/code/tmp/.venv/lib/python3.11/site-packages/shillelagh/lib.py", line 587, in find_adapter
    raise ProgrammingError(f"Unsupported table: {uri}")
shillelagh.exceptions.ProgrammingError: Unsupported table: https://docs.google.com/spreadsheets/d/1Rn6gQOwfGJiN......2ba3mWc/edit?usp=sharing
```

**Comment by rewert** [comment]
> You must use a Google Workspace account and configure Domain-Wide Delegation if you use subject. For regular (personal) Google accounts, just delete the subject in file superset/db_engine_specs/gsheets.py. <img alt="Image" width="1227" height="476" src="https://private-user-images.githubusercontent.com/73045983/472926401-1dba0a8a-8712-44b3-8fc6-aa15f5f2144a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ4NjMwOTMsIm5iZiI6MTc2NDg2Mjc5MywicGF0aCI6Ii83MzA0NTk4My80NzI5MjY0MDEtMWRiYTBhOGEtODcxMi00NGIzLThmYzYtYWExNWY1ZjIxNDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA0VDE1Mzk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMzQ0NTM5ZTE0MWI4MTdlZTAwZWI2MDM2MzRmMGMyZDg3NTJkYjk3OWVhMzJmMDkxNjliNzNlMWUxZmQ5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u9sxqpvbDsP36NhWjY3Qcs725bYQOlw5tFKwEgcAx1M">

This in combination with removing subject from lib.py works.
(removing "if username is not None:" block from get_url_for_impersonation in gsheets.py is also needed)
Just removing subject from gsheets.py gets you past the adding database connection error, but if we try to create dataset from it, we get error again.
Removing subject from "if service_account_info:" and "if service_account_file:" as well as "if username is not None:" block from get_url_for_impersonation in lib.py get_credentials function enables us to create datasets from it because with it, it still tries to use the email from superset user instead of token provided.

**Comment by rusackas** [comment]
Per the discussion, this stems from Google service-account configuration (Domain-Wide Delegation / the `subject` setting in the GSheets engine spec) rather than a Superset code defect. Closing as a configuration issue — please reopen if you believe Superset is mishandling valid public-sheet credentials.
