### ISSUE TITLE
Delayed page activities in SQL Lab

### ISSUE THREAD

**Issue by fzhan** [apache/superset#27009]
### Bug description
There's appears to be delay activities in SQL, where tabs won't get added, sql result doesn't show, and 'Run in SQL' does not add a new tab

### How to reproduce the bug

1. When running SQL, returnes "Database error Update failed"
2. After a refresh, shows 'pending' 
3. When close the tab, display:
 ``` {
    "errors": [
        {
            "message": "Instance '<TabState at 0x7fd77ecd0e80>' has been deleted, or its row is otherwise not present.",
            "error_type": "GENERIC_BACKEND_ERROR",
            "level": "error",
            "extra": {
                "issue_codes": [
                    {
                        "code": 1011,
                        "message": "Issue 1011 - Superset encountered an unexpected error."
                    }
                ]
            }
        }
    ]
} 
```
5. checking the log, display:
```
superset.views.base:Instance '<TabState at 0x7fd77ecd0e80>' has been deleted, or its row is otherwise not present.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 177, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/sql_lab/views.py", line 110, in post
    return json_success(json.dumps({"id": tab_state.id}))
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 481, in __get__
    return self.impl.get(state, dict_)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 941, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 972, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 710, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1465, in load_scalar_attributes
    raise orm_exc.ObjectDeletedError(state)
sqlalchemy.orm.exc.ObjectDeletedError: Instance '<TabState at 0x7fd77ecd0e80>' has been deleted, or its row is otherwise not present.
```

My superset-config.py:
```import os
from flask_caching.backends.rediscache import RedisCache

def env(key, default=None):
    return os.getenv(key, default)

MAPBOX_API_KEY = env('MAPBOX_API_KEY', '')
CACHE_CONFIG = {
      'CACHE_TYPE': 'RedisCache',
      'CACHE_DEFAULT_TIMEOUT': 300,
      'CACHE_KEY_PREFIX': 'superset_',
      'CACHE_REDIS_HOST': env('REDIS_HOST'),
      'CACHE_REDIS_PORT': env('REDIS_PORT'),
      'CACHE_REDIS_PASSWORD': env('REDIS_PASSWORD'),
      'CACHE_REDIS_DB': env('REDIS_DB', 1),
}
DATA_CACHE_CONFIG = CACHE_CONFIG

SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{env('DB_USER')}:{env('DB_PASS')}@{env('DB_HOST')}:{env('DB_PORT')}/{env('DB_NAME')}"
SQLALCHEMY_TRACK_MODIFICATIONS = True

class CeleryConfig:
  imports  = ("superset.sql_lab", )
  broker_url = f"redis://:{env('REDIS_PASSWORD')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/0"
  result_backend = f"redis://:{env('REDIS_PASSWORD')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/0"

CELERY_CONFIG = CeleryConfig
RESULTS_BACKEND = RedisCache(
      host=env('REDIS_HOST'),
      password=env('REDIS_PASSWORD'),
      port=env('REDIS_PORT'),
      key_prefix='superset_results'
)


# Overrides
# additional_config
APP_NAME = 'BI'
SUPERSET_WEBSERVER_PROTOCOL = os.getenv("SUPERSET_WEBSERVER_PROTOCOL","https")
EMAIL_REPORTS_SUBJECT_PREFIX = os.getenv("EMAIL_REPORTS_SUBJECT_PREFIX","BI] ")
ENABLE_PROXY_FIX = True
RATELIMIT_ENABLED = False 
AUTH_RATE_LIMITED = False
DEFAULT_FEATURE_FLAGS: dict[str, bool] = {
    "CLIENT_CACHE": False,  # deprecated
    "DISABLE_DATASET_SOURCE_EDIT": False,  # deprecated
    "DRUID_JOINS": False,
    "DYNAMIC_PLUGINS": False,
    "DISABLE_LEGACY_DATASOURCE_EDITOR": True,
    "ENABLE_EXPLORE_JSON_CSRF_PROTECTION": False,  # deprecated
    "ENABLE_TEMPLATE_PROCESSING": False,
    "ENABLE_TEMPLATE_REMOVE_FILTERS": True,  # deprecated
    "ENABLE_JAVASCRIPT_CONTROLS": False,
    "KV_STORE": False,
    "PRESTO_EXPAND_DATA": False,
    "THUMBNAILS": True,
    "THUMBNAILS_SQLA_LISTENERS": True,
    "DASHBOARD_CACHE": False,  # deprecated
    "REMOVE_SLICE_LEVEL_LABEL_COLORS": False,  # deprecated
    "SHARE_QUERIES_VIA_KV_STORE": False,
    "TAGGING_SYSTEM": True,
    "SQLLAB_BACKEND_PERSISTENCE": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW": False,
    "ESCAPE_MARKDOWN_HTML": False,
    "DASHBOARD_NATIVE_FILTERS": True,  # deprecated
    "DASHBOARD_CROSS_FILTERS": True,
    "DASHBOARD_NATIVE_FILTERS_SET": False,  # deprecated
    "DASHBOARD_FILTERS_EXPERIMENTAL": False,  # deprecated
    "DASHBOARD_VIRTUALIZATION": False,
    "GLOBAL_ASYNC_QUERIES": False,
    "VERSIONED_EXPORT": True,  # deprecated
    "EMBEDDED_SUPERSET": False,
    "ALERT_REPORTS": True,
    "DASHBOARD_RBAC": False,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,  # deprecated
    "ENABLE_ADVANCED_DATA_TYPES": False,
    "ALERTS_ATTACH_REPORTS": True,
    "ALLOW_FULL_CSV_EXPORT": False,
    "GENERIC_CHART_AXES": True,  # deprecated
    "ALLOW_ADHOC_SUBQUERY": False,
    "USE_ANALAGOUS_COLORS": False,
    "RLS_IN_SQLLAB": False,
    "CACHE_IMPERSONATION": False,
    "CACHE_QUERY_BY_USER": False,
    "EMBEDDABLE_CHARTS": True,
    "DRILL_TO_DETAIL": True,
    "DRILL_BY": False,
    "DATAPANEL_CLOSED_BY_DEFAULT": False,
    "HORIZONTAL_FILTER_BAR": False,
    "ESTIMATE_QUERY_COST": False,
    "SSH_TUNNELING": False,
    "AVOID_COLORS_COLLISION": True,
    "MENU_HIDE_USER_INFO": False,
    "ENABLE_SUPERSET_META_DB": True,
    "PLAYWRIGHT_REPORTS_AND_THUMBNAILS": False,
}

# cache_config
from superset.tasks.types import ExecutorType

CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 60 * 60 * 24,
    'CACHE_KEY_PREFIX': 'superset_',
    'CACHE_REDIS_URL': f"redis://:{env('REDIS_PASS')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/1"
}

DATA_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 60 * 60 * 24, # 1 day default (in secs)
    'CACHE_KEY_PREFIX': 'superset_results',
    'CACHE_REDIS_URL': f"redis://:{env('REDIS_PASS')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/2"
}

FILTER_STATE_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 60 * 60 * 24, # 1 day default (in secs)
    'CACHE_KEY_PREFIX': 'superset_filter_state',
    'CACHE_REDIS_URL': f"redis://:{env('REDIS_PASS')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/4"
}

THUMBNAIL_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 24*60*60*7,
    'CACHE_KEY_PREFIX': 'thumbnail_',
    'CACHE_REDIS_URL': f"redis://:{env('REDIS_PASS')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/3"
}

THUMBNAIL_SELENIUM_USER = "admin"
THUMBNAIL_EXECUTE_AS = [ExecutorType.SELENIUM]

# celery_conf
from celery.schedules import crontab

class CeleryConfig:
  broker_url = f"redis://:{env('REDIS_PASS')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/0"
  imports = (
      "superset.sql_lab",
      "superset.tasks.cache",
      "superset.tasks.scheduler",
  )
  result_backend = f"redis://:{env('REDIS_PASS')}@{env('REDIS_HOST')}:{env('REDIS_PORT')}/0"
  worker_prefetch_multiplier = 10
  task_acks_late = True
  task_annotations = {
      "sql_lab.get_sql_results": {
          "rate_limit": "100/s",
      },
  }
  beat_schedule = {
      "reports.scheduler": {
          "task": "reports.scheduler",
          "schedule": crontab(minute="*", hour="*"),
      },
      "reports.prune_log": {
          "task": "reports.prune_log",
          'schedule': crontab(minute=0, hour=0),
      },
      'cache-warmup-hourly': {
          "task": "cache-warmup",
          "schedule": crontab(minute="*/30", hour="*"),
          "kwargs": {
              "strategy_name": "top_n_dashboards",
              "top_n": 10,
              "since": "7 days ago",
          },
      }
  }

CELERY_CONFIG = CeleryConfig

# enable_oauth
import sys
sys.path.append('/app/configs/')
print (sys.path)
from flask_appbuilder.security.manager import AUTH_OAUTH
from custom_sso_security_manager import CustomSsoSecurityManager

CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager # For managing User data after fetching from SSO app

AUTH_TYPE = AUTH_OAUTH
OAUTH_PROVIDERS = [
  {   
    'name':'azure',
      'token_key':'access_token', # Name of the token in the response of access_token_url
      'icon':'fa-address-card',   # Icon for the provider
      'remote_app': {
...
      }
  }
]
AUTH_ROLE_PUBLIC = 'Public'
AUTH_USER_REGISTRATION = True

# extend_timeout
# Extend timeout to allow long running queries.
SUPERSET_WEBSERVER_TIMEOUT = 300

# feature_flags
import ast

FEATURE_FLAGS = {
    "ALERT_REPORTS": True
}

SMTP_HOST = os.getenv("SMTP_HOST","localhost")
SMTP_STARTTLS = ast.literal_eval(os.getenv("SMTP_STARTTLS", "True"))
SMTP_SSL = ast.literal_eval(os.getenv("SMTP_SSL", "False"))
SMTP_USER = os.getenv("SMTP_USER","superset")
SMTP_PORT = os.getenv("SMTP_PORT",25)
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD","superset")
SMTP_MAIL_FROM = os.getenv("SMTP_MAIL_FROM","superset@superset.com")

SLACK_API_TOKEN = os.getenv("SLACK_API_TOKEN",None)

# reports
EMAIL_PAGE_RENDER_WAIT = 60
WEBDRIVER_BASEURL = "http://superset:8088/"
WEBDRIVER_BASEURL_USER_FRIENDLY = os.getenv("WEBDRIVER_BASEURL_USER_FRIENDLY", "https://www.example.com/")
WEBDRIVER_TYPE= "chrome"
WEBDRIVER_OPTION_ARGS = [
    "--force-device-scale-factor=2.0",
    "--high-dpi-support=2.0",
    "--headless",
    "--disable-gpu",
    "--disable-dev-shm-usage",
    # This is required because our process runs as root (in order to install pip packages)
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-extensions",
]

SCREENSHOT_LOCATE_WAIT = 100
SCREENSHOT_LOAD_WAIT = 1200

from superset.utils.urls import headless_url
from superset.utils.machine_auth import MachineAuthProvider

def auth_driver(driver, user):
    # Setting cookies requires doing a request first, but /login is redirected to oauth provider, and stuck there.
    driver.get(headless_url("/doesnotexist"))

    cookies = MachineAuthProvider.get_auth_cookies(user)

    for cookie_name, cookie_val in cookies.items():
        driver.add_cookie(dict(name=cookie_name, value=cookie_val))

    return driver

WEBDRIVER_AUTH_FUNC = auth_driver
```

### Screenshots/recordings
<img width="286" alt="image" src="https://github.com/apache/superset/assets/894804/9646d448-b719-4150-8e16-79ba4b2663a1">

![image](https://github.com/apache/superset/assets/894804/d4972b64-1bb2-4862-bfbd-8c0bdd5449f3)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by fzhan** [comment]
after switching to a stable postgresql, the problem was gone.
