### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_cors'

### ISSUE THREAD

**Issue by butuzov** [apache/superset#27102]
### Bug description

Was installing superset with `ENABLE_CORS` setting set to True and got unexpected error.
(context - config was from existing installation of local superset)

### How to reproduce the bug

1. git clone https://github.com/apache/superset
2. enable `venv` and perform `pip isntall -e .`
3. change `ENABLE_CORS` at `superset/config.py` to True
4. change `SECTER_KEY` to make it real
5. run `superset fab create-admin`

### Superset version

master / latest-dev

### Python version

3.11

### Node version

16

### Browser

Chrome

### Additional context

<details><summary>Details</summary>
<pre>

> superset fab create-admin
logging was configured successfully
2024-02-13 16:09:08,068:INFO:superset.utils.logging_configurator:logging was configured successfully
2024-02-13 16:09:08,071:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Failed to create app
Traceback (most recent call last):
  File "/Dev/Experimetns/superset-os/superset/app.py", line 40, in create_app
    app_initializer.init_app()
  File "/Dev/Experimetns/superset-os/superset/initialization/__init__.py", line 487, in init_app
    self.configure_middlewares()
  File "/Dev/Experimetns/superset-os/superset/initialization/__init__.py", line 560, in configure_middlewares
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
2024-02-13 16:09:08,071:ERROR:superset.app:Failed to create app
Traceback (most recent call last):
  File "/Dev/Experimetns/superset-os/superset/app.py", line 40, in create_app
    app_initializer.init_app()
  File "/Dev/Experimetns/superset-os/superset/initialization/__init__.py", line 487, in init_app
    self.configure_middlewares()
  File "/Dev/Experimetns/superset-os/superset/initialization/__init__.py", line 560, in configure_middlewares
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
Traceback (most recent call last):
  File "/Dev/Experimetns/superset-os/.venv/bin/superset", line 8, in <module>
    sys.exit(superset())
             ^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/flask/cli.py", line 354, in decorator
    app = __ctx.ensure_object(ScriptInfo).load_app()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/flask/cli.py", line 235, in locate_app
    return find_best_app(module)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/.venv/lib/python3.11/site-packages/flask/cli.py", line 63, in find_best_app
    app = app_factory()
          ^^^^^^^^^^^^^
  File "/Dev/Experimetns/superset-os/superset/app.py", line 47, in create_app
    raise ex
  File "/Dev/Experimetns/superset-os/superset/app.py", line 40, in create_app
    app_initializer.init_app()
  File "/Dev/Experimetns/superset-os/superset/initialization/__init__.py", line 487, in init_app
    self.configure_middlewares()
  File "/Dev/Experimetns/superset-os/superset/initialization/__init__.py", line 560, in configure_middlewares
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'

</pre>
</details> 

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by dpgaspar** [comment]
Hi,

flask-cors is considered an optional dependency, necessary for the optional ENABLE_CORS

https://github.com/apache/superset/blob/master/setup.py#L148

**Comment by michael-s-molina** [comment]
Closing this as @dpgaspar pointed out, cors is an extra dependency and should be installed by admins that wish to use the feature 😉
