### ISSUE TITLE
Error warming up cache: Error 302

### ISSUE THREAD

**Issue by Cerberus112** [apache/superset#27160]
### Bug description

Cache warm-up is not functioning when configured using the latest version (3.1.1rc1) and the previous one (3.1.0) in kubernetes enviroment (with Helm chart version 0.2.15 or earlier).

When the task is triggered, logs of superset worker throws 308 error trying to request the API endpoint.

Note: Reports are working correctly on the same worker.

### How to reproduce the bug

1. Apply cache warm-up config in kubernetes enviroment
2. Review the logs of superset worker

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

The values.yalm (cache warm-up configs):

```
  celery_conf: |
    from celery.schedules import crontab
    class CeleryConfig:
      broker_url = f"redis://{env('REDIS_HOST')}:{env('REDIS_PORT')}/0"
      imports = (
          "superset.sql_lab",
          "superset.tasks.cache",
          "superset.tasks.scheduler",
      )
      result_backend = f"redis://{env('REDIS_HOST')}:{env('REDIS_PORT')}/0"
      task_annotations = {
          "sql_lab.get_sql_results": {
              "rate_limit": "100/s",
          },
      }
      beat_schedule = {
          "reports.scheduler": {
              "task": "reports.scheduler",
              "schedule": crontab(minute="*", hour="*"),
          },
          "reports.prune_log": {
              "task": "reports.prune_log",
              'schedule': crontab(minute=0, hour=0),
          },
          'cache-warmup-hourly': {
              "task": "cache-warmup",
              "schedule": crontab(minute="*/2", hour="*"), ## for testing
              "kwargs": {
                  "strategy_name": "dummy"
              },
          }
      }
    CELERY_CONFIG = CeleryConfig
    THUMBNAIL_SELENIUM_USER = "admin"
```

Superset worker logs:
```
[2024-02-19 14:26:00,227: INFO/ForkPoolWorker-1] fetch_url[ecc6c59f-1a81-472c-bb3c-25daf1ccb203]: Fetching http://url.of.my.site/superset/warm_up_cache/ with payload {"chart_id": 43}
[2024-02-19` 14:22:00,263: ERROR/ForkPoolWorker-3] fetch_url[ecc6c59f-1a81-472c-bb3c-25daf1ccb203]: Error warming up cache!
Traceback (most recent call last):
  File "/app/superset/tasks/cache.py", line 242, in fetch_url
    response = request.urlopen(  # pylint: disable=consider-using-with
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by craig-rueda** [comment]
Could be an issue with the worker's webdriver config or something. Unclear from the logs as to what the initial cause of the 308 is.

**Comment by Cerberus112** [comment]
UPDATE:

Finally, I found that the redirection was due to the WEBDRIVER_BASEURL not being configured at the service level.
```
WEBDRIVER_BASEURL = "http://{{ template "superset.fullname" . }}:8088/"
```
However, I now encounter receiving 400 errors due to missing CSRF when trying to warm up the cache, both from the worker and externally using the API. 
```
{'errors': [{'message': '400 Bad Request: The CSRF session token is missing.', 'error_type': 'GENERIC_BACKEND_ERROR', 'level': 'error', 'extra': {'issue_codes': [{'code': 1011, 'message': 'Issue 1011 - Superset encountered an unexpected error.'}]}}]}
```
If I disable CSRF:
```
WTF_CSRF_ENABLED = False
```
it returns 302:
```
[2024-02-29 17:00:00,368: INFO/ForkPoolWorker-2] fetch_url[356f2e18-4069-4f16-a8aa-d3bee8323296]: Fetching http://superset:8088/api/v1/chart/warm_up_cache with payload {"chart_id": 49}
[2024-02-29 17:00:00,377: ERROR/ForkPoolWorker-3] fetch_url[ba8a1804-8ea0-460a-8892-da8f8fa9b733]: Error warming up cache!
Traceback (most recent call last):
  File "/app/superset/tasks/cache.py", line 242, in fetch_url
    response = request.urlopen(  # pylint: disable=consider-using-with
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 726, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/local/lib/python3.9/urllib/request.py", line 664, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 302: FOUND
[2024-02-29 17:00:00,378: ERROR/ForkPoolWorker-2] fetch_url[356f2e18-4069-4f16-a8aa-d3bee8323296]: Error warming up cache!
Traceback (most recent call last):
  File "/app/superset/tasks/cache.py", line 242, in fetch_url
    response = request.urlopen(  # pylint: disable=consider-using-with
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 726, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/local/lib/python3.9/urllib/request.py", line 664, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 302: FOUND
```

Related errors reported before: https://github.com/apache/superset/issues/24717#issue-1808086329 https://github.com/apache/superset/issues/24579#issue-1786075530

**Comment by dmuldoonadl** [comment]
I'm experiencing the same issue.

**Comment by rusackas** [comment]
Just a head-up that while we're trying to get the linked PR merged, we're also no longer supporting 3.0.x, and will stop supporting 3.x.x when Superset 4.1 is released soon. If anyone can confirm this is a 4.x.x issue, that'd be appreciated!

**Comment by sanjaynayak007** [comment]
I am experiencing the cache warmup issue in Superset version 4.0.2.
```
[2024-08-28 10:30:01,206: INFO/ForkPoolWorker-2] fetch_url[d490c4c1-2b0a-4078-8f5a-7abc7f8f96ca]: Fetching http://superset:8088/superset/warm_up_cache/ with payload {"chart_id": 125, "dashboard_id": 22}
[2024-08-28 10:30:01,212: ERROR/ForkPoolWorker-2] fetch_url[d490c4c1-2b0a-4078-8f5a-7abc7f8f96ca]: Error warming up cache!
Traceback (most recent call last):
  File "/app/superset/tasks/cache.py", line 227, in fetch_url
    response = request.urlopen(  # pylint: disable=consider-using-with
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: METHOD NOT ALLOWED
```

**Comment by tamarinkeisari** [comment]
> I am experiencing the cache warmup issue in Superset version 4.0.2.
> 
> ```
> [2024-08-28 10:30:01,206: INFO/ForkPoolWorker-2] fetch_url[d490c4c1-2b0a-4078-8f5a-7abc7f8f96ca]: Fetching http://superset:8088/superset/warm_up_cache/ with payload {"chart_id": 125, "dashboard_id": 22}
> [2024-08-28 10:30:01,212: ERROR/ForkPoolWorker-2] fetch_url[d490c4c1-2b0a-4078-8f5a-7abc7f8f96ca]: Error warming up cache!
> Traceback (most recent call last):
>   File "/app/superset/tasks/cache.py", line 227, in fetch_url
>     response = request.urlopen(  # pylint: disable=consider-using-with
>   File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
>     response = meth(req, response)
>   File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
>     response = self.parent.error(
>   File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
>     return self._call_chain(*args)
>   File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
>     result = func(*args)
>   File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 405: METHOD NOT ALLOWED
> ```

I am facing the same problem, also version 4.0.2
Have you found a solution?

**Comment by nicholaslimck** [comment]
Error 405 was due to a change to the API endpoint; the cache code was not updated accordingly. That issue was resolved in #28706 and 4.1.1, but the new Error 400 persists on 4.1.1 due to a missing CSRF token. Waiting on #31173 to fix that.

**Comment by laimis9133** [comment]
Hi @nicholaslimck,

Although known already I'm just here to confirm that we are facing cache warmup problems with 4.1.1
```
[2025-02-10 18:30:00,892: INFO/ForkPoolWorker-15] fetch_url[9f55c367-1c0f-447a-b2ab-f147f330cd80]: Fetching http://superset.data-prod:8088/api/v1/security/csrf_token/
[2025-02-10 18:30:00,898: ERROR/ForkPoolWorker-16] fetch_url[05c625da-6580-4220-8250-32591ea54287]: Error warming up cache!
Traceback (most recent call last):
  File "/app/superset/tasks/cache.py", line 231, in fetch_url
    response = request.urlopen(  # pylint: disable=consider-using-with
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: UNAUTHORIZED
```

I see that [#31173](https://github.com/apache/superset/pull/31173) is already merged - do we wait now for 4.1.2 release or is it backported to 4.1.1?

**Comment by nicholaslimck** [comment]
@laimis9133 I think it's set to be included in the [4.1.2 release](https://github.com/orgs/apache/projects/437/views/1). Haven't tested the fix myself, but hopefully it will resolve our issues.
