### ISSUE TITLE
Official Steps Keep Failing for Docker-compose on ARM Mac

### ISSUE THREAD

**Issue by kuro337** [apache/superset#27242]
### Bug description

The Websockets container seems to be failing

```bash
2024-02-24 01:05:10 
2024-02-24 01:05:10 > superset-websocket@0.0.1 start
2024-02-24 01:05:10 > node dist/index.js start
2024-02-24 01:05:10 
2024-02-24 01:05:11 {"date":"Sat Feb 24 2024 06:05:11 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Please provide a JWT secret at least 32 bytes long\nError: Please provide a JWT secret at least 32 bytes long\n    at Object.<anonymous> (/home/superset-websocket/dist/index.js:76:11)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:22:47","os":{"loadavg":[4.15,3.73,3.65],"uptime":2582},"process":{"argv":["/usr/local/bin/node","/home/superset-websocket/dist/index.js","start"],"cwd":"/home/superset-websocket","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":644539,"external":1801709,"heapTotal":30183424,"heapUsed":15528608,"rss":0},"pid":22,"uid":1000,"version":"v16.20.2"},"stack":"Error: Please provide a JWT secret at least 32 bytes long\n    at Object.<anonymous> (/home/superset-websocket/dist/index.js:76:11)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:22:47","trace":[{"column":11,"file":"/home/superset-websocket/dist/index.js","function":null,"line":76,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1198,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1252,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1076,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":911,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":22,"method":null,"native":false}]}
2024-02-24 01:05:11 config.json file not found
2024-02-24 01:05:14 npm notice 
2024-02-24 01:05:14 npm notice New major version of npm available! 8.19.4 -> 10.4.0
2024-02-24 01:05:14 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
2024-02-24 01:05:14 npm notice Run `npm install -g npm@10.4.0` to update!
2024-02-24 01:05:14 npm notice 

```

Tried around 5 variations now of all these

```bash
export DOCKER_DEFAULT_PLATFORM=linux/amd64

# Adding these to all Superset services in Docker-compose
  superset:
    platform: linux/amd64/v8
    env_file: docker/.env
    image: *superset-image
    container_name: superset_app

Tried a variation of only linux/amd64/v8 , amd64 etc.

```

### How to reproduce the bug

```bash
git clone https://github.com/apache/superset.git

cd superset

docker compose up -d

https://superset.apache.org/docs/installation/docker/

# export DOCKER_DEFAULT_PLATFORM=linux/amd64

http://localhost:8088



# clear images for it
docker image prune -a

export DOCKER_DEFAULT_PLATFORM=linux/x86_64

# and update the docker-compose.yml file to change superset-websockets image

```

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Closing as stale, and because I think all of this has smoothed out since the issue was open. If you're still unable to get it running, let us know if there are updated specifics. Thanks!
