### ISSUE TITLE
Superset Async Query Websocket JWT not present

### ISSUE THREAD

**Issue by Haoran-Qi** [apache/superset#27293]
### Bug description

Hi 

I find a bug in the Async Query Websocket code while I'm trying to enable the Async query "ws" mode, and I followed the instructions and docs to set up all the config values
https://github.com/apache/superset/blob/master/CONTRIBUTING.md#async-chart-queries
https://github.com/apache/superset/issues/9190

In the websocket code,  it is looking for the channel_id from cookie encrypted by JWT (https://github.com/apache/superset/blob/9900f566700e6d0a2c376aa4260a0a3f4db27404/superset-websocket/src/index.ts#L278)

However in the sueprset_app's  ws connection, we are not provbiding proper JWT token (https://github.com/apache/superset/blob/9900f566700e6d0a2c376aa4260a0a3f4db27404/superset-frontend/src/middleware/asyncEvent.ts#L196) 

Which lead to a JWT not present error.

I notice the we create the channel_id and set the cookie in async_mananger, but I don't think it reflects on websocket container https://github.com/apache/superset/blob/9900f566700e6d0a2c376aa4260a0a3f4db27404/superset/async_events/async_query_manager.py#L157

### How to reproduce the bug

1. follow the instruction to enable Async query
2. docker compose up
3. you can see the superset_app cannot connect to websocket container because of the JWT token missing

my config
GLOBAL_ASYNC_QUERIES_JWT_SECRET = "***********"
GLOBAL_ASYNC_QUERIES_TRANSPORT = "ws"
GLOBAL_ASYNC_QUERIES_JWT_COOKIE_SECURE = True
GLOBAL_ASYNC_QUERIES_REDIS_CONFIG = {
    "port": REDIS_PORT,
    "host": REDIS_HOST,
    "password": "",
    "db": 0,
    "ssl": False,
}

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by ericho-bbai** [comment]
Did you make a copy of `superset-websocket/config.example.json` as `superset-websocket/config.json` and change the `jwtSecret` value? You can use https://jwt.io/ to generate a valid token.

**Comment by Haoran-Qi** [comment]
Yeah, I did make the superset-websocket/config.json file with 32 bytes secret key, same key as the GLOBAL_ASYNC_QUERIES_JWT_SECRET I set up in docker/pythonpath_dev/superset_config.py.

In  superset app container  https://github.com/apache/superset/blob/9900f566700e6d0a2c376aa4260a0a3f4db27404/superset-frontend/src/middleware/asyncEvent.ts#L196

I don't think it provids the JWT in the header, that's why websocket container is giving a JWT not present error

If the token is invalid, it should shrow an error with the jwt verification failure in the following line.

https://git.geotab.com/BigData/data-platform/bap/superset/-/blob/DNA-34153/Async-Query-System/superset-websocket/src/index.ts#L282

**Comment by amitdixit** [comment]
I am facing the same issue with Kubernetes deployment. JWT

**Comment by rusackas** [comment]
Is anyone still facing this? It seems to have gone silent, so may eventually be closed as stale. In the meantime, the websocket connection is being addressed in a forthcoming SIP by @villebro and subject to architecture redesign. 

For good measure, I'll also ping @dosu-bot in case it's helpful here.

**Comment by ptdtan** [comment]
I'm still having the same problem.

**Comment by FullStackHan** [comment]
I encountered the same problem. When using the Docker Compose UP to build an superset environment, websocket will report to the error of `WebSocket Connection Failed JWT not present`.
`
{"level":"error","message":"JWT not present","stack":"Error: JWT not present\n    at readChannelId (/home/superset-websocket/dist/index.js:242:15)\n    at Server.httpUpgrade (/home/superset-websocket/dist/index.js:337:9)\n    at Server.emit (node:events:513:28)\n    at onParserExecuteCommon (node:_http_server:772:14)\n    at onParserExecute (node:_http_server:686:3)"}
`


Debug found that JWT Token was not stored in Cookies.

[https://github.com/apache/superset/blob/9900f566700e6d0a2c376aa4260a0a3f4db27404/superset-websocket/src/index.ts#L279](https://github.com/apache/superset/blob/9900f566700e6d0a2c376aa4260a0a3f4db27404/superset-websocket/src/index.ts#L279)

**Comment by drparavozik** [comment]
To resolve this issue, you need to:

1. Update the `FEATURE_FLAGS` in your `superset_config.py` file
2. Specifically, set `GLOBAL_ASYNC_QUERIES` to `True` to override the default value in `superset/config.py`

This setting is necessary for the token to be set in your cookies - **without this change, the tokens will not be set at all**

You could check whether this flag is set printing this to console in your browser in your superset app: `console.log(window.featureFlags)`

_Additionally, please review all the points mentioned by @dosubot in the earlier comments, they are still valid, except JWT_SECRET & JWT_COOKIE_NAME_

**Comment by rusackas** [comment]
Thanks for reporting this issue and to everyone who provided additional context.

## Current Status

This issue has been identified as a **configuration requirement** that may not be clearly documented. 

## Workaround

As discovered by @drparavozik, the JWT token for async queries via WebSocket requires the `GLOBAL_ASYNC_QUERIES` feature flag to be enabled:

1. In your `superset_config.py`, add or update:
   ```python
   FEATURE_FLAGS = {
       "GLOBAL_ASYNC_QUERIES": True,
   }
   ```

2. Configure the other async query settings as documented:
   ```python
   GLOBAL_ASYNC_QUERIES_JWT_SECRET = "your-32-byte-secret"
   GLOBAL_ASYNC_QUERIES_TRANSPORT = "ws"
   GLOBAL_ASYNC_QUERIES_REDIS_CONFIG = {
       "port": REDIS_PORT,
       "host": REDIS_HOST,
       # ... other settings
   }
   ```

3. Ensure `superset-websocket/config.json` uses the same `jwtSecret`

**Without the feature flag enabled, the JWT cookie will not be set at all**, causing the "JWT not present" error.

## Related Work

PR #37809 is adding validation to fail fast with a clear error message when async queries are misconfigured, which should prevent this silent failure mode in the future.

## Request for Validation

Can those who reported this issue (@Haoran-Qi @amitdixit @ptdtan @FullStackHan @thomasrea0113) confirm whether enabling the `GLOBAL_ASYNC_QUERIES` feature flag resolves the issue?

If confirmed, we should update the async query documentation to clarify this requirement.

**Comment by rusackas** [comment]
Resolving as a configuration requirement: the async-token cookie is only set when the GLOBAL_ASYNC_QUERIES feature flag is enabled. Remaining work is documentation, not a code bug, and we're _alwyays_ open to docs PRs if anyone wants to open one.
