### ISSUE TITLE
Unable to start non-dev locally on main

### ISSUE THREAD

**Issue by bryanjknight** [apache/superset#27400]
### Bug description

When starting locally with docker, the `superset_init` job fails because it cannot find the correct version of cryptography

### How to reproduce the bug

1. Check out main/master
2. Run `docker compose -f docker-compose-non-dev.yml up`
3. Note `superset_init` fails with exit code 1

Also tried this with `TAG=3.1.1` with the same results

### Screenshots/recordings

```
2024-03-05 14:32:48 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
2024-03-05 14:32:48 apache-superset 3.1.0 requires cryptography<41.1.0,>=41.0.2, but you have cryptography 42.0.5 which is incompatible.
2024-03-05 14:32:48 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2024-03-05 14:32:48 
2024-03-05 14:32:48 [notice] A new release of pip is available: 23.0.1 -> 24.0
2024-03-05 14:32:48 [notice] To update, run: pip install --upgrade pip
2024-03-05 14:32:51 Traceback (most recent call last):
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
2024-03-05 14:32:51     ws.require(__requires__)
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
2024-03-05 14:32:51     needed = self.resolve(parse_requirements(requirements))
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
2024-03-05 14:32:51     raise VersionConflict(dist, req).with_context(dependent_req)
2024-03-05 14:32:51 pkg_resources.ContextualVersionConflict: (cryptography 42.0.5 (/usr/local/lib/python3.9/site-packages), Requirement.parse('cryptography<41.1.0,>=41.0.2'), {'apache-superset'})
2024-03-05 14:32:51 
2024-03-05 14:32:51 During handling of the above exception, another exception occurred:
2024-03-05 14:32:51 
2024-03-05 14:32:51 Traceback (most recent call last):
2024-03-05 14:32:51   File "/usr/local/bin/superset", line 33, in <module>
2024-03-05 14:32:51     sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
2024-03-05 14:32:51   File "/usr/local/bin/superset", line 25, in importlib_load_entry_point
2024-03-05 14:32:51     return next(matches).load()
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
2024-03-05 14:32:51     module = import_module(match.group('module'))
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-03-05 14:32:51     return _bootstrap._gcd_import(name[level:], package, level)
2024-03-05 14:32:51   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-03-05 14:32:51   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-03-05 14:32:51   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2024-03-05 14:32:51   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2024-03-05 14:32:51   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2024-03-05 14:32:51   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2024-03-05 14:32:51   File "/app/superset/cli/main.py", line 28, in <module>
2024-03-05 14:32:51     from superset.cli.lib import normalize_token
2024-03-05 14:32:51   File "/app/superset/cli/lib.py", line 20, in <module>
2024-03-05 14:32:51     from superset import config
2024-03-05 14:32:51   File "/app/superset/config.py", line 39, in <module>
2024-03-05 14:32:51     import pkg_resources
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
2024-03-05 14:32:51     def _initialize_master_working_set():
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
2024-03-05 14:32:51     f(*args, **kwargs)
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
2024-03-05 14:32:51     working_set = WorkingSet._build_master()
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
2024-03-05 14:32:51     return cls._build_from_requirements(__requires__)
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
2024-03-05 14:32:51     dists = ws.resolve(reqs, Environment())
2024-03-05 14:32:51   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
2024-03-05 14:32:51     raise DistributionNotFound(req, requirers)
2024-03-05 14:32:51 pkg_resources.DistributionNotFound: The 'cryptography<41.1.0,>=41.0.2' distribution was not found and is required by apache-superset
```

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
@sadpandajoe @dpgaspar maybe this is fallout from the recent cryptography PRs?

**Comment by Navya-Prakash** [comment]
upgraded pip???

**Comment by bryanjknight** [comment]
Pretty sure it's wrong version of pip. Closing out but will reopen if that doesn't work
