### ISSUE TITLE
Adding IBM DB2 to superset using ibm_db_sa

### ISSUE THREAD

**Issue by rahulbharalsaini** [apache/superset#27568]
### Bug description

To support integration with db2, when I run "pip install ibm_db_sa" in the docker container running the latest image, I get the following error.

### How to reproduce the bug

1.  Run the superset container from the official image.
2.  Go inside the running container to install ibm_db_sa library using "pip install ibm_db_sa"
3. Following error message is encounered.
```
superset@6c1f1dace2bb:/app$ pip install ibm_db_sa
Defaulting to user installation because normal site-packages is not writeable
Collecting ibm_db_sa
  Using cached ibm_db_sa-0.4.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: sqlalchemy>=0.7.3 in ./superset_home/.local/lib/python3.9/site-packages (from ibm_db_sa) (1.3.23)
Collecting ibm-db>=2.0.0 (from ibm_db_sa)
  Using cached ibm_db-3.2.3.tar.gz (210 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Detected 64-bit Python
      Detected platform = linux, uname = aarch64
      Traceback (most recent call last):
        File "/app/superset_home/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/app/superset_home/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/app/superset_home/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-cplvxetm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-cplvxetm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-cplvxetm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 369, in <module>
      NameError: name 'arch_' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.


```

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rahulbharalsaini** [comment]
I am able to resolve this by making the custom image on the window based platform. 
rahulbharalsaini/superset:latest is build on top of official superset image which ibm_db_sa package pre-isntalled.

**Comment by rahulbharalsaini** [comment]
Resolved
