### ISSUE TITLE
pkg-config not found on docker compose build

### ISSUE THREAD

**Issue by Issykul** [apache/superset#27792]
### Bug description

I cannot `docker compose build` nor `docker compose up -d` the file `docker-compose-non-dev.yml`

See log attached.

### How to reproduce the bug

1. clone repo
2. do `docker compose -f docker-compose-non-dev.yml pull`
3. do `docker compose -f docker-compose-non-dev.yml build`

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Not applicable

### Additional context

```
#0 9.513   Using cached mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
#0 9.564 Collecting mysqlclient==2.2.4 (from -r requirements/development.txt (line 143))
#0 9.567   Using cached mysqlclient-2.2.4.tar.gz (90 kB)
#0 9.593   Installing build dependencies: started
#0 12.76   Installing build dependencies: finished with status 'done'
#0 12.77   Getting requirements to build wheel: started
#0 12.96   Getting requirements to build wheel: finished with status 'error'
#0 12.97   error: subprocess-exited-with-error
#0 12.97   
#0 12.97   × Getting requirements to build wheel did not run successfully.
#0 12.97   │ exit code: 1
#0 12.97   ╰─> [27 lines of output]
#0 12.97       /bin/sh: 1: pkg-config: not found
#0 12.97       /bin/sh: 1: pkg-config: not found
#0 12.97       /bin/sh: 1: pkg-config: not found
#0 12.97       Trying pkg-config --exists mysqlclient
#0 12.97       Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
#0 12.97       Trying pkg-config --exists mariadb
#0 12.97       Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
#0 12.97       Trying pkg-config --exists libmariadb
#0 12.97       Command 'pkg-config --exists libmariadb' returned non-zero exit status 127.
#0 12.97       Traceback (most recent call last):
#0 12.97         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#0 12.97           main()
#0 12.97         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#0 12.97           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 12.97         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#0 12.97           return hook(config_settings)
#0 12.97         File "/tmp/pip-build-env-6ke4u52w/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
#0 12.97           return self._get_build_requires(config_settings, requirements=['wheel'])
#0 12.97         File "/tmp/pip-build-env-6ke4u52w/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
#0 12.97           self.run_setup()
#0 12.97         File "/tmp/pip-build-env-6ke4u52w/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
#0 12.97           exec(code, locals())
#0 12.97         File "<string>", line 155, in <module>
#0 12.97         File "<string>", line 49, in get_config_posix
#0 12.97         File "<string>", line 28, in find_package_name
#0 12.97       Exception: Can not find valid pkg-config name.
#0 12.97       Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
#0 12.97       [end of output]
#0 12.97   
#0 12.97   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 12.97 error: subprocess-exited-with-error
#0 12.97 
#0 12.97 × Getting requirements to build wheel did not run successfully.
#0 12.97 │ exit code: 1
#0 12.97 ╰─> See above for output.
#0 12.97 
#0 12.97 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: process "/bin/sh -c pip install -r requirements/development.txt" did not complete successfully: exit code: 1
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Issykul** [comment]
Even after I do a `docker builder prune -a` it doesn't work and gives me the same error.
It doesn't matter whether I use `docker compose build` or `docker compose up -d`.

**Comment by Issykul** [comment]
Now I also tried to do a `docker system prune -a` and tried to up the most basic installation that is possible like stated in the documentation. I didn't edit the docker-compose, I didn't edit the .env file. But it still gives the same error. 

So clearly I am doing something wrong or something changed that this isn't working on a clean installation.

**Comment by zzlgreat** [comment]
same problem

**Comment by davionchai** [comment]
had the same issue, what i did was adding pkg-config after line 121 [here](https://github.com/apache/superset/blob/master/Dockerfile#L121)

```
...
        libxtst6 \
        wget \
        pkg-config \
    # Install GeckoDriver WebDriver
...
```

**Comment by michael-s-molina** [comment]
Fixed by https://github.com/apache/superset/pull/27855
