### ISSUE TITLE
`mysqlclient` installation via makefile scripts throws an error

### ISSUE THREAD

**Issue by corocoto** [apache/superset#27879]
## Description
I follow by steps from the ["Setup Local Environment for Development" section](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#setup-local-environment-for-development). And stoped at the ["OS Dependencies"](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#os-dependencies).

I tried to install them via various make scripts (`install` and `superset`). But unfortunately got error at moment of installing `mysqlclient`.

Logs:

```
Collecting mysqlclient==2.2.4 (from -r requirements/development.txt (line 144))
  Using cached mysqlclient-2.2.4.tar.gz (90 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      /bin/sh: pkg-config: command not found
      /bin/sh: pkg-config: command not found
      /bin/sh: pkg-config: command not found
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
      Trying pkg-config --exists libmariadb
      Command 'pkg-config --exists libmariadb' returned non-zero exit status 127.
      Traceback (most recent call last):
        File "/Users/ar.gusev/Documents/research/superset/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/ar.gusev/Documents/research/superset/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ar.gusev/Documents/research/superset/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/xw/c2n12c1s3hb35q5480hj15w00000gp/T/pip-build-env-z2pbj3op/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/xw/c2n12c1s3hb35q5480hj15w00000gp/T/pip-build-env-z2pbj3op/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/xw/c2n12c1s3hb35q5480hj15w00000gp/T/pip-build-env-z2pbj3op/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 155, in <module>
        File "<string>", line 49, in get_config_posix
        File "<string>", line 28, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### How to reproduce the bug

1. Install python v3.10 and pip 24.0
2. Start executing steps from ["OS Dependencies" section](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#os-dependencies)
3. Got an error a the point of working with makefile scripts

### Superset version

master / latest-dev

### Python version

3.10

### Node version

Not applicable

### Browser

Not applicable

### Additional context

OS: macOS 14.4.1

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by corocoto** [comment]
This issue isn't actual anymore.

My wrong, I didn't have the `pkg-config` installed.
