### ISSUE TITLE
Error connecting to Elasticsearch 

### ISSUE THREAD

**Issue by ChanKaki** [apache/superset#28098]
## Screenshot
![image](https://github.com/apache/superset/assets/39516298/3b6a5f8a-e116-4088-8c16-b3fc1504e0fa)

version
es : 7.13.4
superset:3.0

run by docker-compose

```yal
  superset:
    image: apache/superset:3.0.0
    container_name: superset
    command: >
      /bin/sh -c "
      pip install authlib &&
      superset db upgrade &&
      pip install elasticsearch-dbapi==0.2.9 &&
      set FLASK_APP=superset &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"
    restart: unless-stopped
    ports:
      - "13030:8088"
    environment:
      - superset_create
      - SUPERSET_LOAD_EXAMPLES=yes
    volumes:
      - ${SUPERSER_VOLUME}:/home/superset
      - ${CONFIG_PY}:/app/pythonpath/superset_config.py
      - ${CUSTOM_SSO_PY}:/app/pythonpath/custom_sso_security_manager.py

    depends_on:
      - postgres
```

## Description
es was work,but i connected a new databse in superset,it showed error
connected failed and got the error log

```
2024-04-17 05:06:53,776:WARNING:superset.views.base:SupersetErrorsException
Traceback (most recent call last):
  File "/app/superset/databases/commands/test_connection.py", line 163, in run
    raise DBAPIError(ex_str or None, None, None)
sqlalchemy.exc.DBAPIError: (builtins.NoneType) None
[SQL: Error connecting to Elasticsearch]
(Background on this error at: https://sqlalche.me/e/14/dbapi)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1526, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 93, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/databases/api.py", line 908, in test_connection
    TestConnectionDatabaseCommand(item).run()
  File "/app/superset/databases/commands/test_connection.py", line 192, in run
    raise SupersetErrorsException(errors) from ex
superset.exceptions.SupersetErrorsException: [SupersetError(message='(builtins.NoneType) None\n[SQL: Error connecting to Elasticsearch]\n(Background on this error at: https://sqlalche.me/e/14/dbapi)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'ElasticSearch (SQL API)', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]

```

**Comment by despot84** [comment]
Same problem

**Comment by Hrishiranade** [comment]
@rusackas I am also Facing the Same Issue. Any update on this...

**Comment by rusackas** [comment]
> @rusackas I am also Facing the Same Issue. Any update on this...

I'm not working on it, and don't know anyone who is. This thread is all the news I have. I also don't have access to Elasticsearch, so if you do, please feel free to diagnose and open a PR if you have the means :)

**Comment by leezj-cbm** [comment]
I am having same issue here. Any advicec/help will be greatly appreciated

![image](https://github.com/user-attachments/assets/d5b9b92d-753d-48e3-921b-40ed3c2a6589)

```
superset.exceptions.SupersetErrorsException: [SupersetError(message='(builtins.NoneType) None\n[SQL: Error connecting to Elasticsearch]\n(Background on this error at: https://sqlalche.me/e/14/dbapi)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'ElasticSearch (SQL API)', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
2024-08-01 10:37:49,997:INFO:werkzeug:127.0.0.1 - - [01/Aug/2024 10:37:49] "POST /api/v1/database/test_connection/ HTTP/1.1" 500 -
```

**Comment by rusackas** [comment]
I'm assuming from the silence around here (>200 days) that your solution worked! I'll call this one case closed.
