### ISSUE TITLE
Query history page is not usable in 3.1.2 and 4.0.0, caused by bug in sql_parse.py

### ISSUE THREAD

**Issue by AutumnSun1996** [apache/superset#28145]
### Bug description

Cannot accesse 'Query history' page, and get empty list with this error:

![image](https://github.com/apache/superset/assets/20429502/6ee84b92-ff36-417f-9991-0d273547db91)

the error comes from sql_parse.py. check the logs below.

### How to reproduce the bug

Minimum sample:

1. Start superset with following docker-compose.yml
```docker-compose
version: "3.7"

services:
  superset:
    image: apachesuperset.docker.scarf.sh/apache/superset:3.1.2
    volumes:
      - superset_home:/app/superset_home
    environment:
      SUPERSET_SECRET_KEY: secretkey
      SUPERSET_DB_URI: sqlite:///superset_home/superset.db?check_same_thread=false
      SUPERSET_CONFIG_PATH: /app/superset_home/superset_config.py
    ports:
      - 8088:8088
    command:
      - "sh"
      - "-c"
      - |-
        # allow sqlite for easier reproduce
        echo 'PREVENT_UNSAFE_DB_CONNECTIONS=False' > /app/superset_home/superset_config.py
        # init database
        superset db upgrade
        # init admin user
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin
        # init roles
        superset init
        # run server
        /usr/bin/run-server.sh

volumes:
  superset_home:
    external: false

```

2. Go localhost:8088, login as admin/admin
3. Add one database, can just use 'sqlite:///superset_home/superset.db?check_same_thread=false'
4. Goto SQL->SQLLab, run some queries.
5. Goto SQL->Query hisory, and the error appears.

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/20429502/6ee84b92-ff36-417f-9991-0d273547db91)

### Superset version

3.1.2

### Python version

3.10

### Node version

Not applicable

### Browser

Chrome

### Additional context

tried both 3.1.2 and 4.0.0, and got same error with slightly different line numbers.

logs from 3.1.2:
```log
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 252, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 487, in get_list_headless
    duration, response = time_function(super().get_list_headless, **kwargs)
  File "/app/superset/utils/core.py", line 1463, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 1613, in get_list_headless
    response[API_RESULT_RES_KEY] = list_model_schema.dump(lst, many=True)
  File "/usr/local/lib/python3.10/site-packages/marshmallow/schema.py", line 557, in dump
    result = self._serialize(processed_obj, many=many)
  File "/usr/local/lib/python3.10/site-packages/marshmallow/schema.py", line 519, in _serialize
    return [
  File "/usr/local/lib/python3.10/site-packages/marshmallow/schema.py", line 520, in <listcomp>
    self._serialize(d, many=False)
  File "/usr/local/lib/python3.10/site-packages/marshmallow/schema.py", line 525, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "/usr/local/lib/python3.10/site-packages/marshmallow/fields.py", line 344, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/marshmallow/fields.py", line 1991, in _serialize
    return self._serialize_method(obj)
  File "/app/superset/queries/schemas.py", line 76, in get_sql_tables
    return obj.sql_tables
  File "/app/superset/models/sql_lab.py", line 75, in sql_tables
    extract_tables_from_jinja_sql(
  File "/app/superset/sql_parse.py", line 1110, in extract_tables_from_jinja_sql
    | ParsedQuery(
  File "/app/superset/sql_parse.py", line 280, in __init__
    self._parsed = sqlparse.parse(self.stripped())
  File "/app/superset/sql_parse.py", line 517, in stripped
    return self.sql.strip(" \t\r\n;")
AttributeError: 'Template' object has no attribute 'strip'
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Hmmm... can't reproduce this one so far. Are you using any particular DB, or doing anything fancy with jinja?

**Comment by AutumnSun1996** [comment]
The problem first appears with our test env, which use mysql:8.
But I can reproduce it using sqlite, with reproduce steps above, so I think it's related to superset itself.
Are u using the same docker-compose.yml? The image digest is sha256:0106a05a9e612df6c5972cc28e4712ff4a9ab2972665bad384aff6e5ef3112c8

**Comment by AutumnSun1996** [comment]
and there is no use or modify with jinja, just some simple queries.
BTW, I'm now using force cast 'self.sql' to str inside the 'ParsedQuery.stripped' method as a workaround to fix the http api, but not sure if it's the right way.

**Comment by dagostinelli** [comment]
I have this same problem.  I experienced it during an upgrade.  Old superset was based on an older Github commit.  New superset is based on whatever is currently in Dockerhub.  I backed up the database (Postgres 10) and restored it to the new database (Postgres 10) I performed a `superset db upgrade` followed by a `superset init`.  I get that exact error in the query history page.

**Comment by dagostinelli** [comment]
Here's a screenshot: 
![image](https://github.com/apache/superset/assets/715418/c7b84ae2-435a-432a-b933-f1d2c29518a7)

**Comment by Umkqq** [comment]
I am experiencing the same issue.  Using PostgreSQL version 12.18 and docker deployment based on latest superset image. Deployed from scratch and using empty database. 
Issue is reproduced only when data exists to show on query history page.
![image](https://github.com/apache/superset/assets/7967684/7f764fec-e18a-443c-b2d1-f45c6ac71e11)

**Comment by dagostinelli** [comment]
I patched the file with this attached patch and I was able to get it working.  I think this is a hack, but it's got me past the problem.

filename: sql_parse.patch
```
diff --git a/sql_parse.py b/sql_parse.py
index 62a2457..ceba521 100644
--- a/sql_parse.py
+++ b/sql_parse.py
@@ -514,7 +514,7 @@ class ParsedQuery:
         return self._parsed[0].get_type() == "UNKNOWN"
 
     def stripped(self) -> str:
-        return self.sql.strip(" \t\r\n;")
+        return str(self.sql).strip(" \t\r\n;")
 
     def strip_comments(self) -> str:
         return sqlparse.format(self.stripped(), strip_comments=True)
```

I applied it as follows:
```
cd /app/superset/ &&patch sql_parse.py < sql_parse.patch
```

**Comment by rusackas** [comment]
Pinging @michael-s-molina @dpgaspar in case they see a better way to provide a generalized fix/migration for others getting stuck. Otherwise, I hope the change above resolves this issue enough for now. 🤞

**Comment by gthomas-strike** [comment]
We are encountering the same issue with a deployment using the latest `0.12.9` helm chart version

**Comment by ichux** [comment]
> I patched the file with this attached patch and I was able to get it working. I think this is a hack, but it's got me past the problem.
> 
> filename: sql_parse.patch
> 
> ```
> diff --git a/sql_parse.py b/sql_parse.py
> index 62a2457..ceba521 100644
> --- a/sql_parse.py
> +++ b/sql_parse.py
> @@ -514,7 +514,7 @@ class ParsedQuery:
>          return self._parsed[0].get_type() == "UNKNOWN"
>  
>      def stripped(self) -> str:
> -        return self.sql.strip(" \t\r\n;")
> +        return str(self.sql).strip(" \t\r\n;")
>  
>      def strip_comments(self) -> str:
>          return sqlparse.format(self.stripped(), strip_comments=True)
> ```
> 
> I applied it as follows:
> 
> ```
> cd /app/superset/ &&patch sql_parse.py < sql_parse.patch
> ```

This also worked for us but we just linked an edited version back into the container. Thanks

**Comment by toniphan21** [comment]
I think [this PR](https://github.com/apache/superset/pull/28357) will also fix this problem.

**Comment by vivian-rook** [comment]
This error still appears in an upgrade from superset 3.1.1 (helm chart 0.12.7) to 4.0.1 (helm chart 0.12.11)

**Comment by Habeeb556** [comment]
The issue still exists in the new `version 4.0.2`, but the sql_parse.patch provided by @dagostinelli has resolved it.

**Comment by Aaron-ML** [comment]
We are seeing this issue on 4.0.2 also from a fresh deployment.

**Comment by shengbinxu** [comment]
> > I patched the file with this attached patch and I was able to get it working. I think this is a hack, but it's got me past the problem.
> > filename: sql_parse.patch
> > ```
> > diff --git a/sql_parse.py b/sql_parse.py
> > index 62a2457..ceba521 100644
> > --- a/sql_parse.py
> > +++ b/sql_parse.py
> > @@ -514,7 +514,7 @@ class ParsedQuery:
> >          return self._parsed[0].get_type() == "UNKNOWN"
> >  
> >      def stripped(self) -> str:
> > -        return self.sql.strip(" \t\r\n;")
> > +        return str(self.sql).strip(" \t\r\n;")
> >  
> >      def strip_comments(self) -> str:
> >          return sqlparse.format(self.stripped(), strip_comments=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I applied it as follows:
> > ```
> > cd /app/superset/ &&patch sql_parse.py < sql_parse.patch
> > ```
> 
> This also worked for us but we just linked an edited version back into the container. Thanks


If you installed Superset using Docker Compose, you can follow these steps:

1. Use the command `docker exec -it 5e7f2e42f256 bash` to enter the container.
2. Modify the code as per the instructions above.
3. Run `docker restart 5e7f2e42f256` to restart the container.

**Comment by adangadang** [comment]
bug

**Comment by rusackas** [comment]
This has been silent for quite a > 6 months. Is this still an issue anyone's facing?

**Comment by rusackas** [comment]
@Habeeb556 does your thumbs down mean it's no longer an issue, or you're upset I asked? 

SqlParse is now gone from the codebase, as of a day or so ago. If anyone can test on current `master` it would be appreciated.

**Comment by Habeeb556** [comment]
> [@Habeeb556](https://github.com/Habeeb556) does your thumbs down mean it's no longer an issue, or you're upset I asked?
> 
> SqlParse is now gone from the codebase, as of a day or so ago. If anyone can test on current `master` it would be appreciated.

Yes, I meant that it is no longer an issue. Thanks for following up.
