### ISSUE TITLE
Published Dashboard without charts can only be reached by owners

### ISSUE THREAD

**Issue by giuseppecg** [apache/superset#28515]
### Bug description

We've are communicating templates in our company through dashboards without charts, but already with text boxes, tabs, etc. But we can't spread adoption because we need to always add new owners. 

To bypass this we are leaving a empty chart so the dashboard becomes available

It seems to me it's because of the gamma role setup and the lack of chart, the dash is blocked, but not quite.

### How to reproduce the bug

Version 3.0.2

You'll need at least 2 users with gamma and a single db connection should do. Both of them would have access to this same DB

1. create a dashboard with only text boxes, tabs, and/or any layout feat
2. Publish this dashboard
3. Use the other account and search for the dash name on the dash tab and it should not appear
4. Use the other account to try to access this dashboard and this should return an unexpected error on the front

Looking at the logs you should find this error

werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    raise NotFound()
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
...

5. come back to the first user and add any chart, can be a `select 1` dataset.
6. Now the second user must be able to access the dashboard 

### Superset version

3.1.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

the issue occured on all browsers, the version I can't select the correct one

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Not sure if this is still an issue in 4.x, but we're no longer supporting 3.x, and this issue has been untouched in almost a year, so we'll close it as inactionable. Happy to revisit/reopen if you can provide updated context.

**Comment by ampil** [comment]
Confirming this on 4.1.1

How to reproduce:
1. Create a dashboard with markdown textboxes only
2. Use a gamma role or create a custom role 'reader' with the following permissions:
<details>
  <summary>Permissions</summary>
  
```
permission_view_id: 
26; 28; 31; 33; 36; 37; 38; 39; 40; 41; 46; 49; 59; 60; 61; 62; 63; 73; 78; 92; 99; 101; 102; 104; 105; 107; 109; 112; 113; 115; 117; 130; 131; 134; 136; 139; 141; 147; 150; 157; 167; 168; 169; 43; 128 
```

![Image](https://github.com/user-attachments/assets/f4487761-8125-4b2c-b135-af39fcfe5637)
  
</details>

3. Create new user with a gamma or reader roles.
4. Open the dashboard from 1.
5. Confirm error on opening the dashboard
