### ISSUE TITLE
superset-frontend ReferenceError: module is not defined

### ISSUE THREAD

**Issue by tym3515** [apache/superset#28557]
### Bug description

npm run dev-server 

module is not defined
ReferenceError: module is not defined
    at eval (webpack-internal:///./packages/superset-ui-core/node_modules/micromark-extension-gfm-autolink-literal/dev/lib/syntax.js:6:151)
    at eval (webpack-internal:///./packages/superset-ui-core/node_modules/micromark-extension-gfm-autolink-literal/dev/lib/syntax.js:6:161)
    at ./packages/superset-ui-core/node_modules/micromark-extension-gfm-autolink-literal/dev/lib/syntax.js (http://localhost:9000/static/assets/vendors-node_modules_ant-design_icons_es_components_Icon_js-node_modules_ant-design_icons_es_-ee1f88.05bed6d2.entry.js:29051:1)
    at __webpack_require__ (http://localhost:9000/static/assets/spa.52592bdf.entry.js:1931:33)
    at fn (http://localhost:9000/static/assets/spa.52592bdf.entry.js:2264:21)
    at eval (webpack-internal:///./packages/superset-ui-core/node_modules/micromark-extension-gfm/index.js:6:98)
    at ./packages/superset-ui-core/node_modules/micromark-extension-gfm/index.js (http://localhost:9000/static/assets/vendors-node_modules_ant-design_icons_es_components_Icon_js-node_modules_ant-design_icons_es_-ee1f88.05bed6d2.entry.js:29183:1)
    at __webpack_require__ (http://localhost:9000/static/assets/spa.52592bdf.entry.js:1931:33)
    at fn (http://localhost:9000/static/assets/spa.52592bdf.entry.js:2264:21)
    at eval (webpack-internal:///./packages/superset-ui-core/node_modules/remark-gfm/index.js:4:81)

### How to reproduce the bug

npm install 

npm run dev-server 

### Screenshots/recordings

![2024517111348778](https://github.com/apache/superset/assets/31526867/fdcbf6e6-1565-400e-95f5-f061aff92007)

### Superset version

3.1.3

### Python version

3.9

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Hopefully the bot's right, that an `npm install` will fix it. You can delete the `node modules` folder and _then_ `npm install` (or just `npm ci`) if you want to be extra sure.

**Comment by harrychristianx** [comment]
I tried `npm install`, `npm ci ` on `superset-frontend` directory but the error still persists. I experimented with clean installing `superset-ui-core` by deleting the `node_modules` and having `npm ci` still error shows. This goes for both 4.0.0 and 4.0.1 releases on superset.

**Comment by LuvKaranwal21** [comment]
I've the same problem with no resolution, anyone found a fix ?

**Comment by chen-xiaohu** [comment]
I've the same problem with no resolution, anyone found a fix ?

**Comment by zhangchengda** [comment]
Have you solved your problem? I encountered the same problem

**Comment by rusackas** [comment]
I'm curious if you get the same issue when running `master`. 

You can also nuke your `node_modules` folder contents entirely, and _then `npm install` again. Basically, "nuke it from orbit"
<img src="https://media4.giphy.com/media/xXXhLy1M4RML6/giphy.gif"/>

If that doesn't work, I wonder if you can just `npm install micromark-extension-gfm-autolink-literal` to solve this. You shouldn't _have to_, but maybe it'll work for your situation.

**Comment by LuvKaranwal21** [comment]
Nope, it's still not solved for me, and I've tried nuking it out as well, that doesn't solve the problem, also tried ```npm install micromark-extension-gfm-autolink-literal```

btw the same installation steps works in linux

**Comment by rusackas** [comment]
> btw the same installation steps works in linux

What OS are you running?

**Comment by LuvKaranwal21** [comment]
> > btw the same installation steps works in linux
> 
> What OS are you running?

nevermind, I don't know the OS that my colleague was using before 

but the problem persists for me on windows

I used 4.0.0 version of superset, did installation with node 16, 

I'm not sure, but might be related to this

https://github.com/gaearon/react-hot-loader/issues/1707

**Comment by rusackas** [comment]
Windows is unsupported at this time. It's certainly _possible_ to run Superset on Windows (with the right layer of Linux installed) but historically we've seen random dependency/Docker issues that we can't really support. None (as far as I know) of the core committers/PMC use Windows, and nearly all deployments are on some flavor of Linux.

**Comment by LuvKaranwal21** [comment]
Superset works very well for me (I used the Docker Compose method mentioned in the installation for superset), this issue happens with me when I try to access the proxy of superset on port 9000.

![image](https://github.com/apache/superset/assets/95748449/49ca13e4-bff3-4750-a629-0b1e48c3802e)
![image](https://github.com/apache/superset/assets/95748449/db9b7bfe-bce7-4342-b1bd-18c45989a383)

**Comment by rusackas** [comment]
Looks like you're also running Windows. I assume this is the crux of the issue.

**Comment by FFFirer** [comment]
Maybe generate different things on windows or linux?
check these files:
on windows: 
[syntax-windows.js.txt](https://github.com/user-attachments/files/15912275/syntax-windows.js.txt)
on linux: 
[syntax-linux.js.txt](https://github.com/user-attachments/files/15912278/syntax-linux.js.txt)

The difference between the two files may be related to ‘react-hot-loader’, I guess

**Comment by FFFirer** [comment]
After looking through the source code of 'react-hot-loader', I decided to comment out the following code to disable react-hot-loader from working.

```javascript
# /superset-frontend/babel.config.js

module.exports = {
...
  plugins: [
    ...
    // 'react-hot-loader/babel',
  ]
...]
```

And it works. 

But I still haven't found the root cause, just temporarily masked the problem, and it's not clear what the differences between Linux and Windows are causing the inconsistent behavior on this issue.

**Comment by harrychristianx** [comment]
> After looking through the source code of 'react-hot-loader', I decided to comment out the following code to disable react-hot-loader from working.
> 
> ```js
> # /superset-frontend/babel.config.js
> 
> module.exports = {
> ...
>   plugins: [
>     ...
>     // 'react-hot-loader/babel',
>   ]
> ...]
> ```
> 
> And it works.
> 
> But I still haven't found the root cause, just temporarily masked the problem, and it's not clear what the differences between Linux and Windows are causing the inconsistent behavior on this issue.

This works!

**Comment by TejParker** [comment]
> found the root cause

This works, and did you found the root cause?

**Comment by TejParker** [comment]
> After looking through the source code of 'react-hot-loader', I decided to comment out the following code to disable react-hot-loader from working.
> 
> ```js
> # /superset-frontend/babel.config.js
> 
> module.exports = {
> ...
>   plugins: [
>     ...
>     // 'react-hot-loader/babel',
>   ]
> ...]
> ```
> 
> And it works.
> 
> But I still haven't found the root cause, just temporarily masked the problem, and it's not clear what the differences between Linux and Windows are causing the inconsistent behavior on this issue.

This works, and did you found the root cause?

**Comment by sam-hieken** [comment]
> After looking through the source code of 'react-hot-loader', I decided to comment out the following code to disable react-hot-loader from working.
> 
> ```js
> # /superset-frontend/babel.config.js
> 
> module.exports = {
> ...
>   plugins: [
>     ...
>     // 'react-hot-loader/babel',
>   ]
> ...]
> ```
> 
> And it works.
> 
> But I still haven't found the root cause, just temporarily masked the problem, and it's not clear what the differences between Linux and Windows are causing the inconsistent behavior on this issue.

If anyone's experiencing the "hot update failed 😭" error, this also fixed the problem...

**Comment by rusackas** [comment]
Sounds like this was more or less resolved (or worked around) quite some time ago, so I'll close it out. Contributions/documentation on this topic is welcome from anyone interested, as we likely won't officially offer Windows support unless some Windows users start making contributions!

CC @eschutho who is looking (with anyone's help, if they're interested!) to investigate supporting Windows a little better.
