### ISSUE TITLE
Create Dashboard API not working

### ISSUE THREAD

**Issue by akashgiri9975** [apache/superset#28564]
### Bug description

Getting an issue while calling Dashboard API using guest token.
Error
2024-05-17 18:24:16,603:ERROR:flask_appbuilder.api:'GuestUser' object has no attribute '_sa_instance_state'
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask_appbuilder/api/__init__.py", line 111, in wraps
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/superset/views/base_api.py", line 128, in wraps
    raise ex
  File "/venv/lib/python3.11/site-packages/superset/views/base_api.py", line 122, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/superset/utils/core.py", line 1466, in time_function
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/superset/views/base_api.py", line 93, in wraps
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/superset/dashboards/api.py", line 499, in post
    new_model = CreateDashboardCommand(item).run()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/superset/commands/dashboard/create.py", line 44, in run
    dashboard = DashboardDAO.create(attributes=self._properties, commit=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/superset/daos/base.py", line 158, in create
    db.session.add(item)
  File "<string>", line 2, in add
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2648, in add
    self._save_or_update_state(state)
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2675, in _save_or_update_state
    for o, m, st_, dct_ in mapper.cascade_iterator(
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 3309, in cascade_iterator
    queue = deque(
            ^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/relationships.py", line 1995, in cascade_iterator
    tuples = state.manager[self.key].impl.get_all_pending(state, dict_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1417, in get_all_pending
    current_states = [
                     ^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1418, in <listcomp>
    ((c is not None) and instance_state(c) or None, c)
                         ^^^^^^^^^^^^^^^^^
AttributeError: 'GuestUser' object has no attribute '_sa_instance_state'
2024-05-17 18:24:16,652:INFO:werkzeug:127.0.0.1 - - [17/May/2024 18:24:16] "POST /api/v1/dashboard/ HTTP/1.1" 500 -

### How to reproduce the bug

Call Dashboard API Using Guest token
Either from postman or from browser

### Superset version

4.0.1

### Python version

3.11

### Node version

18 or greater

### Browser

Chrome

### Additional context

Got something similar
https://stackoverflow.com/questions/16151729/attributeerror-int-object-has-no-attribute-sa-instance-state?rq=1
But not sure where to make the changes

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Closing this as stale/inactionable... I don't think this is a bug, but rather a config issue, and there's been no activity (including bot feedback from the user) in almost a year. Happy to open this as a Q&A Discussion if you're still facing this.
