### ISSUE TITLE
Error in SQL Lab or trying to create a Dataset based on Hive

### ISSUE THREAD

**Issue by alessio-bernesco** [apache/superset#28560]
### Bug description

After connecting to a Hive server (created throug a Flink Sql Gateway) i can browse the schema and tables list but when showing the table schema there's an exception in the logs:

```
superset_app          | 2024-05-15 09:53:27,461:ERROR:flask_appbuilder.api:'bool' object has no attribute 'strip'
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app          |     raise ex
superset_app          |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app          |     duration, response = time_function(f, self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1463, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/app/superset/utils/log.py", line 255, in wrapper
superset_app          |     value = f(*args, **kwargs)
superset_app          |   File "/app/superset/databases/api.py", line 741, in table_metadata
superset_app          |     table_info = get_table_metadata(database, table_name, schema_name)
superset_app          |   File "/app/superset/databases/utils.py", line 67, in get_table_metadata
superset_app          |     columns = database.get_columns(table_name, schema_name)
superset_app          |   File "/app/superset/models/core.py", line 847, in get_columns
superset_app          |     return self.db_engine_spec.get_columns(
superset_app          |   File "/app/superset/db_engine_specs/hive.py", line 419, in get_columns
superset_app          |     return BaseEngineSpec.get_columns(inspector, table_name, schema, options)
superset_app          |   File "/app/superset/db_engine_specs/base.py", line 1343, in get_columns
superset_app          |     cast(list[SQLAColumnType], inspector.get_columns(table_name, schema))
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
superset_app          |     col_defs = self.dialect.get_columns(
superset_app          |   File "/usr/local/lib/python3.10/site-packages/pyhive/sqlalchemy_hive.py", line 325, in get_columns
superset_app          |     rows = [[col.strip() if col else None for col in row] for row in rows]
superset_app          |   File "/usr/local/lib/python3.10/site-packages/pyhive/sqlalchemy_hive.py", line 325, in <listcomp>
superset_app          |     rows = [[col.strip() if col else None for col in row] for row in rows]
superset_app          |   File "/usr/local/lib/python3.10/site-packages/pyhive/sqlalchemy_hive.py", line 325, in <listcomp>
superset_app          |     rows = [[col.strip() if col else None for col in row] for row in rows]
superset_app          | AttributeError: 'bool' object has no attribute 'strip'
```

### How to reproduce the bug

In the SQL Lab or "Create Dataset" area try to connect to a Hive server created by Flink Sql Gateway, the connection and table list is retrieved but whe browsing for the table schema the exeption is fired.

### Superset version

4.0.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Since there hasn't been any feedback to the bot response, and the issue has been quiet otherwise for nearly a year, I'll close this as stale. If you're still facing this, we can certainly revisit/reopen!
