### ISSUE TITLE
Problem Exporting Charts as Image

### ISSUE THREAD

**Issue by CharlesNkdl** [apache/superset#28713]
### Bug description

Hi Superset Community,

I have a problem exporting Charts as Image, from multiple Dashboards and instance of Superset.

### How to reproduce the bug

1. Go to a Dashboards with Charts
2. Click the three dots on the top right of a charts
3. Download => Download as Image

### Screenshots/recordings

Here is the result for my charts : 
![valeur-moyennes-selon-surface-2024-05-27T14-20-12 529Z](https://github.com/apache/superset/assets/100453363/127e9e1e-e5b7-49dc-a538-f1401d9a9ed8)

I was wondering if maybe this was related to the fact that the query is quite complicated + a lot of filters in the dashboard so i tried to export another charts from the examples datasets.

![genders-2024-05-27T14-21-50 342Z](https://github.com/apache/superset/assets/100453363/a736255c-cdd2-4469-bae8-d7e95fcd02be)

Not quite right too...

### Superset version

4.0.1

### Python version

3.10

### Node version

Not applicable

### Browser

Firefox

### Additional context

I use Apache Superset 4.0.1 in Local using Windows and a WSL Backend, but this problem was also on my prod. env with Apache Superset 4.0.0 used with Cloudron which handles the deployment.

Even if template processing is ON, i can't download image, with or without Jinja Templating in them.

Here are my superset_config.py flags in local : 
```
SECRET_KEY` = ""

SQLALCHEMY_DATABASE_URI = ''

WTF_CSRF_ENABLED = True (tried with False too...)
WTF_CSRF_EXEMPT_LIST = []
# A CSRF token that expires in 1 year
WTF_CSRF_TIME_LIMIT = 60 * 60 * 24 * 365
                                                                                                                
MAPBOX_API_KEY = ''

LANGUAGES = {
        'en': {'flag': 'us', 'name': 'English'},
        'fr': {'flag': 'fr', 'name': 'French'}
}

ENABLE_JAVASCRIPT_CONTROLS = True

APP_NAME = "Superset Local"

WELCOME_MESSAGE = "secret"

PRIMARY_COLOR = "green"

ENABLE_TEMPLATE_PROCESSING = True

CONTENT_SECURITY_POLICY_WARNING = False

TALISMAN_ENABLED = False

DEFAULT_FEATURE_FLAGS = {
        "ENABLE_TEMPLATE_PROCESSING" : True,
}
```

Here is my python stack trace, minus the get and post request : 
````
Superset.explore_json This API endpoint is deprecated and will be removed in version 4.0.0
2024-05-27 16:34:36,711:WARNING:superset.views.base:Superset.explore_json This API endpoint is deprecated and will be removed in version 4.0.0
2024-05-27 16:34:36,717:DEBUG:parsedatetime:eval - with context - False, False
```


### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Seems to be an issue in Safari too.

**Comment by CharlesNkdl** [comment]
@visharavana I'm using Firefox. The solution was so simple i just didn't thought of it, i'm kind of embarassed, thank you ! I tried on Microsoft Edge and it worked

Maybe due to firefox and safari not being chromium-based, compared to Chrome and Edge

**Comment by stasDomb** [comment]
I still have this type of problem
![all-final-acceptance-2024-06-17T13-44-33 596Z](https://github.com/apache/superset/assets/27229336/e37eb1e9-c99c-4570-b557-4ba83bec1409)

Version 4.0.1 (4.0.0)
I added to **Feature Flags**:
```
FEATURE_FLAGS = {
          "DASHBOARD_CROSS_FILTERS": True,
          "DASHBOARD_EDIT_CHART_IN_NEW_TAB": True,
          "DASHBOARD_RBAC": True,
          "EMBEDDED_SUPERSET": True,
          "ENABLE_TEMPLATE_PROCESSING": True,
          "PLAYWRIGHT_REPORTS_AND_THUMBNAILS": True
        }
```
But it doesn't work. In Safari there are now charts. In Chrome there are a few (as in picture).
Does anybody can help with this ?

**Comment by xiaoqufengdi** [comment]
I solved the problem.
https://github.com/apache/superset/pull/29614#issue-2413172382

**Comment by Gordonei** [comment]
Also seeing this with `4.1.1` and Firefox `135.0.1`, for both dashboards **and** charts:

![Image](https://github.com/user-attachments/assets/df97c99b-27c4-462d-b04b-ae596cbadcc1)

Chrome and M$ Edge seem to be working fine. Not sure if it's relevant or not, but the partial Firefox download seems to be wider than the complete Chrome one.

**Comment by stanislav-dombrovskiy-dp** [comment]
Version 4.1.1
Google Chrome - Version 133.0.6943.142 (Official Build) (arm64)
It doesn't work (pdf or jpg)

<img width="1419" alt="Image" src="https://github.com/user-attachments/assets/e8465efa-1928-4a08-9ae0-41a85ea3a7a1" />

**Comment by doriansechal** [comment]
Same problem with Firefox and Safari, but it works on Chromium-based engines (Brave, Chrome...).

**Comment by LHARISMENDY** [comment]
Same problem here, is there a temporary solution?

**Comment by rusackas** [comment]
These all seem like they might effectively be the same issue:

https://github.com/apache/superset/issues/29394
https://github.com/apache/superset/issues/31158
https://github.com/apache/superset/issues/29719
https://github.com/apache/superset/issues/28713
https://github.com/apache/superset/issues/27532

Can anyone here test this with DASHBOARD_VIRTUALIZATION set to `false`? I have a suspicion that may fix it. If so, we can probably just disable viewport virtualization when the headless browser is building the screencap.

**Comment by doriansechal** [comment]
I tested the suggested fix with DASHBOARD_VIRTUALIZATION = False in my superset_config.py but the issue persists on both Firefox and Safari

**Comment by stanislav-dombrovskiy-dp** [comment]
I've tried 
```
FEATURE_FLAGS = {
DASHBOARD_VIRTUALIZATION: False
}
```
And it helped in Chrome. In Safari still doesn't work.
I'm confused a bit, because in the docs this parameter is False by default.
But anyway Thank you!

**Comment by bhavabhuthi** [comment]
Superset Version: `4.1.2`

Firefox Version: `139.0.1` (64-bit) [Mozilla Firefox for Arch Linux]

Chromium Version: Version `137.0.7151.68` (Official Build) Arch Linux (64-bit)


Same problem here as well.

When I download the chart as Image in dashboard, the feature is working for Chromium browser without the need for aforementioned configuration

```
FEATURE_FLAGS = {
DASHBOARD_VIRTUALIZATION: False
}
```

Whereas it downloads a cropped image in the Firefox browser. 

Images below:
Dashboard:
![Image](https://github.com/user-attachments/assets/293f5039-2891-44bf-80f1-d11cd3ae664a)


Firefox Downloaded Image: 
![Image](https://github.com/user-attachments/assets/fd2d6476-cbc2-4d04-b405-84cf4a1d8d85)


Chromium Downloaded Image
![Image](https://github.com/user-attachments/assets/064c8fe4-7488-4755-96bb-4a579a228874)

**Comment by geekdinazor** [comment]
Problem remains in version 5.0.0.  We tried to add 

```py
FEATURE_FLAGS = {
    DASHBOARD_VIRTUALIZATION: False
}
```
in superset_config.py but it gives error: 

```
[2025-07-24 10:23:24 +0000] [54] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 94, in init_process
    super().init_process()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 423, in import_app
    app = app(*args, **kwargs)
  File "/app/superset/app.py", line 37, in create_app
    app.config.from_object(config_module)
  File "/app/.venv/lib/python3.10/site-packages/flask/config.py", line 231, in from_object
    obj = import_string(obj)
  File "/app/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 596, in import_string
    __import__(import_name)
  File "/app/superset/config.py", line 1955, in <module>
    import superset_config
  File "/app/pythonpath/superset_config.py", line 57, in <module>
    DASHBOARD_VIRTUALIZATION: False
NameError: name 'DASHBOARD_VIRTUALIZATION' is not defined
```

We use official Apache Superset 5.0.0 Docker image from [Docker Hub](https://hub.docker.com/layers/apache/superset/v5.0.0/images/sha256-2f62fe152008e19669e2402a71e174f44808cbf2ebb7665e634f21feed1e442d).  

 Chart image look incorrectly cropped when downloaded in Firefox. We tested it on  Firefox 140.0.4 (64 bit; Windows/Linux).  This problem not occurs on Chrome 138.0.7204.157 (Linux) and Chrome 138.0.7204.159  (Windows).     

Selected chart:
<img width="1084" height="526" alt="Image" src="https://github.com/user-attachments/assets/9b0bbb7e-283f-461c-9790-7aff23ed10a5" />

Output in Firefox (Which is broken):
![Image](https://github.com/user-attachments/assets/60ebc047-51ec-4fe5-bb31-444aa22a3d2c)

Output in Chrome (Which is good):

![Image](https://github.com/user-attachments/assets/7a151b09-e4d1-4f11-86ec-e4e7e96a964c)

**Comment by aukfood** [comment]
Hello, I have same problem with 6.0.0rc2, I had 
```
114 # Add Dashboard virtualization
115 FEATURE_FLAGS = {
116         "ALERT_REPORTS": True,
117         "DASHBOARD_VIRTUALIZATION": False,
118                 }
```
And the result with firefox and chromium : 

![Image](https://github.com/user-attachments/assets/7782fc36-8d3b-4a7b-846c-7b8f7a377717)

Regards

**Comment by tejavegesna-lb** [comment]
Individual query/grid download worked find for me on chrome and firefox after adding these feature flags on superset 5.0.0

```
      "ENABLE_DASHBOARD_SCREENSHOT_ENDPOINTS": True,
      "THUMBNAILS": True,
      "ENABLE_DASHBOARD_DOWNLOAD_WEBDRIVER_SCREENSHOT": True,
```

```
    THUMBNAIL_CACHE_CONFIG = {
        'CACHE_TYPE': 'RedisCache',
        'CACHE_DEFAULT_TIMEOUT': 86400,
        'CACHE_KEY_PREFIX': 'superset_thumbnail_cache',
        'CACHE_REDIS_URL': f"{env('REDIS_PROTO')}://{env('REDIS_HOST')}:{env('REDIS_PORT')}/{env('REDIS_CELERY_DB')}?ssl_cert_reqs={env('REDIS_SSL_CERT_REQS')}",
    }
```

i still can't download whole dashboard as pdf or image

i followed it from here
https://github.com/apache/superset/issues/32037#issuecomment-3112497493

**Comment by aukfood** [comment]
@tejavegesna-lb it seems don't work with 6.0.0rc2

```
# Modification THUMBNAIL_CACHE_CONFIG
THUMBNAIL_CACHE_CONFIG = {
        'CACHE_TYPE': 'RedisCache',
        'CACHE_DEFAULT_TIMEOUT': 86400,
        'CACHE_KEY_PREFIX': 'superset_thumbnail_cache',
        "CACHE_REDIS_HOST": REDIS_HOST,
        "CACHE_REDIS_PORT": REDIS_PORT,
        "CACHE_REDIS_DB": REDIS_RESULTS_DB,
}

...

# Add Dashboard virtualization
FEATURE_FLAGS = {
	"ALERT_REPORTS": True,
	"DASHBOARD_VIRTUALIZATION": False,
        "ENABLE_DASHBOARD_SCREENSHOT_ENDPOINTS": True,
        "ENABLE_DASHBOARD_DOWNLOAD_WEBDRIVER_SCREENSHOT": True,
	"THUMBNAILS": True
}
```

**Comment by stasDomb** [comment]
It doesn't work in 6.1.0 release

**Comment by rusackas** [comment]
Still open across a lot of versions and both browsers. Sounds like a real Firefox/Safari-specific rendering bug in the image capture path. Anyone want to pin it down with a Playwright repro so we can actually fix it?

**Comment by rusackas** [comment]
The linked fix in `#29614` closed without landing, and export still goes through `dom-to-image-more`, which has known Firefox/Safari gaps. Can anyone confirm this still repros on a recent release? Anyone want to open a new/revised PR?

**Comment by khushboogupta10october** [comment]
This is still reproducible in 6.1.0. Root cause : dom-to-image-more  wraps DOM in SVG <foreignObject> -> safari blocks this. 
Fix: Use html2canvas  for the Safari path.

**Comment by Gordonei** [comment]
Can confirm `6.1.0` with Firefox 153 on Windows is working with image export, but PDF is cutting off on what is currently visible in the viewport.

**Comment by rusackas** [comment]
Thanks @khushboogupta10october, that's a plausible read of the `dom-to-image-more` foreignObject gap on WebKit. Want to open the PR for the Safari path? `html2canvas` already comes in via `dom-to-pdf`, so it shouldn't need a new dependency.

**Comment by hadimobarra** [comment]
Opened a PR for the Safari/WebKit path suggested above: #44529. It routes chart/dashboard image capture through `html2canvas` when running on Safari, and leaves the existing `dom-to-image-more` pipeline untouched on other engines. Feedback welcome.

**Comment by rusackas** [comment]
Nice, thanks @hadimobarra! Taking a look at #44529.
