### ISSUE TITLE
Cannot fetch schema list and table list in sqllab after setting values to table_cache_timeout and schema_cache_timeout

### ISSUE THREAD

**Issue by kidusmakonnen** [apache/superset#28735]
### Bug description

We’ve identified an issue when using `FileSystemCache` where setting values for TABLE CACHE TIMEOUT and/or SCHEMA CACHE TIMEOUT in the database properties modal leads to failures in fetching the schema list and table list in SQLLab. Specifically, requests to `/api/v1/database/{dbId}/tables/?q=(force:!f,schema_name:{schemaName}) `return a status code 422 UNPROCESSABLE ENTITY with the response: `{"message":"Unexpected error occurred, please check your logs for details"}`

The issue appears to be related to how `table_cache_timeout` and `schema_cache_timeout` values are handled in the payload and how these values are handled in the backend (cachelib).

### How to reproduce the bug

1. Set CACHE_CONFIG to use FileSystemCache in config.py/superset_config.py
2. Go to Settings &rarr; Database Connections
3. Edit a DB connection
4. Go to Advanced &rarr; Performance
5. Set values to `SCHEMA CACHE TIMEOUT` and `TABLE CACHE TIMEOUT`
6. Go to SqlLab, select the DB you edited
7. Try to refresh the schema list and table list

### Screenshots/recordings

https://github.com/apache/superset/assets/8809047/16eda66e-f28e-455f-8bd2-6ad9a7a05d1b

### Superset version

4.0.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

Stacktrace
```
2024-05-28 03:48:58,426:ERROR:flask_appbuilder.api:unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 182, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1463, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/databases/api.py", line 608, in schemas
    schemas = database.get_all_schema_names(
  File "/app/superset/utils/cache.py", line 135, in wrapped_f
    cache.set(cache_key, obj, timeout=kwargs.get("cache_timeout", 0))
  File "/usr/local/lib/python3.9/site-packages/flask_caching/__init__.py", line 193, in set
    return self.cache.set(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cachelib/file.py", line 241, in set
    timeout = self._normalize_timeout(timeout)
  File "/usr/local/lib/python3.9/site-packages/cachelib/file.py", line 100, in _normalize_timeout
    timeout = int(time()) + timeout
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Still hoping for a PR touch-up 🤞 Anyone is welcome to adopt it, if the author doesn't patch it.
