### ISSUE TITLE
Unable to execute any Superset command in terminal

### ISSUE THREAD

**Issue by EuphoriaCelestial** [apache/superset#28759]
### Bug description

I deploy my Superset instance using Docker image and Helm
When the service is up, I can not login using admin/admin account
So I search on document and found out that I need to create admin account using superset fab command
But that command failed to execute, error log provided below
I also tried other superset command, but nothing is executable, all return the same error

### How to reproduce the bug

1. Build a Superset image using Dockerfile
2. Deploy using Helm
3. Create admin account using "superset fab create-admin"
4. Encounter error

### Screenshots/recordings

`root@superset-564cfd87c4-mkcqq:/app# superset superset fab create-admin
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
logging was configured successfully
2024-05-29 09:48:52,198:INFO:superset.utils.logging_configurator:logging was configured successfully
2024-05-29 09:48:52,204:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
logging was configured successfully
logging was configured successfully
2024-05-29 09:48:53,511:INFO:superset.utils.logging_configurator:logging was configured successfully
2024-05-29 09:48:53,512:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
Failed to create app
Traceback (most recent call last):
  File "/app/superset/app.py", line 40, in create_app
    app_initializer.init_app()
  File "/app/superset/initialization/__init__.py", line 512, in init_app
    self.init_app_in_ctx()
  File "/app/superset/initialization/__init__.py", line 438, in init_app_in_ctx
    self.configure_fab()
  File "/app/superset/initialization/__init__.py", line 562, in configure_fab
    appbuilder.init_app(self.superset_app, db.session)
  File "/app/custom-lib/flask_appbuilder/base.py", line 218, in init_app
    self._add_admin_views()
  File "/app/custom-lib/flask_appbuilder/base.py", line 325, in _add_admin_views
    self.sm.register_views()
  File "/app/custom-lib/flask_appbuilder/security/sqla/manager.py", line 95, in register_views
    super(SecurityManager, self).register_views()
  File "/app/custom-lib/flask_appbuilder/security/manager.py", line 737, in register_views
    self.limiter.limit(self.auth_rate_limit, methods=["POST"])(
  File "/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py", line 1164, in call
    name = get_qualified_name(obj)
  File "/usr/local/lib/python3.9/site-packages/flask_limiter/util.py", line 32, in get_qualified_name
    return f"{callable.module}.{callable.name}.{callable.qualname}"
AttributeError: 'NoneType' object has no attribute 'module'
Failed to create app
Traceback (most recent call last):
  File "/app/superset/app.py", line 40, in create_app
    app_initializer.init_app()
  File "/app/superset/initialization/__init__.py", line 512, in init_app
    self.init_app_in_ctx()
  File "/app/superset/initialization/__init__.py", line 438, in init_app_in_ctx
    self.configure_fab()
  File "/app/superset/initialization/__init__.py", line 562, in configure_fab
    appbuilder.init_app(self.superset_app, db.session)
  File "/app/custom-lib/flask_appbuilder/base.py", line 218, in init_app
    self._add_admin_views()
  File "/app/custom-lib/flask_appbuilder/base.py", line 325, in _add_admin_views
    self.sm.register_views()
  File "/app/custom-lib/flask_appbuilder/security/sqla/manager.py", line 95, in register_views
    super(SecurityManager, self).register_views()
  File "/app/custom-lib/flask_appbuilder/security/manager.py", line 737, in register_views
    self.limiter.limit(self.auth_rate_limit, methods=["POST"])(
  File "/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py", line 1164, in call
    name = get_qualified_name(obj)
  File "/usr/local/lib/python3.9/site-packages/flask_limiter/util.py", line 32, in get_qualified_name
    return f"{callable.module}.{callable.name}.{callable.qualname}"
    AttributeError: 'NoneType' object has no attribute 'module'
2024-05-29 09:48:53,550:ERROR:superset.app:Failed to create app
Traceback (most recent call last):
  File "/app/superset/app.py", line 40, in create_app
    app_initializer.init_app()
  File "/app/superset/initialization/__init__.py", line 512, in init_app
    self.init_app_in_ctx()
  File "/app/superset/initialization/__init__.py", line 438, in init_app_in_ctx
    self.configure_fab()
  File "/app/superset/initialization/__init__.py", line 562, in configure_fab
    appbuilder.init_app(self.superset_app, db.session)
  File "/app/custom-lib/flask_appbuilder/base.py", line 218, in init_app
    self._add_admin_views()
  File "/app/custom-lib/flask_appbuilder/base.py", line 325, in _add_admin_views
    self.sm.register_views()
  File "/app/custom-lib/flask_appbuilder/security/sqla/manager.py", line 95, in register_views
    super(SecurityManager, self).register_views()
  File "/app/custom-lib/flask_appbuilder/security/manager.py", line 737, in register_views
    self.limiter.limit(self.auth_rate_limit, methods=["POST"])(
  File "/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py", line 1164, in call
    name = get_qualified_name(obj)
  File "/usr/local/lib/python3.9/site-packages/flask_limiter/util.py", line 32, in get_qualified_name
    return f"{callable.module}.{callable.name}.{callable.qualname}"
AttributeError: 'NoneType' object has no attribute 'module'
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in call
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 578, in get_command
    app = info.load_app()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 237, in locate_app
    return find_app_by_string(module, app_name)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 165, in find_app_by_string
    app = attr(*args, **kwargs)
  File "/app/superset/app.py", line 47, in create_app
    raise ex
  File "/app/superset/app.py", line 40, in create_app
    app_initializer.init_app()
  File "/app/superset/initialization/__init__.py", line 512, in init_app
    self.init_app_in_ctx()
  File "/app/superset/initialization/__init__.py", line 438, in init_app_in_ctx
    self.configure_fab()
  File "/app/superset/initialization/__init__.py", line 562, in configure_fab
    appbuilder.init_app(self.superset_app, db.session)
  File "/app/custom-lib/flask_appbuilder/base.py", line 218, in init_app
    self._add_admin_views()
  File "/app/custom-lib/flask_appbuilder/base.py", line 325, in _add_admin_views
    self.sm.register_views()
  File "/app/custom-lib/flask_appbuilder/security/sqla/manager.py", line 95, in register_views
    super(SecurityManager, self).register_views()
  File "/app/custom-lib/flask_appbuilder/security/manager.py", line 737, in register_views
    self.limiter.limit(self.auth_rate_limit, methods=["POST"])(
  File "/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py", line 1164, in call
    name = get_qualified_name(obj)
  File "/usr/local/lib/python3.9/site-packages/flask_limiter/util.py", line 32, in get_qualified_name
    return f"{callable.module}.{callable.name}.{callable.qualname}"
    AttributeError: 'NoneType' object has no attribute 'module'`

### Superset version

3.1.3

### Python version

3.9

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Closing this out since the bot didn't get any feedback, it's gone quite silent/stale, and it's more of a help issue than a bug. Happy to move it to a Discussion if warrante.
