### ISSUE TITLE
Method 405 not allowed for guest_token fetching

### ISSUE THREAD

**Issue by stockarea** [apache/superset#28777]
### Bug description

I am not able to fetch the guest_token. I am facing the same issue as described here in this issue 
#23060 

I am also getting the access_token, but I am not able to get guest_token afterwards (405 method not allowed)
I have nginx proxy server in front of my superset which is passing the request from port 443 to 8088. I am still getting this issue.

### How to reproduce the bug

..

### Superset version

master

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by stockarea** [comment]
Hello,
I am passing POST request only.
Here is the screenshot for it.

![image](https://github.com/apache/superset/assets/51982217/6898aa52-fdde-4f99-99ee-29d6b0073be1)



Also, nginx is working correctly I suppose that's why I am able to fetch the access_token it seems? Otherwise that API will also fail correct?

**Comment by zarkerus** [comment]
I got the same error, this is the stacktrace, the application got "POST /api/v1/security/guest_token HTTP/1.1" 308 293 " correctly at first but somehow ended up with the error.
```
10.0.2.40 - - [01/Jun/2024:12:31:57 +0000] "POST /api/v1/security/guest_token HTTP/1.1" 308 293 "-" "PostmanRuntime/7.39.0"
HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing/map.py", line 647, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2024-06-01 12:31:58,099:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing/map.py", line 647, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
10.0.2.40 - - [01/Jun/2024:12:31:58 +0000] "GET /api/v1/security/guest_token/ HTTP/1.1" 405 271 "http://dashboard.mkdc.vn/api/v1/security/guest_token/" "PostmanRuntime/7.39.0"
```

**Comment by zarkerus** [comment]
So this is the fix
- Add this config in **superset_config_docker.py** 
**ENABLE_PROXY_FIX = True**

- Set **X-Forwarded-Proto** header in nginx proxy **"https"**

**Comment by rusackas** [comment]
@stockarea let us know if this indeed resolves the issue for you. 🤞

**Comment by rusackas** [comment]
Assuming this is indeed resolved, but happy to reopen if folks are facing this in 4.1.1 or newer.
