### ISSUE TITLE
It's impossible to attach more than one alert/report to a single chart/dashboard

### ISSUE THREAD

**Issue by isharamet** [apache/superset#29095]
### Bug description

Creating alert or report via API (I suspect the same will happen when creating it via UI, but it's currently broken in **4.0.1** due to https://github.com/apache/superset/issues/28712) in presence of another one attached to the same chart or dashboard will result in internal server error (status code 500).

The issue was reported [before](https://github.com/apache/superset/issues/20544), but it's still relevant as the same behaviour present in the latest release version.

### How to reproduce the bug

1. Create alert for specific chart (by setting "chart" value in payload to the chart ID) via Superset API.
2. Create another alert for the same chart via Superset API.
3. Second attempt will fail returning status code 500 and producing following log message:

```shell
2024-06-05T10:54:04,786 WARNING [superset.views.base] [153] CommandException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/hooks.py", line 79, in wrapped_handler
    return handler(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 104, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1463, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 93, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/reports/api.py", line 359, in post
    new_model = CreateReportScheduleCommand(item).run()
  File "/app/superset/commands/report/create.py", line 53, in run
    self.validate()
  File "/app/superset/commands/report/create.py", line 106, in validate
    raise ReportScheduleCreationMethodUniquenessValidationError()
superset.commands.report.exceptions.ReportScheduleCreationMethodUniquenessValidationError: Resource already has an attached report.
```

### Superset version

4.0.1

### Python version

3.9

### Node version

16

### Browser

Not applicable

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by nytai** [comment]
This validation is applied when reports are created from the chart/dashboard page and it's meant to prevent the same user from subscribing to multiple versions of the same report. 

validation code: https://github.com/apache/superset/blob/2b27e9eda173762cac596cfeb45719ea8cb26b4b/superset/commands/report/create.py#L113

This validation can be bypassed by supplying `"creation_method": "alerts_reports"` in the payload
