### ISSUE TITLE
500 error and unexpected keyword argument 'extra_filters'

### ISSUE THREAD

**Issue by fgvieira** [apache/superset#29289]
### Bug description

When trying to access `superset` through the browser I get a 500 error and the logs say:
```
2024-06-18 10:45:34,669:WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
monkey_patch_field_process.<locals>.process() got an unexpected keyword argument 'extra_filters'
Traceback (most recent call last):
  File "envs/superset/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "envs/superset/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "envs/superset/lib/python3.11/site-packages/flask_appbuilder/security/views.py", line 526, in login
    form = LoginForm_db()
           ^^^^^^^^^^^^^^
  File "envs/superset/lib/python3.11/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "envs/superset/lib/python3.11/site-packages/flask_wtf/form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "envs/superset/lib/python3.11/site-packages/wtforms/form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "envs/superset/lib/python3.11/site-packages/wtforms/form.py", line 127, in process
    field.process(formdata, data, extra_filters=field_extra_filters)
```

### How to reproduce the bug

1. `micromamba env create --name superset -c conda-forge superset pillow psycopg2-binary`
2. `export FLASK_APP=superset`
3. `export SUPERSET_CONFIG_PATH=/var/superset/config.py` (the same as in [here](https://superset.apache.org/docs/configuration/configuring-superset/))
4. `superset db upgrade`
5. `superset fab create-admin`
6. `superset init`

Access `superset on browser.

### Superset version

4.0.1

### Python version

3.11

### Node version

I don't know

### Browser

Firefox

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by fgvieira** [comment]
@dosu I think the issue is with `monkey_patch_field_process.<locals>.process() got an unexpected keyword argument 'extra_filters'`. Any idea what that argument is?

**Comment by johnarevalo** [comment]
It seems related to https://github.com/pallets-eco/flask-admin/issues/2142. It worked after downgrading `wtforms` from `3.1.2` to `2.3.3`

**Comment by rusackas** [comment]
Assuming @johnarevalo has moved on, and closing this as stale/not-planned, but we're available if you want to reopen this and/or get a PR merged. Thanks!
