### ISSUE TITLE
Server Side Session with Redis Fails to Serialize LazyString Objects

### ISSUE THREAD

**Issue by weigosw** [apache/superset#29362]
### Bug description

When configuring Superset to use server-side sessions with Redis, an error occurs during the serialization of session data. Specifically, the error message indicates that encoding objects of type **LazyString** is unsupported. This issue arises when attempting to upload an Excel file, but it may also affect other functionalities that involve session data.

### How to reproduce the bug

1. Configure Superset to use server-side sessions with Redis by setting the following configurations in `superset_config.py`:

```python
from flask_session import Session
import redis

SESSION_TYPE = 'redis'
SESSION_REDIS = redis.from_url('redis://localhost:6379')
```

2. Start superset with the follow command:

```shell
export FLASK_APP=superset
export SUPERSET_CONFIG_PATH="$HOME/.superset/config/superset_config.py"
superset db upgrade
superset init
superset run -p 8088 -h 0.0.0.0 --with-threads --reload --debugger
```

3. Start Superset and attempt to upload an Excel file via the Superset UI.

**Expected Behavior**:
The session data should be serialized and stored in Redis without errors, and the Excel file should be uploaded successfully.

**Actual Behavior**:
The following error is logged:

```
2024-06-25 20:46:33,851:DEBUG:superset.stats_logger:[stats_logger] (incr) failed_excel_upload
2024-06-25 20:46:33,851:ERROR:superset.app:Failed to serialize session data: Encoding objects of type LazyString is unsupported
2024-06-25 20:46:33,851:ERROR:superset.app:Exception on /exceltodatabaseview/form [POST]
Traceback (most recent call last):
  File "/Users/suwei/.pyenv/versions/3.9.19/envs/superset-env/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/suwei/.pyenv/versions/3.9.19/envs/superset-env/lib/python3.9/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/suwei/.pyenv/versions/3.9.19/envs/superset-env/lib/python3.9/site-packages/flask/app.py", line 1508, in finalize_request
    response = self.process_response(response)
  File "/Users/suwei/.pyenv/versions/3.9.19/envs/superset-env/lib/python3.9/site-packages/flask/app.py", line 2005, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/Users/suwei/.pyenv/versions/3.9.19/envs/superset-env/lib/python3.9/site-packages/flask_session/base.py", line 305, in save_session
    self._upsert_session(app.permanent_session_lifetime, session, store_id)
  File "/Users/suwei/.pyenv/versions/3.9.19/envs/superset-env/lib/python3.9/site-packages/flask_session/redis/redis.py", line 78, in _upsert_session
    serialized_session_data = self.serializer.encode(session)
  File "/Users/suwei/.pyenv/versions/3.9.19/envs/superset-env/lib/python3.9/site-packages/flask_session/base.py", line 132, in encode
    return self.encoder.encode(dict(session))
TypeError: Encoding objects of type LazyString is unsupported
```

### Screenshots/recordings

![截屏2024-06-25 21 25 20](https://github.com/apache/superset/assets/11239462/6960ea9c-649f-4945-b6b3-1e4ceced6ae5)

### Superset version

4.0.1

### Python version

3.9

### Node version

Not applicable

### Browser

Chrome

### Additional context

**superset_config.py**

```python
import os
import json
import logging

from redis import Redis



DEBUG = True

SHOW_STACKTRACE = True
# 生成的 secret key
SECRET_KEY = 'GoOeN5Uo3wEPliy3PgAgpCi36vw9GEjN9N6ZZR3pEDSH/6E8nkf1ha4d'

# PostgreSQL 数据库 URI
SQLALCHEMY_DATABASE_URI = 'postgresql://superset:superset2024@localhost/superset'

LANGUAGES = {
    'zh': {'flag': 'cn', 'name': 'Chinese'},
    'en': {'flag': 'us', 'name': 'English'},
}

# Setup default language
BABEL_DEFAULT_LOCALE = 'zh'



# 会话配置
SESSION_TYPE = "redis"
SESSION_REDIS = Redis(host="localhost", port=6379, db=0)
SESSION_SERVER_SIDE = True

```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by weigosw** [comment]
Hi Thanks for help, but i can't import RedisSessionInterface
ImportError: cannot import name 'RedisSessionInterface' from 'flask_session'

**Comment by weigosw** [comment]
I printed the Session object with encoding errors,  the problem should be related to text leading by 'l'
```js
{
    '_permanent': True,
    'locale': 'zh',
    '_fresh': True,
    'csrf_token': 'cdecffb548f609b2b38eeeaf65ace448e9f847da',
    '_user_id': '2',
    '_id': 'd45ed5036f66c80fe6791e116e9c0f31e26c8489ea5acb8b4ea42d274e1be740c93d6f82573d2185896865f164a744bd5394c79c5a791fd08175bb7810baa8e1',
    'page_history': ['http://localhost:8088/exceltodatabaseview/form'],
    '_flashes': [
        (
            'danger', 
            l'无法将Excel文件 "Efficiency-Data-0625.xlsx" 上传到数据库 "Efficiency" 中的表 "Requirements" 内。错误消息：Table \'Requirements\' already exists.'
        )
    ]
}

```

**Comment by rusackas** [comment]
Not sure if @dosu-bot has more feedback here. Are you still facing this? It's been open quite a while, sorry about that.

**Comment by rusackas** [comment]
Assuming we're either good, or you've moved on. Happy to revisit/reopen if needed!

**Comment by alisonatwork** [comment]
For what it's worth, we just experienced the same problem in our setup, in what appears to be exactly the same scenario.

1. Sessions stored in Redis
2. Try to upload CSV file
-> error page, even though if you open a new tab and reload Superset it shows that the load actually succedeed

The error page hide the stack trace in the browser, but the actual stack trace in the server logs is exactly what was documented above - some mysterious error about `LazyString` not serializing correctly. We also patched the Superset source code in prod to print out the `dict` representation of the session to try figure out what was going wrong, and we also found this:

```py
'_flashes': [
  (
    'danger',
    l'Unable to upload CSV file "REDACTED.csv" to table "REDACTED" in database "REDACTED". Error message: Table 'REDACTED' already exists.'
  )
]
```

I.e. exactly the same error as @weigosw.

There are a couple of bugs here.

I think the first bug is "table already exists" is happening even on the first attempt to upload. It's also a bit weird because I thought CSV upload was supposed to be additive/merge, but that's by-the-by.

The second bug is that the error message is a `LazyString` instead of a plain old string, which means it cannot be serialized to Redis when the session manager try to JSONify the session. I don't know where that error message is generated, but perhaps it could be converted earlier, before it even get put into the session object.

A broader question I have is why error messages should go into the session at all, since seems like no need to make them stateful and could just be part of the HTTP response, but perhaps that's just a side-effect of the framework?

Edit to add a @rusackas ping just in case this seems worth reopening.
