### ISSUE TITLE
Tried reading schema message, was null or length 0

### ISSUE THREAD

**Issue by Habeeb556** [apache/superset#29398]
### Bug description

I am facing the below error while using Asynchronous query execution

```
superset[3830187]: Query 58614: Running query on a Celery worker
superset[3830187]: 2024-06-28 11:38:00,722:INFO:superset.sqllab.sql_json_executer:Query 58614: Running query on a Celery worker
superset[3830187]: 2024-06-28 11:38:00,723:DEBUG:celery.utils.functional:
superset[3830187]: def get_sql_results(query_id, rendered_query, return_results=0, store_results=1, username=2, start_time=3, expand_data=4, log_params=5):
superset[3830187]:    return 1
superset[3830187]: Tried reading schema message, was null or length 0
superset[3830187]: Traceback (most recent call last):
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
superset[3830187]:    rv = self.dispatch_request()
superset[3830187]:         ^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
superset[3830187]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset[3830187]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset[3830187]:    return f(self, *args, **kwargs)
superset[3830187]:           ^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/views/base_api.py", line 127, in wraps
superset[3830187]:    raise ex
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/views/base_api.py", line 121, in wraps
superset[3830187]:    duration, response = time_function(f, self, *args, **kwargs)
superset[3830187]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/core.py", line 1463, in time_function
superset[3830187]:    response = func(*args, **kwargs)
superset[3830187]:               ^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask_appbuilder/api/__init__.py", line 183, in wraps
superset[3830187]:    return f(self, *args, **kwargs)
superset[3830187]:           ^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/log.py", line 255, in wrapper
superset[3830187]:    value = f(*args, **kwargs)
superset[3830187]:            ^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/sqllab/api.py", line 342, in get_results
superset[3830187]:    result = SqlExecutionResultsCommand(key=key, rows=rows).run()
superset[3830187]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/commands/sql_lab/results.py", line 110, in run
superset[3830187]:    obj = _deserialize_results_payload(
superset[3830187]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/views/utils.py", line 512, in _deserialize_results_payload
superset[3830187]:    pa_table = pa.ipc.open_stream(reader).read_all()
superset[3830187]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/pyarrow/ipc.py", line 190, in open_stream
superset[3830187]:    return RecordBatchStreamReader(source, options=options,
superset[3830187]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/pyarrow/ipc.py", line 52, in __init__
superset[3830187]:    self._open(source, options=options, memory_pool=memory_pool)
superset[3830187]:  File "pyarrow/ipc.pxi", line 929, in pyarrow.lib._RecordBatchStreamReader._open
superset[3830187]:  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
superset[3830187]:  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
superset[3830187]: pyarrow.lib.ArrowInvalid: Tried reading schema message, was null or length 0
superset[3830187]: 2024-06-28 11:38:02,217:ERROR:superset.views.base:Tried reading schema message, was null or length 0
superset[3830187]: Traceback (most recent call last):
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
superset[3830187]:    rv = self.dispatch_request()
superset[3830187]:         ^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
superset[3830187]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset[3830187]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset[3830187]:    return f(self, *args, **kwargs)
superset[3830187]:           ^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/views/base_api.py", line 127, in wraps
superset[3830187]:    raise ex
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/views/base_api.py", line 121, in wraps
superset[3830187]:    duration, response = time_function(f, self, *args, **kwargs)
superset[3830187]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/core.py", line 1463, in time_function
superset[3830187]:    response = func(*args, **kwargs)
superset[3830187]:               ^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask_appbuilder/api/__init__.py", line 183, in wraps
superset[3830187]:    return f(self, *args, **kwargs)
superset[3830187]:           ^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/log.py", line 255, in wrapper
superset[3830187]:    value = f(*args, **kwargs)
superset[3830187]:            ^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/sqllab/api.py", line 342, in get_results
superset[3830187]:    result = SqlExecutionResultsCommand(key=key, rows=rows).run()
superset[3830187]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/commands/sql_lab/results.py", line 110, in run
superset[3830187]:    obj = _deserialize_results_payload(
superset[3830187]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/views/utils.py", line 512, in _deserialize_results_payload
superset[3830187]:    pa_table = pa.ipc.open_stream(reader).read_all()
superset[3830187]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/pyarrow/ipc.py", line 190, in open_stream
superset[3830187]:    return RecordBatchStreamReader(source, options=options,
superset[3830187]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[3830187]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/pyarrow/ipc.py", line 52, in __init__
superset[3830187]:    self._open(source, options=options, memory_pool=memory_pool)
superset[3830187]:  File "pyarrow/ipc.pxi", line 929, in pyarrow.lib._RecordBatchStreamReader._open
superset[3830187]:  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
superset[3830187]:  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
superset[3830187]: pyarrow.lib.ArrowInvalid: Tried reading schema message, was null or length 0

```

### How to reproduce the bug

Go to Asynchronous query execution and check it ON.

Note that I upgraded from v2 to v4. When I switch the virtual environment back to the old version, it works fine with no issues.

### Superset version

4.0.1

### Python version

3.11

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Habeeb556** [comment]
++ /swloc/.superset/superset_config.py

```
# Redis Caching
CACHE_NO_NULL_WARNING = True
CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 86400,
    'CACHE_KEY_PREFIX': 'superset_results',
    'CACHE_REDIS_HOST': 'localhost',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 1,
    'CACHE_REDIS_URL': 'redis://localhost:6379/1'
}


DATA_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 60 * 60 * 24, # 1 day default (in secs)
    'CACHE_KEY_PREFIX': 'superset_results',
    'CACHE_REDIS_URL': 'redis://localhost:6379/0',
}

# Long running query handling using Celery workers
class CeleryConfig(object):
    BROKER_URL = 'redis://localhost:6379/0'
    CELERY_IMPORTS = ('superset.sql_lab',
                      'superset.tasks'
    )
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERYD_LOG_LEVEL = 'DEBUG'
    CELERYD_PREFETCH_MULTIPLIER = 10
    CELERY_ACKS_LATE = True
    CELERY_ANNOTATIONS = {
        'sql_lab.get_sql_results': {
            'rate_limit': '100/s',
        },
        'email_reports.send': {
            'rate_limit': '1/s',
            'time_limit': 120,
            'soft_time_limit': 150,
            'ignore_result': True,
        },
    }
#    CELERYBEAT_SCHEDULE = {
#        'email_reports.schedule_hourly': {
#            'task': 'email_reports.schedule_hourly',
#            'schedule': crontab(minute=1, hour='*'),
#        },
#    }

CELERY_CONFIG = CeleryConfig

# Persisting results from running query handling using Celery workers
from cachelib.redis import RedisCache
RESULTS_BACKEND = RedisCache(host='localhost', port=6379, key_prefix='superset_results')
```

**Comment by Habeeb556** [comment]
It resolves the error, but the data returns as undefined.

![image](https://github.com/apache/superset/assets/35889071/a8f4b1e3-b212-4f66-a5d0-a032143f7ceb)

**Comment by Habeeb556** [comment]
Sorry, my mistake. I understand now. When I migrated to the new virtual environment, I missed updating the path in the /etc/systemd/system/celery.service
