### ISSUE TITLE
Asynchronous query execution sometimes stuck in PENDING status

### ISSUE THREAD

**Issue by Habeeb556** [apache/superset#29401]
### Bug description

I encountered the following issue: all ASYNC queries are PENDING.

The log shows that the queries are passed to the workers but do not return.

```
superset[3920984]: Triggering query_id: 58629
superset[3920984]: 2024-06-28 15:25:08,876:INFO:superset.commands.sql_lab.execute:Triggering query_id: 58629
superset[3920984]: Query 58629: Running query on a Celery worker
superset[3920984]: 2024-06-28 15:25:08,886:INFO:superset.sqllab.sql_json_executer:Query 58629: Running query on a Celery worker
superset[3920984]: Triggering query_id: 58630
superset[3920984]: 2024-06-28 15:25:10,448:INFO:superset.commands.sql_lab.execute:Triggering query_id: 58630
superset[3920984]: Query 58630: Running query on a Celery worker
superset[3920984]: 2024-06-28 15:25:10,456:INFO:superset.sqllab.sql_json_executer:Query 58630: Running query on a Celery worker
```

### How to reproduce the bug

Allow using Asynchronous query execution in database. When there a heavy load the queries get stuck in PENDING status.

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/35889071/859970dd-feab-4018-8dc7-d9a8f6e7b83e)

### Superset version

4.0.1

### Python version

3.11

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Habeeb556** [comment]
@dosu

Yes, configured as below:

```
# Redis Caching
CACHE_NO_NULL_WARNING = True
CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 86400,
    'CACHE_KEY_PREFIX': 'superset_results',
    'CACHE_REDIS_HOST': 'localhost',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 1,
    'CACHE_REDIS_URL': 'redis://localhost:6379/1'
}


DATA_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 60 * 60 * 24, # 1 day default (in secs)
    'CACHE_KEY_PREFIX': 'superset_results',
    'CACHE_REDIS_URL': 'redis://localhost:6379/0',
}

# Long running query handling using Celery workers
class CeleryConfig(object):
    BROKER_URL = 'redis://localhost:6379/0'
    CELERY_IMPORTS = ('superset.sql_lab',
                      'superset.tasks'
    )
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERYD_LOG_LEVEL = 'DEBUG'
    CELERYD_PREFETCH_MULTIPLIER = 10
    CELERY_ACKS_LATE = True
    CELERY_ANNOTATIONS = {
        'sql_lab.get_sql_results': {
            'rate_limit': '100/s',
        },
        'email_reports.send': {
            'rate_limit': '1/s',
            'time_limit': 120,
            'soft_time_limit': 150,
            'ignore_result': True,
        },
    }
#    CELERYBEAT_SCHEDULE = {
#        'email_reports.schedule_hourly': {
#            'task': 'email_reports.schedule_hourly',
#            'schedule': crontab(minute=1, hour='*'),
#        },
#    }

CELERY_CONFIG = CeleryConfig

# Persisting results from running query handling using Celery workers
from cachelib.redis import RedisCache
RESULTS_BACKEND = RedisCache(host='localhost', port=6379, key_prefix='superset_results')

# Disable MessagePack and PyArrow for results serialization
RESULTS_BACKEND_USE_MSGPACK = False
```

**Comment by rusackas** [comment]
@Habeeb556 just curious what wound up working, but glad it's resolved! :D

**Comment by Habeeb556** [comment]
@rusackas, I forgot to restart the service after upgrading the configurations. ^^

**Comment by Habeeb556** [comment]
@dosubot I encountered this error with a pending status in Celery.

```
error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): operation timed out
Traceback (most recent call last):
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/screenshots.py", line 170, in compute_and_cache
   payload = self.get_screenshot(user=user, window_size=window_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/screenshots.py", line 93, in get_screenshot
   self.screenshot = driver.get_screenshot(self.url, self.element, user)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/webdriver.py", line 354, in get_screenshot
   driver = self.auth(user)
            ^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/webdriver.py", line 276, in auth
   driver = self.create()
            ^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/webdriver.py", line 273, in create
   return driver_class(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 195, in __init__
   self.service.path = DriverFinder.get_path(self.service, options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
   raise err
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
   path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
   result = self.run(args)
            ^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
   raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --output json.
error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): operation timed out
```

**Comment by Habeeb556** [comment]
@dosu I am not using a docker

**Comment by Habeeb556** [comment]
@docu still the same issue with the below

`[2024-07-15 14:47:34,476: INFO/ForkPoolWorker-3] Applicable driver not found; attempting to install with Selenium Manager (Beta)`

**Comment by Habeeb556** [comment]
++ @dosu find the below also

```
WARNING/ForkPoolWorker-3] Unable to obtain driver using Selenium Manager: Selenium Manager failed for: /swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --output json.
error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): operation timed out
Failed at generating thumbnail Message: Selenium Manager failed for: /swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --output json.
```

**Comment by Habeeb556** [comment]
@dosu How to solve this error I got from log:

`superset.utils.screenshots:Failed at getting from cache: bf9c347bd37226bfbb1022c653927f76`

**Comment by Habeeb556** [comment]
@dosu How to resolve this issue cache in celery:

```
Failed at getting from cache: bdf9c4ac399103eaffbfa8b9322d6afc
INFO:superset.utils.screenshots:Failed at getting from cache: bdf9c4ac399103eaffbfa8b9322d6afc
```

**Comment by Habeeb556** [comment]
NICE! RESOLVED


```
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")
REDIS_CELERY_DB = os.getenv("REDIS_CELERY_DB", "2")
REDIS_RESULTS_DB = os.getenv("REDIS_RESULTS_DB", "3")
REDIS_CACHE_DB = os.getenv("REDIS_CACHE_DB", "4")

# Redis Caching
CACHE_CONFIG = {
    "CACHE_TYPE": "RedisCache",
    "CACHE_DEFAULT_TIMEOUT": 900,
    "CACHE_KEY_PREFIX": "superset_results",
    "CACHE_REDIS_URL": f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_CACHE_DB}",
}
DATA_CACHE_CONFIG = CACHE_CONFIG

# Long running query handling using Celery workers
class CeleryConfig(object):
    BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_CELERY_DB}"
    CELERY_IMPORTS = ("superset.sql_lab", "superset.tasks.thumbnails")
    CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_RESULTS_DB}"
    #CELERY_ANNOTATIONS = {"sql_lab.add": {"rate_limit": "10/s"}}
    CELERYD_LOG_LEVEL = 'DEBUG'
    CONCURRENCY = 1
    #CELERYD_PREFETCH_MULTIPLIER = 10
    #CELERY_ACKS_LATE = TRUE

CELERY_CONFIG = CeleryConfig

# Persisting results from running query handling using Celery workers
from cachelib.redis import RedisCache
RESULTS_BACKEND = RedisCache(host='localhost', port=6379, key_prefix='superset_results')
```

**Comment by Habeeb556** [comment]
> ```python
> driver = webdriver.Firefox(executable_path='/usr/local/bin/geckodriver', options=options)
> ```

@dosu PermissionError: [Errno 13] Permission denied: 'geckodriver.log'

**Comment by Habeeb556** [comment]
Resolved with this:

```
from selenium import webdriver

options = webdriver.FirefoxOptions()
options.headless = True  # Run in headless mode if needed

driver = webdriver.Firefox(executable_path='/usr/local/bin/geckodriver', options=options, log_path='/swloc/log/geckodriver.log')

```

But still have issue with this error in Celery log:

`selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
`
