### ISSUE TITLE
MSSQL Error: list index out of range

### ISSUE THREAD

**Issue by Habeeb556** [apache/superset#29494]
### Bug description

I received the following error message:

`list index out of range`

This occurred when upgrading from `version 2.1.3`, which supports Python 3.8, to Superset `version 4.0.2`, which supports Python 3.11, using the MSSQL engine with `pyodbc version 5.0.1`.

### How to reproduce the bug

I think the problem lies with the pyodbc version, as it works fine when using pymssql. However, all databases are currently configured with pyodbc. Do you have any recommendations to work around this issue?

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/35889071/0c412c79-1fc7-45e1-b31c-bedcd28b3258)

### Superset version

4.0.1

### Python version

3.11

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Habeeb556** [comment]
@dosu I am sure that `pyodbc_rows_to_tuples` method is correctly implemented and still get the `list index out of range` issue.

**Comment by Habeeb556** [comment]
++ Traceback @dosu

```
Traceback (most recent call last):
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
   rv = self.dispatch_request()
        ^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
   return f(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/views/base_api.py", line 127, in wraps
   raise ex
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/views/base_api.py", line 121, in wraps
   duration, response = time_function(f, self, *args, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/core.py", line 1470, in time_function
   response = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/views/base_api.py", line 93, in wraps
   return f(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/utils/log.py", line 255, in wrapper
   value = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/sqllab/api.py", line 409, in execute_sql_query
   command_result: CommandResult = command.run()
                                   ^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/commands/sql_lab/execute.py", line 121, in run
   raise ex
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/commands/sql_lab/execute.py", line 103, in run
   status = self._run_sql_json_exec_from_scratch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/commands/sql_lab/execute.py", line 163, in _run_sql_json_exec_from_scratch
   raise ex
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
   return self._sql_json_executor.execute(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/sqllab/sql_json_executer.py", line 111, in execute
   raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message='list index out of range', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Microsoft SQL Server', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```

**Comment by Habeeb556** [comment]
Okay, I found the error. It was a syntax mistake caused by a small detail in the copied source code. The old version of Python ignored it during execution, but the latest version doesn't, resulting in a `list index out of range` generic error.

![image](https://github.com/apache/superset/assets/35889071/b453258c-1fe7-4e8b-bdf8-4a2e1b296873)
