### ISSUE TITLE
No module named 'superset.translations.utils'

### ISSUE THREAD

**Issue by praveer38** [apache/superset#29613]
### Bug description

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 354, in decorator
    app = __ctx.ensure_object(ScriptInfo).load_app()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 237, in locate_app
    return find_app_by_string(module, app_name)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 165, in find_app_by_string
    app = attr(*args, **kwargs)
  File "/app/superset/app.py", line 47, in create_app
    raise ex
  File "/app/superset/app.py", line 40, in create_app
    app_initializer.init_app()
  File "/app/superset/initialization/__init__.py", line 489, in init_app
    self.init_app_in_ctx()
  File "/app/superset/initialization/__init__.py", line 417, in init_app_in_ctx
    self.configure_data_sources()
  File "/app/superset/initialization/__init__.py", line 515, in configure_data_sources
    __import__(module_name, fromlist=class_names)
  File "/app/superset/connectors/sqla/__init__.py", line 17, in <module>
    from . import models, views
  File "/app/superset/connectors/sqla/views.py", line 35, in <module>
    from superset.views.base import (
  File "/app/superset/views/__init__.py", line 17, in <module>
    from . import (
  File "/app/superset/views/alerts.py", line 25, in <module>
    from .base import BaseSupersetView
  File "/app/superset/views/base.py", line 81, in <module>
    from superset.translations.utils import get_language_pack
ModuleNotFoundError: No module named 'superset.translations.utils'

### How to reproduce the bug

This is happening after creating the container using the dockerfile created image.

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by praveer38** [comment]
@dosu "scripts/translations/generate_mo_files.sh: no such file or directory" : I'm getting this error while trying to compile translations using your step 3.

**Comment by praveer38** [comment]
These are the contents of my dockerfile, please help me resolve the superset/translations issue.
FROM apache/superset:4.0.2

USER root

RUN pip install mysqlclient
RUN pip install Authlib


COPY ./docker-init.sh /superset-init.sh
COPY docker-bootstrap.sh /app/docker/docker-bootstrap.sh

COPY superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py


USER superset
ENTRYPOINT [ "/superset-init.sh" ]

**Comment by rusackas** [comment]
I think this issue has gone silent prior to when many of the translation workflows were rejiggered. You can now follow these instructions to build updated translation files, and restart Superset: https://superset.apache.org/docs/contributing/howtos/#applying-translations

Closing in hopes that this is just outdated, but holler if this needs a revisit/reopen.
