### ISSUE TITLE
SQL Lab Error 'str' object has no attribute 'set'

### ISSUE THREAD

**Issue by deviardn** [apache/superset#29611]
### Bug description

Sorry, my English is not good. I am using apache superset version 4.0.2. I tried using the SQL Lab menu, I got an error like in the picture. what do I have to do? Thank You
![apache_superset_4_2](https://github.com/user-attachments/assets/8fe15b65-64d5-4ac3-a884-d2dd69754855)

### How to reproduce the bug

1. Login to apache superset
2. Click sql lab menu
3. Select database and table
4. Error

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by fzhan** [comment]
Not sure if it's related or the same issue to the issue I'm facing:
https://github.com/apache/superset/issues/29853

**Comment by rusackas** [comment]
If these are the same, let's close one in favor of the other.

**Comment by fzhan** [comment]
@rusackas I've tested the suggestion with sqlglot, it's not the same issue.

**Comment by fzhan** [comment]
I have captured the error log here:
```
2024-09-06 02:07:16,653:INFO:superset.sql_lab:Query 970: Executing 1 statement(s)
Query 970: Set query to 'running'
2024-09-06 02:07:16,653:INFO:superset.sql_lab:Query 970: Set query to 'running'
Query 970: Running statement 1 out of 1
2024-09-06 02:07:17,246:INFO:superset.sql_lab:Query 970: Running statement 1 out of 1
0.0.0.11 - - [06/Sep/2024:02:07:17 +0000] "POST /superset/log/?explode=events&dashboard_id=46 HTTP/1.1" 200 1 "https://superset.local/sqllab/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0"
2024-09-06 02:07:18,020:DEBUG:root:Query 970: Running query: select * from suppliers
LIMIT 1001
2024-09-06 02:07:18,035:DEBUG:root:Query 970: Handling cursor
Query 970: Storing results in results backend, key: 363e3e52-01cd-4938-b61a-1d0f6da2060a
2024-09-06 02:07:18,053:INFO:superset.sql_lab:Query 970: Storing results in results backend, key: 363e3e52-01cd-4938-b61a-1d0f6da2060a
0.0.0.11 - - [06/Sep/2024:02:07:18 +0000] "GET /api/v1/query/updated_since?q=(last_updated_ms:1725588358985) HTTP/1.1" 200 432 "https://superset.local/sqllab/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0"
SupersetErrorsException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1470, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 93, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/sqllab/api.py", line 409, in execute_sql_query
    command_result: CommandResult = command.run()
  File "/app/superset/commands/sql_lab/execute.py", line 121, in run
    raise ex
  File "/app/superset/commands/sql_lab/execute.py", line 103, in run
    status = self._run_sql_json_exec_from_scratch()
  File "/app/superset/commands/sql_lab/execute.py", line 163, in _run_sql_json_exec_from_scratch
    raise ex
  File "/app/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
    return self._sql_json_executor.execute(
  File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
    raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message="int() argument must be a string, a bytes-like object or a real number, not 'set'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'MySQL', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
2024-09-06 02:07:18,423:WARNING:superset.views.base:SupersetErrorsException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1470, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 93, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/sqllab/api.py", line 409, in execute_sql_query
    command_result: CommandResult = command.run()
  File "/app/superset/commands/sql_lab/execute.py", line 121, in run
    raise ex
  File "/app/superset/commands/sql_lab/execute.py", line 103, in run
    status = self._run_sql_json_exec_from_scratch()
  File "/app/superset/commands/sql_lab/execute.py", line 163, in _run_sql_json_exec_from_scratch
    raise ex
  File "/app/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
    return self._sql_json_executor.execute(
  File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
    raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message="int() argument must be a string, a bytes-like object or a real number, not 'set'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'MySQL', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
10.1.176.0 - - [06/Sep/2024:02:07:18 +0000] "POST /api/v1/sqllab/execute/ HTTP/1.1" 500 306 "https://superset.local/sqllab/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0"
```
```

**Comment by gorouter** [comment]
Superset 4.1.2 :

superset_app  | 2025-05-20 00:38:44,873:INFO:superset.commands.sql_lab.execute:Triggering query_id: 1
superset_app  | 2025-05-20 00:38:44,891:INFO:superset.sql_lab:Query 1: Executing 1 statement(s)
superset_app  | 2025-05-20 00:38:44,891:INFO:superset.sql_lab:Query 1: Set query to 'running'
superset_app  | 2025-05-20 00:38:44,918:INFO:superset.sql_lab:Query 1: Running statement 1 out of 1
superset_app  | 2025-05-20 00:38:44,974:INFO:superset.sql_lab:Query 1: Storing results in results backend, key: 2e5ccb97-e8cf-4a8f-9f63-9f69c4b5e121
superset_app  | 2025-05-20 00:38:44,990:WARNING:superset.views.error_handling:SupersetErrorsException
superset_app  | Traceback (most recent call last):
superset_app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
superset_app  |     rv = self.dispatch_request()
superset_app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
superset_app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app  |   File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset_app  |     return f(self, *args, **kwargs)
superset_app  |   File "/app/superset/views/base_api.py", line 119, in wraps
superset_app  |     duration, response = time_function(f, self, *args, **kwargs)
superset_app  |   File "/app/superset/utils/core.py", line 1364, in time_function
superset_app  |     response = func(*args, **kwargs)
superset_app  |   File "/app/superset/views/base_api.py", line 91, in wraps
superset_app  |     return f(self, *args, **kwargs)
superset_app  |   File "/app/superset/utils/log.py", line 303, in wrapper
superset_app  |     value = f(*args, **kwargs)
superset_app  |   File "/app/superset/sqllab/api.py", line 409, in execute_sql_query
superset_app  |     command_result: CommandResult = command.run()
superset_app  |   File "/app/superset/utils/decorators.py", line 266, in wrapped
superset_app  |     return on_error(ex)
superset_app  |   File "/app/superset/utils/decorators.py", line 236, in on_error
superset_app  |     raise ex
superset_app  |   File "/app/superset/utils/decorators.py", line 259, in wrapped
superset_app  |     result = func(*args, **kwargs)
superset_app  |   File "/app/superset/commands/sql_lab/execute.py", line 105, in run
superset_app  |     status = self._run_sql_json_exec_from_scratch()
superset_app  |   File "/app/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
superset_app  |     return self._sql_json_executor.execute(
superset_app  |   File "/app/superset/sqllab/sql_json_executer.py", line 110, in execute
superset_app  |     raise SupersetErrorsException(
superset_app  | superset.exceptions.SupersetErrorsException: [SupersetError(message="'dict' object has no attribute 'set'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'MySQL', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]

**Comment by fzhan** [comment]
@deviardn I had the similar issue where my redis result backend set to below:
```RESULTS_BACKEND = RedisCache(host="{env('REDIS_HOST')}", port={env('REDIS_PORT')}, key_prefix='superset_results', password="{env('REDIS_PASS')}")```

After I updated it to 
```RESULTS_BACKEND = RedisCache(host=f"{env('REDIS_HOST')}", port=int(env('REDIS_PORT')), key_prefix='superset_results', password=f"{env('REDIS_PASSWORD')}")```

Problem resolved.

Perhaps check your config for similar implementation.

**Comment by rusackas** [comment]
Closing this issue as it appears to be a configuration error rather than a Superset bug.

**Solution** (thanks @fzhan!): The error occurs when Redis configuration uses string literals instead of f-strings:

```python
# ❌ Wrong - missing 'f' prefix:
RESULTS_BACKEND = RedisCache(host="{env('REDIS_HOST')}", port={env('REDIS_PORT')}, ...)

# ✅ Correct - use f-strings:
RESULTS_BACKEND = RedisCache(host=f"{env('REDIS_HOST')}", port=f"{env('REDIS_PORT')}", ...)
```

This issue has been inactive for 270+ days and the solution was identified in the thread. If anyone encounters this on current versions after verifying their config, please open a new issue with details. Thanks! 🙏
