### ISSUE TITLE
SECRET KEY ERROR

### ISSUE THREAD

**Issue by iali9906** [apache/superset#29619]
### Bug description

Hello, 
I entered the variable 'SESSION_SERVER_SIDE = True ' and I encounter the following error:

```
superset-prod-01              | The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
superset-prod-01              | Traceback (most recent call last):
superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset-prod-01              |     rv = self.dispatch_request()
superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
superset-prod-01              |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_oidc/views.py", line 47, in login_view
superset-prod-01              |     session["next"] = request.args.get("next", request.root_url)
superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/sessions.py", line 98, in _fail
superset-prod-01              |     raise RuntimeError(
superset-prod-01              | RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
superset-prod-01              | 2024-07-17 12:04:04,327:ERROR:superset.views.base:The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
superset-prod-01              | Traceback (most recent call last):
superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset-prod-01              |     rv = self.dispatch_request()
superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
superset-prod-01              |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_oidc/views.py", line 47, in login_view
superset-prod-01              |     session["next"] = request.args.get("next", request.root_url)
superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/sessions.py", line 98, in _fail
superset-prod-01              |     raise RuntimeError(
superset-prod-01              | RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
```

in my superset_config.py I have the string SECRET_KEY = 'STRONGSTRING'

and logging into the shel with 'docker exec -en superset-prod-01 superset shell' and running the command “from flask import current_app; print(current_app.config[”SECRET_KEY“])” returns me the same string that I entered in superset_config.py

How can I solve it?

### How to reproduce the bug

1) add SESSION_SERVER_SIDE = True in superset_config.py
2) add secret key in superset_config.py
3) restart docker container

### Superset version

4.0.2

### Python version

I don't know

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by ylq5126** [comment]
> Hi @dosu now i set this value, but i have another errors:
> 
> SESSION_TYPE = "redis" SESSION_REDIS = Redis(host="superset-redis-prod-01", port=6379, db=0) SESSION_USE_SIGNER = True SESSION_COOKIE_SECURE = True SESSION_COOKIE_HTTPONLY = True SESSION_COOKIE_SAMESITE = "Lax"
> 
> ```
> 
> superset-prod-01              | Exception on / [GET]
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
> superset-prod-01              |     response = self.full_dispatch_request()
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
> superset-prod-01              |     return self.finalize_request(rv)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              | 2024-07-17 12:20:45,421:ERROR:superset.app:Exception on / [GET]
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
> superset-prod-01              |     response = self.full_dispatch_request()
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
> superset-prod-01              |     return self.finalize_request(rv)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              | Request finalizing failed with an error while handling an error
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
> superset-prod-01              |     response = self.full_dispatch_request()
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
> superset-prod-01              |     return self.finalize_request(rv)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              |
> superset-prod-01              | During handling of the above exception, another exception occurred:
> superset-prod-01              |
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              | 2024-07-17 12:20:45,423:ERROR:superset.app:Request finalizing failed with an error while handling an error
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
> superset-prod-01              |     response = self.full_dispatch_request()
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
> superset-prod-01              |     return self.finalize_request(rv)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              |
> superset-prod-01              | During handling of the above exception, another exception occurred:
> superset-prod-01              |
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              | 10.100.138.2 - - [17/Jul/2024:12:20:45 +0000] "GET / HTTP/1.1" 500 332 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
> ```

in docker change Werkzeug version to 2.3.8, it works fine
pip install werkzeug==2.3.8

**Comment by ylq5126** [comment]
> The error "TypeError: cannot use a string pattern on a bytes-like object" indicates a mismatch between string and byte data types. To resolve this issue in your Superset application when using Redis for session management, ensure that the session data is properly encoded and decoded.
> 
> Here's how you can adjust your `superset_config.py` to handle this:
> 
> 1. **Ensure Proper Encoding and Decoding**:
>    Make sure that any data being stored or retrieved from the session is properly encoded to bytes or decoded to strings as needed.
>    ```python
>    from redis import Redis
>    
>    SESSION_TYPE = "redis"
>    SESSION_REDIS = Redis(host="superset-redis-prod-01", port=6379, db=0)
>    SESSION_USE_SIGNER = True
>    SESSION_COOKIE_SECURE = True
>    SESSION_COOKIE_HTTPONLY = True
>    SESSION_COOKIE_SAMESITE = "Lax"
>    
>    # Example of encoding and decoding session data
>    def encode_data(data):
>        return data.encode('utf-8') if isinstance(data, str) else data
>    
>    def decode_data(data):
>        return data.decode('utf-8') if isinstance(data, bytes) else data
>    ```
> 2. **Check Session Data Handling**:
>    If you are manually handling session data, ensure that you encode strings to bytes before storing them in Redis and decode bytes to strings when retrieving them.
>    ```python
>    # Example usage
>    session_data = "some string data"
>    encoded_session_data = encode_data(session_data)
>    # Store `encoded_session_data` in Redis
>    
>    # When retrieving
>    retrieved_data = decode_data(encoded_session_data)
>    ```
> 
> By ensuring that the data types are correctly handled, you can avoid the "TypeError: cannot use a string pattern on a bytes-like object" error [[1]](https://github.com/apache/superset/blob/master/docs/docs/security/security.mdx).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

in docker 4.0.2-dev， werkzeug version not support bytes value

**Comment by ylq5126** [comment]
from this issue , https://github.com/pallets/werkzeug/issues/2795


> superset-prod-01              | Exception on / [GET]
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
> superset-prod-01              |     response = self.full_dispatch_request()
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
> superset-prod-01              |     return self.finalize_request(rv)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              | 2024-07-17 12:20:45,421:ERROR:superset.app:Exception on / [GET]
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
> superset-prod-01              |     response = self.full_dispatch_request()
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
> superset-prod-01              |     return self.finalize_request(rv)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              | Request finalizing failed with an error while handling an error
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
> superset-prod-01              |     response = self.full_dispatch_request()
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
> superset-prod-01              |     return self.finalize_request(rv)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              |
> superset-prod-01              | During handling of the above exception, another exception occurred:
> superset-prod-01              |
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              | 2024-07-17 12:20:45,423:ERROR:superset.app:Request finalizing failed with an error while handling an error
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
> superset-prod-01              |     response = self.full_dispatch_request()
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
> superset-prod-01              |     return self.finalize_request(rv)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              |
> superset-prod-01              | During handling of the above exception, another exception occurred:
> superset-prod-01              |
> superset-prod-01              | Traceback (most recent call last):
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1847, in finalize_request
> superset-prod-01              |     response = self.process_response(response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2344, in process_response
> superset-prod-01              |     self.session_interface.save_session(self, ctx.session, response)
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/flask_session/sessions.py", line 164, in save_session
> superset-prod-01              |     response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py", line 224, in set_cookie
> superset-prod-01              |     dump_cookie(
> superset-prod-01              |   File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1303, in dump_cookie
> superset-prod-01              |     if not _cookie_no_quote_re.fullmatch(value):
> superset-prod-01              | TypeError: cannot use a string pattern on a bytes-like object
> superset-prod-01              | 10.100.138.2 - - [17/Jul/2024:12:20:45 +0000] "GET / HTTP/1.1" 500 332 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

https://github.com/apache/superset/issues/29695

**Comment by ylq5126** [comment]
https://github.com/apache/superset/issues/29695
change  werkzeug version to 2.3.8
or 
update flask-session version to 0.8.0

**Comment by meghana1911** [comment]
I'm facing the exact list of errors above. Were you able to solve this? @iali9906

**Comment by rusackas** [comment]
Is anyone still facing this, particularly in 4.1.2 or newer? It's been slient for > 200 days. Hopefully [this](https://github.com/apache/superset/issues/29619#issuecomment-2249250115) solved things?

**Comment by rusackas** [comment]
Assuming from the silence that the dependency patches listed above worked, and all is well now. Correct me if i'm wrong, and I'll be happy to reopen.
