### ISSUE TITLE
Report fails to generate if dashboard doesn't contain a chart

### ISSUE THREAD

**Issue by oscep** [apache/superset#29629]
### Bug description

Superset cannot create a report for a dashboard without a chart element because the Selenium code involved waits for at least one chart element to render. A timeout occurs without a chart element present (see stack trace below).

This leads to an error message in the execution log which doesn't provide any meaningful information:
<img width="1469" alt="Screenshot 2024-07-18 at 10 00 03" src="https://github.com/user-attachments/assets/5bb053d9-8a8d-4330-88ab-e839cf185001">

We would suggest to either take a screenshot without chart elements present or to include a meaningful hint in the error message. Feel free to propose different solutions :-) 

### How to reproduce the bug

1. Create a Superset dashboard with a text layout element but no chart
2. Enable and configure Alerts & Reports for your Superset instance
3. Schedule a report for the dashboard created above
4. Access the execution log of the report.

### Superset version

4.0.2

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Additional context

```
Selenium timed out waiting for chart containers to draw at url http://superset.data:30080/superset/dashboard/914cb113-ac4a-4ba4-a46e-8f05e517691b/?force=false&standalone=3
Traceback (most recent call last):
  File "/app/superset/utils/webdriver.py", line 378, in get_screenshot
    WebDriverWait(driver, self._screenshot_locate_wait).until(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
This issue has been resolved by two separate fixes:

1. **For Selenium-based screenshots**: PR #30767 (merged Nov 2024) - Checks if a dashboard contains charts first and skips the wait if empty
2. **For Playwright-based screenshots**: PR #33107 (merged Apr 2025) - Allows screenshotting empty dashboards without timeout

Both fixes are now available in recent Superset releases. Empty dashboards containing only text or other non-chart elements can now be successfully screenshot for reports.

Thank you for the detailed bug report with reproduction steps and stack trace - this helped identify and fix the issue for both screenshot implementations.

Closing as fixed.
