### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by justinTM** [apache/superset#29624]
### Bug description

```console
> poetry add apache-superset
Using version ^4.0.2 for apache-superset
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/9c/e2/1a3507af7c8f91f8a4975d651d4aeb6a846dfdf74713954186ade4205
Resolving dependencies... (25.1s)
...
```

```console
> superset db upgrade
Traceback (most recent call last):
  File "/Users/me/git/gl/myorg/myproj/.venv/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/Users/me/git/gl/myorg/myproj/.venv/lib/python3.11/site-packages/superset/cli/main.py", line 28, in <module>
    from superset.cli.lib import normalize_token
  File "/Users/me/git/gl/myorg/myproj/.venv/lib/python3.11/site-packages/superset/cli/lib.py", line 20, in <module>
    from superset import config
  File "/Users/me/git/gl/myorg/myproj/.venv/lib/python3.11/site-packages/superset/config.py", line 39, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### How to reproduce the bug

see above

### Superset version

4.0.2

### Python version

3.11

### Node version

Not applicable

### Browser

Not applicable

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by justinTM** [comment]
fixed with:
```console
> poetry add setuptools
```

and re-running `superset` command
