### ISSUE TITLE
Fatal error when creating a chart from a saved_query via API call

### ISSUE THREAD

**Issue by imtiaznizami** [apache/superset#29697]
### Bug description

This is a repeat of #23189. I am unable to create a chart using `saved_query` following the superset API. It responds with `Fatal error` instead. (superset version 4.0.2 using docker compose)

### How to reproduce the bug

- Create a saved_query (query is based on my setup with valid db_id `2` and a table named `car`)

```
curl --location 'http://localhost:8088/api/v1/saved_query/' \
--header 'Authorization: Bearer eyJ...' \
--header 'X-CSRFToken: ImQ...' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Cookie: .eJ...' \
--data '{
  "db_id": 2,
  "label": "saved_query",
  "schema": "public",
  "sql": "SELECT * from car"
}
'
```

This gives back

```
{
    "id": 11,
    "result": {
        "db_id": 2,
        "description": null,
        "label": "saved_query",
        "schema": "public",
        "sql": "SELECT * from car",
        "template_parameters": null
    }
}
```

- Create the chart

```
curl --location 'http://localhost:8088/api/v1/chart/' \
--header 'Authorization: Bearer eyJ...' \
--header 'X-CSRFToken: ImQ...' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Cookie: .eJ...' \
--data '{
    "datasource_id": 11,
    "datasource_type": "saved_query",
    "slice_name": "some_name",
    "viz_type": "table"
}
'
```

This gives back

```
{
    "message": "Fatal error"
}
```

**Expected results**
Curl command to complete successfully with the creation of the chart from the saved query.

**Actual results**
Curl result is `{"message" : "Fatal error"}`

superset app stacktrace:

```
superset_app          | 2024-07-25 06:15:09,186:DEBUG:superset.stats_logger:[stats_logger] (incr) SavedQueryRestApi.post.success
superset_app          | 2024-07-25 06:15:09,186:DEBUG:superset.stats_logger:[stats_logger] (timing) SavedQueryRestApi.post.time | 21.099509991472587 
superset_app          | 172.26.0.1 - - [25/Jul/2024:06:15:09 +0000] "POST /api/v1/saved_query/ HTTP/1.1" 201 191 "-" "PostmanRuntime/7.40.0"
superset_app          | 2024-07-25 06:15:32,776:DEBUG:superset.stats_logger:[stats_logger] (incr) health
superset_app          | 127.0.0.1 - - [25/Jul/2024:06:15:32 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.88.1"
superset_app          | 2024-07-25 06:15:47,916:DEBUG:superset.stats_logger:[stats_logger] (incr) ChartRestApi.post.error
superset_app          | 2024-07-25 06:15:47,917:ERROR:flask_appbuilder.api:'SavedQuery' object has no attribute 'name'
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app          |     raise ex
superset_app          |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app          |     duration, response = time_function(f, self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1470, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/app/superset/utils/log.py", line 255, in wrapper
superset_app          |     value = f(*args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 93, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/charts/api.py", line 329, in post
superset_app          |     new_model = CreateChartCommand(item).run()
superset_app          |   File "/app/superset/commands/chart/create.py", line 46, in run
superset_app          |     self.validate()
superset_app          |   File "/app/superset/commands/chart/create.py", line 65, in validate
superset_app          |     self._properties["datasource_name"] = datasource.name
superset_app          | AttributeError: 'SavedQuery' object has no attribute 'name'
superset_app          | 172.26.0.1 - - [25/Jul/2024:06:15:47 +0000] "POST /api/v1/chart/ HTTP/1.1" 500 31 "-" "PostmanRuntime/7.40.0"
```

Also note that in #23189 the answer by ShaliniIruvuru ([answer](https://github.com/apache/superset/issues/23189#issuecomment-1515875030)) mentions `query` instead of `saved_query` in the chart creation JSON (which should be a different object). 

### Superset version

4.0.2

### Python version

I don't know

### Node version

I don't know

### Browser

Chrome

### Additional context

Used the following command to create superset container:

```
export TAG=4.0.2 && docker compose -f docker-compose-image-tag.yml up
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by imtiaznizami** [comment]
@dosu As mentioned in my original post, I am using 4.0.2 which is more recent than 4.0.0 suggested by you. Also, the issue you referenced has 4.0.2 label as well.

**Comment by imtiaznizami** [comment]
@dosu
The data-source table should have completely different IDs than data-source saved_queries.

However, I tried your suggestion, and the chart was created with an entirely different set of columns (which compliments what I wrote above).

**Comment by imtiaznizami** [comment]
This did not work. I am getting the same error.

**Comment by rusackas** [comment]
Sorry the bot didn't help, but this has slid under the radar and been silent for quite a long time. Are you still facing this issue? Maybe it's better in 4.1.2/5.0.0?

**Comment by KahaanD** [comment]
Facing the same issue; Any resolution to this? I suspect it might have something to do with Pivoted Tables

**Comment by rusackas** [comment]
This continues to be reported. If anyone can provide a minimal reproduction — a SQL query body, chart type, and the exact API call — that would help narrow down the root cause. A pivot table connection seems plausible based on recent comments.

**Comment by rusackas** [comment]
Circling back since nobody's landed a minimal repro yet. @KahaanD, if pivot tables are involved for you, could you share the exact chart type, a sample `sql` body, and the API call you're making? That'd be enough to actually chase this down.

This might be closed due to lack of engagement if we can't get a clear repro.

**Comment by endimonan** [comment]
Hello @rusackas 

<img width="722" height="572" alt="Image" src="https://github.com/user-attachments/assets/c933ce16-3c94-44a7-9ac2-0af742d4f7d7" />

After some tests I can reproduce that, seems to be a real issue. I think we can either add e2e chart support for saved_query or remove it from the chart API's accepted datasource types. What do you think? 

Cheers

**Comment by rusackas** [comment]
This one's been open too long, looking into it now...

**Comment by rusackas** [comment]
Thanks @endimonan, the minimal repro was exactly what was needed to pin this down.

Root cause: `Slice.datasource` only ever resolves the `table` relationship, so `datasource_type: "saved_query"` was always going to be a dead end — `SavedQuery` has no `.name` attribute, which is what crashes with the 500. `datasource_type: "query"` has the same underlying problem but doesn't crash (Query has an unrelated `.name` property used for CTAS naming), it just silently creates a chart that can never render.

Given how deep the "not actually wired up" gap goes (this isn't just the `.name` line — there's no code path that can query a saved_query/query-backed chart at all), went with your second option: reject both at chart create/update time with a clean 422 instead of the opaque 500, rather than trying to build out full e2e support for something charts were never actually plumbed to do.

PR: #43500
