### ISSUE TITLE
[4.0.2] SQL LAB int argument error since version 4

### ISSUE THREAD

**Issue by fzhan** [apache/superset#29853]
### Bug description

Since upgraded to version 4, currently running 4.0.2, SQL LAB has stop working on all previous functioning database connections, mariadb, postgres and mssql. 

### How to reproduce the bug

1. Add a db connection,
2. Go to sql lab
3. Run a query

Here's the log: 
```
2024-08-05 00:02:35,647:INFO:superset.sql_lab:Query 940: Storing results in results backend, key: 3f218da6-8f9f-47c1-a68f-8b1abfc89b12
SupersetErrorsException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1470, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 93, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/sqllab/api.py", line 409, in execute_sql_query
    command_result: CommandResult = command.run()
  File "/app/superset/commands/sql_lab/execute.py", line 121, in run
    raise ex
  File "/app/superset/commands/sql_lab/execute.py", line 103, in run
    status = self._run_sql_json_exec_from_scratch()
  File "/app/superset/commands/sql_lab/execute.py", line 163, in _run_sql_json_exec_from_scratch
    raise ex
  File "/app/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
    return self._sql_json_executor.execute(
  File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
    raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message="int() argument must be a string, a bytes-like object or a real number, not 'set'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'MySQL', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/d7fe4779-85c9-4655-b6bf-d19bd5ee6f79)
<img width="613" alt="image" src="https://github.com/user-attachments/assets/ce0ae4b7-8628-475a-a348-b92588301b62">

### Superset version

4.0.2

### Python version

3.10

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Hmm, something seems funny here... if you couldn't run any query in postgres/mysql, there'd be pitchforks and torches out on the streets by now. Can you give an example failing query, preferably using an example dataset?

**Comment by fzhan** [comment]
@rusackas I do have some custom libs:
```
pip install sqlalchemy-bigquery redis pymssql pyodbc pymysql mysql-connector-python holidays==0.32 prophet==1.1.4 authlib celery==5.3.6 kombu==5.4.0rc3 sqlglot
```

**Comment by rusackas** [comment]
Hey @fzhan  - sorry for the lack of reply... I simply don't know how to troubleshoot/fix this one personally. Now that it's been 200+ days, are you still facing this issue, or did you find a workaround?

**Comment by fzhan** [comment]
Hi @rusackas, I do have good news, I found exactly what was the issue:

I used the k8s package where config was written in configOverrides section:
originally, I had 
RESULTS_BACKEND = RedisCache(host="{env('REDIS_HOST')}", port={env('REDIS_PORT')}, key_prefix='superset_results', password="{env('REDIS_PASS')}")

Then I changed it to 
RESULTS_BACKEND = RedisCache(host=f"{env('REDIS_HOST')}", port=int(env('REDIS_PORT')), key_prefix='superset_results', password=f"{env('REDIS_PASSWORD')}")

Apparent the port number was the issue, format it to int solve the problem.
