### ISSUE TITLE
The in-memory storage for tracking rate limits

### ISSUE THREAD

**Issue by Habeeb556** [apache/superset#29908]
### Bug description

The below warnings appears in logs when startup:

```
superset[2032316]:  warnings.warn(
superset[2032276]: logging was configured successfully
superset[2032276]: 2024-08-09 22:52:32,367:INFO:superset.utils.logging_configurator:logging was configured successfully
superset[2032276]: 2024-08-09 22:52:32,371:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
superset[2032276]: /swloc/.virtualenvs/supersetvenv5/lib/python3.10/site-packages/flask_limiter/extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
superset[2032276]:  warnings.warn(
superset[2032328]: logging was configured successfully
superset[2032328]: 2024-08-09 22:52:32,492:INFO:superset.utils.logging_configurator:logging was configured successfully
superset[2032328]: 2024-08-09 22:52:32,519:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
superset[2032328]: /swloc/.virtualenvs/supersetvenv5/lib/python3.10/site-packages/flask_limiter/extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
superset[2032328]:  warnings.warn(
```

### How to reproduce the bug

Fresh setup.

### Superset version

4.0.2

### Python version

3.11

### Node version

I don't know

### Browser

Not applicable

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by Habeeb556** [comment]
Issue resolved and configured successfully. Awesome!

```
# A storage location conforming to the scheme in storage-scheme. See the limits
# library for allowed values: https://limits.readthedocs.io/en/stable/storage.html
RATELIMIT_STORAGE_URI = f"redis://{REDIS_HOST}:{REDIS_PORT}"
```

**Comment by Habeeb556** [comment]
++ @dosu could you help me with the warning also:

`superset[1501968]: 2024-08-09 23:09:34,652:WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped`

**Comment by Habeeb556** [comment]
@dosu how to pass this line? where

```
# Instead of passing the proxy directly, access the underlying object
actual_results_backend = results_backend._get_current_object()
# Use actual_results_backend in your ORM operations
```

**Comment by Habeeb556** [comment]
@dosu find the below error:

```
superset[1654904]: NameError: name 'results_backend' is not defined
superset[1654904]: Failed to create app
superset[1654904]: Traceback (most recent call last):
superset[1654904]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/app.py", line 37, in create_app
superset[1654904]:    app.config.from_object(config_module)
superset[1654904]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask/config.py", line 231, in from_object
superset[1654904]:    obj = import_string(obj)
superset[1654904]:          ^^^^^^^^^^^^^^^^^^
superset[1654904]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/werkzeug/utils.py", line 595, in import_string
superset[1654904]:    __import__(import_name)
superset[1654904]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/config.py", line 1699, in <module>
superset[1654904]:    override_conf = imp.load_source("superset_config", cfg_path)
superset[1654904]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[1654904]:  File "/usr/local/lib/python3.11/imp.py", line 172, in load_source
superset[1654904]:    module = _load(spec)
superset[1654904]:             ^^^^^^^^^^^
superset[1654904]:  File "/swloc/.superset/superset_config.py", line 9, in <module>
superset[1654904]:    actual_results_backend = results_backend._get_current_object()
superset[1654904]:                             ^^^^^^^^^^^^^^^
superset[1654904]: NameError: name 'results_backend' is not defined
```

**Comment by Habeeb556** [comment]
@dosu find this:

```
superset[1660637]: AttributeError: 'FileSystemCache' object has no attribute '_get_current_object'
superset[1660637]: Failed to create app
superset[1660637]: Traceback (most recent call last):
superset[1660637]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/app.py", line 37, in create_app
superset[1660637]:    app.config.from_object(config_module)
superset[1660637]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/flask/config.py", line 231, in from_object
superset[1660637]:    obj = import_string(obj)
superset[1660637]:          ^^^^^^^^^^^^^^^^^^
superset[1660637]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/werkzeug/utils.py", line 595, in import_string
superset[1660637]:    __import__(import_name)
superset[1660637]:  File "/swloc/.virtualenvs/supersetvenv4/lib/python3.11/site-packages/superset/config.py", line 1699, in <module>
superset[1660637]:    override_conf = imp.load_source("superset_config", cfg_path)
superset[1660637]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[1660637]:  File "/usr/local/lib/python3.11/imp.py", line 172, in load_source
superset[1660637]:    module = _load(spec)
superset[1660637]:             ^^^^^^^^^^^
superset[1660637]:  File "/swloc/.superset/superset_config.py", line 12, in <module>
superset[1660637]:    actual_results_backend = RESULTS_BACKEND._get_current_object()
superset[1660637]:                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
superset[1660637]: AttributeError: 'FileSystemCache' object has no attribute '_get_current_object'
```

**Comment by Habeeb556** [comment]
@dosu but it doesn't solve the warning:

`WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped`

**Comment by Habeeb556** [comment]
@dosu still the below warning exists, how to skip it.

`WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped`

**Comment by PHTremor** [comment]
> To resolve the warning about using in-memory storage for tracking rate limits in Superset during startup, you need to configure a persistent storage backend for rate limiting. This can be done by setting the `RATELIMIT_STORAGE_URI` in your configuration file to a supported storage backend, such as Redis.
> 
> Here is how you can set it up in your `superset_config.py`:
> 
> # A storage location conforming to the scheme in storage-scheme. See the limits
> # library for allowed values: https://limits.readthedocs.io/en/stable/storage.html
> RATELIMIT_STORAGE_URI = "redis://host:port"
> Replace `"redis://host:port"` with the actual URI of your Redis instance. This will configure Superset to use Redis for tracking rate limits instead of the default in-memory storage.


Is there a way to have this tag inside values.yaml for helm installation?
