### ISSUE TITLE
DynamoDB Chart Failure 

### ISSUE THREAD

**Issue by noahabbott123** [apache/superset#29920]
### Bug description

Very basic column retrieval from a DynamoDB table with numbers results in a failure in any Chart function. 

### How to reproduce the bug

1. Setup Dynamo DB connector
2. Run query in SQL Lab 
3. Click "Create Chart"
4. Any preview, chart, configuration gives the error "Error: Expected table, found '('  (at char 28), (line:3, col:3)"

### Screenshots/recordings

Here is the stack trace:
`2024-08-12 16:53:18,496:WARNING:superset.models.helpers:Query SELECT COUNT(*)
FROM
  (SELECT NUMBER(TotalAlerts)
   FROM AlertsMetrics) AS virtual_table
LIMIT 50000 on schema default failed
Traceback (most recent call last):
  File "/app/superset/models/helpers.py", line 1032, in exc_query
    df = self.database.get_df(sql, self.schema, mutator=assign_column_label)
  File "/app/superset/models/core.py", line 604, in get_df
    self.db_engine_spec.execute(cursor, sqls[-1])
  File "/app/superset/db_engine_specs/base.py", line 1599, in execute
    raise cls.get_dbapi_mapped_exception(ex) from ex
  File "/app/superset/db_engine_specs/base.py", line 1597, in execute
    cursor.execute(query)
  File "/app/superset_home/.local/lib/python3.10/site-packages/pydynamodb/util.py", line 23, in _wrapper
    return wrapped(*args, **kwargs)
  File "/app/superset_home/.local/lib/python3.10/site-packages/pydynamodb/cursor.py", line 85, in execute
    statement = Statement(operation)
  File "/app/superset_home/.local/lib/python3.10/site-packages/pydynamodb/model.py", line 172, in __init__
    self._api_request = self._sql_parser.transform()
  File "/app/superset_home/.local/lib/python3.10/site-packages/pydynamodb/sql/parser.py", line 108, in transform
    return self.parser.transform()
  File "/app/superset_home/.local/lib/python3.10/site-packages/pydynamodb/sql/dml_select.py", line 171, in transform
    table_name_ = self.root_parse_results["table"]
  File "/app/superset_home/.local/lib/python3.10/site-packages/pydynamodb/sql/base.py", line 34, in root_parse_results
    self._root_parse_results = self.syntax_def.parseString(self._executed_statement)
  File "/usr/local/lib/python3.10/site-packages/pyparsing/core.py", line 1127, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected CaselessKeyword 'FROM', found '('  (at char 12), (line:1, col:13)`

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

16

### Browser

Not applicable

### Additional context

Running in K8 cluster. 

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by santhosh25s** [comment]
Hi There, I am facing the same issue, is there any update ?

**Comment by rusackas** [comment]
@TheShubhendra is the only person in the [DB user Rolodex](https://docs.google.com/spreadsheets/d/1U1qxiLvOX0kBTUGME1AHHi6Ywel6ECF8xk_Qy-V9R8c/edit?gid=0#gid=0) that uses Dynamo DB. Not sure if they can help, but worth a ping! 

Otherwise, I'm not sure who might be able to help here, but there may need to be some adjustments in the SQL parser or DBAPI driver. @betodealmeida might be able to advise.

According to a quick Claude chat, it sounds like you can remove `AS virtual_table` and change `COUNT(*)` to `COUNT(1)` in your query, but I have no idea if that's accurate :P

**Comment by rusackas** [comment]
Anyone have any luck with the above suggestion(s)? This might be closed due to inactivity before long. Updated context would be appreciated, or if anyone can troubleshoot and open a PR, we'd be happy to review it.

**Comment by rusackas** [comment]
Closing this issue due to inactivity. This appears to be a SQL parsing issue specific to the DynamoDB connector, and we haven't had anyone available to troubleshoot it further.

If you're using DynamoDB with Superset and can help debug this issue, please:
1. Reopen this issue with updated context (Superset version, exact query, full stack trace)
2. Or better yet, open a PR with a fix if you can identify the root cause

The issue seems to be in how the SQL parser handles DynamoDB's query syntax when creating virtual tables for charts. Thanks for your patience! 🙏
