### ISSUE TITLE
AttributeError: 'Template' object has no attribute 'strip'

### ISSUE THREAD

**Issue by MEclipse1** [apache/superset#29940]
## Screenshot

![image](https://github.com/user-attachments/assets/d591adc3-a03a-4b6c-9825-eff5edc40bdd)

## Description

2024-08-14 11:39:14,348:ERROR:marvel.views.error_handling:'Template' object has no attribute 'strip'
Traceback (most recent call last):
  File "e:\project\marvel\marvel\views\error_handling.py", line 84, in wraps
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\project\marvel\marvel\views\base_api.py", line 447, in get_list_headless
    duration, response = time_function(super().get_list_headless, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\project\marvel\marvel\utils\core.py", line 1348, in time_function
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dabu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_appbuilder\api\__init__.py", line 1629, in get_list_headless
    response[API_RESULT_RES_KEY] = list_model_schema.dump(lst, many=True)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dabu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\marshmallow\schema.py", line 549, in dump
    result = self._serialize(processed_obj, many=many)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dabu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\marshmallow\schema.py", line 511, in _serialize
    return [
           ^
  File "C:\Users\dabu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\marshmallow\schema.py", line 512, in <listcomp>
    self._serialize(d, many=False)
  File "C:\Users\dabu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\marshmallow\schema.py", line 517, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dabu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\marshmallow\fields.py", line 341, in serialize
    return self._serialize(value, attr, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dabu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\marshmallow\fields.py", line 1985, in _serialize
    return self._serialize_method(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\project\marvel\marvel\queries\schemas.py", line 60, in get_sql_tables
    return obj.sql_tables
           ^^^^^^^^^^^^^^
  File "e:\project\marvel\marvel\models\sql_lab.py", line 67, in sql_tables
    extract_tables_from_jinja_sql(
  File "e:\project\marvel\marvel\sql_parse.py", line 1609, in extract_tables_from_jinja_sql
    | ParsedQuery(
      ^^^^^^^^^^^^
  File "e:\project\marvel\marvel\sql_parse.py", line 735, in __init__
    self._parsed = sqlparse.parse(self.stripped())
                                  ^^^^^^^^^^^^^^^
  File "e:\project\marvel\marvel\sql_parse.py", line 1015, in stripped
    return self.sql.strip(" \t\r\n;")
           ^^^^^^^^^^^^^^
AttributeError: 'Template' object has no attribute 'strip'

**Comment by sfirke** [comment]
It would help if you followed the bug report template and included the version of Superset you're using, etc.

This looks like a duplicate of https://github.com/apache/superset/issues/28145, what do you think?

**Comment by MEclipse1** [comment]
> It would help if you followed the bug report template and included the version of Superset you're using, etc.
> 
> This looks like a duplicate of #28145, what do you think?

That helped. Thanks a lot!

**Comment by MEclipse1** [comment]
> It would help if you followed the bug report template and included the version of Superset you're using, etc.
> 
> This looks like a duplicate of #28145, what do you think?

That helped. Thanks a lot!
