### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by ohitsdoh** [apache/superset#30162]
### Bug description

Periodically getting this issue in dashboard filters, particularly when there are a lot of filters

### How to reproduce the bug

Load a dashboard with a lot of filters

### Screenshots/recordings

<img width="263" alt="image" src="https://github.com/user-attachments/assets/3e12ed74-f30f-4c25-9cf1-7156317c7524">
<img width="611" alt="image" src="https://github.com/user-attachments/assets/8918efb2-73fb-4aa7-8d1b-59b27075ad9f">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at uc (react-dom.production.min.js:230:46)
    at gi (react-dom.production.min.js:163:512)
    at useChildElementTruncation.ts:99:9
    at ul (react-dom.production.min.js:211:320)
    at sl (react-dom.production.min.js:212:65)
    at Cc (react-dom.production.min.js:255:229)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Ka (react-dom.production.min.js:122:325)
    at Pc (react-dom.production.min.js:248:370)
    at mc (react-dom.production.min.js:239:376)
ol @ react-dom.production.min.js:209
Show 1 more frame
Show less

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by kirmorozov1992** [comment]
Hello everyone! I met this bug using sqllab in Superset. Besides, only one user had the bug. I tried to resolve an issue - let user login from my PC. So, result is now it`s problem in my account, and user`s problem was resolved. Floating bug ...

![image](https://github.com/user-attachments/assets/c19f4664-3d82-4c73-85cc-5551bcb32d14)

**Comment by rusackas** [comment]
Is anyone still facing this issue? I've thus far been unable to reproduce, and it's been silent here for about 5 months. I'll close this as inactive, but if anyone's able to reproduce this in currently supported versions (4.1.2/5.0.0) I'm more than happy to reopen/revisit.
