### ISSUE TITLE
docker bug

### ISSUE THREAD

**Issue by vyouzhis** [apache/superset#30183]
### Bug description

website img
![image](https://github.com/user-attachments/assets/d2f97b21-6112-4d4e-aaf1-ebf47d2280fb)

docker log -f 

`
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-09-07 08:36:18,303:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:18] "GET /static/assets/images/superset-logo-horiz.png HTTP/1.1" 404 -
2024-09-07 08:36:18,364:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:18] "GET /static/appbuilder/css/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 -
2024-09-07 08:36:18,429:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-09-07 08:36:18,430:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:18] "GET /static/assets/images/favicon.png HTTP/1.1" 404 -
2024-09-07 08:36:21,994:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:21] "POST /login/ HTTP/1.1" 302 -
2024-09-07 08:36:22,011:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:22] "GET / HTTP/1.1" 302 -
2024-09-07 08:36:22,065:DEBUG:superset.stats_logger:[stats_logger] (incr) welcome
2024-09-07 08:36:22,073:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:22] "GET /superset/welcome/ HTTP/1.1" 200 -
2024-09-07 08:36:22,157:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-09-07 08:36:22,158:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:22] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
2024-09-07 08:36:22,167:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-09-07 08:36:22,167:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:22] "GET /static/assets/images/favicon.png HTTP/1.1" 404 -
2024-09-07 08:36:43,056:DEBUG:superset.stats_logger:[stats_logger] (incr) health
2024-09-07 08:36:43,056:INFO:werkzeug:127.0.0.1 - - [07/Sep/2024 08:36:43] "GET /health HTTP/1.1" 200 -
2024-09-07 08:36:53,585:DEBUG:superset.stats_logger:[stats_logger] (incr) welcome
2024-09-07 08:36:53,593:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:53] "GET /superset/welcome/ HTTP/1.1" 200 -
2024-09-07 08:36:53,625:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-09-07 08:36:53,626:INFO:werkzeug:192.168.2.100 - - [07/Sep/2024 08:36:53] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
2024-09-07 08:37:13,160:DEBUG:superset.stats_logger:[stats_logger] (incr) health
2024-09-07 08:37:13,160:INFO:werkzeug:127.0.0.1 - - [07/Sep/2024 08:37:13] "GET /health HTTP/1.1" 200 -

`

### How to reproduce the bug

1. superset-4.0.2
2. sudo docker compose up -d

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by pesekon2** [comment]
Getting exactly the same for the developer and non-dev images. The image one works for me but that one is not useful for me.

**Comment by Darrenzzy** [comment]
According to the configuration of Nginx in the Docker directory, there is no configuration directing static resources. It is recommended to make the following modifications:

Steps:

1.	Stop docker-compose first.

2.	Edit nginx.conf:
          ```        vim docker/nginx/nginx.conf ```

Add and modify the following content:
```

server {
   listen 80 default_server;
   server_name  _;

   location /ws {
       proxy_pass http://superset_websocket;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "Upgrade";
       proxy_set_header Host $host;
   }
   location /static {
            alias /app/superset-frontend/src;
            expires 30d;
            access_log off;
   }

   location / {
       proxy_pass http://superset_app;
       proxy_set_header    Host                $host;
       proxy_set_header    X-Real-IP           $remote_addr;
       proxy_set_header    X-Forwarded-For     $remote_addr;
       proxy_set_header    X-Forwarded-Host    $host;
       proxy_set_header    X-Forwarded-Proto   $scheme;
       proxy_http_version 1.1;
       port_in_redirect off;
       proxy_connect_timeout 300;
   }
}
```
	
3.  After making the changes, restart docker-compose:

```
docker compose up
```

**Comment by mistercrunch** [comment]
Related: https://github.com/apache/superset/pull/30752

**Comment by fuomag9** [comment]
Same issue here, apache superset is unusable

**Comment by mistercrunch** [comment]
How did you build/start the docker?

**Comment by fuomag9** [comment]
> How did you build/start the docker?

By following the official documentation https://superset.apache.org/docs/installation/docker-compose/#option-1---for-an-interactive-development-environment

**Comment by mistercrunch** [comment]
Now that I think about it, after a pull/rebase you may have to run `docker compose build`, let me clarify in the docs

**Comment by fuomag9** [comment]
> Now that I think about it, after a pull/rebase you may have to run `docker compose build`, prior to `docker compose up` let me clarify in the docs

I don't think that's the problem, since when running `docker compose up` docker will try to build the image locally first, if defined inside the docker-compose file and alternatively it will try to pull the image defined for all containers from the specified or default registry

**Comment by mistercrunch** [comment]
I think it may matter in this case, from my experience, running `docker compose up` after say a rebase where `requirements.txt` has changed, won't run a build cycle while the app will now require the new lib and fail. Seems like the very existence of `--build` as an argument says that it won't build by default. Though note that if the image does not exist at all it will have to build. Note that this only affects docker-compose.yml and not the 2 other files as the former references a `Dockerfile` while others reference properly labeled image that are consistent with themselves. 

Please try running it and report back.

Related: https://github.com/apache/superset/pull/30864

**Comment by fuomag9** [comment]
> I think it may matter in this case, from my experience, running `docker compose up` after say a rebase where `requirements.txt` has changed, won't run a build cycle while the app will now require the new lib and fail. Seems like the very existence of `--build` as an argument says that it won't build by default. Though note that if the image does not exist at all it will have to build. Note that this only affects docker-compose.yml and not the 2 other files as the former references a `Dockerfile` while others reference properly labeled image that are consistent with themselves.
> 
> Please try running it and report back.
> 
> Related: #30864

As expected, this does not fix the issue even after running. I can replicate this on another machine as well

```
superset_app          | 2024-11-06 23:11:00,682:WARNING:superset.views.error_handling:HTTPException
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
superset_app          |     rv = self.dispatch_request()
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
superset_app          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 502, in <lambda>
superset_app          |     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 317, in send_static_file
superset_app          |     return send_from_directory(
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 557, in send_from_directory
superset_app          |     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
superset_app          |   File "/usr/local/lib/python3.10/site-packages/werkzeug/utils.py", line 575, in send_from_directory
superset_app          |     raise NotFound()
superset_app          | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
superset_app          | 2024-11-06 23:11:00,683:INFO:werkzeug:172.18.0.1 - - [06/Nov/2024 23:11:00] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
superset_app          | 2024-11-06 23:11:00,686:WARNING:superset.views.error_handling:HTTPException
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
superset_app          |     rv = self.dispatch_request()
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
superset_app          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 502, in <lambda>
superset_app          |     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 317, in send_static_file
superset_app          |     return send_from_directory(
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 557, in send_from_directory
superset_app          |     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
superset_app          |   File "/usr/local/lib/python3.10/site-packages/werkzeug/utils.py", line 575, in send_from_directory
superset_app          |     raise NotFound()
superset_app          | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
superset_app          | 2024-11-06 23:11:00,687:INFO:werkzeug:172.18.0.1 - - [06/Nov/2024 23:11:00] "GET /static/assets/images/favicon.png HTTP/1.1" 404 -
```

**Comment by mistercrunch** [comment]
So what's different from your environment and everyone else's? Please share which git ref/sha you're using and local environment settings that may be relevant (platform, docker-version, docker-compose version). Also maybe nuking you docker environment might help (?) If that's reasonable to do in your env:

```bash
docker builder prune --all --force
docker system prune --all --volumes --force
```

@rusackas if we had this https://github.com/apache/superset/pull/29609 merged I could just say "please run this script and post the output", it would gather relevant info. Thinking about it I should add host-platform, cpu-type, as they would be relevant here. Probably makes sense to merge so that we can iterate on it.

**Comment by fuomag9** [comment]
@mistercrunch FYI https://github.com/apache/superset/pull/30752 fixes this correctly, I just tested it, so it's not related to the docker documentation but a lack of correct configuration in the repository files

**Comment by mistercrunch** [comment]
Still wondering why current docker-compose setup works in some environments and not others, but can review/merge https://github.com/apache/superset/pull/30752

**Comment by mistercrunch** [comment]
Not sure if/how it would matter, maybe local settings, but why not using `http://localhost:8088` instead of `http://{ip}:8088`

**Comment by rusackas** [comment]
This has been silent for quite a while, and a lot has changed in the Docker builds (e.g. you use port 9000 nowadays). Tempted to close this as inactive or move it to a Discussion, but let us know if this is still a blocker for anyone, and we'll act accordingly.

**Comment by fengthedroid** [comment]
I've encountered the same issue after clone the repo and run `docker compose up`

**Comment by mistercrunch** [comment]
Good input, I think there's some funk/layers/complicity around how we serve the static assets, and we could really use a deep dive to improve all that.

Unpacking some of the complexity requirements:
- need to enable for people to use/configure a CDN
- frontend and backend need to be aware of that configuration
- manifest-related stuff, and dealing with outdated frontend single-page-app manifest living in browsers. Here when a previous version of the frontend is trying to hot-load an asset in the previous manifest, it might be gone... We might need some smarts here around checking whether the SPA version is off and force users to reload the SPA when new versions are pushed. We may also have some logic around that already (?)
- timing issues? maybe the page is trying to load before the assets are ready (?)

**Comment by rusackas** [comment]
I've opened PR #38161 to fix this issue.

**Root cause identified:** This is a race condition where nginx starts before the webpack dev server is ready. Nginx proxies `/static` requests to port 9000, but `superset-node` needs time to run `npm install` and start the dev server first.

**The fix:**
1. Added a health check to `superset-node` that verifies the webpack dev server is responding
2. Added `depends_on: service_healthy` to nginx so it waits for the frontend to be ready

This should resolve the 404 errors that occur during initial startup. The "workaround" of running `npm run build` manually worked because it created static assets that Flask could serve directly, bypassing the need for the webpack dev server - but that's not how the dev setup is supposed to work.
