### ISSUE TITLE
Superset 4.1 with Pinot not aggregating timestamps correctly

### ISSUE THREAD

**Issue by anthony-df-nguyen** [apache/superset#30219]
### Bug description

# Issue
It appears that when using Pinot (1.2.0) with Superset 4.1, columns that are epoch_ms formatted fields are not aggregating correctly without a lot of workarounds. It worked okay for us back when we were on Superset 2.0.

On Superset 2.0, when we used the old `Time Series Line Chart`, if we use an epoch_ms column as the time column, the query being made was the following which was working. 

`SELECT DATETIMECONVERT(incident_date_epoch, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:DAYS'),
       count(DISTINCT report_id) AS count_1
FROM "default".incident_reports
GROUP BY DATETIMECONVERT(incident_date_epoch, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:DAYS')
ORDER BY count(DISTINCT report_id) DESC
LIMIT 10000;`

**Example of previously working Time Series Line Chart**
![image](https://github.com/user-attachments/assets/2e02e75a-79ac-4ae1-bdbd-c3c14e30bbee)

Now on Superset 4.0, we use the  newer `Line Chart` but using the same time column uses this query which appears to throw an error 

`SELECT
  CAST(DATE_TRUNC(
    'QUARTER',
    CAST(DATETIMECONVERT(incident_date_epoch, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:MILLISECONDS') AS TIMESTAMP)
  ) AS TIMESTAMP) AS incident_date_epoch,
  COUNT(DISTINCT report_id) AS "COUNT_DISTINCT(report_id)"
FROM "default".incident_reports
GROUP BY
  CAST(DATE_TRUNC(
    'QUARTER',
    CAST(DATETIMECONVERT(incident_date_epoch, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:MILLISECONDS') AS TIMESTAMP)
  ) AS TIMESTAMP)
ORDER BY
  COUNT(DISTINCT report_id) DESC
LIMIT 10000;`

**Error**
![image](https://github.com/user-attachments/assets/adb4d082-0e9d-4a92-8f96-d9a3c5a5d966)

# Workarounds
I was able to workaround this doing 2 things, which are still not ideal

## Workaround 1
I can make a calculated column in Superset for each epoch_ms field im using, in which i set `Data Type` to DATETIME and `Date Time Format` as %Y-%m-%d %H:%M:%S.%f and have the SQL expression ToDateTime(my_epoch_ms_column, 'yyyy-MM-dd') 
![image](https://github.com/user-attachments/assets/d54f0bee-c227-45a4-8509-b06e1ca937f4)

Which will finally successfully plot on the Line Chart
![image](https://github.com/user-attachments/assets/1f220ce7-f94b-4b2f-bcec-158119833db3)

which produces this SQL query
`SELECT
  CAST(DATE_TRUNC('DAY', CAST(TODATETIME(incident_date_epoch, 'yyyy-MM-dd') AS TIMESTAMP)) AS TIMESTAMP) AS parsed_incident_date_epoch,
  COUNT(DISTINCT report_id) AS "COUNT_DISTINCT(report_id)"
FROM "default".incident_reports
GROUP BY
  CAST(DATE_TRUNC('DAY', CAST(TODATETIME(incident_date_epoch, 'yyyy-MM-dd') AS TIMESTAMP)) AS TIMESTAMP)
ORDER BY
  COUNT(DISTINCT report_id) DESC
LIMIT 10000;`

## Workaround 2
It appears that simply renaming the time column in the chart itself will finally get the chart to plot, although the format still looks ugly

![image](https://github.com/user-attachments/assets/648b0167-a774-4821-a64d-9fd29e5e5e9d)

Which produces SQL query
`SELECT
  CAST(DATE_TRUNC(
    'DAY',
    CAST(DATETIMECONVERT(incident_date_epoch, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:MILLISECONDS') AS TIMESTAMP)
  ) AS TIMESTAMP) AS "Incident Date Epoch",
  COUNT(DISTINCT report_id) AS "COUNT_DISTINCT(report_id)"
FROM "default".incident_reports
GROUP BY
  CAST(DATE_TRUNC(
    'DAY',
    CAST(DATETIMECONVERT(incident_date_epoch, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:MILLISECONDS') AS TIMESTAMP)
  ) AS TIMESTAMP)
ORDER BY
  COUNT(DISTINCT report_id) DESC
LIMIT 10000;`

# Other Threads
I've seen these other issues which dont appear to have a clear resolution to the issue im describing
- https://github.com/apache/superset/issues/25749
- https://github.com/apache/superset/pull/26906

### How to reproduce the bug

1. Have a Pinot dataset in which you have a time column formatted in epoch_ms
2. Make sure that in your Dataset, you've set the column as temporal and formatted as `epoch_ms`
3. Build a Line Chart in which you select the epoch_ms time column as the time column
4. Pick any other field as your metric just to get something to plot
5. You should see the error

### Superset version

master / latest-dev

### Python version

3.10

### Node version

I don't know

### Browser

Chrome

### Additional context

This is the logs I see in superset when trying the line chart presented in my issues

Traceback (most recent call last):
  File "/app/superset/connectors/sqla/models.py", line 1724, in query
    df = self.database.get_df(
  File "/app/superset/models/core.py", line 677, in get_df
    self.db_engine_spec.execute(cursor, sql_, self)
  File "/app/superset/db_engine_specs/base.py", line 1828, in execute
    raise cls.get_dbapi_mapped_exception(ex) from ex
  File "/app/superset/db_engine_specs/base.py", line 1824, in execute
    cursor.execute(query)
  File "/usr/local/lib/python3.10/site-packages/pinotdb/db.py", line 44, in g
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pinotdb/db.py", line 312, in execute
    raise exceptions.DatabaseError(msg)
pinotdb.exceptions.DatabaseError: {'errorCode': 150,
 'message': 'SQLParsingError:\n'
            'org.apache.pinot.sql.parsers.SqlCompilationException: '
            "'as(cast(datetrunc('DAY', "
            "cast(datetimeconvert(incident_date_epoch, '1:MILLISECONDS:EPOCH', "
            "'1:MILLISECONDS:EPOCH', '1:MILLISECONDS'), 'TIMESTAMP')), "
            "'TIMESTAMP'), incident_date_epoch)' should appear in GROUP BY "
            'clause.\n'
            '\tat '
            'org.apache.pinot.sql.parsers.CalciteSqlParser.validateGroupByClause(CalciteSqlParser.java:191)\n'
            '\tat '
            'org.apache.pinot.sql.parsers.CalciteSqlParser.validate(CalciteSqlParser.java:174)\n'
            '\tat '
            'org.apache.pinot.sql.parsers.CalciteSqlParser.queryRewrite(CalciteSqlParser.java:550)\n'
            '\tat '
            'org.apache.pinot.sql.parsers.CalciteSqlParser.compileSqlNodeToPinotQuery(CalciteSqlParser.java:484)'}

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by anthony-df-nguyen** [comment]
Update to this thread is that it appears to happen with other normal timestamp fields as well, not just `epoch_ms`

Pic 1: My `day` field is a string in format %Y-%m-%d
![image](https://github.com/user-attachments/assets/28f61239-3d27-41af-9d2e-cb9e6aeba105)

Pic 2: Bar chart cant aggregate the `day` field properly
![image](https://github.com/user-attachments/assets/d5e7248a-73c6-4254-a2f2-8d4dd46e0bfc)


I tried both Workaround 1 and 2 in my original message and this fixed it.

Workaround 1. Forcing the X-axis to have another title got it to plot
![image](https://github.com/user-attachments/assets/25e425af-b640-4718-8342-f331307aed76)

Workaround 2. Making a calculated column without any transformations fixes it
Calculated Column
![image](https://github.com/user-attachments/assets/b33f9931-6abd-47ac-ab26-0a8a126d1b7d)

Working Chart
![image](https://github.com/user-attachments/assets/6fa6203b-7d74-4c51-bf04-779ef94e92d3)

**Comment by anthony-df-nguyen** [comment]
@villebro Hello, im looking to see if you have any realistic estimation of when this can be looked at. Sorry if im tagging the wrong person, I just saw you on https://github.com/apache/superset/pull/26906 so I figured you might be the best person to ask.

**Comment by villebro** [comment]
Ping @michael-s-molina @sadpandajoe as you're the release managers for 4.0 and 4.1 respectively

**Comment by anthony-df-nguyen** [comment]
Thank you @villebro @sadpandajoe .
Is the fix https://github.com/apache/superset/pull/31341 going to end up in a `4.1.2` release? How frequently do those patch versions get released?

**Comment by villebro** [comment]
@anthony-df-nguyen yes, the mentioned fix is already cherry-picked into the 4.1 branch, and should thus be available when 4.1.2 comes out. I believe the plan is to cut 4.1.2 shortly after 5.0.0 is released.
