### ISSUE TITLE
Database Locks are accumulating in the Superset database up to 'sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached'

### ISSUE THREAD

**Issue by dervish54** [apache/superset#30286]
### Bug description

I guess the following issues are related to each other:

1. Superset regularly crashes with the `error: sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00`. 

2. Database Locks are accumulating in the Superset database. Here is an example:
```
Current locks: 124
waitstart, locktype, relation::regclass, mode, objsubid, granted
(None, 'relation', 'pg_stat_activity', 'AccessShareLock', None, True)
(None, 'relation', 'pg_locks', 'AccessShareLock', None, True)
(None, 'virtualxid', None, 'ExclusiveLock', None, True)
(None, 'relation', 'ab_user', 'AccessShareLock', None, True)
(None, 'relation', 'ab_view_menu_name_key', 'AccessShareLock', None, True)
(None, 'relation', 'ab_view_menu_pkey', 'AccessShareLock', None, True)
<...>
```

3. Importing charts and dashboards does not work When trying to import charts and dashboards to a new Superset server with the same configuration (except for the password and secret key), I get an error.

4. The version in the Settings dropdown is shown as "Version: 0.0.0-dev". I am sure this should not be the case.

### How to reproduce the bug

1. `git clone --depth=1 https://github.com/apache/superset.git`
2. `cd superset`
3.  make changes to docker/.env: `POSTGRES_PASSWORD`, `DATABASE_PASSWORD`, `SUPERSET_LOAD_EXAMPLES=no` and `SUPERSET_SECRET_KEY`
4. docker compose -f docker-compose-non-dev.yml up -d
5. Login and face problems from the list above.

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/67cc1788-b882-491e-8b23-5ee615d7f237)

![image](https://github.com/user-attachments/assets/650a7edd-2457-46ec-a012-7d55f69ca2ac)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

```
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
superset_app          |     fairy = _ConnectionRecord.checkout(pool)
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
superset_app          |     rec = pool._do_get()
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
superset_app          |     raise exc.TimeoutError(
superset_app          | sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
superset_app          | 2024-09-10 13:04:48,939:ERROR:superset.views.error_handling:QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Can't say I've run into this one. Assigning to @betodealmeida, but curious if @villebro or @mistercrunch have any advice here.

**Comment by mistercrunch** [comment]
Which version is this on? latest master?

**Comment by dervish54** [comment]
@mistercrunch 
> Which version is this on? latest master?

Yes:
```
~/superset# git branch
* master
```

The repository was cloned on September 11. I followed this instruction https://superset.apache.org/docs/installation/docker-compose/#installing-superset-locally-using-docker-compose

**Comment by mistercrunch** [comment]
Did you git pull since then, master mais not be fully stable at all time and I think there may be a recent fix.

**Comment by dervish54** [comment]
@mistercrunch 
When testing the export-import of dashboards between different instances of Superset, I raised another one in a similar way, it was 4-5 days ago. The same problem was observed in that new instance. 
Now I'm thinking about using earlier versions. Is there any advice on which version to prefer according to the stability criterion?

**Comment by mistercrunch** [comment]
Here's the PR you want to make sure is in your branch, landed last week and should fix a regression around transaction isolation / lock. You can check with `git log` whether it was in there or not.
https://github.com/apache/superset/pull/30174

Latest official stable release is 4.0.2, so you can `git checkout 4.0.2` if you prefer, and there's `4.1.0rc3` too if you want to make sure the issues you are reporting are going to be fixed in `4.1.0`

**Comment by villebro** [comment]
Beyond the fix above, It's a good idea to make sure your `SQLALCHEMY_ENGINE_OPTIONS` has a necessarily big `pool_size` + `max_overflow` to facilitate for all gunicorn threads. Say you have 20 gunicorn threads, your combined `pool_size` and `max_overflow` should not be less than 20 to ensure there's sufficient connections in the pool during high load.

**Comment by sfirke** [comment]
Thanks all.  I ran into this on one of the instances I admin, it's running Superset 4.0.2 and yesterday I ran into a chart loading error that said "QueuePool limit of size 5 overflow 10 reached".  I did not know about `SQLALCHEMY_ENGINE_OPTIONS` and will set that to bump up the `pool_size` per the recommendations above.

**Comment by rusackas** [comment]
This has been silent for quite a while... sounds like it's closeable?

**Comment by villebro** [comment]
Small addition: a quick fix is to set `max_overflow` to -1. This will ensure that you never run out of connections. But do keep in mind that if your `pool_size` is low compared to the thread count, you may hit performance issues due to overflowing connections opening and closing.

I propose we either set max overflow to -1 by default, or add a note to the docs about this. @sfirke @rusackas @mistercrunch thoughts?

**Comment by rusackas** [comment]
Should we oen that PR to set max_overflow to -1 by default? I think that came up on another issue as well.

**Comment by rusackas** [comment]
This was on a master clone from September 2024, and a likely-related fix landed shortly after. Could you re-test on a current tagged release (5.x) and share your pool settings? If it no longer reproduces we'll close this out.

**Comment by rusackas** [comment]
Closing since the likely regression fix (#30174) landed already, remaining reports trace to undersized SQLALCHEMY_ENGINE_OPTIONS pool settings (deployment config), and a June 2026 re-test request got no response.
