### ISSUE TITLE
Seeing a bug with csv or text alerts on 3.0.0rc1, which were working fine on 2.1.0. - Same issue version 4.0.2

### ISSUE THREAD

**Issue by tamarinkeisari** [apache/superset#30368]
Seeing a bug with csv or text alerts on 3.0.0rc1, which were working fine on 2.1.0. 
![image](https://github.com/apache/superset/assets/29596014/58146b12-376a-4c83-b345-0aed7a117615)
PNG is working fine on 3.0.0rc1 (which rules out auth/selenium issues), but CSV and text are failing with:
```
A downstream exception occurred while generating a report: b056bed4-ff76-4e1d-aa0f-0fa7751d3542. Failed generating csv HTTP Error 400: BAD REQUEST
Traceback (most recent call last):
  File "/app/superset/reports/commands/execute.py", line 262, in _get_csv_data
    csv_data = get_chart_csv_data(chart_url=url, auth_cookies=auth_cookies)
  File "/app/superset/utils/csv.py", line 91, in get_chart_csv_data
    response = opener.open(chart_url)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: BAD REQUEST
```

_Originally posted by @padbk in https://github.com/apache/superset/discussions/24581#discussioncomment-6425918_

I'm encountering the same error in superset version 4.0.2,
Can someone please help?

**Comment by sfirke** [comment]
Would you mind creating a new bug report that follows the template?  That would make this a more actionable bug report.  Right now all the info is from an old comment and that comment was addressed by a pull request already.  So it would be helpful if you can describe steps to reproduce this problem in 4.0.2.

If you do so, you can close this bug report and comment with a link to the new one.

**Comment by LJNIC** [comment]
Did you ever solve this? I'm having the same issue, and this is the only reference I can find. :(

**Comment by rusackas** [comment]
I'm a little stumped here, and it's a pretty ancient issue. Is anyone able to reproduce this (and tell us how to) in 4.1.1/4.1.2 or 5.0.0rc1?

**Comment by rusackas** [comment]
5.0.0 is out... would love to know if it's still an issue there. If we don't hear back, this will be closed.

**Comment by padbk** [comment]
No issue for me on 5.0.0

**Comment by rusackas** [comment]
Per @padbk's comment, this appears to be resolved in Superset 5.0.0. Closing as fixed.
