### ISSUE TITLE
Superset Failing to Generate Thumbnails in Docker Compose Environment

### ISSUE THREAD

**Issue by mschaefer-gresham** [apache/superset#30372]
### Bug description

I've enabled thumbnails within the docker compose environment and I am getting this error repeating in the log on startup.

```
superset_worker       | [2024-09-24 09:09:40,506: INFO/ForkPoolWorker-1] Task cache_chart_thumbnail[62684bb1-a0c5-4c20-ba6a-6f522004edbf] succeeded in 1.1576069999864558s: None
superset_worker       | [2024-09-24 09:09:40,508: INFO/MainProcess] Task cache_chart_thumbnail[5859cfc0-e68a-4cc4-a9f0-2b5a30a77cc7] received
superset_worker       | [2024-09-24 09:09:40,510: INFO/ForkPoolWorker-1] Caching chart: http://superset:8088/superset/slice/1305/
superset_worker       | [2024-09-24 09:09:40,511: INFO/ForkPoolWorker-1] Processing url for thumbnail: bd0c91566fdc6a685058e6c065151327
superset_worker       | [2024-09-24 09:09:40,511: DEBUG/ForkPoolWorker-1] Init selenium driver
superset_worker       | [2024-09-24 09:09:41,552: WARNING/ForkPoolWorker-2] Failed at generating thumbnail Message: Process unexpectedly closed with status signal
superset_worker       | Traceback (most recent call last):
superset_worker       |   File "/app/superset/utils/screenshots.py", line 170, in compute_and_cache
superset_worker       |     payload = self.get_screenshot(user=user, window_size=window_size)
superset_worker       |   File "/app/superset/utils/screenshots.py", line 93, in get_screenshot
superset_worker       |     self.screenshot = driver.get_screenshot(self.url, self.element, user)
superset_worker       |   File "/app/superset/utils/webdriver.py", line 354, in get_screenshot
superset_worker       |     driver = self.auth(user)
superset_worker       |   File "/app/superset/utils/webdriver.py", line 276, in auth
superset_worker       |     driver = self.create()
superset_worker       |   File "/app/superset/utils/webdriver.py", line 273, in create
superset_worker       |     return driver_class(**kwargs)
superset_worker       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
superset_worker       |     RemoteWebDriver.__init__(
superset_worker       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
superset_worker       |     self.start_session(capabilities, browser_profile)
superset_worker       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
superset_worker       |     response = self.execute(Command.NEW_SESSION, parameters)
superset_worker       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
superset_worker       |     self.error_handler.check_response(response)
superset_worker       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
superset_worker       |     raise exception_class(message, screen, stacktrace)
superset_worker       | selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status signal
```

What am I missing?

### How to reproduce the bug

Enable thumbnails feature flag. 

### Superset version

master / latest-dev

### Python version

3.9

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mschaefer-gresham** [comment]
@dosu this did not solve the issue.

**Comment by mschaefer-gresham** [comment]
@duso 

1. I verified that redis is running and that I can ping it using the cli.
2. The logs indicate that celery has started successfully.
3. The WEBDRIVER_BASEURL is correct.
4. I am using the default firefox driver and using the following settings:
```
WEBDRIVER_OPTION_ARGS = [
        "--force-device-scale-factor=2.0",
        "--high-dpi-support=2.0",
        "--headless",
        "--disable-gpu",
        "--disable-dev-shm-usage",
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-extensions",
        ]
```
5. There are no issues in the logs other than the error reported in my original post.

**Comment by mschaefer-gresham** [comment]
After much digging around and trying chrome, I suspect the issue is that I'm running docker compose on a Mac M3. It appears the chromedriver and firefox executables won't run on M series.

```
docker exec -it superset_worker bash
root@413ee2048953:/app# cd /usr/local/bin
root@413ee2048953:/usr/local/bin# chromedriver
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
 Trace/breakpoint trap
root@413ee2048953:/usr/local/bin# firefox
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
 Trace/breakpoint trap
```

**Comment by mschaefer-gresham** [comment]
This was caused due to running docker compose on Mac M3. chrome and firefix executables won't run on Apple Silicon Macs. When running on an Intel Mac it started working.

**Comment by sfirke** [comment]
Interesting, thank you @mschaefer-gresham for diagnosing the problem and reporting back!
