### ISSUE TITLE
slack sharing - file.upload api deprecated

### ISSUE THREAD

**Issue by amaurydacosta** [apache/superset#30439]
### Bug description

As of May 8, 2024, new superset-slack connections require use of new slack file upload api endpoint. Trying to share reports via slack using a slack app connection created after May 8 will generate this error:
The request to the Slack API failed. (url: https://www.slack.com/api/files.upload) The server responded with: {'ok': False, 'error': 'method_deprecated'}

per slack:
https://api.slack.com/methods/files.upload#markdown

`files.upload is deprecated and will stop functioning on March 11, 2025. Use [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) and [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal) to upload files instead. Newly created apps will be unable to use files.upload beginning May 8, 2024. See [Uploading files](https://api.slack.com/messaging/files#uploading_files) for more details on the process and [this changelog](https://api.slack.com/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay) for more on the deprecation.`

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by amaurydacosta** [comment]
thanks, looks like we are running version 4.0.2-dev.

**Comment by sadpandajoe** [comment]
This will be resolved with the 4.1 release with https://github.com/apache/superset/pull/28783. Feel free to test out on 4.1.0rc2 to see if this is resolved for you.

**Comment by VMRuiz** [comment]
Hello @sadpandajoe , I'm still getting this error in 4.1.0rc3. 


```
SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR │
A downstream warning occurred while generating a report: 1b228256-dfa9-46d0-803e-def947a116b1. [SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.WARNING: 'warning'>, extra=None)]
 
Traceback (most recent call last): 

File "/app/superset/tasks/scheduler.py", line 95, in execute                                                                                                                                                                                                                         ).run()
File "/app/superset/utils/decorators.py", line 266, in wrapped
  return on_error(ex)
File "/app/superset/utils/decorators.py", line 236, in on_error                                                                                                                                                                                                                         
 raise ex
File "/app/superset/utils/decorators.py", line 259, in wrapped                                                                                                                                                                                                                                
  result = func(*args, **kwargs)                                                                                                                                                                                                                                                              File "/app/superset/commands/report/execute.py", line 797, in run                                                                                                                                                                                                                               
   ).run()
File "/app/superset/utils/decorators.py", line 266, in wrapped                                                                                                                                                                                                                                
  return on_error(ex)                                                                                                                                                                                                                                                                         
File "/app/superset/utils/decorators.py", line 236, in on_error                                                                                                                                                                                                                               
  raise ex
File "/app/superset/utils/decorators.py", line 259, in wrapped                                                                                                                                                                                                                                
  result = func(*args, **kwargs)                                                                                                                                                                                                                                                              
File "/app/superset/commands/report/execute.py", line 759, in run                                                                                                                                                                                                                             
  ).next()
File "/app/superset/commands/report/execute.py", line 627, in next                                                                                                                                                                                                                            
  self.send()                                                                                                                                                                                                                                                                                 
File "/app/superset/commands/report/execute.py", line 527, in send                                                                                                                                                                                                                            
  self._send(notification_content, self._report_schedule.recipients)                                                                                                                                                                                                                          
File "/app/superset/commands/report/execute.py", line 518, in _send                                                                                                                                                                                                                           
  raise ReportScheduleClientErrorsException(errors=notification_errors)                                                                                                                                                                                                                       

superset.commands.report.exceptions.ReportScheduleClientErrorsException: [SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR: 'REPORT_NOTIFICATION_ERROR'>, level=<ErrorLevel.WARNING: 'warning'>, extra=None)] 
```

**Comment by sadpandajoe** [comment]
@VMRuiz do you have the feature flag `ALERT_REPORT_SLACK_V2` turned on in your instance?

**Comment by sadpandajoe** [comment]
@VMRuiz what's the log say after you turned it on. It should be using the apiv2 path

**Comment by sadpandajoe** [comment]
@eschutho do you remember any other settings that might be needed to get slack working on the new api?

**Comment by VMRuiz** [comment]
Another check to make sure the flags were actually loaded:

```python
root@worker-6pqg42:/app/pythonpath# superset shell
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
2024-10-24 07:16:38,805:INFO:superset.initialization:Setting database isolation level to READ COMMITTED
/usr/local/lib/python3.10/site-packages/flask_limiter/extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
Python 3.10.15 (main, Sep 27 2024, 06:07:40) [GCC 12.2.0] on linux
App: superset.app
Instance: /app/instance
>>> from superset import get_feature_flags
>>> import json; print(json.dumps(get_feature_flags(), indent=2))
{
  "DRUID_JOINS": false,
  "DYNAMIC_PLUGINS": false,
  "DISABLE_LEGACY_DATASOURCE_EDITOR": true,
  "ENABLE_TEMPLATE_PROCESSING": false,
  "ENABLE_JAVASCRIPT_CONTROLS": false,
  "KV_STORE": false,
  "PRESTO_EXPAND_DATA": false,
  "THUMBNAILS": false,
  "SHARE_QUERIES_VIA_KV_STORE": false,
  "TAGGING_SYSTEM": false,
  "SQLLAB_BACKEND_PERSISTENCE": true,
  "LISTVIEWS_DEFAULT_CARD_VIEW": false,
  "ESCAPE_MARKDOWN_HTML": false,
  "DASHBOARD_CROSS_FILTERS": true,
  "DASHBOARD_VIRTUALIZATION": true,
  "GLOBAL_ASYNC_QUERIES": false,
  "EMBEDDED_SUPERSET": false,
  "ALERT_REPORTS": true,
  "ALERT_REPORT_TABS": false,
  "ALERT_REPORT_SLACK_V2": true,
  "DASHBOARD_RBAC": false,
  "ENABLE_ADVANCED_DATA_TYPES": false,
  "ALERTS_ATTACH_REPORTS": true,
  "ALLOW_FULL_CSV_EXPORT": false,
  "ALLOW_ADHOC_SUBQUERY": false,
  "USE_ANALAGOUS_COLORS": false,
  "RLS_IN_SQLLAB": false,
  "IMPERSONATE_WITH_EMAIL_PREFIX": false,
  "CACHE_IMPERSONATION": false,
  "CACHE_QUERY_BY_USER": false,
  "EMBEDDABLE_CHARTS": true,
  "DRILL_TO_DETAIL": true,
  "DRILL_BY": true,
  "DATAPANEL_CLOSED_BY_DEFAULT": false,
  "HORIZONTAL_FILTER_BAR": false,
  "ESTIMATE_QUERY_COST": false,
  "SSH_TUNNELING": false,
  "AVOID_COLORS_COLLISION": true,
  "MENU_HIDE_USER_INFO": false,
  "ENABLE_SUPERSET_META_DB": false,
  "PLAYWRIGHT_REPORTS_AND_THUMBNAILS": false,
  "CHART_PLUGINS_EXPERIMENTAL": false,
  "SQLLAB_FORCE_RUN_ASYNC": false,
  "ENABLE_FACTORY_RESET_COMMAND": false,
  "SLACK_ENABLE_AVATARS": false
}
```

I can see the code with the fix is there too : 

```
root@worker-6pqg42:/app/superset/reports# grep "files_upload_v2" -R .
./notifications/slackv2.py:                        client.files_upload_v2(
```

So, the fix was actually included in 4.1.0rc3 but I'm not able to get superset to use it instead of v1.

**Comment by eschutho** [comment]
@amaurydacosta do you see an info level log: `Slack API v2 is available`?

**Comment by VMRuiz** [comment]
Hello @eschutho , I guess your message was addressed to me? 

This is all I get in the logs when starting the main service

```
│ Requirement already satisfied: redis==4.6.0 in /usr/local/lib/python3.10/site-packages (4.6.0)                                                                                                                                                                                                  │
│ Collecting sqlalchemy-bigquery==1.7.0                                                                                                                                                                                                                                                           │
│   Downloading sqlalchemy_bigquery-1.7.0-py2.py3-none-any.whl.metadata (13 kB)                                                                                                                                                                                                                   │
│ Requirement already satisfied: async-timeout>=4.0.2 in /usr/local/lib/python3.10/site-packages (from redis==4.6.0) (5.0.0)                                                                                                                                                                      │
│ Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.10/site-packages (from sqlalchemy-bigquery==1.7.0) (2.11.0)                                                                                                          │
│ Requirement already satisfied: google-auth<3.0.0dev,>=1.25.0 in /usr/local/lib/python3.10/site-packages (from sqlalchemy-bigquery==1.7.0) (2.29.0)                                                                                                                                              │
│ Requirement already satisfied: google-cloud-bigquery<4.0.0dev,>=2.25.2 in /usr/local/lib/python3.10/site-packages (from sqlalchemy-bigquery==1.7.0) (3.20.1)                                                                                                                                    │
│ Requirement already satisfied: packaging in /usr/local/lib/python3.10/site-packages (from sqlalchemy-bigquery==1.7.0) (23.2)                                                                                                                                                                    │
│ Requirement already satisfied: sqlalchemy<2.0.0dev,>=1.2.0 in /usr/local/lib/python3.10/site-packages (from sqlalchemy-bigquery==1.7.0) (1.4.52)                                                                                                                                                │
│ Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /usr/local/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery==1.7.0) (1.63.0)                                                                │
│ Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /usr/local/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery==1.7.0) (4.23.0)      │
│ Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery==1.7.0) (2.32.2)                                                                              │
│ Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/site-packages (from google-auth<3.0.0dev,>=1.25.0->sqlalchemy-bigquery==1.7.0) (5.3.3)                                                                                                                       │
│ Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/site-packages (from google-auth<3.0.0dev,>=1.25.0->sqlalchemy-bigquery==1.7.0) (0.4.0)                                                                                                                        │
│ Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/site-packages (from google-auth<3.0.0dev,>=1.25.0->sqlalchemy-bigquery==1.7.0) (4.9)                                                                                                                                  │
│ Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /usr/local/lib/python3.10/site-packages (from google-cloud-bigquery<4.0.0dev,>=2.25.2->sqlalchemy-bigquery==1.7.0) (2.3.2)                                                                                                 │
│ Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /usr/local/lib/python3.10/site-packages (from google-cloud-bigquery<4.0.0dev,>=2.25.2->sqlalchemy-bigquery==1.7.0) (2.7.0)                                                                                              │
│ Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /usr/local/lib/python3.10/site-packages (from google-cloud-bigquery<4.0.0dev,>=2.25.2->sqlalchemy-bigquery==1.7.0) (2.9.0.post0)                                                                                               │
│ Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/site-packages (from sqlalchemy<2.0.0dev,>=1.2.0->sqlalchemy-bigquery==1.7.0) (3.0.3)                                                                                                                               │
│ Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery<4.0.0dev,>=2.25.2->sqlalchemy-bi │
│ gquery==1.7.0) (1.62.1)                                                                                                                                                                                                                                                                                                      │
│ Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in /usr/local/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery<4.0.0dev,>=2.25.2->sqlalc │
│ hemy-bigquery==1.7.0) (1.60.1)                                                                                                                                                                                                                                                                                               │
│ Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<4.0.0dev,>=2.25.2->sqlalchemy-bigquery==1.7.0) (1.5.0)                                                                  │
│ Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.25.0->sqlalchemy-bigquery==1.7.0) (0.6.0)                                                                                                  │
│ Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/site-packages (from python-dateutil<3.0dev,>=2.7.2->google-cloud-bigquery<4.0.0dev,>=2.25.2->sqlalchemy-bigquery==1.7.0) (1.16.0)                                                                                          │
│ Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery==1.7.0) (3.3.2)                                                     │
│ Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery==1.7.0) (3.7)                                                                   │
│ Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery==1.7.0) (1.26.18)                                                         │
│ Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery==1.7.0) (2024.2.2)                                                        │
│ Downloading sqlalchemy_bigquery-1.7.0-py2.py3-none-any.whl (33 kB)                                                                                                                                                                                                                              │
│ Installing collected packages: sqlalchemy-bigquery                                                                                                                                                                                                                                              │
│   Attempting uninstall: sqlalchemy-bigquery                                                                                                                                                                                                                                                     │
│     Found existing installation: sqlalchemy-bigquery 1.11.0                                                                                                                                                                                                                                     │
│     Uninstalling sqlalchemy-bigquery-1.11.0:                                                                                                                                                                                                                                                    │
│       Successfully uninstalled sqlalchemy-bigquery-1.11.0                                                                                                                                                                                                                                       │
│ Successfully installed sqlalchemy-bigquery-1.7.0                                                                                                                                                                                                                                                │
│ WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-acti │
│ on option if you know what you are doing and want to suppress this warning.                                                                                                                                                                                                                                                  │
│ [2024-11-04 05:02:18 +0000] [12] [INFO] Starting gunicorn 22.0.0                                                                                                                                                                                                                                │
│ [2024-11-04 05:02:18 +0000] [12] [INFO] Listening at: http://0.0.0.0:8088 (12)                                                                                                                                                                                                                  │
│ [2024-11-04 05:02:18 +0000] [12] [INFO] Using worker: gthread                                                                                                                                                                                                                                   │
│ [2024-11-04 05:02:18 +0000] [13] [INFO] Booting worker with pid: 13                                                                                                                                                                                                                             │
│ Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]                                                                                                                                                                                                                         │
│ 2024-11-04 05:02:20,548:INFO:superset.initialization:Setting database isolation level to READ COMMITTED                                                                                                                                                                                         │
│ /usr/local/lib/python3.10/site-packages/flask_limiter/extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-b │
│ ackend for documentation about configuring the storage backend.                                                                                                                                                                                                                                                              │
│   warnings.warn(                                                                                                                                                                                                                                                                                │
```

Also, these are the worker logs when I tried to run the alert: 

```
│2024-11-04 04:55:52,723: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine                                                           │
│hether broker connection retries are made during startup in Celery 6.0 and above.                                                                                                                                                                                                              │
│f you wish to retain the existing behavior for retrying connections on startup,                                                                                                                                                                                                                │
│ou should set broker_connection_retry_on_startup to True.                                                                                                                                                                                                                                      │
│ warnings.warn(                                                                                                                                                                                                                                                                                │
│                                                                                                                                                                                                                                                                                               │
│2024-11-04 04:59:21,829: WARNING/ForkPoolWorker-8] Your current Slack scopes are missing `channels:read`. Please add                                                                                                                                                                           │
│           this to your Slack app in order to continue using the v1 API. Support                                                                                                                                                                                                               │
│           for the old Slack API will be removed in Superset version 6.0.0.                                                                                                                                                                                                                    │
│2024-11-04 04:59:21,830: WARNING/ForkPoolWorker-8] /usr/local/lib/python3.10/site-packages/slack_sdk/web/internal_utils.py:422: UserWarning: client.files_upload() may cause some issues like timeouts for relatively large files. Our latest recommendation is to use client.files_upload_v2( │
│ warnings.warn(message)                                                                                                                                                                                                                                                                        │
│                                                                                                                                                                                                                                                                                               │
│2024-11-04 04:59:22,046: WARNING/ForkPoolWorker-8] SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REPORT_NOTIFICATION_ERROR │
│2024-11-04 04:59:23,076: WARNING/ForkPoolWorker-8] A downstream warning occurred while generating a report: 28693fcf-4cd5-4569-9851-b225ddeba9ca. [SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok' │
│raceback (most recent call last):                                                                                                                                                                                                                                                              │
│ File "/app/superset/tasks/scheduler.py", line 95, in execute                                                                                                                                                                                                                                  │
│   ).run()                                                                                                                                                                                                                                                                                     │
│ File "/app/superset/utils/decorators.py", line 266, in wrapped                                                                                                                                                                                                                                │
│   return on_error(ex)                                                                                                                                                                                                                                                                         │
│ File "/app/superset/utils/decorators.py", line 236, in on_error                                                                                                                                                                                                                               │
│   raise ex                                                                                                                                                                                                                                                                                    │
│ File "/app/superset/utils/decorators.py", line 259, in wrapped                                                                                                                                                                                                                                │
│   result = func(*args, **kwargs)                                                                                                                                                                                                                                                              │
│ File "/app/superset/commands/report/execute.py", line 797, in run                                                                                                                                                                                                                             │
│   ).run()                                                                                                                                                                                                                                                                                     │
│ File "/app/superset/utils/decorators.py", line 266, in wrapped                                                                                                                                                                                                                                │
│   return on_error(ex)                                                                                                                                                                                                                                                                         │
│ File "/app/superset/utils/decorators.py", line 236, in on_error                                                                                                                                                                                                                               │
│   raise ex                                                                                                                                                                                                                                                                                    │
│ File "/app/superset/utils/decorators.py", line 259, in wrapped                                                                                                                                                                                                                                │
│   result = func(*args, **kwargs)                                                                                                                                                                                                                                                              │
│ File "/app/superset/commands/report/execute.py", line 759, in run                                                                                                                                                                                                                             │
│   ).next()                                                                                                                                                                                                                                                                                    │
│ File "/app/superset/commands/report/execute.py", line 627, in next                                                                                                                                                                                                                            │
│   self.send()                                                                                                                                                                                                                                                                                 │
│ File "/app/superset/commands/report/execute.py", line 527, in send                                                                                                                                                                                                                            │
│   self._send(notification_content, self._report_schedule.recipients)                                                                                                                                                                                                                          │
│ File "/app/superset/commands/report/execute.py", line 518, in _send                                                                                                                                                                                                                           │
│   raise ReportScheduleClientErrorsException(errors=notification_errors)                                                                                                                                                                                                                       │
│uperset.commands.report.exceptions.ReportScheduleClientErrorsException: [SupersetError(message="The request to the Slack API failed. (url: https://www.slack.com/api/files.upload)\nThe server responded with: {'ok': False, 'error': 'method_deprecated'}", error_type=<SupersetErrorType.REP │
``` 

I can't find any mention to Slack beyond the error logs above.

**Comment by sadpandajoe** [comment]
@VMRuiz oh, that is the issue. You'll need to add that permission to start using v2. It's a blurb in the release log: https://github.com/apache/superset/tree/4.1/RELEASING/release-notes-4-1
