### ISSUE TITLE
Deletion from tagged_objects fails with multiple tags

### ISSUE THREAD

**Issue by saraburns1** [apache/superset#30494]
### Bug description

If there are multiple tags for a dataset and the dataset is deleted, the 'after_delete' action fails because it attempts to delete more than 1 row.

1. Create dataset with multiple tags
![image](https://github.com/user-attachments/assets/b14b6303-3b38-4185-8330-d54d390bd024)
2. Run `DeleteDatasetCommand([804])`
3. Failure: ```
Traceback (most recent call last):
  File "/app/superset/daos/base.py", line 217, in delete
    db.session.commit()
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1435, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3367, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3507, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3467, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 577, in execute
    self.dependency_processor.process_deletes(uow, states)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/dependency.py", line 1110, in process_deletes
    self._run_crud(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/dependency.py", line 1207, in _run_crud
    raise exc.StaleDataError(
sqlalchemy.orm.exc.StaleDataError: DELETE statement on table 'tagged_object' expected to delete 1 row(s); Only 2 were matched.```

### Superset version

4.0.2

### Python version

3.11

### Node version

16

### Browser

Not applicable

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by saraburns1** [comment]
Is there a way to still use the DeleteCommands but have this work? If not, I would need to delete all tag rows before I can delete the chart/dataset, right?

**Comment by rusackas** [comment]
@eschutho @yousoph do we have anyone actively looking at bugs around tags still?

**Comment by SBIN2010** [comment]
There is a solution to this problem :https://github.com/apache/superset/pull/29117
