### ISSUE TITLE
Error while executing "superset db upgrade"

### ISSUE THREAD

**Issue by y2k3bikash** [apache/superset#30548]
### Bug description

Python Version: 3.10
OS: Ubuntu
Superset: apache-superset

1. Installed Virtual Environment
2. Activated It
3. pip install --upgrade pip setuptools wheel
4. pip install apache-superset
5. export FLASK_APP=superset
6. export SUPERSET_CONFIG_PATH=/superset_vir/lib/python3.9/site-packages/superset/config.py
7. Below Changes Done In Config.py:
        * update SECRET_KEY & SQLALCHEMY_DATABASE_URI(MySQL) as per the need .
        * Commented Below Line & Added Next 3 Lines:
        #override_conf = imp.load_source("superset_config", cfg_path)
        spec = importlib.util.spec_from_file_location("superset_config", cfg_path)
        override_conf = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(override_conf)

8. execute "superset db upgrade"

Got Below Error After That:

**superset db upgrade**

Failed to import config for SUPERSET_CONFIG_PATH=/superset_vir/lib/python3.10/site-packages/superset/config.py
Traceback (most recent call last):
  File "/superset_vir/lib/python3.10/site-packages/superset/config.py", line 1708, in <module>
    module = sys.modules[__name__]
KeyError: 'superset_config'
Failed to import config for SUPERSET_CONFIG_PATH=/superset_vir/lib/python3.10/site-packages/superset/config.py
Traceback (most recent call last):
  File "/superset_vir/lib/python3.10/site-packages/superset/config.py", line 1712, in <module>
    spec.loader.exec_module(override_conf)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/superset_vir/lib/python3.10/site-packages/superset/config.py", line 1708, in <module>
    module = sys.modules[__name__]
KeyError: 'superset_config'
Traceback (most recent call last):
  File "/superset_vir/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/superset_vir/lib/python3.10/site-packages/superset/cli/main.py", line 28, in <module>
    from superset.cli.lib import normalize_token
  File "/superset_vir/lib/python3.10/site-packages/superset/cli/lib.py", line 20, in <module>
    from superset import config
  File "/superset_vir/lib/python3.10/site-packages/superset/config.py", line 1712, in <module>
    spec.loader.exec_module(override_conf)
  File "/superset_vir/lib/python3.10/site-packages/superset/config.py", line 1708, in <module>
    module = sys.modules[__name__]
KeyError: 'superset_config'

### Superset version

master / latest-dev

### Python version

3.10

### Node version

Not applicable

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Sorry, this has gone silent for > 6 months, and seems like it's more of a config issue than a Superset bug. If you're still facing this in 4.1.2 or newer, let us know, and we can reopen it.

**Comment by y2k3bikash** [comment]
Yes, the problem still persists. Please guide me to the solution.


--
With Warm Regards
Bikash Kumar,
The Times Of India.
