### ISSUE TITLE
Embedded SDK seemingly ignoring most dashboardUIConfig options

### ISSUE THREAD

**Issue by apoteet** [apache/superset#30630]
### Bug description

We are using the embedded SDK for embedding, and it more or less works great. However, almost every dashboard configuration option seems to be ignored.

Here's our implementation:
```typescript
superset.embedDashboard({
  id: embeddableDashboardIds[0],
  supersetDomain: supersetDomain,
  mountPoint: elementRef.current,
  fetchGuestToken: () => Promise.resolve(guestToken),
  dashboardUiConfig: {
    hideTitle: true,
    hideTab: true,
    filters: {
      visible: true,
      expanded: true,
    },
  },
})
```

From the dashboardUiConfig options, I would expect us to have a table and nothing more, but the attached screenshot shows filters and no title (good), but visible tabs (no).
Hiding filters with visible/expanded: false doesn't actually work either.

When i pass `standalone=3`, this does remove everything as expected.
But standalone=1 and standalone=2 do nothing, even if i remove the dashboardUiConfig.

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/288799f7-a69f-47bf-a836-9beab3072e0a)

### Superset version

4.0.2

### Python version

I don't know

### Node version

18 or greater

### Browser

Chrome

### Additional context

We have these feature flags enabled:
"EMBEDDED_SUPERSET"
"EMBEDDABLE_CHARTS"
"HORIZONTAL_FILTER_BAR"

I can't say which logs are relevant, but i see two:
`2024-10-16 17:56:33,992:WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped`

```
2024-10-16 17:56:34,752:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
 
11:56:34.753
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
 
11:56:34.753
    rv = self.dispatch_request()
 
11:56:34.753
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1788, in dispatch_request
 
11:56:34.753
    self.raise_routing_exception(req)
 
11:56:34.753
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1770, in raise_routing_exception
 
11:56:34.753
    raise request.routing_exception  # type: ignore
 
11:56:34.753
  File "/usr/local/lib/python3.10/site-packages/flask/ctx.py", line 351, in match_request
 
11:56:34.753
    result = self.url_adapter.match(return_rule=True)  # type: ignore
 
11:56:34.753
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
 
11:56:34.753
    raise NotFound() from None
 
11:56:34.753
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Are you still facing any of these issues? I think much of this has been fixed in the last 6 months + that this has been silent.

**Comment by apoteet** [comment]
Would this be fixed by the embedded sdk or superset itself? I just bumped my sdk version and see the same issue. 
We haven't upgraded superset since this was opened, so TBH i couldn't tell you if that would fix it. We happened to get around the tabs issue due to a requirements change to make each tab a separate page and iframe

**Comment by bahriddin** [comment]
It is still an issue. I am on `ver. 4.1.2` and still can't hide filter bar. Workaround was to set `standalone: 3` in the `urlParams` (also [mentioned here](https://github.com/apache/superset/discussions/29955#discussioncomment-13514714))

**Comment by rusackas** [comment]
This is still confirmed on 4.1.2 as of June 2025. The workaround of using `standalone: 3` in URL params helps for some cases. If anyone can investigate why the Embedded SDK's `dashboardUIConfig` options aren't being respected and submit a PR, that would be very welcome.

**Comment by rusackas** [comment]
There was a real fix attempt at #39788 that traced this to `isReport` unconditionally hiding the filter bar regardless of `show_filters`/`dashboardUIConfig`, but it never merged. Still worth reviving from that diagnosis... taking a look now.
