### ISSUE TITLE
superset db upgrade not working

### ISSUE THREAD

**Issue by krishanthvs** [apache/superset#30641]
### Bug description

getting this error when running the superset db upgrade command.
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "extra": syntax error
[SQL: ALTER TABLE report_schedule RENAME extra TO extra_json]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

### Screenshots/recordings

Loaded your LOCAL configuration at [/home/ec2-user/superset/superset_config.py]
logging was configured successfully
2024-10-17 16:55:04,332:INFO:superset.utils.logging_configurator:logging was configured successfully
2024-10-17 16:55:04,339:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/flask_limiter/extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
WARNI [alembic.env] SQLite Database support for metadata databases will         be removed in a future version of Superset.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 409c7b420ab0 -> ffa79af61a56, rename report_schedule.extra to extra_json
Traceback (most recent call last):
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "extra": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/superset/superset/superset/superset-env/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset==4.0.2', 'console_scripts', 'superset')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/flask/cli.py", line 358, in decorator
    return __ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/flask_migrate/cli.py", line 149, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/flask_migrate/__init__.py", line 98, in wrapped
    f(*args, **kwargs)
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/flask_migrate/__init__.py", line 185, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/script/base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/superset/extensions/../migrations/env.py", line 127, in <module>
    run_migrations_online()
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/superset/extensions/../migrations/env.py", line 119, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/superset/migrations/versions/2022-07-11_11-26_ffa79af61a56_rename_report_schedule_extra_to_extra_.py", line 36, in upgrade
    op.alter_column(
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/operations/ops.py", line 1957, in alter_column
    return operations.invoke(alt)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/operations/base.py", line 442, in invoke
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/operations/toimpl.py", line 53, in alter_column
    operations.impl.alter_column(
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/ddl/impl.py", line 319, in alter_column
    self._exec(
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/alembic/ddl/impl.py", line 210, in _exec
    return conn.execute(construct, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/ec2-user/superset/superset/superset/superset-env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "extra": syntax error
[SQL: ALTER TABLE report_schedule RENAME extra TO extra_json]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by krishanthvs** [comment]
@dosu itried postgress mothod. still not working

**Comment by krishanthvs** [comment]
@dosu can you point this to some one who has expertise on the same

**Comment by krishanthvs** [comment]
how to  manually create the report_schedule table with the extra_json column instead of extra.

**Comment by krishanthvs** [comment]
@dosu how to manually create the report_schedule table with the extra_json column instead of extra.

**Comment by krishanthvs** [comment]
@rusackas can you please help me on this

**Comment by krishanthvs** [comment]
@dosu can you link me to other expert on this

**Comment by krishanthvs** [comment]
@dosu Now i am getting this error
(superset-env1) [root@ip-192-168-3-20 superset]# superset db upgrade
Loaded your LOCAL configuration at [/home/ec2-user/superset_project/superset_config.py]
logging was configured successfully
2024-10-21 12:34:39,107:INFO:superset.utils.logging_configurator:logging was configured successfully
2024-10-21 12:34:39,119:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/home/ec2-user/superset_project/superset-env1/lib/python3.11/site-packages/flask_limiter/extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
WARNI [alembic.env] SQLite Database support for metadata databases will         be removed in a future version of Superset.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [flask_migrate] Error: Can't locate revision identified by '74688be0db29'

**Comment by krishanthvs** [comment]
@rusackas can you please help me on this

**Comment by krishanthvs** [comment]
@dosu where to find the alembic version table

**Comment by krishanthvs** [comment]
@dosu whats the path for .db file
