### ISSUE TITLE
Docker image for 4.1.1rc1 is missing python dependencies

### ISSUE THREAD

**Issue by OldrichDlouhy** [apache/superset#30989]
### Bug description

Running the docker image for version 4.1.1rc1 fails with ModuleNotFoundError: No module named 'psycopg2'.

### Superset version

4.1.0

### Python version

3.10

### Node version

16

### Browser

Chrome

### Additional context

```
2024-11-20 12:20:31,286:ERROR:superset.app:Failed to create app
 Traceback (most recent call last):
   File "/app/superset/app.py", line 40, in create_app
     app_initializer.init_app()
   File "/app/superset/initialization/__init__.py", line 478, in init_app
     self.setup_db()
   File "/app/superset/initialization/__init__.py", line 640, in setup_db
     pessimistic_connection_handling(db.engine)
   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
     return self.get_engine()
   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
     return connector.get_engine()
   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
     self._engine = rv = self._sa.create_engine(sa_url, options)
   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
     return sqlalchemy.create_engine(sa_url, **engine_opts)
   File "<string>", line 2, in create_engine
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
     return fn(*args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
     dbapi = dialect_cls.dbapi(**dbapi_args)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 811, in dbapi
     import psycopg2
 ModuleNotFoundError: No module named 'psycopg2'
 Traceback (most recent call last):
   File "/usr/local/bin/flask", line 8, in <module>
 Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
     sys.exit(main())
   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1064, in main
     cli.main()
   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
     rv = self.invoke(ctx)
   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
     return _process_result(sub_ctx.command.invoke(sub_ctx))
   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
     return __callback(*args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 92, in new_func
     return ctx.invoke(f, obj, *args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
     return __callback(*args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 912, in run_command
     raise e from None
   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 898, in run_command
     app = info.load_app()
   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 309, in load_app
     app = locate_app(import_name, name)
   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 238, in locate_app
     return find_app_by_string(module, app_name)
   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 166, in find_app_by_string
     app = attr(*args, **kwargs)
   File "/app/superset/app.py", line 47, in create_app
     raise ex
   File "/app/superset/app.py", line 40, in create_app
     app_initializer.init_app()
   File "/app/superset/initialization/__init__.py", line 478, in init_app
     self.setup_db()
   File "/app/superset/initialization/__init__.py", line 640, in setup_db
     pessimistic_connection_handling(db.engine)
   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
     return self.get_engine()
   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
     return connector.get_engine()
   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
     self._engine = rv = self._sa.create_engine(sa_url, options)
   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
     return sqlalchemy.create_engine(sa_url, **engine_opts)
   File "<string>", line 2, in create_engine
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
     return fn(*args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
     dbapi = dialect_cls.dbapi(**dbapi_args)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 811, in dbapi
     import psycopg2
 ModuleNotFoundError: No module named 'psycopg2'
```

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sadpandajoe** [comment]
Seems to work for me as I'm able to spin the app up just fine. Have you seen this note in the change log: https://github.com/apache/superset/blob/master/RELEASING/release-notes-4-1/README.md#change-to-docker-image-builds?

**Comment by sadpandajoe** [comment]
Also going to post this here as this was talked about in the 4.1.0 rc releases: https://github.com/apache/superset/discussions/30631#discussioncomment-11016958
