### ISSUE TITLE
Docker Image Tag 4.1.1 is missing support for MySQL

### ISSUE THREAD

**Issue by MVanDerlofske** [apache/superset#31459]
### Bug description

When using the Docker Image tagged 4.1.1 it appears to be missing the ability to support MySQL as a datasource (among others).

Reproduce (performed on both my local system and a newly setup test system):
1. export TAG=4.1.1
2. docker compose -f docker-compose-image-tag.yml up
3. resolve dependency issues that arise (reported in other bug tickets)

Open the Superset interface and add a new database connection. You will note that the MySQL and Presto options are missing.

### Screenshots/recordings

Screenshot of Add Database window on 4.1.1 tag:
![Missing DB Engines](https://github.com/user-attachments/assets/8de99070-0e85-4f8b-862d-b01abb35806f)
Screenshot of editing an existing MySQL connection from an upgraded system:
![Edit Existing MySQL connection](https://github.com/user-attachments/assets/dbd098b4-8e04-4487-afd4-76d344b3447f)
Screenshot of expected add database window (taken for latest-dev 2024-12-14):
![Typical Add Connection Interface](https://github.com/user-attachments/assets/2bdb100a-4c75-42d5-a982-1ba25dd7b15f)
Screenshot of edit database connection window (taken for latest-dev 2024-12-14):
![Typical Edit](https://github.com/user-attachments/assets/9f59d34c-56d2-4b6b-ab21-db90f2d5cae3)

### Superset version

4.1.1

### Python version

I don't know

### Node version

I don't know

### Browser

Chrome

### Additional context

Error callstack:
2024-12-14 16:11:45,537:warning:superset.views.error_handling:SupersetErrorsException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 119, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1364, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 91, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 303, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/sqllab/api.py", line 409, in execute_sql_query
    command_result: CommandResult = command.run()
  File "/app/superset/utils/decorators.py", line 266, in wrapped
    return on_error(ex)
  File "/app/superset/utils/decorators.py", line 236, in on_error
    raise ex
  File "/app/superset/utils/decorators.py", line 259, in wrapped
    result = func(*args, **kwargs)
  File "/app/superset/commands/sql_lab/execute.py", line 105, in run
    status = self._run_sql_json_exec_from_scratch()
  File "/app/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
    return self._sql_json_executor.execute(
  File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
    raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message="No module named 'MySQLdb'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'MySQL', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by MVanDerlofske** [comment]
attempts to install mysql manually failed, I tried using both pymysql and mysqlclient.
pymysql - installed successfully however the same issue presented itself both in the UI and in the error log.
mysqlclient failed to install due to missing dependencies which were not installable via the requirements file.

**Comment by sfirke** [comment]
I'll mark this needs-more-info b/c I'd like to know that installing `mysqlclient` fixes this -- and ideally we link to documentation of how to do that successfully in a Dockerfile in 4.1.1.  Then we can close it as a duplicate of other issues related to no longer including `mysqlclient` and `psycopg2` in the base Superset image, which isn't really a bug per se.

**Comment by bjornjorgensen** [comment]
have the same issue when I use the helm chart

```
kubectl logs my-superset-bd8897d4c-rbql2 -n default

```
Defaulted container "superset" out of: superset, wait-for-postgres (init)
[2024-12-23 23:33:28 +0000] [8] [INFO] Starting gunicorn 22.0.0
[2024-12-23 23:33:28 +0000] [8] [INFO] Listening at: http://0.0.0.0:8088 (8)
[2024-12-23 23:33:28 +0000] [8] [INFO] Using worker: gthread
[2024-12-23 23:33:28 +0000] [9] [INFO] Booting worker with pid: 9
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
2024-12-23 23:33:30,178:ERROR:superset.app:Failed to create app

(...)
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 811, in dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2024-12-23 23:33:30 +0000] [9] [INFO] Worker exiting (pid: 9)
[2024-12-23 23:33:30 +0000] [8] [ERROR] Worker (pid:9) exited with code 3
[2024-12-23 23:33:30 +0000] [8] [ERROR] Shutting down: Master
[2024-12-23 23:33:30 +0000] [8] [ERROR] Reason: Worker failed to boot.

**Comment by Anricx** [comment]
I'm direct use docker image by `docker pull apache/superset`

ENV
```sh
superset@e5f394a4ecb1:/app$ superset --version
Python 3.10.15
Flask 2.3.3
Werkzeug 3.0.6
superset@e5f394a4ecb1:/app$ 
```

```sh
root@DS1-1:~# docker exec -it superset /bin/bash
superset@e5f394a4ecb1:/app$ pip list |grep 'mysql'
superset@e5f394a4ecb1:/app$ 
superset@e5f394a4ecb1:/app$ pip install mysqlclient
Defaulting to user installation because normal site-packages is not writeable
Collecting mysqlclient
  Using cached mysqlclient-2.2.7.tar.gz (91 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /bin/sh: 1: pkg-config: not found
      /bin/sh: 1: pkg-config: not found
      /bin/sh: 1: pkg-config: not found
      /bin/sh: 1: pkg-config: not found
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
      Trying pkg-config --exists libmariadb
      Command 'pkg-config --exists libmariadb' returned non-zero exit status 127.
      Trying pkg-config --exists perconaserverclient
      Command 'pkg-config --exists perconaserverclient' returned non-zero exit status 127.
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-gx6jn3er/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-gx6jn3er/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gx6jn3er/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 156, in <module>
        File "<string>", line 49, in get_config_posix
        File "<string>", line 28, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
superset@e5f394a4ecb1:/app$ 
``` 

need help :)

**Comment by rusackas** [comment]
CC @mistercrunch for good measure.

**Comment by mistercrunch** [comment]
As convenient as it may be to include database drivers into the `lean` images, I still stand by the decision of NOT bundling them in. Every single deploy needs its own set of driver (whether is mysql/postgres/oracle/mssql for metadata db) and different set of analytics database. Serving a `fat` image might be nice, but I would not recommend friends / anyone to use such an image, and it'd be a huge pain to maintain. 

The reality is that if you want to run Superset in production, you should extend `lean` with the set of drivers you need for your environment, and at that point you're in the business of picking the right drivers and keeping them up to date. Note that we try and maintain the "extra_requires" as metadata of supported drivers/versions, but it's been a bit of a loosing battle given the state of the ecosystem.

Knowing this, would love help to improve the docs to make this as clear/straightforward as possible.

**Comment by Anricx** [comment]
Who could I get an image that could install mysql driver or bounded with by `docker pull`? the easy way.

**Comment by sfirke** [comment]
> Knowing this, would love help to improve the docs to make this as clear/straightforward as possible.

One concrete thing to sort out is, does the workflow still work to have dependencies installed at runtime with `requirements.txt`? Someone above wrote:

> mysqlclient failed to install due to missing dependencies which were not installable via the requirements file.

And I had some new struggles last month trying to get packages listed in `requirements.txt` to install. I think that process has changed since 4.0.0, maybe my problem was that the packages were installing but then unavailable to the user that the container runs as? I think this is one place where we may need to update the docs if this approach is not working as currently documented.

I may be going back down this rabbit hole soon. I will probably build my own image as suggested above, but we ought to be clear on what the options are for people who want to try out Superset using drivers for their data warehouse - is there a way for them that doesn't involve building their own image?

**Comment by eff917** [comment]
The main problem is that only installing the mysqlclient package resolves this issue. If you only install pymysql or mysql-python, you can create the database connection, but as soon as you try to use that connection in SQLlab, the preview data panel throws this error. You can select the database and the table, and the left pan correctly shows the columns, but you cannot run a query. I assume this is because of the sqlparse/sqlparsere package.

**Comment by mistercrunch** [comment]
@eff917 seems like someone should open an issue specifically for that problem with proper stacktrace/error-message. Giving the main issue has been answered-to here, closing this issue.
