### ISSUE TITLE
Exporting to PDF does not work if there is a map visualization of the type deck.gl Polygon.

### ISSUE THREAD

**Issue by tonny-skynet** [apache/superset#31579]
### Bug description

We have a need to export to PDF with map visualizations of the deck.gl Polygon type. Unfortunately, this feature does not work if there is a chart of the deck.gl Polygon type.
But for chart types other than deck.gl Polygon, exporting to PDF works. Does Superset not support rendering WebGL-based elements into static formats like PDF?

**How to reproduce the bug**

1. Go to dashboard with map visualizations of the deck.gl Polygon type,
2. Select Download > Export to PDF
3. Chart data should be exported to PDF file.

### Screenshots/recordings

https://github.com/user-attachments/assets/cf9d211d-50b3-4eb7-a66f-735e632eebbc

log superset:

```
Dec 20 14:32:17   superset.sh[800977]: HTTPException

Dec 20 14:32:17   superset.sh[800977]: Traceback (most recent call last):

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request

Dec 20 14:32:17   superset.sh[800977]:     rv = self.dispatch_request()

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/flask/app.py", line 1458, in dispatch_request

Dec 20 14:32:17   superset.sh[800977]:     self.raise_routing_exception(req)

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/flask/app.py", line 1440, in raise_routing_exception

Dec 20 14:32:17   superset.sh[800977]:     raise request.routing_exception  # type: ignore

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/flask/ctx.py", line 353, in match_request

Dec 20 14:32:17   superset.sh[800977]:     result = self.url_adapter.match(return_rule=True)  # type: ignore

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 629, in match

Dec 20 14:32:17   superset.sh[800977]:     raise NotFound() from None

Dec 20 14:32:17   superset.sh[800977]: werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Dec 20 14:32:17   superset.sh[800977]: HTTPException

Dec 20 14:32:17   superset.sh[800977]: Traceback (most recent call last):

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request

Dec 20 14:32:17   superset.sh[800977]:     rv = self.dispatch_request()

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/flask/app.py", line 1458, in dispatch_request

Dec 20 14:32:17   superset.sh[800977]:     self.raise_routing_exception(req)

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/flask/app.py", line 1440, in raise_routing_exception

Dec 20 14:32:17   superset.sh[800977]:     raise request.routing_exception  # type: ignore

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/flask/ctx.py", line 353, in match_request

Dec 20 14:32:17   superset.sh[800977]:     result = self.url_adapter.match(return_rule=True)  # type: ignore

Dec 20 14:32:17   superset.sh[800977]:   File "/home/superset/venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 629, in match

Dec 20 14:32:17   superset.sh[800977]:     raise NotFound() from None

Dec 20 14:32:17   superset.sh[800977]: werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

```

### Superset version

4.0.2

### Python version

3.9

### Node version

Not applicable

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by arcuellar88** [comment]
We have a similar issue with all deck.gl charts. Downloading as image works fine. Downloading as PDF doesn't work. 
Superset 4.1.1

**Comment by rusackas** [comment]
Right... not sure if @fisjac or @kgabryje or @eschutho know the current state of affairs, but I _think_ the PLAYWRIGHT_REPORTS_AND_THUMBNAILS addresses this, since it supports WebGL and other headless browsers might not.

**Comment by rusackas** [comment]
Assuming PLAYWRIGHT_REPORTS_AND_THUMBNAILS is working as planned for folks, thus the long silence, so I'll close this one out. Holler if it needs a revisit!

**Comment by jmeegan2** [comment]
> Assuming PLAYWRIGHT_REPORTS_AND_THUMBNAILS is working as planned for folks, thus the long silence, so I'll close this one out. Holler if it needs a revisit!

Tried the PLAYWRIGHT_REPORTS_AND_THUMBNAILS approach - I couldn't get it to work, I tried for like half an hour. 

What worked: Replaced dom-to-pdf with dom-to-image-more + jsPDF in downloadAsPdf.ts. Removed dom-to-pdf from dependencies. Captures WebGL/deck.gl canvases client-side, no backend changes needed. 

If u want to see the code change for that you can let me know, I have the changes in a private repo atm OR if someone can confirm the suggested fix worked and how they got it to work reply to this.
