### ISSUE TITLE
When I create a chart using a virtual table , it reports error "KeyError: 'compile_state'"

### ISSUE THREAD

**Issue by tuoluzhe8521** [apache/superset#31638]
### Bug description

https://github.com/user-attachments/assets/afa07d8d-bbb9-4984-99a0-80a72814ef1d

### Superset version

4.1.1

### Python version

3.9

### Node version

I don't know

### Browser

Chrome

### Additional context

NFO:sqlalchemy.engine.Engine:[cached since 1371s ago] (1,)
INFO:sqlalchemy.engine.Engine:[cached since 1371s ago] (1,)
INFO:sqlalchemy.engine.Engine:SELECT row_level_security_filters.id AS row_level_security_filters_id, row_level_security_filters.group_key AS row_level_security_filters_group_key, row_level_security_filters.clause AS row_level_security_filters_clause 
FROM row_level_security_filters 
WHERE row_level_security_filters.id IN (SELECT rls_filter_tables.rls_filter_id 
FROM rls_filter_tables 
WHERE rls_filter_tables.table_id = %s) AND (row_level_security_filters.filter_type = %s AND row_level_security_filters.id IN (SELECT rls_filter_roles.rls_filter_id 
FROM rls_filter_roles INNER JOIN row_level_security_filters ON row_level_security_filters.id = rls_filter_roles.rls_filter_id 
WHERE row_level_security_filters.filter_type = %s AND rls_filter_roles.role_id IN (%s)) OR row_level_security_filters.filter_type = %s AND (row_level_security_filters.id NOT IN (SELECT rls_filter_roles.rls_filter_id 
FROM rls_filter_roles INNER JOIN row_level_security_filters ON row_level_security_filters.id = rls_filter_roles.rls_filter_id 
WHERE row_level_security_filters.filter_type = %s AND rls_filter_roles.role_id IN (%s))))
INFO:sqlalchemy.engine.Engine:SELECT row_level_security_filters.id AS row_level_security_filters_id, row_level_security_filters.group_key AS row_level_security_filters_group_key, row_level_security_filters.clause AS row_level_security_filters_clause 
FROM row_level_security_filters 
WHERE row_level_security_filters.id IN (SELECT rls_filter_tables.rls_filter_id 
FROM rls_filter_tables 
WHERE rls_filter_tables.table_id = %s) AND (row_level_security_filters.filter_type = %s AND row_level_security_filters.id IN (SELECT rls_filter_roles.rls_filter_id 
FROM rls_filter_roles INNER JOIN row_level_security_filters ON row_level_security_filters.id = rls_filter_roles.rls_filter_id 
WHERE row_level_security_filters.filter_type = %s AND rls_filter_roles.role_id IN (%s)) OR row_level_security_filters.filter_type = %s AND (row_level_security_filters.id NOT IN (SELECT rls_filter_roles.rls_filter_id 
FROM rls_filter_roles INNER JOIN row_level_security_filters ON row_level_security_filters.id = rls_filter_roles.rls_filter_id 
WHERE row_level_security_filters.filter_type = %s AND rls_filter_roles.role_id IN (%s))))
INFO:sqlalchemy.engine.Engine:[cached since 1371s ago] (17, 'Regular', 'Regular', 1, 'Base', 'Base', 1)
INFO:sqlalchemy.engine.Engine:[cached since 1371s ago] (17, 'Regular', 'Regular', 1, 'Base', 'Base', 1)
INFO:werkzeug:100.127.207.15 - - [29/Dec/2024 02:12:43] "GET / HTTP/1.1" 302 -
INFO:sqlalchemy.engine.Engine:SELECT ssh_tunnels.uuid AS ssh_tunnels_uuid, ssh_tunnels.created_on AS ssh_tunnels_created_on, ssh_tunnels.changed_on AS ssh_tunnels_changed_on, ssh_tunnels.extra_json AS ssh_tunnels_extra_json, ssh_tunnels.id AS ssh_tunnels_id, ssh_tunnels.database_id AS ssh_tunnels_database_id, ssh_tunnels.server_address AS ssh_tunnels_server_address, ssh_tunnels.server_port AS ssh_tunnels_server_port, ssh_tunnels.username AS ssh_tunnels_username, ssh_tunnels.password AS ssh_tunnels_password, ssh_tunnels.private_key AS ssh_tunnels_private_key, ssh_tunnels.private_key_password AS ssh_tunnels_private_key_password, ssh_tunnels.created_by_fk AS ssh_tunnels_created_by_fk, ssh_tunnels.changed_by_fk AS ssh_tunnels_changed_by_fk 
FROM ssh_tunnels 
WHERE ssh_tunnels.database_id = %s
INFO:sqlalchemy.engine.Engine:SELECT ssh_tunnels.uuid AS ssh_tunnels_uuid, ssh_tunnels.created_on AS ssh_tunnels_created_on, ssh_tunnels.changed_on AS ssh_tunnels_changed_on, ssh_tunnels.extra_json AS ssh_tunnels_extra_json, ssh_tunnels.id AS ssh_tunnels_id, ssh_tunnels.database_id AS ssh_tunnels_database_id, ssh_tunnels.server_address AS ssh_tunnels_server_address, ssh_tunnels.server_port AS ssh_tunnels_server_port, ssh_tunnels.username AS ssh_tunnels_username, ssh_tunnels.password AS ssh_tunnels_password, ssh_tunnels.private_key AS ssh_tunnels_private_key, ssh_tunnels.private_key_password AS ssh_tunnels_private_key_password, ssh_tunnels.created_by_fk AS ssh_tunnels_created_by_fk, ssh_tunnels.changed_by_fk AS ssh_tunnels_changed_by_fk 
FROM ssh_tunnels 
WHERE ssh_tunnels.database_id = %s
INFO:sqlalchemy.engine.Engine:[cached since 1371s ago] (1,)
INFO:werkzeug:100.127.207.159 - - [29/Dec/2024 02:12:43] "GET / HTTP/1.1" 302 -
INFO:sqlalchemy.engine.Engine:[cached since 1371s ago] (1,)
WARNING:superset.views.error_handling:Exception
Traceback (most recent call last):
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/views/base_api.py", line 119, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/utils/core.py", line 1364, in time_function
    response = func(*args, **kwargs)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/utils/log.py", line 303, in wrapper
    value = f(*args, **kwargs)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/charts/data/api.py", line 260, in data
    return self._get_data_response(
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/charts/data/api.py", line 416, in _get_data_response
    result = command.run(force_cached=force_cached)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/commands/chart/data/get_data_command.py", line 45, in run
    payload = self._query_context.get_payload(
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/common/query_context.py", line 102, in get_payload
    return self._processor.get_payload(cache_query_context, force_cached)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/common/query_context_processor.py", line 675, in get_payload
    query_results = [
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/common/query_context_processor.py", line 676, in <listcomp>
    get_query_results(
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/common/query_actions.py", line 227, in get_query_results
    return result_func(query_context, query_obj, force_cached)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/common/query_actions.py", line 103, in _get_full
    payload = query_context.get_df_payload(query_obj, force_cached=force_cached)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/common/query_context.py", line 123, in get_df_payload
    return self._processor.get_df_payload(
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/common/query_context_processor.py", line 158, in get_df_payload
    query_result = self.get_query_result(query_obj)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/common/query_context_processor.py", line 237, in get_query_result
    result = query_context.datasource.query(query_object.to_dict())
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/connectors/sqla/models.py", line 1729, in query
    query_str_ext = self.get_query_str_extended(query_obj)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/models/helpers.py", line 881, in get_query_str_extended
    sql = self.database.compile_sqla_query(sqlaq.sqla_query)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/superset/models/core.py", line 700, in compile_sqla_query
    sql = str(qry.compile(engine, compile_kwargs={"literal_binds": True}))
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, **kw)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 558, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3401, in visit_select
    text = self._compose_select_body(
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3579, in _compose_select_body
    text += self.order_by_clause(select, **kwargs)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3691, in order_by_clause
    order_by = self._generate_delimited_list(
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 1685, in _generate_delimited_list
    return separator.join(
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 1685, in <genexpr>
    return separator.join(
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 1687, in <genexpr>
    for s in (c._compiler_dispatch(self, **kw) for c in elements)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/data/module/miniconda3/envs/superset/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 1399, in visit_label_reference
    compile_state = self.stack[-1]["compile_state"]
KeyError: 'compile_state'

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by tuoluzhe8521** [comment]
@dosu ,my SQLAlchemy is 1.4.32  and Virtual dataset can query data normally and Database Connection are correctly configured

**Comment by tuoluzhe8521** [comment]
@dosu This is the front-end request parameter : {"datasource":{"id":17,"type":"table"},"force":false,"queries":[{"filters":[{"col":"channel","op":"IN","val":["gdt","kuaishou","toutiao","xhs"]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["hour"],"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"channel","description":null,"expression":null,"filterable":true,"groupby":true,"id":369,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(channel)","optionName":"metric_h6kqwm5nj0s_njfwix95tz","sqlExpression":null}],"orderby":[["user_cnt",false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"series_limit_metric":"user_cnt","order_desc":true,"url_params":{"datasource_id":"17","datasource_type":"table","form_data_key":"ex5HALrXZfoi4jUSWZ5cjF8t-WRmQvdGFeAfNDPCW1zdIJaBZft69Ufp0fieMdzH"},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"17__table","viz_type":"table","url_params":{"datasource_id":"17","datasource_type":"table","form_data_key":"ex5HALrXZfoi4jUSWZ5cjF8t-WRmQvdGFeAfNDPCW1zdIJaBZft69Ufp0fieMdzH"},"query_mode":"aggregate","groupby":["hour"],"temporal_columns_lookup":{},"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"channel","description":null,"expression":null,"filterable":true,"groupby":true,"id":369,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(channel)","optionName":"metric_h6kqwm5nj0s_njfwix95tz","sqlExpression":null}],"all_columns":["os"],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":["gdt","kuaishou","toutiao","xhs"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_sz5jsn5uasc_5k0xvmr622q","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"channel"}],"timeseries_limit_metric":"user_cnt","order_by_cols":[],"row_limit":1000,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}

**Comment by tuoluzhe8521** [comment]
i solve the problem by tewaking the version:
superset:4.1.1
